[monitoring-kubernetes] Switch to  CustomResourceStateMetrics for VPA
deckhouse/deckhouse pull request #10003
Opened 2024-10-04 18:29 UTC by scaps1

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-10-10 21:48 UTC, vladimirGuryanov requested changes

2024-10-10 21:48 UTC, vladimirGuryanov commented on modules/340-monitoring-kubernetes/templates/kube-state-metrics/additional-scrape-config.yaml
> -  metricsPath: '/main/metrics'
I guess this was removed by mistake

2024-10-11 07:36 UTC, scaps1 commented on modules/340-monitoring-kubernetes/templates/kube-state-metrics/additional-scrape-config.yaml
> -  metricsPath: '/main/metrics'
Yes you are right.
Fixed.

2024-10-11 08:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-11 14:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-14 17:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-16 09:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-17 11:59 UTC, nabokihms approved these changes

2024-10-17 11:59 UTC, nabokihms commented on modules/340-monitoring-kubernetes/templates/kube-state-metrics/additional-scrape-config.yaml
> +    regex: customresource_group
```suggestion
  - action: labeldrop
    regex: customresource_version|customresource_kind|customresource_group
```

2024-10-17 12:25 UTC, lazovskiy commented on modules/340-monitoring-kubernetes/templates/kube-state-metrics/additional-scrape-config.yaml
> +    replacement: ''
I would suggest using the same pattern for readability:
* action is not required here
* keys appear in a different order
* `sourceLabels` written using different yaml-syntax

2024-10-17 13:02 UTC, merged