[monitoring-kubenetes] increase logging info
deckhouse/deckhouse pull request #10169
Opened 2024-10-17 11:19 UTC by scaps1

## Description
Referring to this [issue](https://github.com/deckhouse/deckhouse/issues/8643) we have low informative logs in the sub module kubelet-eviction-thresholds-exporter.

## Why do we need it, and what problem does it solve?
To increase logging info for additional help in debugging problems with kubelet-eviction-thresholds-exporter module 

## Why do we need it in the patch release (if we do)?

No we don't

## What is the expected result?
We have a more informative description of errors in logs

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

```changes
section: monitoring-kubenetes
type: chore
summary: increase logging info
impact_level: low
```

2024-10-17 13:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-02-14 08:08 UTC, scaps1 commented on modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/exporter/main.go
> +		log.Printf("Error reading containerd config: %s, using default /var/lib/containerd,", err)
Fixed

2025-02-14 11:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-02-17 10:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-02-17 15:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-02-18 09:49 UTC, vladimirGuryanov commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.30 13374133235 13374133235-1-con-1-30 /sys/deckhouse-oss/install:pr10169 redos@51.250.92.45

2025-02-18 09:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-02-18 10:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-02-19 10:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-02-19 12:13 UTC, scaps1 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.30 13410671093 13410671093-1-con-1-30 /sys/deckhouse-oss/install:pr10169

2025-02-19 12:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-02-20 12:28 UTC, vladimirGuryanov requested changes

2025-02-20 12:28 UTC, vladimirGuryanov commented on modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/src/main.go
> +		return "/var/lib/containerd", fmt.Errorf("error reading containerd config: %s, using default /var/lib/containerd", err)
```suggestion
         log.Printf("error reading containerd config: %e, using default /var/lib/containerd", err)
		return "/var/lib/containerd", nil
```

2025-02-20 12:28 UTC, vladimirGuryanov commented on modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/src/main.go
> +		return "/var/lib/containerd", fmt.Errorf("containerd config does not contain root dir option, using default /var/lib/containerd")
```suggestion
        log.Println("containerd config does not contain root dir option, using default /var/lib/containerd")
		return "/var/lib/containerd", nil
```

2025-02-20 12:28 UTC, vladimirGuryanov approved these changes

2025-02-20 12:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-02-20 22:32 UTC, merged