[dex] Add v2alpha1 version dex-auth
deckhouse/deckhouse pull request #10200
Opened 2024-10-18 14:59 UTC by trofimovdals

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-10-18 15:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-18 17:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-18 18:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-18 20:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-19 18:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-19 20:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-19 21:40 UTC, trofimovdals commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11410385335 11410385335-1-con-1-27 /sys/deckhouse-oss/install:pr10200 redos@51.250.1.62

2024-10-19 21:44 UTC, trofimovdals commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11419944611 11419944611-1-con-1-27 /sys/deckhouse-oss/install:pr10200 redos@89.169.153.134

2024-10-19 21:58 UTC, trofimovdals commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11420400253 11420400253-1-con-1-27 /sys/deckhouse-oss/install:pr10200 redos@51.250.93.255

2024-10-19 22:03 UTC, trofimovdals commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11420400253 11420400253-1-con-1-27 /sys/deckhouse-oss/install:pr10200 redos@51.250.93.255

2024-10-19 22:07 UTC, trofimovdals commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11420400253 11420400253-1-con-1-27 /sys/deckhouse-oss/install:pr10200 redos@51.250.93.255

2024-10-22 13:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-22 17:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-22 18:27 UTC, trofimovdals commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11465543760 11465543760-1-con-1-27 /sys/deckhouse-oss/install:pr10200 redos@89.169.159.32

2024-10-22 18:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-22 19:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-23 08:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-23 09:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-23 13:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-23 14:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-30 13:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @trofimovdals. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-01 13:35 UTC, nabokihms requested changes
Fix the test case here, add a test with two applications
https://github.com/deckhouse/deckhouse/blob/688ac6231c96c661cba089d5beff68e816d28fd1/modules/150-user-authn/openapi/values.yaml#L74-L107

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/hooks/get_dex_authenticator_crds_test.go
> +        "domainName": "test",
```suggestion
        "domain": "test",
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/hooks/get_dex_authenticator_crds_test.go
> +  - domainName: test
```suggestion
  - domain: test
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/hooks/get_dex_authenticator_crds_test.go
> +        "domainName": "test",
```suggestion
        "domain": "test",
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/hooks/get_dex_authenticator_crds_test.go
> +  - domainName: test
```suggestion
  - domain: test
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/hooks/get_dex_authenticator_crds_test.go
> +        "domainName": "test",
```suggestion
        "domain": "test",
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/template_tests/authenticator_test.go
> +    - domainName: authenticator.example.com
```suggestion
    - domain: authenticator.example.com
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/template_tests/authenticator_test.go
> +    - domainName: authenticator.com
```suggestion
    - domain: authenticator.com
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/template_tests/authenticator_test.go
> +    applications:
There is the reason to add more than one application for a single test case to check the render of the array of applications.

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/deployment.yaml
> +{{- end }}
```suggestion
{{- end }}

```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/ingress.yaml
> +  - host: {{ $app.domainName }}
```suggestion
  - host: {{ $app.domain }}
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/ingress.yaml
> +    - {{ $app.domainName }}
```suggestion
    - {{ $app.domain }}
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/ingress.yaml
> +  - host: {{ $app.domainName }}
```suggestion
  - host: {{ $app.domain }}
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/ingress.yaml
> +    - {{ $app.domainName }}
```suggestion
    - {{ $app.domain }}
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/ingress.yaml
> +{{- end }}
```suggestion
{{- end }}

```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/oauth2client.yaml
> +{{- end }}
```suggestion
{{- end }}

```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/secret.yaml
> +  {{- range $app := $crd.spec.applications }}
```suggestion
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/secret.yaml
> +  {{- end }}
```suggestion
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/secret.yaml
> +{{- end }}
```suggestion
{{- end }}

```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/templates/dex-authenticator/service.yaml
> +  {{- end }}
```suggestion
  {{- end }}

```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/webhooks/conversion/dex-authentificator
> +        domainName: .spec.applicationDomain,
```suggestion
        domain: .spec.applicationDomain,
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/webhooks/conversion/dex-authentificator
> +        applicationDomain: .spec.applications[0].domainName,
```suggestion
        applicationDomain: .spec.applications[0].domain,
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/webhooks/conversion/dex-authentificator
> +      toVersion: deckhouse.io/v2alpha1
```suggestion
      toVersion: deckhouse.io/v1
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/webhooks/conversion/dex-authentificator
> +  - name: v1alpha1_to_v2alpha1
```suggestion
  - name: v1_to_v2alpha1
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/webhooks/conversion/dex-authentificator
> +      toVersion: deckhouse.io/v1alpha1
```suggestion
  - name: v2alpha1_to_v1
    crdName: dexauthenticators.deckhouse.io
    conversions:
    - fromVersion: deckhouse.io/v2alpha1
      toVersion: deckhouse.io/v1
```

2024-11-01 13:35 UTC, nabokihms commented on modules/150-user-authn/webhooks/conversion/dex-authentificator
> +kubernetesCustomResourceConversion:
v1alpha1 <-> v1 <-> v2alpha1

2024-11-02 13:53 UTC, closed without merging