[metallb] Pre-upgrade compatibility check for metallb configuration
deckhouse/deckhouse pull request #10289
Opened 2024-10-24 12:30 UTC by tarabrind

## Description
Add a check of the settings of the `metallb` module and its resources for compliance with the requirements of the new version of the module.

## Why do we need it, and what problem does it solve?
We require the customer to change the settings in the cluster themselves before cluster upgrade.

## What is the expected result?
`Deckhouse` can't be upgraded until the settings meet the new module version requirements.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: metallb
type: feature
summary: Added pre-upgrade compatibility check for metallb configuration.
impact_level: default
```

2024-10-24 13:44 UTC, tarabrind commented
Checking.
```shell
# kubectl get l2advertisements.metallb.io -A
NAMESPACE    NAME     IPADDRESSPOOLS   IPADDRESSPOOL SELECTORS   INTERFACES
d8-metallb   zone-a   ["pool-2"]
default      zone-b   ["pool-1"]

# kubectl -n d8-system exec deployments/deckhouse -- deckhouse-controller requirements | jq | grep metallb
  "metallb:ConfigurationStatus": "nsMismatch",

# kubectl get deckhousereleases.deckhouse.io -A
NAME       PHASE     TRANSITIONTIME   MESSAGE
v1.100.1   Pending   6s               "metallbHasStandardConfiguration" requirement for DeckhouseRelease "1.100.1" not met: metallb: all L2Advertisement must be in the d8-metallb namespace
```

2024-10-24 13:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-25 03:40 UTC, Beastlex commented on ee/se/modules/380-metallb/hooks/check_requirements_for_upgrade.go
> +	if !reflect.DeepEqual(ipAddressPollNamesFromL2A, ipAddressPollNamesFromIAP) {
It is better to use slices.Equal instead of reflect.deepEqual

2024-10-25 03:45 UTC, Beastlex commented on ee/se/modules/380-metallb/requirements/check.go
> +		case configurationStatus == "nsMismatch":
Better to use
switch configurationStatus := configurationStatusRaw.(string); configurationStatus
case "nsMismatch"
or
configurationStatus := configurationStatusRaw.(string)
switch configurationStatus
case "nsMismatch"

2024-10-30 01:26 UTC, apolovov requested changes

2024-10-30 01:26 UTC, apolovov commented on ee/se/modules/380-metallb/hooks/check_requirements_for_upgrade.go
> +		requirements.SaveValue(metallbConfigurationStatusKey, "addressPollsMismatch")
sed -i 's/addressPollsMismatch/addressPoolsMismatch/'

2024-10-30 01:26 UTC, apolovov commented on ee/se/modules/380-metallb/requirements/check.go
> +		case "nsMismatch":
CamelCase:
NSMismatch
NodeSelectorsMismatch
AddressPoolsMismatch
OK

2024-10-30 12:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-31 07:37 UTC, AndreyPavlovFlant approved these changes

2024-10-31 09:12 UTC, apolovov approved these changes

2024-10-31 09:34 UTC, miklezzzz approved these changes

2024-10-31 10:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-01 08:58 UTC, merged

2024-11-01 16:07 UTC, deckhouse-BOaTswain commented
Cherry pick PR [10433](https://github.com/deckhouse/deckhouse/pull/10433) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!