[prometheus] Depricate Grafana v8
deckhouse/deckhouse pull request #10359
Opened 2024-10-30 07:41 UTC by scaps1

## Description
As a way of keeping products that are included in our platform up to date, in this PR, we are dropping support for Grafana-v8.

## Why do we need it, and what problem does it solve?
This pull request removes Grafana version 8 from our project, transitioning solely to version 10. The upgrade is necessary to leverage enhanced features, performance improvements, and new security patches available in Grafana v10. By using the latest version, we ensure compatibility with modern infrastructures and continued support. Additionally, maintaining a single version simplifies management and reduces potential for conflicts. This change is a strategic step towards future-proofing our monitoring capabilities.

## Why do we need it in the patch release (if we do)?

To keep products that are included in our platform up to date.

## What is the expected result?
New and only version of Grafana

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: chore
summary: Depricate Grafana v8
impact_level: default
```

2024-10-30 09:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-30 19:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-31 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-01 08:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-01 18:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-02 10:05 UTC, alexey-gavrilov-flant commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11634528534 11634528534-1-con-1-27 /sys/deckhouse-oss/install:pr10359 redos@89.169.148.210

2024-11-02 10:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-11-02 10:07 UTC, alexey-gavrilov-flant commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11626809908 11626809908-1-con-1-27 /sys/deckhouse-oss/install:pr10359 redos@130.193.51.77

2024-11-02 10:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-11-05 11:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-07 07:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-07 10:55 UTC, scaps1 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 11718471182 11718471182-3-con-1-27 /sys/deckhouse-oss/install:pr10359 redos@89.169.133.128

2024-11-07 13:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-07 16:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-11-29 07:59 UTC, name212 approved these changes

2024-12-18 21:35 UTC, vladimirGuryanov approved these changes

2024-12-20 14:55 UTC, sprait requested changes
one thing

2024-12-20 14:55 UTC, sprait commented on ee/modules/040-node-manager/capi/huaweicloud 2
> +/deckhouse/modules/030-cloud-provider-huaweicloud/capi
some trash?

2024-12-23 09:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-12-23 09:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-12-23 13:02 UTC, lazovskiy approved these changes

2024-12-23 16:14 UTC, nabokihms approved these changes

2024-12-23 16:15 UTC, merged