[node-manager] ignore heartbeat annotation in hook
deckhouse/deckhouse pull request #10368
Opened 2024-10-30 13:45 UTC by d2285

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-10-30 15:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-30 15:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-11-05 17:18 UTC, mvasl requested changes

2024-11-05 17:18 UTC, mvasl commented on modules/040-node-manager/hooks/handle_node_templates.go
> +		return settings, nil
This return is redundant

2024-11-06 07:53 UTC, d2285 commented on modules/040-node-manager/hooks/handle_node_templates.go
> +		return settings, nil
fixed

2024-11-06 13:28 UTC, mvasl approved these changes

2024-11-06 17:31 UTC, name212 approved these changes

2024-11-06 17:32 UTC, merged

2024-11-06 18:18 UTC, deckhouse-BOaTswain commented
Cherry pick PR [10501](https://github.com/deckhouse/deckhouse/pull/10501) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!