item 30792
deckhouse/deckhouse pull request #10441
Opened 2024-11-02 09:57 UTC by alexey-gavrilov-flant

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-11-13 15:20 UTC, name212 commented on dhctl/pkg/app/ssh.go
> +	sSHHostsRaw          = make([]string, 0)
```suggestion
	sshHostsRaw          = make([]string, 0)
```

2024-11-13 15:50 UTC, name212 commented on dhctl/pkg/system/node/ssh/checks.go
> +	case userPassedHostsLen == 3 && replicas == 1 && phase == "scale-to-single-master":
please add comment for this condition

2024-11-13 15:51 UTC, name212 requested changes
two small thing

2024-11-18 07:42 UTC, name212 approved these changes

2024-11-18 07:46 UTC, merged

2024-11-18 07:47 UTC, deckhouse-BOaTswain commented
Cherry pick PR [10691](https://github.com/deckhouse/deckhouse/pull/10691) to the branch [release-1.65](https://github.com/deckhouse/deckhouse/tree/release-1.65) successful!

2024-11-18 07:49 UTC, deckhouse-BOaTswain commented
Cherry pick PR [10692](https://github.com/deckhouse/deckhouse/pull/10692) to the branch [release-1.66](https://github.com/deckhouse/deckhouse/tree/release-1.66) successful!