[monitoring] Prometheus Operator upgrade to 0.77.2 version and CRDs actualize.
deckhouse/deckhouse pull request #10469
Opened 2024-11-05 11:10 UTC by kozharskyad

## Description
Following changes upgrades Prometheus Operator to version 0.77.2.

## Why do we need it, and what problem does it solve?
At present, Deckhouse is compatible with version 0.68.0 of the Prometheus Operator. However, upgrading to version 0.77.2 brings a notable enhancement: it resolves issues related to CRD (Custom Resource Definition) - reading for Custom Resources (CR) without necessitating a rollout restart of the operator. This improvement ensures smoother functionality and reduces downtime, enhancing the overall efficiency of the system.

## Why do we need it in the patch release (if we do)?
-

## What is the expected result?
ScrapeConfig or other Prometheus Operator CRD must working after upgrade without errors. There is must be none of error logs in prometheus-operator deployment.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
Upgrade prometheus-operator from 0.68.0 to 0.77.2 (include CRDs).

```changes
section: operator-prometheus
type: fix
summary: Upgrade prometheus-operator from 0.68.0 to 0.77.2 (include CRDs).
impact_level: low
```

2024-11-05 14:56 UTC, kozharskyad commented on modules/200-operator-prometheus/images/prometheus-operator/patches/001_endpointslices.patch
This patch removed, because same functional already exists in 0.77.2 version of operator.

2025-01-15 07:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-15 11:45 UTC, vladimirGuryanov requested changes

2025-01-15 11:45 UTC, vladimirGuryanov commented on modules/200-operator-prometheus/crds/podmonitors.yaml
> -    backup.deckhouse.io/cluster-config: "true"
Do not need to delete this label.

2025-01-15 11:45 UTC, vladimirGuryanov commented on modules/200-operator-prometheus/crds/probes.yaml
> -    backup.deckhouse.io/cluster-config: "true"
Do not need to delete this label.

2025-01-15 11:45 UTC, vladimirGuryanov commented on modules/200-operator-prometheus/crds/prometheusrules.yaml
> -    backup.deckhouse.io/cluster-config: "true"
Do not need to delete this label.

2025-01-15 11:45 UTC, vladimirGuryanov commented on modules/200-operator-prometheus/crds/servicemonitors.yaml
> -    backup.deckhouse.io/cluster-config: "true"
Do not need to delete this label

2025-01-15 11:45 UTC, vladimirGuryanov commented on modules/200-operator-prometheus/crds/scrapeconfigs.yaml
> -    backup.deckhouse.io/cluster-config: "true"
Do not need to delete this label

2025-01-15 11:56 UTC, ykav-flant commented on modules/200-operator-prometheus/crds/podmonitors.yaml
> -    backup.deckhouse.io/cluster-config: "true"
Fixed.

2025-01-15 14:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-15 15:49 UTC, vladimirGuryanov approved these changes

2025-01-15 15:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-16 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-16 14:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-17 11:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-17 13:30 UTC, vladimirGuryanov commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12827888964 12827888964-1-con-1-29 /sys/deckhouse-oss/install:pr10469 redos@89.169.140.204

2025-01-17 13:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-01-17 13:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @vladimirGuryanov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-17 14:42 UTC, ykav-flant commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12830091241 12830091241-1-con-1-29 /sys/deckhouse-oss/install:pr10469 redos@89.169.145.5

2025-01-17 14:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-01-17 14:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-17 15:26 UTC, ykav-flant commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12831308227 12831308227-1-con-1-29 /sys/deckhouse-oss/install:pr10469 redos@158.160.60.13

2025-01-17 15:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-17 15:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-01-17 15:46 UTC, closed without merging