[core] Another attempt to replace the d8-cni configuration.
deckhouse/deckhouse pull request #10517
Opened 2024-11-07 13:33 UTC by AndreyPavlovFlant

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-11-07 15:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-11-07 15:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-11-07 15:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-11-07 15:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-11-07 15:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-11-07 15:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2024-11-07 15:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2025-01-10 17:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2025-01-10 17:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-10 17:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2025-01-10 17:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2025-01-10 17:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-10 17:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2025-01-10 17:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2025-01-10 17:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2025-01-10 17:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2025-01-13 06:40 UTC, sprait approved these changes

2025-01-13 09:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2025-01-13 09:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2025-01-13 09:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-13 09:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2025-01-13 09:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-13 09:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2025-01-15 14:16 UTC, aleksey-su approved these changes

2025-01-20 07:49 UTC, RomanenkoDenys approved these changes

2025-01-20 08:57 UTC, apolovov requested changes

2025-01-20 08:57 UTC, apolovov commented on dhctl/pkg/config/module_config.go
> +	log.InfoLn("Doesn't found ModuleConfig for cni, creating.")
```suggestion
	log.InfoLn("ModuleConfig for cni not found, creating.")
```

2025-01-20 08:57 UTC, apolovov commented on dhctl/pkg/config/module_config_test.go
> +Copyright 2023 Flant JSC
```suggestion
Copyright 2025 Flant JSC
```

2025-01-20 08:57 UTC, apolovov commented on global-hooks/cleanup_d8_cni_secret.go
> +Copyright 2023 Flant JSC
```suggestion
Copyright 2025 Flant JSC
```

2025-01-20 08:57 UTC, apolovov commented on global-hooks/cleanup_d8_cni_secret_test.go
> +// Copyright 2021 Flant JSC
```suggestion
// Copyright 2025 Flant JSC
```

2025-01-20 09:51 UTC, nabokihms approved these changes

2025-01-20 11:02 UTC, apolovov requested changes

2025-01-20 11:02 UTC, apolovov commented on modules/035-cni-flannel/hooks/set_pod_network_mode.go
>  	input.Values.Set("cniFlannel.internal.podNetworkMode", podNetworkMode)
This could be done in template:
```
  {{- $mode := dict "HostGW" "host-gw" "VXLAN" "vxlan" }}
      mode: {{ get $mode $.Values.cniFlannel.podNetworkMode }}

```

2025-01-20 11:02 UTC, apolovov commented on modules/035-cni-flannel/hooks/set_pod_network_mode.go
>  	input.Values.Set("cniFlannel.internal.podNetworkMode", podNetworkMode)
it isn't urgent to change.

2025-01-21 16:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-21 16:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2025-01-21 16:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2025-01-22 07:09 UTC, AndreyPavlovFlant commented on global-hooks/enable_cni.go
>  	return nil
Fixed

2025-01-22 16:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2025-01-22 16:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-22 19:46 UTC, AndreyPavlovFlant commented
/e2e/abort aws;WithoutNAT;containerd;1.27 12913011223 12913011223-2-con-1-27 /sys/deckhouse-oss/install:pr10517 ec2-user@3.79.146.33

2025-01-22 19:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-01-22 20:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-23 07:15 UTC, AndreyPavlovFlant commented
/e2e/abort aws;WithoutNAT;containerd;1.27 12916292981 12916292981-1-con-1-27 /sys/deckhouse-oss/install:pr10517

2025-01-23 07:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-01-23 07:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2025-01-23 07:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-23 07:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-23 07:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2025-01-23 07:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2025-01-23 09:00 UTC, AndreyPavlovFlant commented
/e2e/abort aws;WithoutNAT;containerd;1.27 12924198035 12924198035-1-con-1-27 /sys/deckhouse-oss/install:pr10517

2025-01-23 09:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-01-23 09:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-23 09:13 UTC, AndreyPavlovFlant commented
/e2e/abort aws;WithoutNAT;containerd;1.27 12925714324 12925714324-1-con-1-27 /sys/deckhouse-oss/install:pr10517

2025-01-23 09:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-01-24 09:17 UTC, apolovov approved these changes

2025-01-24 09:18 UTC, merged