[dhct] Add human readable error on dhctl converge except
deckhouse/deckhouse pull request #10589
Opened 2024-11-12 12:33 UTC by d2285

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-11-13 15:05 UTC, name212 commented on dhctl/pkg/operations/converge/converger.go
> +        "github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes"
imports are not sorted

2024-11-13 15:05 UTC, name212 requested changes
one thing

2024-11-14 07:46 UTC, d2285 commented on dhctl/pkg/operations/converge/converger.go
> +        "github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes"
fixed

2024-11-14 14:43 UTC, merged

2024-11-28 08:34 UTC, KraMorK commented
/backport 1.66