change python
deckhouse/deckhouse pull request #10582
Opened 2024-11-12 06:20 UTC by KraMorK

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-11-14 14:45 UTC, name212 approved these changes

2024-12-05 06:49 UTC, RomanenkoDenys requested changes
We should use own python not only in common-base, but in the all shell-operator images too.

2024-12-27 09:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2024-12-27 09:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-12-27 11:28 UTC, KraMorK commented
> We should use own python not only in common-base, but in the all shell-operator images too.

Done

2024-12-27 13:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-13 07:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-13 07:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-13 08:59 UTC, RomanenkoDenys commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
> +    - mkdir -p ~/.ssh && echo "StrictHostKeyChecking accept-new" > ~/.ssh/config
isn't needed

2025-01-13 09:00 UTC, RomanenkoDenys commented on modules/000-common/images/python-static/werf.inc.yaml
> +  {{- include "alt packages proxy" . | nindent 2 }}
isn't needed

2025-01-13 09:00 UTC, RomanenkoDenys reviewed
some nits

2025-01-13 10:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-14 11:56 UTC, alexey-gavrilov-flant commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
> +    - usr/lib/python3/site-packages
What do we copy /usr/lib/python3/site-packages for ?
If there are packages there, we should put the necessary packages through /opt/python-static/bin/pip3.

2025-01-14 11:56 UTC, alexey-gavrilov-flant commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
> +{{- $binaries := "/opt/python-static/bin/python3 /lib64/libz.so* /lib64/libexpat.so* /usr/lib64/libffi.so* /lib64/libcrypto.so* /lib64/libssl.so* /usr/sbin/dnsmasq /lib64/libnss_*" }}
Why do we copy the /opt/python-static/bin/python3 binary to /relocate if we copy the contents of /opt/python-static in the following image?

2025-01-14 12:13 UTC, alexey-gavrilov-flant commented on modules/000-common/images/shell-operator/werf.inc.yaml
> +  add: /
```
- image: common/python-static-artifact
  add: /opt/python-static
  before: setup
```
The smaller the scope in add, the faster the copying will be.
The “to” can be omitted if it is the same as “add”.

2025-01-14 12:13 UTC, alexey-gavrilov-flant commented on modules/000-common/images/shell-operator/werf.inc.yaml
> +  - export PATH="/opt/python-static/bin:$PATH"
What is this line for? It has no effect.
If you need guaranteed inheritance of a variable, it is better to add this.
```
docker:
  ENV:
    PATH: "/opt/python-static/bin:$PATH"
```

2025-01-14 12:13 UTC, alexey-gavrilov-flant commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
> +    - /opt/python-static/bin/pip3 install pyroute2 six ipcalc
You need to do as in the example in the [link](https://github.com/deckhouse/deckhouse/blob/330188255b420e48a0f687cc6a82a2cb38d6e1be/ee/modules/650-runtime-audit-engine/images/rules-loader/werf.inc.yaml#L58-L61).

2025-01-14 12:13 UTC, alexey-gavrilov-flant commented on modules/002-deckhouse/images/webhook-handler/werf.inc.yaml
> +  - /opt/python-static/bin/pip3 install -r /requirements.txt
You need to do as in the example in the [link](https://github.com/deckhouse/deckhouse/blob/330188255b420e48a0f687cc6a82a2cb38d6e1be/ee/modules/650-runtime-audit-engine/images/rules-loader/werf.inc.yaml#L58-L61).

2025-01-14 12:13 UTC, alexey-gavrilov-flant commented on modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml
> +  - /opt/python-static/bin/pip3 install -r /requirements.txt
You need to do as in the example in the [link](https://github.com/deckhouse/deckhouse/blob/330188255b420e48a0f687cc6a82a2cb38d6e1be/ee/modules/650-runtime-audit-engine/images/rules-loader/werf.inc.yaml#L58-L61).

2025-01-14 12:13 UTC, alexey-gavrilov-flant commented on modules/002-deckhouse/images/webhook-handler/werf.inc.yaml
> +    PATH: "/opt/python-static/bin:$PATH"
it is better to put it in the base image  `common/shell-operator`

2025-01-14 12:13 UTC, alexey-gavrilov-flant commented on modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml
> +  add: /
```
- image: common/python-static-artifact
  add: /opt/python-static
  before: setup
```
The smaller the scope in add, the faster the copying will be.
The “to” can be omitted if it is the same as “add”.

2025-01-14 12:13 UTC, alexey-gavrilov-flant commented on modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml
> +    PATH: "/opt/python-static/bin:$PATH"
it is better to put it in the base image common/shell-operator

2025-01-14 12:22 UTC, alexey-gavrilov-flant commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
>    - add: /{{ $.ModulePath }}modules/450-{{ $.ModuleName }}/images/{{ $.ImageName }}/prepare-config.py
In a good way, this code should be touched up as well. https://github.com/deckhouse/deckhouse/blob/330188255b420e48a0f687cc6a82a2cb38d6e1be/.werf/defines/base.tmpl#L90-L94

2025-01-14 12:23 UTC, KraMorK commented on modules/000-common/images/shell-operator/werf.inc.yaml
> +  - export PATH="/opt/python-static/bin:$PATH"
this is an intermediate image, there is no point in changing PATH outside the build console, it is only needed at the build stage. it would be more correct to use docker.ARG, not docker.ENV. I can do it like this

2025-01-14 12:25 UTC, alexey-gavrilov-flant commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
>    - add: /{{ $.ModulePath }}modules/450-{{ $.ModuleName }}/images/{{ $.ImageName }}/prepare-config.py
Here it is important to make sure that “externally” modules are included in e2e or to check their work in the cluster by yourself.

2025-01-15 08:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-20 10:21 UTC, alexey-gavrilov-flant commented on modules/000-common/images/shell-operator/werf.inc.yaml
> +  - export PATH="/opt/python-static/bin:$PATH"
Then the current string doesn't make sense.

2025-01-21 07:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-21 07:40 UTC, alexey-gavrilov-flant requested changes

2025-01-21 07:40 UTC, alexey-gavrilov-flant commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
> +    - /opt/python-static/bin/pip3 install -f file:///wheels --no-index -r requirements.txt
```
rm -rf /wheels
```

2025-01-21 09:04 UTC, KraMorK commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.29 12882098067 12882098067-1-con-1-29 /sys/deckhouse-oss/install:pr10582 redos@89.169.144.100

2025-01-21 09:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-01-21 09:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-21 10:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-21 11:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-22 07:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-22 08:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-24 03:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-24 06:53 UTC, alexey-gavrilov-flant approved these changes

2025-02-03 12:19 UTC, RomanenkoDenys commented
needs rebase

2025-02-26 09:38 UTC, name212 requested changes
Needs rebase and please check new python with external modules, eg virtualization or/and ceph-csi for example

2025-02-27 08:42 UTC, closed without merging