chore: update common module
deckhouse/deckhouse pull request #10753
Opened 2024-11-21 06:27 UTC by KraMorK

## Description

Reduce differences between cse and main branches. Standardize build, update module dependencies
## Why do we need it, and what problem does it solve?

Migrate cse changes to main branch
## Why do we need it in the patch release (if we do)?

not related to release
## What is the expected result?

Migrate cse changes to main branch
## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

```changes
section: common
type: chore
summary: Reduce differences between cse and main branches - common-images.
impact_level: low
```

2024-11-21 14:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-11-21 16:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2024-11-21 17:08 UTC, KraMorK commented
/e2e/abort eks;WithoutNAT;containerd;1.27 11957541171 11957541171-1-con-1-27 /sys/deckhouse-oss/install:pr10753

2024-11-21 17:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-11-21 17:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2024-11-22 08:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-11-27 08:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2024-11-27 08:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-11-29 03:26 UTC, Taior commented
/e2e/abort eks;WithoutNAT;containerd;1.27 12046506974 12046506974-1-con-1-27 /sys/deckhouse-oss/install:pr10753

2024-11-29 03:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @Taior. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-11-29 07:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2024-12-02 09:36 UTC, name212 commented on modules/000-common/images/check-kernel-version/werf.inc.yaml
> +artifact: {{ .ModuleName }}/{{ .ImageName }}-artifact
```suggestion
artifact: {{ $.ModuleName }}/{{ $.ImageName }}-artifact
```

2024-12-02 09:36 UTC, name212 commented on modules/000-common/images/check-kernel-version/werf.inc.yaml
> +from: {{ .Images.BASE_GOLANG_23_ALPINE }}
```suggestion
from: {{ $.Images.BASE_GOLANG_23_ALPINE }}
```

2024-12-02 09:39 UTC, name212 commented on modules/000-common/images/csi-external-provisioner/werf.inc.yaml
> +  - rm -r vendor
Why do we need remove vendor here?

2024-12-02 09:49 UTC, name212 commented on modules/000-common/images/iptables-wrapper/werf.inc.yaml
> +  - git clone {{ .SOURCE_REPO }}/kubernetes-sigs/iptables-wrappers.git /src
```suggestion
  - git clone {{ $.SOURCE_REPO }}/kubernetes-sigs/iptables-wrappers.git /src
```

2024-12-02 09:50 UTC, name212 commented on modules/000-common/images/kube-rbac-proxy/werf.inc.yaml
> +artifact: {{ .ModuleName }}/{{ .ImageName }}-artifact
```suggestion
artifact: {{ $.ModuleName }}/{{ $.ImageName }}-artifact
```

2024-12-02 09:52 UTC, name212 commented on modules/000-common/images/nginx-static/werf.inc.yaml
>  artifact: {{ .ModuleName }}/build-nginx-static-artifact
```suggestion
artifact: {{ $.ModuleName }}/build-nginx-static-artifact
```

2024-12-02 09:52 UTC, name212 commented on modules/000-common/images/nginx-static/werf.inc.yaml
> +from: {{ .Images.BASE_UBUNTU }}
```suggestion
from: {{ $.Images.BASE_UBUNTU }}
```

2024-12-02 09:54 UTC, name212 commented on modules/000-common/images/shell-operator/werf.inc.yaml
> +artifact: {{ .ModuleName }}/{{ $.ImageName }}-artifact
```suggestion
artifact: {{ $.ModuleName }}/{{ $.ImageName }}-artifact
```

2024-12-02 09:55 UTC, name212 commented on modules/000-common/images/shell-operator/werf.inc.yaml
>  image: {{ .ModuleName }}/{{ $.ImageName }}
```suggestion
image: {{ $.ModuleName }}/{{ $.ImageName }}
```

2024-12-02 09:55 UTC, name212 commented on modules/000-common/images/shell-operator/werf.inc.yaml
> +  - git clone --branch {{ $shellOperatorVersion }} --depth 1 {{ .SOURCE_REPO }}/flant/shell-operator.git /src/shell-operator
```suggestion
  - git clone --branch {{ $shellOperatorVersion }} --depth 1 {{ $.SOURCE_REPO }}/flant/shell-operator.git /src/shell-operator
```

2024-12-02 09:55 UTC, name212 commented on modules/000-common/images/shell-operator/werf.inc.yaml
> +  - git clone --depth 1 {{ .SOURCE_REPO }}/jqlang/jq --branch "jq-1.7.1" /src/jq
```suggestion
  - git clone --depth 1 {{ $.SOURCE_REPO }}/jqlang/jq --branch "jq-1.7.1" /src/jq
```

2024-12-02 09:56 UTC, name212 requested changes
Some nits

2024-12-04 08:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-12-04 10:02 UTC, KraMorK commented
/e2e/abort aws;WithoutNAT;containerd;1.27 12155676965 12155676965-1-con-1-27 /sys/deckhouse-oss/install:pr10753 ec2-user@52.58.158.9

2024-12-04 10:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-12-04 12:26 UTC, name212 approved these changes

2024-12-04 12:27 UTC, merged