[deckhouse-controller] rollout restart for deckhouse workloads (heritage=deckhouse) is forbidden
deckhouse/deckhouse pull request #10844
Opened 2024-11-27 13:53 UTC by juev

## Description

Fixed: #10752

## Why do we need it, and what problem does it solve?

Restart must be allowed for objects containing annotation

`spec.template.metadata.annotation."kubectl.kubernetes.io/restartedAt"`

## What is the expected result?

Deployment, StatefulSet, DaemonSet should do rollout restart gracefully

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: fix
summary: rollout restart for deckhouse workloads (heritage=deckhouse) is forbidden
impact_level: default
```

2024-11-27 14:53 UTC, juev commented
how I tested:

<img width="1499" alt="Screenshot 2024-11-27 at 17 29 53" src="https://github.com/user-attachments/assets/5169d5c8-8a91-4ec4-a0f8-36b6c053bfed">

2024-11-28 12:07 UTC, juev commented
Added the ability to change only the anotation `spec.templata.annotation.kubectl.kubernetes.io/restartedAt', any other change in objects is not allowed, as previously conceived.

2024-12-03 08:36 UTC, miklezzzz requested changes
couldn't restart a deployment without the `spec.template.annotations` field
```
  ....
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
    ....
```
and got the following reject:
```
kubectl rollout restart deployment echo-server  
error: failed to patch: deployments.apps "echo-server" is forbidden: ValidatingAdmissionPolicy 'label-objects.deckhouse.io' with binding 'heritage-label-objects.deckhouse.io' denied request: expression '!(oldObject.spec.template.metadata.annotations != null && object.spec.template.metadata.annotations != null) || (oldObject.spec.template.metadata.annotations == object.spec.template.metadata.annotations || (oldObject.spec.template.metadata.annotations != null && "kubectl.kubernetes.io/restartedAt" in oldObject.spec.template.metadata.annotations && object.spec.template.metadata.annotations != null && "kubectl.kubernetes.io/restartedAt" in object.spec.template.metadata.annotations && oldObject.spec.template.metadata.annotations["kubectl.kubernetes.io/restartedAt"] == object.spec.template.metadata.annotations["kubectl.kubernetes.io/restartedAt"]))' resulted in error: no such key: annotations
```

2024-12-05 14:11 UTC, juev commented
I tested the changes, now if there was no annotation before the start of the restart, it works correctly. The problem with the fact that by changing the annotation, we can also change the deployment itself, remains.

2024-12-09 15:49 UTC, miklezzzz approved these changes
seems to do the trick

2024-12-12 09:26 UTC, yalosev approved these changes

2024-12-12 13:06 UTC, merged