[ingress-nginx] Return lost TLSv1.3 if legacySSL activated
deckhouse/deckhouse pull request #10871
Opened 2024-11-28 22:52 UTC by unreturned

## Description
Return lost `TLSv1.3` if `legacySSL` activated.
Sync style between CRD description.
Update link to OWASP (old link deprecated).

## Why do we need it, and what problem does it solve?
If we set `legacySSL` for ingressnginxcontroller, we lost TLSv1.3, in logs of controller we have diff:
```
	-	ssl_protocols TLSv1.2 TLSv1.3;
	+	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

## Why do we need it in the patch release (if we do)?
Not necessarily.

## What is the expected result?
```
	-	ssl_protocols TLSv1.2 TLSv1.3;
	+	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
```

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ingress-nginx
type: fix
summary: Return lost TLSv1.3 if legacySSL activated
impact_level: default
```

2024-12-04 07:34 UTC, maxinsky approved these changes

2024-12-04 07:50 UTC, Lada7878 commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    Также опция разрешает legacy cipher suites для поддержки старых библиотек и программ: [OWASP Cipher String 'C'](https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Secu
Текст под ссылкой (анкор) должен сообщать, куда ведет ссылка. Поэтому под ссылкой нельзя писать «здесь» и «тут», «документ» и «файл», «ссылка» и «сайт». https://wiki.flant.ru/doc/redpolitika-flanta-dlya-tehnicheskih-pisatelej-i-redaktorov-y8FsQyHASF#h-oformlenie

2024-12-04 07:52 UTC, Lada7878 commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    **По умолчанию** включены только TLSv1.2, TLSv1.3 и самые новые cipher suites.
Давай "по умолчанию" сделаем по аналогии с прочими "по умолчанию" в этом тексте? Не жирным, а курсивом.

2024-12-04 08:58 UTC, Lada7878 approved these changes

2024-12-05 12:25 UTC, z9r5 commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    Разрешает следующие комбинации алгоритмов шифрования в порядке от наиболее надёжной к наименее надёжной: `ECDHE-ECDSA-AES256-GCM-SHA384`, `ECDHE-RSA-AES256-GCM-SHA384`, `ECDHE-ECD
```suggestion
                    Разрешает следующие комбинации алгоритмов шифрования в порядке от наиболее надёжного к наименее надёжному: `ECDHE-ECDSA-AES256-GCM-SHA384`, `ECDHE-RSA-AES256-GCM-SHA384`, `ECDHE-ECDSA-CHACHA20-POLY1305`, `ECDHE-RSA-CHACHA20-POLY1305`, `ECDHE-ECDSA-AES128-GCM-SHA256`, `ECDHE-RSA-AES128-GCM-SHA256`, `ECDHE-ECDSA-AES256-SHA384`, `ECDHE-RSA-AES256-SHA384`, `ECDHE-ECDSA-AES128-SHA256`, `ECDHE-RSA-AES128-SHA256`, `ECDHE-ECDSA-AES256-SHA`, `ECDHE-RSA-AES256-SHA`, `ECDHE-ECDSA-AES128-SHA`, `ECDHE-RSA-AES128-SHA`, `AES256-GCM-SHA384`, `AES128-GCM-SHA256`, `AES256-SHA256`, `AES128-SHA256`, `AES256-SHA`, `AES128-SHA`.
```

2024-12-05 12:27 UTC, z9r5 approved these changes

2024-12-09 11:42 UTC, unreturned commented
just rebased

2024-12-13 12:38 UTC, Beastlex requested changes

2024-12-13 12:38 UTC, Beastlex commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    Разрешает работу по следующим версиям протокола TLS: `TLSv1`, `TLSv1.1`, `TLSv1.2`, `TLSv1.3`.
```suggestion
                    Работа разрешена для следующих версий протокола TLS: `TLSv1`, `TLSv1.1`, `TLSv1.2`, `TLSv1.3`.
```

2024-12-13 12:38 UTC, Beastlex commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    Разрешает следующие комбинации алгоритмов шифрования в порядке от наиболее надёжной к наименее надёжной: `ECDHE-ECDSA-AES256-GCM-SHA384`, `ECDHE-RSA-AES256-GCM-SHA384`, `ECDHE-ECD
```suggestion
                    Допустимые комбинации алгоритмов шифрования расположены в порядке убывания надёжности: `ECDHE-ECDSA-AES256-GCM-SHA384`, `ECDHE-RSA-AES256-GCM-SHA384`, `ECDHE-ECDSA-CHACHA20-POLY1305`, `ECDHE-RSA-CHACHA20-POLY1305`, `ECDHE-ECDSA-AES128-GCM-SHA256`, `ECDHE-RSA-AES128-GCM-SHA256`, `ECDHE-ECDSA-AES256-SHA384`, `ECDHE-RSA-AES256-SHA384`, `ECDHE-ECDSA-AES128-SHA256`, `ECDHE-RSA-AES128-SHA256`, `ECDHE-ECDSA-AES256-SHA`, `ECDHE-RSA-AES256-SHA`, `ECDHE-ECDSA-AES128-SHA`, `ECDHE-RSA-AES128-SHA`, `AES256-GCM-SHA384`, `AES128-GCM-SHA256`, `AES256-SHA256`, `AES128-SHA256`, `AES256-SHA`, `AES128-SHA`.
```

2024-12-13 12:38 UTC, Beastlex commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    Разрешены ли устаревшие версии протокола TLS и алгоритмов шифрования (cipher suites).
```suggestion
                    Определяет, разрешены ли устаревшие версии протокола TLS и алгоритмов шифрования (cipher suites).
```

2024-12-13 12:51 UTC, z9r5 commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    Разрешает работу по следующим версиям протокола TLS: `TLSv1`, `TLSv1.1`, `TLSv1.2`, `TLSv1.3`.
@Lada7878 Please review

2024-12-13 13:17 UTC, Lada7878 commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    Разрешает следующие комбинации алгоритмов шифрования в порядке от наиболее надёжной к наименее надёжной: `ECDHE-ECDSA-AES256-GCM-SHA384`, `ECDHE-RSA-AES256-GCM-SHA384`, `ECDHE-ECD
```suggestion
                    Допустимые комбинации алгоритмов шифрования представлены по степени надёжности от самой высокой к самой низкой: `ECDHE-ECDSA-AES256-GCM-SHA384`, `ECDHE-RSA-AES256-GCM-SHA384`, `ECDHE-ECDSA-CHACHA20-POLY1305`, `ECDHE-RSA-CHACHA20-POLY1305`, `ECDHE-ECDSA-AES128-GCM-SHA256`, `ECDHE-RSA-AES128-GCM-SHA256`, `ECDHE-ECDSA-AES256-SHA384`, `ECDHE-RSA-AES256-SHA384`, `ECDHE-ECDSA-AES128-SHA256`, `ECDHE-RSA-AES128-SHA256`, `ECDHE-ECDSA-AES256-SHA`, `ECDHE-RSA-AES256-SHA`, `ECDHE-ECDSA-AES128-SHA`, `ECDHE-RSA-AES128-SHA`, `AES256-GCM-SHA384`, `AES128-GCM-SHA256`, `AES256-SHA256`, `AES128-SHA256`, `AES256-SHA`, `AES128-SHA`.
```

2024-12-14 11:35 UTC, z9r5 commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                    Допустимые комбинации алгоритмов шифрования, расположеные в порядке от наиболее надёжной к наименее надёжной: `ECDHE-ECDSA-AES256-GCM-SHA384`, `ECDHE-RSA-AES256-GCM-SHA384`, `ECDH
```suggestion
                    Допустимые комбинации алгоритмов шифрования, расположенные в порядке от наиболее надёжной к наименее надёжной: `ECDHE-ECDSA-AES256-GCM-SHA384`, `ECDHE-RSA-AES256-GCM-SHA384`, `ECDHE-ECDSA-CHACHA20-POLY1305`, `ECDHE-RSA-CHACHA20-POLY1305`, `ECDHE-ECDSA-AES128-GCM-SHA256`, `ECDHE-RSA-AES128-GCM-SHA256`, `ECDHE-ECDSA-AES256-SHA384`, `ECDHE-RSA-AES256-SHA384`, `ECDHE-ECDSA-AES128-SHA256`, `ECDHE-RSA-AES128-SHA256`, `ECDHE-ECDSA-AES256-SHA`, `ECDHE-RSA-AES256-SHA`, `ECDHE-ECDSA-AES128-SHA`, `ECDHE-RSA-AES128-SHA`, `AES256-GCM-SHA384`, `AES128-GCM-SHA256`, `AES256-SHA256`, `AES128-SHA256`, `AES256-SHA`, `AES128-SHA`.
```

2024-12-17 10:05 UTC, Beastlex approved these changes

2025-01-10 12:02 UTC, merged