[dhctl] Add quotes to highlight the error in the component when loading
deckhouse/deckhouse pull request #10877
Opened 2024-11-29 10:34 UTC by VaLosev

## Description
With bootstrap an error may occur:

 `❗ ~ bashible dependency tar error: execute command 'command': exit status 1 - Warning: Permanently`

This can lead to diagnostic confusion due to a misunderstanding of the "tar" component.

## Why do we need it, and what problem does it solve?
To avoid confusion during diagnostics, it is suggested to highlight the problematic component with quotation marks:

## Why do we need it in the patch release (if we do)?

## What is the expected result?

` ❗ ~ bashible dependency 'tar' error: execute command 'command': exit status 1 - Warning: Permanently`

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: chore
summary: add quotes to highlight the error in the component when loading
impact_level: low
```

2024-11-29 16:14 UTC, name212 commented
@VaLosev Thank you for your contribution!
Can you fix the DCO issue? https://github.com/apps/dco

2024-11-29 16:14 UTC, name212 requested changes
DCO

2024-12-02 16:11 UTC, VaLosev commented
DCO fixed.
I don't have enough rights to change labels to run tests.
I'll try to fix it tomorrow.

2024-12-04 11:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @VaLosev. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2024-12-04 16:00 UTC, VaLosev commented
Error in yandex
```
Error: error creating IAM OIDC Provider: LimitExceeded: Cannot exceed quota for OpenIdConnectProvidersPerAccount: 100
	status code: 409, request id: d965510e-e105-429e-8fb2-480784740b0c

  on .terraform/modules/eks/main.tf line 212, in resource "aws_iam_openid_connect_provider" "oidc_provider":
 212: resource "aws_iam_openid_connect_provider" "oidc_provider" {
```

2024-12-05 11:51 UTC, VaLosev commented
/e2e/abort eks;WithoutNAT;containerd;1.27 12158898757 12158898757-3-con-1-27 /sys/deckhouse-oss/install:pr10877

2024-12-05 11:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @VaLosev. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-12-05 14:44 UTC, VaLosev commented
/e2e/abort eks;WithoutNAT;containerd;1.27 12158898757 12158898757-2-con-1-27 /sys/deckhouse-oss/install:pr10877

2024-12-05 14:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @VaLosev. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-12-05 15:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @VaLosev. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-12-06 10:18 UTC, VaLosev commented
Error creating branch, created new one in [#10983](https://github.com/deckhouse/deckhouse/pull/10983)

2024-12-06 10:18 UTC, closed without merging