[extended-monitoring] Add namespace-scoped overrides for threshold labels
deckhouse/deckhouse pull request #10880
Opened 2024-11-29 15:35 UTC by ykav-flant

Add namespace-scoped overrides for threshold.extended-monitoring.flant.com labels
## Description
- Enable overriding default thresholds with labels from the namespace using `threshold.extended-monitoring.flant.com`.

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2025-01-16 13:54 UTC, vladimirGuryanov requested changes

2025-01-16 13:54 UTC, vladimirGuryanov commented on modules/340-extended-monitoring/docs/CONFIGURATION.md
> +If you want to override the default thresholds for all objects in a namespace, you can set the `threshold.extended-monitoring.deckhouse.io/` label at the namespace level. For example:
inode it's not namespaced metric, can you use in example something like this: 

```text
To change the threshold for the 5xx-warning alert for all ingresses in a namespace, you can set the following label on the namespace:
threshold.extended-monitoring.deckhouse.io/5xx-warning: "5"
```

2025-01-16 14:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @ykav-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-17 12:47 UTC, z9r5 approved these changes

2025-01-17 12:52 UTC, merged