[candi] replace logrus
deckhouse/deckhouse pull request #10909
Opened 2024-12-03 08:06 UTC by sprait

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-12-09 07:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-12-10 11:14 UTC, name212 commented on dhctl/go.mod
> +	github.com/sirupsen/logrus v1.9.3 // indirect
logrus was not deleted fully

2024-12-10 11:14 UTC, name212 requested changes
logrus was not deleted fully

2024-12-11 10:07 UTC, sprait commented on modules/039-registry-packages-proxy/images/registry-packages-proxy/src/go.mod
> +	github.com/sirupsen/logrus v1.9.3 // indirect
we discussed and decided that we would not avoid  inderect dependencies.

2024-12-18 09:44 UTC, name212 approved these changes

2024-12-18 09:45 UTC, merged