[ingress-nginx] Add requirements check for ModuleConfig defaultControllerVersion
deckhouse/deckhouse pull request #10941
Opened 2024-12-04 12:22 UTC by Beastlex

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-12-05 08:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-12-05 12:00 UTC, tarabrind approved these changes

2024-12-09 23:28 UTC, apolovov requested changes

2024-12-09 23:28 UTC, apolovov commented on modules/402-ingress-nginx/hooks/minimal_ingress_nginx_version.go
> +	moduleConfigVersionKey  = "ingressNginx:moduleConfigVersion"
```suggestion
	configuredDefaultVersionKey  = "ingressNginx:configuredDefaultVersion"
```
moduleConfigVersion is version of ModuleConfig ("1" in our case).

2024-12-19 14:41 UTC, AndreyPavlovFlant requested changes

2024-12-20 08:02 UTC, AndreyPavlovFlant approved these changes

2024-12-20 10:23 UTC, merged