Chore/upgrade registrypackages build
deckhouse/deckhouse pull request #11006
Opened 2024-12-09 08:07 UTC by KraMorK

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-12-09 13:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-12-09 13:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2024-12-09 14:18 UTC, KraMorK commented
/e2e/abort azure;Standard;containerd;1.29 12236736021 12236736021-1-con-1-29 /sys/deckhouse-oss/install:pr11006 azureuser@20.86.138.250

2024-12-09 14:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-12-09 14:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2024-12-18 11:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2024-12-19 09:00 UTC, RomanenkoDenys commented on modules/007-registrypackages/images/containerd/werf.inc.yaml
> +fromArtifact: common/src-artifact
fromImage

2024-12-19 09:01 UTC, RomanenkoDenys commented on modules/007-registrypackages/images/crictl/werf.inc.yaml
> +fromArtifact: common/src-artifact
fromImage

2024-12-19 09:02 UTC, RomanenkoDenys commented on modules/007-registrypackages/images/d8-curl/werf.inc.yaml
> +fromArtifact: common/src-artifact
fromImage

2024-12-19 09:02 UTC, RomanenkoDenys commented on modules/007-registrypackages/images/d8/werf.inc.yaml
> +fromArtifact: common/src-artifact
fromImage

2024-12-19 09:02 UTC, RomanenkoDenys commented on modules/007-registrypackages/images/docker-registry/werf.inc.yaml
> +fromArtifact: common/src-artifact
fromImage

2024-12-19 09:02 UTC, RomanenkoDenys commented on modules/007-registrypackages/images/e2fsprogs/werf.inc.yaml
> +fromArtifact: common/src-artifact
fromImage

2024-12-19 09:03 UTC, RomanenkoDenys requested changes
some nits

2024-12-19 09:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2024-12-19 14:08 UTC, KraMorK commented
/e2e/abort azure;Standard;containerd;1.29 12409758647 12409758647-1-con-1-29 /sys/deckhouse-oss/install:pr11006 azureuser@20.86.148.16

2024-12-19 14:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-12-25 11:09 UTC, sprait requested changes
one suggestion

2024-12-25 11:09 UTC, sprait commented on modules/007-registrypackages/images/socat/werf.inc.yaml
> +- artifact: {{ $.ModuleName }}/{{ $.ImageName }}-src-artifact-{{ $image_version }}
```suggestion
- image: {{ $.ModuleName }}/{{ $.ImageName }}-src-artifact-{{ $image_version }}
```

2024-12-26 06:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-12-26 06:44 UTC, sprait requested changes
some suggestions

2024-12-26 06:44 UTC, sprait commented on modules/007-registrypackages/images/crictl/werf.inc.yaml
> +from: {{ $.Images.BASE_GOLANG_23_ALPINE_DEV }}
```suggestion
from: {{ $.Images.BASE_GOLANG_23_ALPINE }}
```

2024-12-26 06:44 UTC, sprait commented on modules/007-registrypackages/images/docker-registry/werf.inc.yaml
>  from: {{ $.Images.BASE_GOLANG_22_ALPINE_DEV }}
```suggestion
from: {{ $.Images.BASE_GOLANG_23_ALPINE }}
```

2024-12-26 06:44 UTC, sprait commented on werf.yaml
> +- artifact: registrypackages/d8-curl-artifact-8-9-1
```suggestion
- image: registrypackages/d8-curl-artifact-8-9-1
```

2024-12-26 07:26 UTC, sprait approved these changes

2024-12-26 08:56 UTC, name212 approved these changes

2024-12-26 08:59 UTC, merged