chore: admission policy engine src artifact
deckhouse/deckhouse pull request #11021
Opened 2024-12-10 06:26 UTC by KraMorK

## Description

Reduce differences between cse and main branches. Standardize build, update module dependencies
## Why do we need it, and what problem does it solve?

Migrate cse changes to main branch
## Why do we need it in the patch release (if we do)?

Not related to release.
## What is the expected result?

Reduce differences between cse and main branches
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: admission-policy-engine
type: chore
summary: Migrate cse changes to main branch.
impact_level: low
```

2024-12-10 08:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-12-10 08:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-12-10 11:36 UTC, KraMorK commented
/e2e/abort aws;WithoutNAT;containerd;1.29 12251912934 12251912934-1-con-1-29 /sys/deckhouse-oss/install:pr11021 ec2-user@52.59.64.123

2024-12-10 11:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-12-10 11:37 UTC, z9r5 approved these changes

2024-12-10 11:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-12-18 09:59 UTC, name212 commented on modules/015-admission-policy-engine/crds/native/config-customresourcedefinition.yaml
> +            description: |-
why do we need this changes?

2024-12-18 10:00 UTC, name212 commented on modules/015-admission-policy-engine/images/constraint-exporter/werf.inc.yaml
> +fromCacheVersion: "2024-09-24 15:35"
please remove it

2024-12-18 10:01 UTC, name212 requested changes
one question one thing

2025-02-03 11:16 UTC, closed without merging