[dhctl] Global converge refactoring
deckhouse/deckhouse pull request #11086
Opened 2024-12-13 23:01 UTC by name212

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-12-16 14:39 UTC, mvasl requested changes

2024-12-16 14:39 UTC, mvasl commented on dhctl/pkg/kubernetes/actions/entity/node_user.go
> +				return err
I'm losing it here, why try to create object if it already exists? Did you mean to use `Update`?

2024-12-16 14:39 UTC, mvasl commented on dhctl/pkg/kubernetes/kube.go
> +type KubeClientGetter interface {
I'm not insisting but `KubeClientProvider` sounds like a better fit to me

2024-12-16 14:39 UTC, mvasl commented on dhctl/pkg/kubernetes/kube.go
> +
```suggestion
var _ KubeClientGetter = &SimpleKubeClientGetter{}
```

2024-12-16 14:39 UTC, mvasl commented on dhctl/pkg/operations/converge/commander/check.go
> +type NodeGroupGroupOptions struct {
`NodeGroupOptions`?

2024-12-16 14:39 UTC, mvasl commented on dhctl/pkg/operations/converge/commander/check.go
> +		step = "master-node"
These step names should probably go to some enum

2024-12-18 07:09 UTC, sprait approved these changes

2025-02-14 07:11 UTC, name212 commented on dhctl/pkg/operations/phases/phases.go
> +	ScaleToSingleMasterPhase OperationPhase = "SScaleToSingleMaster"
done

2025-02-14 07:26 UTC, mvasl commented on dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
> +		// TODO check that is correct
Is it?

2025-02-14 07:53 UTC, name212 commented on dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
> +		// TODO check that is correct
forget to delete, thanks

2025-02-14 08:52 UTC, merged