[huaweicloud] docs
deckhouse/deckhouse pull request #11094
Opened 2024-12-16 08:51 UTC by aleksey-su

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2025-01-22 05:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2025-01-22 06:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2025-01-22 06:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2025-01-27 12:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2025-01-30 12:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @Zhbert. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2025-01-30 13:13 UTC, Zhbert requested changes
Some comments

2025-01-30 13:48 UTC, mortelumina98 commented on docs/site/_includes/getting_started/huaweicloud/partials/config.ru.yml.standard.other.inc
> +  # [<ru>] Включите Elastic IP для мастер узлов.
```suggestion
  # [<ru>] Включите Elastic IP для master-узлов.
```

2025-01-30 13:48 UTC, mortelumina98 commented on ee/candi/cloud-providers/huaweicloud/docs/LAYOUTS_RU.md
> +* Elastic IP-адрес можно назначить мастер-узлу.
```suggestion
* Elastic IP-адрес можно назначить master-узлу.
```

2025-01-30 13:48 UTC, mortelumina98 commented on docs/site/_includes/getting_started/huaweicloud/partials/config.yml.standard.other.inc
> +  # [<ru>] Включите Elastic IP для мастер узлов.
```suggestion
  # [<ru>] Включите Elastic IP для master-узлов.
```

2025-01-31 08:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @Zhbert. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2025-01-31 08:49 UTC, Zhbert approved these changes

2025-01-31 09:16 UTC, z9r5 approved these changes

2025-02-02 17:49 UTC, merged