[istio] Migrate images to werf with distroless
deckhouse/deckhouse pull request #11189
Opened 2024-12-20 12:30 UTC by skurbatov

## Description
The source code assembly for all components has been implemented. The vulnerabilities identified by the security scanner during the build have been fixed. This made it possible to increase the security of the system components.

## Why do we need it, and what problem does it solve?
Increased security, fix vulnerabilities, and a controlled source code build process

## What is the expected result?
The functionality of the components works perfectly.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: istio
type: feature
summary: Istio components builded from source without CVE
impact_level: default
```

2025-01-23 18:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-23 18:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2025-01-23 18:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2025-01-23 18:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2025-01-23 18:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2025-01-23 18:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2025-01-23 19:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2025-01-24 07:56 UTC, AndreyPavlovFlant requested changes

2025-01-24 07:56 UTC, AndreyPavlovFlant commented on modules/110-istio/images/proxyv2-v1x19x7/werf.inc.yaml
> +    apt-get install -y ca-certificates iptables curl
iptables should be replaced with a self-built one, as in 1.21.6.

2025-01-24 07:56 UTC, AndreyPavlovFlant commented on modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml
> +---
It would be helpful to include documentation or instructions that explain the factors that guided our decisions during the building process and the reasons behind our choices.

2025-01-24 11:50 UTC, skurbatov commented on modules/110-istio/images/proxyv2-v1x19x7/werf.inc.yaml
> +    apt-get install -y ca-certificates iptables curl
Fixed

2025-01-27 15:40 UTC, alexey-gavrilov-flant commented on modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml
> +    clang14.0 clang14.0-tools lld14.0 llvm14.0-devel \
The image also includes llvm-18, which is not used.

2025-01-28 11:25 UTC, alexey-gavrilov-flant commented on ee/modules/110-istio/images/api-proxy/werf.inc.yaml
> +    - "*.go"
shell is required otherwise werf will not handle updates to src correctly.
```suggestion
    - "*.go"
shell:
  install:
  - cd /src
```

2025-01-28 12:39 UTC, skurbatov commented on ee/modules/110-istio/images/api-proxy/werf.inc.yaml
> +- add: /{{ $.ModulePath }}modules/{{ $.ModulePriority }}-{{ $.ModuleName }}/images/{{ $.ImageName }}
Fixed

2025-01-28 12:41 UTC, skurbatov commented on ee/modules/110-istio/images/metadata-exporter/werf.inc.yaml
> +  - rm -rf  /var/log/*log /var/lib/apt/lists/* /var/log/apt/* /var/lib/dpkg/*-old /var/cache/debconf/*-old
Add this string and I left the deletion of the log files, as this is the final image.

2025-01-28 12:43 UTC, skurbatov commented on modules/110-istio/images/proxyv2-v1x19x7/werf.inc.yaml
> +  - apt-get update && apt-get install -y ca-certificates
fixed

2025-01-28 12:43 UTC, skurbatov commented on ee/modules/110-istio/images/api-proxy/werf.inc.yaml
> +    - "*.go"
fixed

2025-01-28 12:45 UTC, skurbatov commented on ee/modules/110-istio/images/metadata-exporter/werf.inc.yaml
> +fromImage: common/alt-p11
To debug in this image, needed a shell, it is present in the Alt Linux image. That's why we left it, and in the future we plan to switch to distroless for this component.

2025-01-28 14:52 UTC, skurbatov commented on ee/modules/110-istio/images/metadata-exporter/werf.inc.yaml
> +- add: /{{ $.ModulePath }}modules/{{ $.ModulePriority }}-{{ $.ModuleName }}/images/{{ $.ImageName }}
fixed

2025-01-28 15:07 UTC, skurbatov commented on modules/110-istio/images/common-v1x19x7/werf.inc.yaml
> +  - find /patches -name '*.patch' | xargs git apply --verbose
fixed

2025-01-28 15:07 UTC, skurbatov commented on modules/110-istio/images/common-v1x21x6/werf.inc.yaml
> +  - find /patches -name '*.patch' | xargs git apply --verbose
fixed

2025-01-28 15:12 UTC, skurbatov commented on modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml
> +    clang14.0 clang14.0-tools lld14.0 llvm14.0-devel \
For build istio envoy needed clang and llvm version 14.0. We cannot change the build to alpine linux, as it is not designed for this operating system. We cannot delete clan18.0 and so on, since it is a dependency of clan14.0 in Alt linux.

2025-01-28 17:33 UTC, AndreyPavlovFlant approved these changes

2025-01-28 17:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-28 17:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2025-01-28 17:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2025-01-28 17:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2025-01-29 09:41 UTC, alexey-gavrilov-flant commented on modules/110-istio/images/cni-v1x21x6/werf.inc.yaml
> +  - go mod tidy
```suggestion
  - go mod download
```

2025-01-29 09:49 UTC, alexey-gavrilov-flant commented on modules/110-istio/images/pilot-v1x21x6/werf.inc.yaml
> +  - go mod tidy
```suggestion
  - go mod download
```

2025-01-29 09:49 UTC, alexey-gavrilov-flant commented on modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml
> +  - go mod tidy
```suggestion
  - go mod download
```

2025-01-29 09:50 UTC, alexey-gavrilov-flant commented on modules/110-istio/images/operator-v1x21x6/werf.inc.yaml
> +  - go mod tidy
```suggestion
  - go mod download
```

2025-01-29 10:34 UTC, alexey-gavrilov-flant approved these changes

2025-01-30 09:06 UTC, merged