[node-local-dns] Migrate to timeseries for dashboards
deckhouse/deckhouse pull request #11228
Opened 2024-12-23 15:21 UTC by scaps1

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2025-01-15 09:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-16 05:54 UTC, sprait approved these changes

2025-01-17 15:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-17 22:21 UTC, vladimirGuryanov commented
Need to hide  “Total” line from the graph (not from the legend) in all panels.  Additional, if “Total” will have yellow color in legend, it will be great.

2025-01-20 15:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-20 16:00 UTC, vladimirGuryanov requested changes

2025-01-20 16:00 UTC, vladimirGuryanov commented on ee/be/modules/350-node-local-dns/monitoring/grafana-dashboards/kubernetes-cluster/dns-node-local.json
> +  "editable": true,
All imbedded dashboards must me not editable.
```suggestion
  "editable": false,
```

2025-01-20 16:00 UTC, vladimirGuryanov commented on ee/be/modules/350-node-local-dns/monitoring/grafana-dashboards/kubernetes-cluster/dns-node-local.json
> +  "uid": "HrJTjvuiz2",
It's not good idea to change the dashboard uid.
```suggestion
  "uid": "HrJTjvuiz",
```

2025-01-20 17:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @scaps1. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-20 20:20 UTC, vladimirGuryanov approved these changes

2025-01-20 20:24 UTC, merged