[node-manager] cse-1.67 refactor
deckhouse/deckhouse pull request #11222
Opened 2024-12-23 12:22 UTC by sprait

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-12-24 14:30 UTC, z9r5 approved these changes

2024-12-25 09:49 UTC, RomanenkoDenys requested changes

2024-12-25 09:49 UTC, RomanenkoDenys commented on modules/040-node-manager/images/early-oom/werf.inc.yaml
> +from: {{ .Images.BASE_GOLANG_20_ALPINE }}
```suggestion
from: {{ .Images.BASE_GOLANG_23_ALPINE }}
```

2024-12-25 09:49 UTC, RomanenkoDenys commented on modules/040-node-manager/images/fencing-agent/werf.inc.yaml
> +from: {{ $.Images.BASE_GOLANG_21_ALPINE_DEV }}
```suggestion
from: {{ $.Images.BASE_GOLANG_23_ALPINE }}
```

2024-12-25 09:49 UTC, RomanenkoDenys commented on modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
>  from: {{ .Images.BASE_GOLANG_20_ALPINE }}
```suggestion
from: {{ .Images.BASE_GOLANG_23_ALPINE }}
```

2024-12-25 13:31 UTC, merged