Chore/upgrade deckhouse tools build to main
deckhouse/deckhouse pull request #11254
Opened 2024-12-24 11:48 UTC by KraMorK

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-12-25 10:04 UTC, RomanenkoDenys commented on modules/800-deckhouse-tools/images/web/werf.inc.yaml
> +  - git apply /src/patches/*.patch --verbose
```suggestion
  - git describe --tags > VERSION
  - sed -i "s|sh: git describe --tags|sh: cat VERSION|" Taskfile
```

2024-12-25 10:05 UTC, RomanenkoDenys requested changes
Please remove patch and patch Taskfile on-the-fly

2024-12-26 06:52 UTC, KraMorK commented
> Please remove patch and patch Taskfile on-the-fly

Done

2024-12-28 08:53 UTC, sprait approved these changes

2025-01-02 16:43 UTC, RomanenkoDenys commented on modules/800-deckhouse-tools/images/web/werf.inc.yaml
>      - cd /app
```suggestion
    {{- include "node packages proxy" . | nindent 4 }}
    - cd /app
```

2025-01-02 19:54 UTC, RomanenkoDenys approved these changes
LGTM

2025-01-02 19:54 UTC, merged