[snapshot-controller] Update build and bump version
deckhouse/deckhouse pull request #11279
Opened 2024-12-25 06:11 UTC by YuryLysov

## Description
Update build and bump version to 8.2.0

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: snapshot-controller
type: chore
summary: Update build and bump version to 8.2.0.
impact_level: default
```

2024-12-28 12:01 UTC, sprait requested changes
one thing

2024-12-28 12:01 UTC, sprait commented on modules/045-snapshot-controller/images/snapshot-validation-webhook/werf.inc.yaml
>    - mkdir -p ~/.ssh && echo "StrictHostKeyChecking accept-new" > ~/.ssh/config
the same

2024-12-28 12:18 UTC, YuryLysov commented on modules/045-snapshot-controller/images/snapshot-controller/werf.inc.yaml
>    - mkdir -p ~/.ssh && echo "StrictHostKeyChecking accept-new" > ~/.ssh/config
Done

2024-12-28 12:18 UTC, YuryLysov commented on modules/045-snapshot-controller/images/snapshot-validation-webhook/werf.inc.yaml
>    - mkdir -p ~/.ssh && echo "StrictHostKeyChecking accept-new" > ~/.ssh/config
Done

2024-12-28 13:30 UTC, sprait approved these changes

2025-01-08 14:40 UTC, z9r5 approved these changes

2025-01-10 13:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-10 13:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @YuryLysov. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2025-01-10 14:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @YuryLysov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2025-01-13 07:19 UTC, merged