[cilium-hubble] bump cilium version to 1.16.5
deckhouse/deckhouse pull request #11293
Opened 2024-12-25 10:59 UTC by Beastlex

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2025-01-09 06:28 UTC, RomanenkoDenys requested changes
some nits

2025-01-09 14:27 UTC, apolovov requested changes
a nit

2025-01-09 14:27 UTC, apolovov commented on modules/500-cilium-hubble/images/relay/patches/go-mod.patch
> +diff --git a/Documentation/requirements.txt b/Documentation/requirements.txt
Why renamed?
Call it 001-go-mod.patch

2025-01-09 14:28 UTC, apolovov approved these changes

2025-01-13 11:07 UTC, RomanenkoDenys approved these changes

2025-01-13 11:07 UTC, merged