[extended-monitoring] Bump versions and update build
deckhouse/deckhouse pull request #11328
Opened 2024-12-26 09:35 UTC by YuryLysov

## Description

Bump versions and update build

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: extended-monitoring
type: chore
summary: Bump versions and update build.
impact_level: default
```

2025-01-02 17:13 UTC, RomanenkoDenys commented on modules/340-extended-monitoring/images/image-availability-exporter/werf.inc.yaml
> +  - mkdir -p ~/.ssh && echo "StrictHostKeyChecking accept-new" > ~/.ssh/config
Why we need openssh-client here ?

2025-01-02 17:13 UTC, RomanenkoDenys requested changes
some nits

2025-01-02 17:45 UTC, YuryLysov commented on modules/340-extended-monitoring/images/image-availability-exporter/werf.inc.yaml
> +  - mkdir -p ~/.ssh && echo "StrictHostKeyChecking accept-new" > ~/.ssh/config
Fixed

2025-01-09 06:48 UTC, RomanenkoDenys commented on modules/340-extended-monitoring/images/cert-exporter/werf.inc.yaml
> +  - apk add --no-cache make bash
```suggestion
  {{- include "alpine packages proxy" . | nindent 2 }}
  - apk add --no-cache make bash
```

2025-01-09 06:48 UTC, RomanenkoDenys commented on modules/340-extended-monitoring/images/events-exporter/werf.inc.yaml
> +  - apk add --no-cache make bash
```suggestion
  {{- include "alpine packages proxy" . | nindent 2 }}
  - apk add --no-cache make bash
```

2025-01-09 06:50 UTC, RomanenkoDenys commented on modules/340-extended-monitoring/images/extended-monitoring-exporter/werf.inc.yaml
> +    add: /opt/python-static/lib/python3.11
```suggestion
    add: /opt/python-static/lib/python3*
```

2025-01-09 06:50 UTC, RomanenkoDenys commented on modules/340-extended-monitoring/images/extended-monitoring-exporter/werf.inc.yaml
> +    add: /opt/python-static/lib/python3.11
```suggestion
    add: /opt/python-static/lib/python3*
```

2025-01-09 07:01 UTC, YuryLysov commented on modules/340-extended-monitoring/images/events-exporter/werf.inc.yaml
> +  - apk add --no-cache make bash
Done

2025-01-09 07:01 UTC, YuryLysov commented on modules/340-extended-monitoring/images/extended-monitoring-exporter/werf.inc.yaml
> +    add: /opt/python-static/lib/python3.11
Done

2025-01-09 10:40 UTC, RomanenkoDenys approved these changes

2025-01-10 11:34 UTC, RomanenkoDenys approved these changes

2025-01-10 11:34 UTC, merged