[openvpn] Go hooks
deckhouse/deckhouse pull request #1489
Opened 2022-04-27 23:39 UTC by vitaliy-sn

## Description

This MR is a part of "Global" Deckhouse refactoring.

## Why do we need it, and what problem does it solve?

It is aimed to improve UX and DX.

Go is more reliable and suitable to describe cloud infrastructure components, especially in distributed systems/environments
Open API specs will help us with bounding a contract between user and deckhouse, and between hooks and helm
An Open API spec for a module will become the single source of truth (documenting, validating, testing)
More tests, more stability

## Changelog entries

```changes
section: openvpn
type: feature
summary: Hooks rewritten in Go.
```

2022-05-04 10:20 UTC, nabokihms requested changes

2022-05-04 10:20 UTC, nabokihms commented on ee/fe/modules/500-openvpn/hooks/copy_rbd_secret.go
> +}, copyRBDSecretHandler)
There is the same hook in the `prometheus` module. It is required to move it to the go_lib then.

2022-05-04 10:20 UTC, nabokihms commented on ee/fe/modules/500-openvpn/hooks/generate_password.go
> +func generatePassword(input *go_hook.HookInput) error {
Let's also move this hook to the shared library (and replace it for other modules).

2022-05-04 10:20 UTC, nabokihms commented on ee/fe/modules/500-openvpn/hooks/set_push_routes.go
> +	return nil
What with the `KUBE_NODES_INFO=$(kubectl get nodes -o json)`? Is it crucial to have routes to nodes?

2022-05-13 21:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-05-13 21:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-05-13 21:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-05-14 08:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2022-05-14 10:12 UTC, nabokihms requested changes
@vitaliy-sn, could you please rebase your branch onto the main branch?

Integration tests fail with the following error
```
{"event.id":"220b1640-7d0e-4932-85f4-d1f13fd5c0ce","event.triggered-by.binding":"kubernetes","event.triggered-by.binding.name":"ready_not_master_nodes","event.triggered-by.hook":"cluster_is_bootstrapped.go","event.triggered-by.watchEvent":"Modified","level":"error","module":"helm","msg":"ModuleRun failed in phase 'Startup'. Requeue task to retry after delay. Failed count is 36. Error: module hook '013-helm/hooks/startup_metrics.go' failed: Get \"https://prometheus.d8-monitoring:9090/api/v1/query?query=resource_versions_compatibility\": dial tcp: lookup prometheus.d8-monitoring on 169.254.169.254:53: no such host","operator.component":"taskRunner","queue":"main","task.id":"e629649a-3b5d-4bb1-9f87-0469c6efeb81","time":"2022-05-14T08:42:25Z"}
```

2022-05-16 03:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2022-05-16 05:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-05-17 13:19 UTC, nabokihms approved these changes

2022-05-17 13:20 UTC, merged