Fix nat instance
deckhouse/deckhouse pull request #1592
Opened 2022-05-20 12:02 UTC by name212

## Description

## Why do we need it, and what problem does it solve?

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2022-05-30 12:30 UTC, konstantin-axenov requested changes

2022-05-30 12:30 UTC, konstantin-axenov commented on candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
> +      "ru-central1-a" = local.should_create_subnets ? yandex_vpc_subnet.kube_a[0].id : (local.is_existing_subnet_a ? data.yandex_vpc_subnet.kube_a[0].id : null)
Pls, check variables `is_existing_subnet_*` naming.

2022-05-30 12:30 UTC, konstantin-axenov commented on candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
> +      network_interface,
Remove `network_interface, zone` from ignore_changes.

2022-06-08 21:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2022-06-15 17:26 UTC, name212 commented on candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
> +      network_interface,
removed

2022-06-15 17:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2022-06-20 07:00 UTC, nabokihms approved these changes

2022-06-20 07:01 UTC, merged