[cilium] improvements
deckhouse/deckhouse pull request #1594
Opened 2022-05-20 18:23 UTC by RomanenkoDenys

## Description

## Why do we need it, and what problem does it solve?

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2022-05-30 09:50 UTC, zuzzas requested changes

2022-05-30 09:50 UTC, zuzzas commented on modules/021-cni-cilium/templates/configmap.yaml
> +  {{- if eq (.Values.cniCilium.bpfLBMode | lower) "disabled" }}
"disabled" is not present in the OpenAPI.

2022-05-31 09:45 UTC, zuzzas requested changes

2022-05-31 09:45 UTC, zuzzas commented on modules/021-cni-cilium/templates/agent/daemonset.yaml
> +  {{- include "helm_lib_module_labels" (list . (dict "app" $.Chart.Name "workload-resource-policy.deckhouse.io" "every-node")) | nindent 2 }}
Why such a label? Are we not using a VPA resource for operator as well?

2022-05-31 09:53 UTC, zuzzas approved these changes

2022-06-02 13:22 UTC, konstantin-axenov approved these changes

2022-06-02 13:22 UTC, merged