[Upmeter] Add alerts for probe garbage
deckhouse/deckhouse pull request #1648
Opened 2022-05-27 14:45 UTC by shvgn

## Description

Add alerts for garbage left by upmeter probes.

## Why do we need it, and what problem does it solve?

We should clean the garbage when it cannot be delted. Moreover, upmeter agent does not delete
garbage by labels, it only tracks objects by name within single run.

## Changelog entries

```changes
section: upemter
type: chore
summary: Added alerts for garbage oljects left by probes
```

2022-06-07 10:45 UTC, nabokihms requested changes
Overall, everything looks good. I left a couple of suggestions. Please look through them when you have time.

2022-06-07 10:45 UTC, nabokihms commented on modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
> +          min_over_time  (count (kube_deployment_labels{namespace="d8-upmeter",
Why do you use `_over_time` queries? `min` and `avg` should be enough for this case, as far as I can tell. Over time functions are more resource-consuming.

2022-06-07 10:45 UTC, nabokihms commented on modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
> +          min_over_time  (count (kube_deployment_labels{namespace="d8-upmeter",
Why do you use `_over_time` queries?  `min` and `avg` should be enough for this case, as far as I can tell.

2022-06-07 10:45 UTC, nabokihms commented on modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
> +        ) >= 1
I would simplify the rule to make it less complicated and avoid false positives. Let's say 15 configmaps in the namespaces is a problem.  Just sharing my thoughts, you do not need to change the current logic.

2022-06-07 10:45 UTC, nabokihms commented on modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
> +        ) >= 1
I would simplify the rule to make it less complicated and avoid false positives. Let's say 15 configmaps in the namespaces is a problem.  Just sharing my thoughts, you do not need to change the current logic.

2022-06-07 10:45 UTC, nabokihms commented on modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
> +      expr: |
Let's set the `for` at least for 5 minutes or more. We do not need to react if configmaps number is back to normal.

2022-06-07 10:45 UTC, nabokihms commented on modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
> +      expr: |
Let's set the `for` value for at least 5 minutes or more. We do not need to react if configmaps number is back to normal on its own.

2022-06-08 15:26 UTC, shvgn commented
Simplified, added `for` and groups auto-creation

2022-06-14 11:20 UTC, nabokihms approved these changes

2022-06-14 11:20 UTC, merged