[linstor] Add SPAAS docker image
deckhouse/deckhouse pull request #1761
Opened 2022-06-09 22:41 UTC by kvaps

Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

## Description

## Why do we need it, and what problem does it solve?

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2022-06-27 12:56 UTC, kvaps commented on modules/031-linstor/templates/spaas/deployment.yaml
> +  replicas: {{ include "helm_lib_is_ha_to_value" (list . 2 1) }}
Sure, `revisionHistoryLimit: 2` added, PR rebased on master

2022-06-27 12:58 UTC, kvaps commented on modules/031-linstor/images/drbd-driver-loader/Dockerfile
> + && git config --global user.name "Andrei Kvapil" \
Done.
DRBD has a check that all the changes are committed before the build.
This was needed this to apply our patch.
Now this patch is already in upstream repo, so we can just cherry-pick it.

2022-06-27 16:11 UTC, kvaps commented on modules/031-linstor/images/drbd-driver-loader/Dockerfile
> + && git config --global user.name "Andrei Kvapil" \
Ah, no way, cherry-pick still requires commiter name and email.
I replaced it with information from the commit:

https://github.com/deckhouse/deckhouse/blob/0284958609edafe85094b56de4a61e7f39d20327/modules/031-linstor/images/drbd-driver-loader/Dockerfile#L15-L20

2022-06-29 08:04 UTC, nabokihms requested changes

2022-06-29 08:04 UTC, nabokihms reviewed
DCO check did not pass.

2022-07-04 07:50 UTC, kvaps commented on modules/031-linstor/templates/spaas/deployment.yaml
> +      {{- include "helm_lib_tolerations" (tuple . "wildcard") | nindent 6 }}
I think we need SPAAS be deployed even In case if cluster has just master and system nodes.

2022-07-04 07:59 UTC, kvaps commented on modules/031-linstor/templates/spaas/deployment.yaml
> +    spec:
added system

2022-07-04 08:00 UTC, kvaps commented on modules/031-linstor/templates/spaas/deployment.yaml
> +      {{- include "helm_lib_tolerations" (tuple . "wildcard") | nindent 6 }}
changed to system

2022-07-04 08:09 UTC, kvaps commented on modules/031-linstor/templates/spaas/deployment.yaml
> +        startupProbe:
added conditional matching

2022-07-11 19:05 UTC, nabokihms commented
We discussed the PR and agreed that moving linstor components to system nodes would be ok.

2022-07-19 13:32 UTC, merged