[istio] don't export unready ingressgateway nodes via metadata-exporter
deckhouse/deckhouse pull request #2055
Opened 2022-07-18 22:50 UTC by apolovov

## Description
Don't export unready ingressgateway nodes via metadata-exporter for multiclusters and federations.

## Why do we need it, and what problem does it solve?
metadata-exporter exposes NotReady and cordoned nodes. It leads to unwanted connection errors.

## What is the expected result?
metadata-exporter won't export unwanted nodes.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: istio
type: fix
summary: Don't export unready ingressgateway nodes via metadata-exporter for multiclusters and federations.
```

2022-07-20 07:51 UTC, zuzzas requested changes

2022-07-26 21:15 UTC, apolovov commented on ee/modules/110-istio/images/metadata-discovery/hooks/ingressgateways
> +               (any((.spec.taints // [])[]; .key == "node.kubernetes.io/unschedulable") | not) and
Nice suggestion. I've accepted it as is.

2022-08-10 07:51 UTC, zuzzas approved these changes

2022-08-10 07:52 UTC, zuzzas commented
@konstantin-axenov 
You can't dislike this. :smile: 
![image](https://user-images.githubusercontent.com/950313/183846035-2da107b2-7e25-4f6f-ac84-a69a6f1396b2.png)

2022-08-11 14:53 UTC, konstantin-axenov approved these changes

2022-08-11 14:54 UTC, merged