[candi] migrate to containerd 1.6
deckhouse/deckhouse pull request #2211
Opened 2022-08-15 12:23 UTC by RomanenkoDenys

Signed-off-by: Denis Romanenko <denis.romanenko@flant.com>

## Description

Upgrade containerd version to 1.6 and remove unneeded containerd-flant-edition binary.

## Why do we need it, and what problem does it solve?

New containerd version contains many fixes.
## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: migrate to containerd 1.6
impact_level: low
```

2022-08-15 14:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-08-15 17:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-08-16 08:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2022-08-16 08:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2022-08-16 13:01 UTC, konstantin-axenov requested changes

2022-08-16 13:12 UTC, RomanenkoDenys commented on candi/bashible/bundles/centos/node-group/031_install_containerd.sh.tpl
> +# Copyright 2022 Flant JSC
ok, fixed

2022-08-16 14:25 UTC, konstantin-axenov requested changes

2022-08-16 14:25 UTC, konstantin-axenov commented on candi/bashible/common-steps/node-group/032_remove_containerd_fe.sh.tpl
> +# Copyright 2022 Flant JSC
```suggestion
# Copyright 2021 Flant JSC
```

2022-08-16 14:28 UTC, konstantin-axenov commented on modules/007-registrypackages/images/containerd-fe/werf.inc.yaml
> -  - git cherry-pick 5f3ce9512b74718ac9519196ba70dfb1ee075fbe # Do not append []string{""} to command to preserve Docker and Werf compatibility
This is still not in release of containerd - https://github.com/containerd/containerd/blob/release/1.6/pkg/cri/opts/spec.go#L66

2022-08-16 15:38 UTC, konstantin-axenov commented on modules/007-registrypackages/images/containerd-fe/werf.inc.yaml
> -  - git cherry-pick 5f3ce9512b74718ac9519196ba70dfb1ee075fbe # Do not append []string{""} to command to preserve Docker and Werf compatibility
It seem that we should wait for https://github.com/containerd/containerd/pull/7298 to be merged.

2022-12-29 15:24 UTC, closed without merging