[cloud-provider-aws] Add ability to configure additional policies for IAM roles
deckhouse/deckhouse pull request #2256
Opened 2022-08-18 14:46 UTC by gmaiorov

## Description

Add an `additionalRolePolicies` parameter to AWSClusterConfiguration and update.
## Why do we need it, and what problem does it solve?

Fixes #1005. 

## What is the expected result?

Following changes are expected:
- `additionalRolePolicies` parameter added to AWSClusterConfiguration;
- corresponding roles attached to the [`Action`](https://github.com/deckhouse/deckhouse/blob/498eb618bbdd98b21950b1795eb02b6e2a3e50b2/candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf#L165)  list in `aws_iam_role_policy` resource.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: Add an `additionalRolePolicies` parameter to AWSClusterConfiguration (#1005)
impact_level: low
```

2022-08-22 07:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-08-22 10:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-08-23 07:39 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-08-23 09:12 UTC, gmaiorov commented
[Smoke test report PR2256.pdf](https://github.com/deckhouse/deckhouse/files/9401126/Smoke.test.report.PR2256.pdf)

2022-08-23 09:34 UTC, RomanenkoDenys approved these changes

2022-08-24 15:59 UTC, konstantin-axenov requested changes

2022-08-24 15:59 UTC, konstantin-axenov commented on candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf
> +          %{ for policy in local.additional_role_policies }
```suggestion
          %{for policy in local.additional_role_policies}
```

2022-08-24 15:59 UTC, konstantin-axenov commented on candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf
> +          %{ for policy in local.additional_role_policies }
```suggestion
          %{for policy in local.additional_role_policies}
```

2022-08-24 15:59 UTC, konstantin-axenov commented on candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf
> +          %{ endfor }
```suggestion
          %{endfor}
```

2022-08-24 15:59 UTC, konstantin-axenov commented on candi/cloud-providers/aws/layouts/without-nat/base-infrastructure/main.tf
> +          %{ for policy in local.additional_role_policies }
```suggestion
          %{for policy in local.additional_role_policies}
```

2022-08-24 15:59 UTC, konstantin-axenov commented on candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf
> +          %{ for policy in local.additional_role_policies }
These changes of terraform files are just to match `terraform fmt`. Not all existing files are correctly formatted, but if we add or change code, it's better to format it correctly.

2022-08-25 10:58 UTC, gmaiorov commented on candi/cloud-providers/aws/openapi/cluster_configuration.yaml
> +        description: List containing an additional policies for IAM roles.
I've clarified additionalRolePolicies parameter documentation and added a translated description in 746812d9085c0bf4087bd6c0efad2d3154dcb03e.

2022-08-25 11:23 UTC, gmaiorov commented
Rebased onto main & force-pushed to fix matrix tests.

2022-08-25 16:14 UTC, konstantin-axenov approved these changes

2022-08-25 16:16 UTC, konstantin-axenov approved these changes

2022-08-25 16:58 UTC, merged