[dhctl] Change color, fix empty host connection attempts
deckhouse/deckhouse pull request #2346
Opened 2022-08-26 04:21 UTC by nabokihms

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

## Description
* Changes font colour for bold blocks from white to normal
* Fail if there is empty host for ssh connection

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Changes font colour for bold blocks from white to normal
impact_level: low
---
section: dhctl
type: fix
summary: Fail if there is empty host for ssh connection
impact_level: default
```

2022-08-29 08:12 UTC, name212 commented on dhctl/pkg/system/ssh/frontend/waiting.go
> +		return fmt.Errorf("empty host for connection received")
```suggestion
		return fmt.Errorf("Empty host for connection received")
```

2022-08-29 08:13 UTC, name212 requested changes
One suggest and plese run e2e

2022-08-31 04:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2022-09-01 10:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2022-09-01 11:52 UTC, name212 approved these changes

2022-09-01 11:53 UTC, merged