[openvpn] ccd for udp
deckhouse/deckhouse pull request #2366
Opened 2022-08-30 16:41 UTC by vitaliy-sn

Signed-off-by: Vitaliy Snurnitsin <vitaliy.snurnitsin@flant.com>

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2022-09-05 23:28 UTC, apolovov commented on modules/500-openvpn/templates/openvpn/configmap.yaml
> +  sync_ccd_udp.sh: |-
don't we need sync_ccd_tcp?

2022-09-06 11:33 UTC, apolovov commented
Please, fill the `Why do we need it, and what problem does it solve?` section.

2022-09-19 07:39 UTC, vitaliy-sn commented on modules/500-openvpn/templates/openvpn/configmap.yaml
> +  sync_ccd_udp.sh: |-
Made a common script for tcp and udp

2022-09-20 08:08 UTC, apolovov requested changes

2022-09-20 08:08 UTC, apolovov commented on modules/500-openvpn/templates/openvpn/configmap.yaml
> +          for f in $(ls -1 /etc/openvpn/ccd); do
```suggestion
          for f in /etc/openvpn/ccd/*; do
```

2022-09-27 04:32 UTC, z9r5 commented on modules/500-openvpn/docs/CONFIGURATION_RU.md
> +
```suggestion
**Внимание!** В панели администратора при назначении статического адреса нужно выбирать адрес из диапазона tunnelNetwork. Подсети для TCP и UDP-сервера должны быть одного размера. Статические адреса в CCD (Client-specific configuration) для UDP-сервера преобразутся из CCD для TCP подменой подсети.

```

2022-09-27 04:33 UTC, z9r5 approved these changes

2022-10-06 06:40 UTC, vitaliy-sn commented on modules/500-openvpn/templates/openvpn/statefullset.yaml
> +            {{- include "helm_lib_module_ephemeral_storage_logs_with_extra" 10 | indent 12 }}
fixed

2022-10-06 06:40 UTC, vitaliy-sn commented on modules/500-openvpn/templates/openvpn/statefullset.yaml
> +            {{- include "helm_lib_module_ephemeral_storage_logs_with_extra" 10 | indent 12 }}
fixed

2022-10-06 06:42 UTC, vitaliy-sn commented on modules/500-openvpn/templates/openvpn/statefullset.yaml
> +            --ovpn.network="{{ include "get_network_with_bitmask" (list . .Values.openvpn.tunnelNetwork) }}"
After the last discussion, we decided to always use tunnelNetwork and add information about this to the documentation

2022-10-06 06:45 UTC, vitaliy-sn commented on modules/500-openvpn/templates/openvpn/statefullset.yaml
> +      - name: ccd-udp
After the last changes, the ccd-tcp (original files) and ccd-udp directories remained.

2022-10-06 06:45 UTC, vitaliy-sn commented on modules/500-openvpn/templates/openvpn/statefullset.yaml
> +            {{- include "helm_lib_module_ephemeral_storage_logs_with_extra" 10 | indent 12 }}
fixed

2022-10-14 13:13 UTC, apolovov commented on modules/500-openvpn/docs/CONFIGURATION.md
> +**Caution!** The admin panel always uses tunnelNetwork. Static addresses must be issued from it. If UDP openvpn server is enabled, tunnelNetwork and udpTunnelNetwork must be the same size.
```suggestion
**Caution!** The admin panel always uses tunnelNetwork (not udpTunnelNetwork one). Static addresses must be issued from it. If UDP openvpn server is enabled,  tunnelNetwork and udpTunnelNetwork must be the same size.
```

2022-10-14 13:13 UTC, apolovov commented on modules/500-openvpn/docs/CONFIGURATION_RU.md
> +**Внимание!** В панели администратора всегда используется tunnelNetwork, статические адреса необходимо выдавать из неё. Если включен UDP openvpn сервер, то tunnelNetwork и udpTunnelNetwork должны быт
```suggestion
**Внимание!** В панели администратора всегда используется tunnelNetwork (но не udpTunnelNetwork), статические адреса необходимо выдавать из неё. Если включен UDP openvpn сервер, то tunnelNetwork и udpTunnelNetwork должны быть одного размера.
```

2022-10-14 13:29 UTC, apolovov approved these changes

2022-10-14 14:38 UTC, merged