[monitoring-applications] fixed dashboards if exist custom
deckhouse/deckhouse pull request #2559
Opened 2022-09-21 12:44 UTC by alexey-gavrilov-flant

## Description
fixes dashboard when using custom label

## Why do we need it, and what problem does it solve?
fixes dashboard when using custom label

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-applications
type: chore
summary: fixes dashboard when using custom label
impact_level: low
```

2022-09-21 12:49 UTC, alexey-gavrilov-flant commented
cherry-pick  to stable channel

2022-09-21 12:50 UTC, alexey-gavrilov-flant commented
https://flant.slack.com/archives/CML93AWG2/p1663687033024089?thread_ts=1663683757.925339&cid=CML93AWG2

2022-09-23 05:27 UTC, nabokihms commented
@alexey-gavrilov-flant, I didn't get an idea how this PR fixes the dashboard. Could you please elaborate more?

2022-09-23 05:28 UTC, nabokihms requested changes
Let's talk more about the case because, as I see it, this PR limits all queries to some custom jobs.

2022-09-26 07:12 UTC, alexey-gavrilov-flant commented
I set up a queue length alert, but then the dashboard display breaks. because there are no filters for custom services.
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus.deckhouse.io/custom-target: rabbitmq-queue
  annotations:
    prometheus.deckhouse.io/path: /metrics/detailed
    prometheus.deckhouse.io/query-param-family: queue_coarse_metrics
  name: rabbitmq-queue
spec:
  ports:
  - name: http-metrics
    port: 15692
    protocol: TCP
    targetPort: 15692
  selector:
    app.kubernetes.io/name: rabbitmq
  type: ClusterIP
```

2022-09-26 07:37 UTC, alexey-gavrilov-flant commented
these two queries give part of the same metrics, which is the reason for not working.

2023-04-05 10:17 UTC, nabokihms reviewed
Instead of excluding, let's include only rabbitmq jobs

2023-04-05 10:17 UTC, nabokihms commented on ee/fe/modules/340-monitoring-applications/applications/rabbitmq/grafana-dashboards/rabbitmq.json
> +          "expr": "sum(rate(rabbitmq_channel_messages_published_total[60s]) * on(instance) group_left(namespace) rabbitmq_identity_info{namespace=\"$namespace\",job !~ \"^custom-.*\"})",
```suggestion
          "expr": "sum(rate(rabbitmq_channel_messages_published_total[60s]) * on(instance) group_left(namespace) rabbitmq_identity_info{namespace=\"$namespace\",job=\"rabbitmq\"})",
```

2023-04-06 06:27 UTC, merged