Disable cilium-hubble module by default
deckhouse/deckhouse pull request #2581
Opened 2022-09-23 17:45 UTC by gmaiorov

## Description

This PR disables `cilium-hubble` module by default.

## Why do we need it, and what problem does it solve?

Hubble generates moderate CPU overhead, and should be enabled on demand.

## What is the expected result?

* `cilium-hubble` module disabled by default
* documentation updated correspondingly

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cilium-hubble
type: chore
summary: cilium-hubble module disabled by default
impact_level: default
```

2022-09-23 18:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2022-09-24 01:03 UTC, yalosev requested changes
You have to change enabled script to the ` enabled::disable_module_if_cluster_is_not_bootstraped` also

2022-09-24 13:39 UTC, gmaiorov commented
> You have to change enabled script to the `enabled::disable_module_if_cluster_is_not_bootstraped` also

It seems `enabled` file already contains both `enabled::disable_module_if_cluster_is_not_bootstraped` and logic for disabling module when `cni-cilium` module isn't enabled.

2022-09-25 10:39 UTC, z9r5 approved these changes

2022-09-28 11:27 UTC, RomanenkoDenys approved these changes

2022-09-29 06:45 UTC, yalosev approved these changes

2022-09-29 09:18 UTC, merged