[node-manager] Rename D8EarlyOOMPodIsNotReady alert to EarlyOOMPodIsNotReady
deckhouse/deckhouse pull request #2590
Opened 2022-09-26 17:51 UTC by name212

…

Signed-off-by: Nikolay Mitrofanov <nikolay.mitrofanov@flant.com>

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2022-09-27 16:45 UTC, zuzzas requested changes

2022-09-27 16:45 UTC, zuzzas commented on modules/040-node-manager/monitoring/prometheus-rules/early-oom.tpl
> +        For fix it you can:
```suggestion
        To fix it you can:
```

2022-09-28 10:32 UTC, zuzzas submitted a review, later dismissed

2022-10-17 09:37 UTC, merged

2022-10-17 09:42 UTC, deckhouse-BOaTswain commented
Cherry pick PR [2751](https://github.com/deckhouse/deckhouse/pull/2751) to the branch [release-1.38](https://github.com/deckhouse/deckhouse/tree/release-1.38) successful!