Add rsyslog unit check
deckhouse/deckhouse pull request #2757
Opened 2022-10-17 21:10 UTC by gyrter

## Description

Closes #2756 

## Why do we need it, and what problem does it solve?

Easy installation on minimal os

## What is the expected result?

Install on minimal ubuntu 22.04

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2022-10-18 20:17 UTC, RomanenkoDenys requested changes
Please add normal description why this PR is needed

2022-10-18 20:17 UTC, RomanenkoDenys commented on candi/bashible/common-steps/all/083_disable_rsyslog_for_docker_and_kubelet.sh.tpl
> +if [ systemctl -q is-enabled rsyslog >/dev/null 2>&1 ]; then
```suggestion
if systemctl -q is-enabled rsyslog 2>/dev/null; then
```

2022-10-18 20:17 UTC, RomanenkoDenys commented on candi/bashible/common-steps/all/083_disable_rsyslog_for_docker_and_kubelet.sh.tpl
> +fi
```suggestion
if [ -d /etc/rsyslog.d ]; then
  bb-sync-file /etc/rsyslog.d/10-kubelet.conf - <<END
:programname,isequal, "kubelet" ~
END

  bb-sync-file /etc/rsyslog.d/10-dockerd.conf - <<END
:programname,isequal, "dockerd" ~
END
fi
```

2022-10-19 11:45 UTC, gyrter commented
@RomanenkoDenys done. Description updated

2022-10-19 11:56 UTC, RomanenkoDenys requested changes
one small suggestion, it is my fault

2022-10-19 11:56 UTC, RomanenkoDenys commented on candi/bashible/common-steps/all/083_disable_rsyslog_for_docker_and_kubelet.sh.tpl
> +if systemctl -q is-enabled rsyslog 2>/dev/null; then
```suggestion
if ! systemctl -q is-enabled rsyslog 2>/dev/null; then
```

2022-10-19 15:54 UTC, gyrter commented on candi/bashible/common-steps/all/083_disable_rsyslog_for_docker_and_kubelet.sh.tpl
> +if systemctl -q is-enabled rsyslog 2>/dev/null; then
Yeap. It's my fault.

2022-10-19 15:54 UTC, gyrter commented
I think every this is done here.

2022-10-20 10:21 UTC, RomanenkoDenys approved these changes
LGTM

2022-10-20 10:22 UTC, merged