Add version in install image. For #2920
deckhouse/deckhouse pull request #2933
Opened 2022-10-31 14:24 UTC by gyrter

## Description

Add version file to install image.

## Why do we need it, and what problem does it solve?

New users want's to have easy method to determine installer version

## What is the expected result?

File with version in image

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2022-11-03 10:01 UTC, name212 reviewed
I don't like variant with injection version as ld flag.
We have file `/deckhouse/version`. May be we can read this file (if file not found, get 'dev' version) and get version from it?

2022-11-03 13:20 UTC, gyrter commented
No problem. We can read file.

2023-01-13 09:09 UTC, name212 commented
please add DCO https://github.com/apps/dco for your commits

2023-01-13 09:10 UTC, name212 requested changes
DCO for commits

2023-01-22 06:59 UTC, gyrter commented
DCO added

2023-01-23 15:50 UTC, name212 approved these changes

2023-01-23 15:51 UTC, merged