[node-manager] added pattern and length limit for NodeGroup name check
deckhouse/deckhouse pull request #2938
Opened 2022-10-31 15:47 UTC by duckhawk

## Description
Additional NodeGroup name validation

## Why do we need it, and what problem does it solve?
One of labels assigned by the cloud instance manager contains full node name.
Kubernetes label can't be longer than 63 characters. 
Also, in Amazon cloud AWSMachineClass name can't contain dots.
We limit node names to 63 characters and restrict dots usage.
Fix #2726

## What is the expected result?
It is forbidden to use dots in the NodeGroup name. Length of clusterPrefix and NodeGroup name sum limited to 42 characters.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: node-manager
type: chore
summary: Added pattern and limit of 42 characters in NodeGroup name check in CRD.
impact_level: low
```

2022-11-02 08:26 UTC, apolovov requested changes

2022-11-02 08:26 UTC, apolovov commented on candi/openapi/node_group.yaml
> +                  maxLength: 42
```suggestion
                  maxLength: 42 # because of ...
```

2022-11-02 08:26 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +  clusterPrefix="$(context::jq -r '.snapshots.cluster_config[0].filterResult' | grep "prefix" | cut -d" " -f4)"
```suggestion
  clusterPrefixLen="$(context::jq -r '.snapshots.cluster_config[0].filterResult' | grep "prefix:" | awk {print len($2)})"
```

2022-11-02 08:26 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +  if [[ $clusterPrefix ]]; then
```suggestion
  if [[ -n "$clusterPrefix" ]]; then
```

2022-11-02 08:26 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +    nodeGroupName=$(context::jq -r '.review.request.object.metadata.name')
```suggestion
    nodeGroupNameLen=$(context::jq -r '.review.request.object.metadata.name | length')
```

2022-11-02 08:26 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +    jqFilter: '.data."cluster-configuration.yaml" // "" | @base64d'
```suggestion
    jqFilter: |
      {
        "defaultCRI": (.data."cluster-configuration.yaml" // "" | @base64d  | match("(\w*defaultCRI:\w+)(.+$)").captures[1].string,

        "prefixLen": (.data."cluster-configuration.yaml" // "" | @base64d  | match("(\w*prefix:\w+)(.+$)").captures[1].string | length,
         "nameLen": (.metadata.name | length)
         )
      }
```

2022-11-03 13:45 UTC, apolovov requested changes
See discussions.

2022-11-03 13:45 UTC, apolovov commented on candi/openapi/node_group.yaml
> +                                # Further, in the hooks, it is checked that the length of <cluster prefix>-<group node name>
```suggestion
                                # Further, in the validation webhook, it is checked that the length of <cluster prefix>-<group node name>
```

2022-11-03 13:45 UTC, apolovov commented on candi/openapi/node_group.yaml
> +                                # Further, in the hooks, it is checked that the length of <cluster prefix>-<group node name>
```suggestion
                                # Further, in the validation webhook, it is checked that the length of <cluster prefix>-<group node name>
```

2022-11-03 13:45 UTC, apolovov commented on candi/openapi/node_group.yaml
> +                                # Further, in the hooks, it is checked that the length of <cluster prefix>-<group node name>
```suggestion
                                # Further, in the validation webhook, it is checked that the length of <cluster prefix>-<group node name>
```

2022-11-03 13:45 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +        "prefixLen": (.data."cluster-configuration.yaml" // "" | @base64d | match("[ ]*prefix:[ ]+(.*)\n").captures[0].string | length)
```suggestion
        "clusterPrefixLen": (.data."cluster-configuration.yaml" // "" | @base64d | match("[ ]*prefix:[ ]+(.*)\n").captures[0].string | length)
```

2022-11-03 13:45 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +  if [[ -n $clusterPrefixLen ]]; then
```suggestion
  if [[ "$clusterType" == "Cloud" ]]; then
```

2022-11-03 13:45 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +    nodeNameTemplateLen=$(($clusterPrefixLen + $nodeGroupNameLen + 1))
```suggestion
                                                    # (<prefix>-<NodeGroup name>)-<hashes>
    nodeNameTemplateLen=$(($clusterPrefixLen + 1 + $nodeGroupNameLen))
```

2022-11-03 13:45 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +{"allowed":false, "message":"for cloud clusters it is forbidden to set (cluster prefix + node group name) length more then 42 symbols"}
TODO

2022-11-03 15:20 UTC, apolovov requested changes
see discussion

2022-11-03 15:20 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +                        # (<prefix>-<NodeGroup name>)-<hashes>
```suggestion
if $(( 63 - $clusterPrefixLen - 1 - $nodeGroupNameLen - 21 )) < 0; then
error
fi
```

2022-11-07 10:46 UTC, apolovov approved these changes

2022-11-07 15:20 UTC, yalosev approved these changes

2022-11-09 13:38 UTC, apolovov requested changes

2022-11-09 13:38 UTC, apolovov commented on candi/openapi/node_group.yaml
> +                  pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" # in Amazon cloud AWSMachineClass name can't contain dots
```suggestion
                  pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" # In Amazon cloud, AWSMachineClass name can't contain dots.
```

2022-11-09 13:38 UTC, apolovov commented on candi/openapi/node_group.yaml
> +                                # is equal or shorter than 42 characters
```suggestion
                  maxLength: 42 # One of labels assigned by the cloud instance manager contains full node name,
                                # the same time, kubernetes labels keys and values can't be longer than 63 characters.
                                # Length of hashes is 21 characters, so we leave 63-21=42 characters.
                                # Further, validation webhook will check that length of <cluster prefix>-<group node name>
                                # fits the 42 characters limitation.
```

2022-11-09 13:38 UTC, apolovov commented on modules/040-node-manager/webhooks/validating/node_group
> +    # Label must be equal or shorter than 63 characters
```suggestion
    # Label value must be >= 63 characters
```

2022-11-10 08:53 UTC, apolovov submitted a review, later dismissed

2022-11-14 07:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2022-11-14 08:55 UTC, yalosev approved these changes

2022-11-14 13:02 UTC, RomanenkoDenys approved these changes
LGTM

2022-11-14 13:07 UTC, apolovov approved these changes

2022-11-14 13:40 UTC, yalosev approved these changes

2022-11-14 13:44 UTC, merged