[multiple modules] changed memory size pattern for support dotted notation
deckhouse/deckhouse pull request #2940
Opened 2022-11-01 07:36 UTC by duckhawk

## Description
[multiple modules] changed memory size pattern for support dotted notation

## Why do we need it, and what problem does it solve?
Fix issue #2233

## What is the expected result?
Memory validation allows to use notation like '5.0Gi'

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: chore
summary: Memory validation allows to use notation like '5.0Gi'
impact: no impact expected
impact_level: low
```

2022-11-01 14:51 UTC, yalosev approved these changes
LGTM
but fix tests ;)

2022-11-02 08:41 UTC, yalosev commented on ee/modules/110-istio/openapi/config-values.yaml
> +                      pattern: "^[0-9]+(\.[0-9]+)?(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$"
You have to use single quote, not double. Otherwise `\.` will lead to error

2022-11-02 08:52 UTC, apolovov requested changes
Also, add openapi-case-tests.yaml to related openapi's.

2022-11-02 08:52 UTC, apolovov commented on candi/openapi/node_group.yaml
> -                              pattern: '^[0-9]+(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)?$'
Why K is different?

2022-11-02 08:52 UTC, apolovov commented on candi/openapi/node_group.yaml
> -                              pattern: '^[0-9]+(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)?$'
Don't change it, add a little k to the pattern. And be sure if it is supported.

2022-11-02 08:52 UTC, apolovov commented on candi/openapi/node_group.yaml
> -                              pattern: '^[0-9]+(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)?$'
Get off the K's. Focus on dots.

2022-11-02 08:52 UTC, apolovov commented on candi/openapi/node_group.yaml
> -                              pattern: '^[0-9]+(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)?$'
Don't change em.

2022-11-02 18:34 UTC, apolovov commented on ee/modules/110-istio/openapi/openapi-case-tests.yaml
> +              min: "1G"
```suggestion
              max: "2.000G"
              min: "1.123G"
```

2022-11-08 08:20 UTC, merged