[monitoring-kubernetes] removed unschedulable nodes from K8SNodeNotReady and K8SManyNodesNotReady alerts
deckhouse/deckhouse pull request #2942
Opened 2022-11-01 10:07 UTC by duckhawk

## Description
Removed unschedulable nodes from K8SNodeNotReady alert

## Why do we need it, and what problem does it solve?
Alert K8SNodeNotReady was active while autoscaler removed the node from the cluster
Fix #2829

## What is the expected result?
If node is cordoned, alert K8SNodeNotReady ignores it.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-kubernetes
type: chore
summary: removed unschedulable nodes from K8SNodeNotReady alert
impact: no impact expected
impact_level: low
```

2022-11-07 09:42 UTC, nabokihms approved these changes

2022-11-07 09:45 UTC, nabokihms requested changes
Oh, by the way, I realized that the `K8SManyNodesNotReady` alert should also be changed.

2022-11-08 09:11 UTC, apolovov commented
Vasily will make it today.

2022-11-08 21:13 UTC, nabokihms approved these changes

2022-11-08 21:13 UTC, merged