[monitoring-ping] Skip unschedulabe nodes
deckhouse/deckhouse pull request #3139
Opened 2022-11-28 14:41 UTC by gmaiorov

Signed-off-by: Gleb Maiorov <gleb.maiorov@flant.com>

## Description

Skip unschedulabe nodes in `monitoring-ping`.
## Why do we need it, and what problem does it solve?

Currently unschedulable nodes are still pinged in monitoring-ping module.
This causes false positive alerts when unschedulable node is no longer accessible, but isn't removed from k8s yet.

## What is the expected result?

`monitoring-ping` no longer tries to ping unschedulable nodes.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-ping
type: chore
summary: Skip unschedulabe nodes in `monitoring-ping`
impact_level: low
```

2022-11-29 14:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2022-11-29 15:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-11-29 19:57 UTC, RomanenkoDenys commented on modules/340-monitoring-ping/hooks/discover_targets.go
> +		}
```suggestion
        if address == nil {
          continue
        }  
	
	   convertedAddress := address.(nodeTarget)
	   combinedTargets.Cluster = append(combinedTargets.Cluster, convertedAddress)
```

2022-11-29 19:57 UTC, RomanenkoDenys requested changes
small suggestion

2022-11-30 08:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2022-11-30 08:53 UTC, RomanenkoDenys approved these changes

2022-11-30 09:35 UTC, merged