[cloud-provider-openstack] Fix ordering static nodes without security…
deckhouse/deckhouse pull request #3182
Opened 2022-11-30 09:02 UTC by vitaliy-sn

… groups

Signed-off-by: Vitaliy Snurnitsin <vitaliy.snurnitsin@flant.com>

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2022-12-02 10:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2022-12-05 17:47 UTC, konstantin-axenov requested changes

2022-12-05 17:47 UTC, konstantin-axenov commented on ee/candi/cloud-providers/openstack/terraform-modules/static-node/main.tf
> +  volume_type_map      = var.providerClusterConfiguration.masterNodeGroup.volumeTypeMap
`masterNodeGroup`?

2022-12-05 17:47 UTC, konstantin-axenov commented on ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
> +                We recommend using the fastest disks provided by the provider in all cases.
```suggestion
```

2022-12-09 07:45 UTC, vitaliy-sn commented on ee/candi/cloud-providers/openstack/terraform-modules/static-node/main.tf
> +  volume_type_map      = var.providerClusterConfiguration.masterNodeGroup.volumeTypeMap
fixed

2022-12-13 07:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2022-12-13 09:33 UTC, merged