[deckhouse] one source of truth for deckhouse registry
deckhouse/deckhouse pull request #3193
Opened 2022-11-30 13:57 UTC by fl64

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2022-12-07 07:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-12-13 08:07 UTC, name212 requested changes
one thing and need rebase

2022-12-14 11:28 UTC, fl64 commented on global-hooks/discovery/deckhouse_registry.go
The `dockercfg` check already exists in the filter, so I added the `address` field check there. But I'm not sure about the path.

2022-12-14 18:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-12-19 09:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2022-12-19 10:48 UTC, name212 submitted a review, later dismissed

2022-12-26 09:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-12-26 12:42 UTC, name212 submitted a review, later dismissed

2022-12-26 13:03 UTC, yalosev submitted a review, later dismissed

2022-12-26 14:17 UTC, apolovov requested changes
LGTM, but it would be nice to rename all templates to registry-secret.yaml

2022-12-26 17:11 UTC, shvgn commented
Regarding flant-integation changes, it look good to me. 

Regarding changelog block, there should be improvements. 

1. Valid YAML
2. I think flant-integration it doesn't deserve a special mention among all other modules.

Here is my suggestion for the summary, omitting internal detail

>  Changed `deckhouse_registry` hook to get registry data form secret `docker-registry`. The global values of the registry is refactored for all modules.

2022-12-26 17:11 UTC, shvgn submitted a review, later dismissed

2022-12-26 23:03 UTC, apolovov approved these changes

2022-12-27 08:40 UTC, apolovov approved these changes

2022-12-27 08:45 UTC, yalosev approved these changes

2022-12-27 08:53 UTC, name212 approved these changes

2022-12-27 09:05 UTC, RomanenkoDenys approved these changes

2022-12-27 09:07 UTC, merged

2022-12-29 08:51 UTC, kvaps commented
@RomanenkoDenys could you confirm if this is not affecting this script, please:

https://github.com/deckhouse/deckhouse/blob/e5bd9d7e2818ee7610d2205e340e644f9f7d4993/candi/bashible/bashible.sh.tpl#L121-L126

2022-12-29 08:55 UTC, kvaps reviewed
@fl64 docs are not updated https://github.com/deckhouse/deckhouse/blob/e5bd9d7e2818ee7610d2205e340e644f9f7d4993/docs/documentation/pages/DECKHOUSE-FAQ.md?plain=1#L122-L123

2022-12-29 09:15 UTC, fl64 commented
> @fl64 docs are not updated
> 
> https://github.com/deckhouse/deckhouse/blob/e5bd9d7e2818ee7610d2205e340e644f9f7d4993/docs/documentation/pages/DECKHOUSE-FAQ.md?plain=1#L122-L123
@kvaps 
I'm not sure we need to update this document, because these settings refer to configs for dhctl, and my changes concerned internal variables.
@name212 Can you please tell me if I'm right?