[user-authn] Add claim mappings for OIDC providers
deckhouse/deckhouse pull request #3198
Opened 2022-11-30 21:32 UTC by nabokihms

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

## Description
Add the claim mappings option for OIDC providers to be able to deal with custom claims.

## Why do we need it, and what problem does it solve?
Some providers return non-standard claims (eg. mail). Dex cannot map mail to email by default, so it needs some hints from the user side.

https://dexidp.io/docs/connectors/oidc/

## What is the expected result?
Nothing.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: user-authn
type: feature
summary: Add claim mappings for OIDC providers.
impact_level: default
```

2022-11-30 21:36 UTC, nabokihms commented
Documentation validation is skipped because I fixed some spelling only in the english doc.

2022-11-30 23:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2022-12-01 04:56 UTC, z9r5 commented on modules/010-user-authn-crd/crds/doc-ru-dex-provider.yaml
> +                        Некоторые провайдеры возвращают не стандартные claim'ы (например mail). Claim mappings помогают Dex преобразовать их в [стандартные claim'ы OIDC](https://openid.net/specs/open
```suggestion
                        Некоторые провайдеры возвращают нестандартные claim'ы (например mail). Claim mappings помогают Dex преобразовать их в [стандартные claim'ы OIDC](https://openid.net/specs/openid-connect-core-1_0.html#Claims).
```

2022-12-01 04:56 UTC, z9r5 commented on modules/010-user-authn-crd/crds/doc-ru-dex-provider.yaml
> +                        Dex может преобразовать не стандартный claim в стандартный только если id_token полученный от OIDC-провайдера не содержит аналогичный стандартный claim.
```suggestion
                        Некоторые провайдеры возвращают нестандартные claim'ы (например mail). Claim mappings помогают Dex преобразовать их в [стандартные claim'ы OIDC](https://openid.net/specs/openid-connect-core-1_0.html#Claims).

                        Dex может преобразовать нестандартный claim в стандартный только если id_token полученный от OIDC-провайдера не содержит аналогичный стандартный claim.
```

2022-12-01 04:57 UTC, z9r5 submitted a review, later dismissed

2022-12-01 09:04 UTC, shvgn requested changes

2022-12-01 22:20 UTC, nabokihms commented on modules/010-user-authn-crd/crds/dex-provider.yaml
> +                    claimMappings:
Fixed

2022-12-01 22:22 UTC, nabokihms commented on modules/010-user-authn-crd/crds/dex-provider.yaml
> +                        preferredUsername:
I changed camal case to snake case for the preferred username because it seems reasonable.

2022-12-01 22:25 UTC, nabokihms commented on modules/010-user-authn-crd/crds/dex-provider.yaml
> +                        preferredUsername:
About the proposal - as of today, Dex cannot map any claim to any claim, so the spec cannot be applied. The progress of impelementation of the token content manipulation feature for Dex can be tracked in this issue.
https://github.com/dexidp/dex/issues/1635

2022-12-01 23:26 UTC, shvgn approved these changes

2022-12-02 06:03 UTC, merged