[node-manager] Clarify using NodeGroup parameters
deckhouse/deckhouse pull request #3315
Opened 2022-12-14 11:24 UTC by z9r5

## Description
Clarify using NodeGroup parameters.

## Changelog entries
```changes
section: docs
type: chore
summary: Clarify using NodeGroup parameters.
impact_level: low
```

2022-12-14 13:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2022-12-26 14:32 UTC, yalosev requested changes

2022-12-26 14:32 UTC, yalosev commented on modules/040-node-manager/docs/FAQ_RU.md
> +| cloudInstances.maxSurgePerZone        | -                          | +                 | -               |
```suggestion
| cloudInstances.maxSurgePerZone        | -                          | -                 | -               |
```

2022-12-26 14:32 UTC, yalosev commented on modules/040-node-manager/docs/FAQ_RU.md
> +| update.maxConcurrent                  | -                          | +                 | -               |
```suggestion
| update.maxConcurrent                  | -                          | -                 | -               |
```

2022-12-26 14:32 UTC, yalosev commented on modules/040-node-manager/docs/FAQ.md
> +| cloudInstances.maxSurgePerZone        | -                          | +                 | -               |
```suggestion
| cloudInstances.maxSurgePerZone        | -                          | -                 | -               |
```

2022-12-26 14:32 UTC, yalosev commented on modules/040-node-manager/docs/FAQ.md
> +| update.maxConcurrent                  | -                          | +                 | -               |
```suggestion
| update.maxConcurrent                  | -                          | -                 | -               |
```

2022-12-28 09:05 UTC, yalosev approved these changes

2022-12-28 09:06 UTC, merged

2022-12-28 09:06 UTC, z9r5 commented
/backport 1.42

2022-12-28 09:07 UTC, deckhouse-BOaTswain commented
Cherry pick PR [3433](https://github.com/deckhouse/deckhouse/pull/3433) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!

2022-12-28 09:07 UTC, z9r5 commented
/backport 1.41

2022-12-28 09:08 UTC, deckhouse-BOaTswain commented
Failure: cherry-pick commit e4fb36d9bab5f17422f5f5d667e08084c3eea0e4 to the branch [release-1.41](https://github.com/deckhouse/deckhouse/tree/release-1.41) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/3792923943) for details.