[global] added image id generate
deckhouse/deckhouse pull request #3318
Opened 2022-12-14 13:07 UTC by duckhawk

Signed-off-by: v.oleynikov <vasily.oleynikov@flant.com>

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-01-18 11:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-01-18 11:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-01-18 11:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-18 11:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-18 11:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-01-18 11:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-18 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-01-18 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-01-18 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-18 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-18 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-18 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-01-18 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-01-18 12:45 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.21 3948759805 3948759805-1-con-1-21 /sys/deckhouse-oss/install:pr3318 user@35.246.138.202

2023-01-18 12:46 UTC, duckhawk commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.21 3948759730 3948759730-1-con-1-21 /sys/deckhouse-oss/install:pr3318 cloud-user@158.160.39.141

2023-01-18 12:46 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.21 3948759647 3948759647-1-con-1-21 /sys/deckhouse-oss/install:pr3318 centos@52.59.53.38

2023-01-18 12:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-18 12:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-18 12:46 UTC, duckhawk commented
/e2e/abort static;Static;containerd;1.21 3948759518 3948759518-1-con-1-21 /sys/deckhouse-oss/install:pr3318 astra@192.168.199.78

2023-01-18 12:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-18 12:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-18 12:47 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.21 3948759499 3948759499-1-con-1-21 /sys/deckhouse-oss/install:pr3318 ubuntu@10.220.203.29

2023-01-18 12:48 UTC, duckhawk commented
/e2e/abort openstack;Standard;containerd;1.21 3948759487 3948759487-1-con-1-21 /sys/deckhouse-oss/install:pr3318 debian@5.159.101.138

2023-01-18 12:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-18 12:48 UTC, duckhawk commented
/e2e/abort azure;Standard;containerd;1.21 3948759517 3948759517-1-con-1-21 /sys/deckhouse-oss/install:pr3318 azureuser@20.229.188.26

2023-01-18 12:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-18 12:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-18 13:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-18 13:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-26 06:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-01-26 06:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-01-26 06:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-01-26 06:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-26 06:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-26 06:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-26 06:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-01-26 07:31 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.21 4012964824 4012964824-1-con-1-21 /sys/deckhouse-oss/install:pr3318 user@34.89.134.100

2023-01-26 07:31 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.21 4012964824 4012964824-1-con-1-21 /sys/deckhouse-oss/install:pr3318 user@34.89.134.100

2023-01-26 07:31 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.21 4012964824 4012964824-1-con-1-21 /sys/deckhouse-oss/install:pr3318 user@34.89.134.100

2023-01-26 07:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:31 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.21 4012964824 4012964824-1-con-1-21 /sys/deckhouse-oss/install:pr3318 user@34.89.134.100

2023-01-26 07:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:32 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.21 4012964626 4012964626-1-con-1-21 /sys/deckhouse-oss/install:pr3318 ubuntu@10.220.203.29

2023-01-26 07:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:32 UTC, duckhawk commented
/e2e/abort static;Static;containerd;1.21 4012964645 4012964645-1-con-1-21 /sys/deckhouse-oss/install:pr3318 astra@192.168.199.40

2023-01-26 07:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:32 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.21 4012964564 4012964564-1-con-1-21 /sys/deckhouse-oss/install:pr3318 centos@18.157.69.90

2023-01-26 07:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:32 UTC, duckhawk commented
/e2e/abort openstack;Standard;containerd;1.21 4012964548 4012964548-1-con-1-21 /sys/deckhouse-oss/install:pr3318 debian@5.159.102.25

2023-01-26 07:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:33 UTC, duckhawk commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.21 4012964522 4012964522-1-con-1-21 /sys/deckhouse-oss/install:pr3318 cloud-user@158.160.57.179

2023-01-26 07:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:33 UTC, duckhawk commented
/e2e/abort azure;Standard;containerd;1.21 4012964499 4012964499-1-con-1-21 /sys/deckhouse-oss/install:pr3318 azureuser@20.56.35.82

2023-01-26 07:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-26 07:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-27 08:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-01-31 14:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-01-31 14:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-31 14:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-31 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-01-31 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-01-31 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-01-31 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-01 05:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-01 05:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-01 05:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-01 05:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-01 05:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-01 05:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-01 05:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-01 07:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-01 07:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-01 07:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-01 07:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-01 07:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-01 07:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-05 16:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-05 16:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-05 16:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-05 16:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-05 16:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-05 16:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-05 16:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-13 14:58 UTC, apolovov requested changes
God bless you.

2023-02-13 14:58 UTC, apolovov commented on modules/040-control-plane-manager/templates/daemonset.yaml
> +        image: "{{ $.Values.global.modulesImages.registry.base }}@{{ $imageTag }}"
```suggestion
        image: "{{ $.Values.global.modulesImages.registry.base }}@{{ $imageDigest }}"
```

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
> +image: release-channel-version-artifact
```suggestion
image: release-channel-version-prebuild
```

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
> +      yq w /deckhouse/release.yaml version $version digest $deckhouseImageDigest  | yq r - -j > version.json
```suggestion
      yq w /deckhouse/release.yaml version $version digest $deckhouseImageDigest | yq r - -j > version.json
```

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
> +  - image: release-channel-version-artifact
```suggestion
  - image: release-channel-version-prebuild
```

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
>      - type: ImageTag
Why ImageTag? Consider removing it.

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
> +    env | grep MODULES_IMAGES_TAGS | cut -f 4- -d '_' > tags_wo_sha.lst
It is garbage.

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
>      imports:
image name must be image-digests.

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
> +      targetEnv: MODULES_IMAGES_ID_{{ $ModuleNameCamel }}_{{ $ImageNameCamel }}
```suggestion
      targetEnv: MODULE_IMAGE_DIGEST_{{ $ModuleNameCamel }}_{{ $ImageNameCamel }}
```

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
> +      targetEnv: MODULES_IMAGES_ID_{{ $ModuleNameCamel }}_{{ $ImageNameCamel }}
Note, it is single MID.

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
> +      echo $tagKey'='$imageId >> tags_full.lst
```suggestion
      # 'AAA_BBB_CCC=asassd@xxx' -> 'asdasd'
      imageKey=`echo $line | cut -f 4- -d '_' | cut -f 1 -d '='`
      imageDigest=`echo $line | cut -f 4- -d '_' | cut -f 2 -d '='`
      echo $imageKey'='$imageDigest >> tags_full.lst
```

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
> +    cat tags_full.lst | jq -Rn '
```suggestion
    cat digests_full.lst | jq -Rn '
```

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
>            {($moduleName): {($imageName): $tag}}
tag => digest.

2023-02-13 14:58 UTC, apolovov commented on werf.yaml
>            {($moduleName): {($imageName): $tag}}
grep the whole project pls with word 'tag'.

2023-02-13 14:58 UTC, apolovov commented on helm_lib/templates/_module_image.tpl
> +  {{- printf "%s@%s" $registryBase $imageHash }}
```suggestion
  {{- printf "%s@%s" $registryBase $imageDigest }}
```

2023-02-13 14:58 UTC, apolovov commented on dhctl/pkg/kubernetes/actions/deckhouse/install.go
> +	return fmt.Sprintf("%s%s:%s", c.Registry.Address, c.Registry.Path, tag)
It isn't needed.

2023-02-13 14:58 UTC, apolovov commented on modules/002-deckhouse/hooks/update_deckhouse_image.go
> +	isDigest := strings.LastIndex(dpi.Image, "@sha256")
add a comment pls.

2023-02-13 14:58 UTC, apolovov commented on modules/040-node-manager/hooks/lock_bashible_apiserver.go
> +			isDigest := strings.LastIndex(cont.Image, "@sha256")
it isn't necessary, remove pls.

2023-02-13 14:58 UTC, apolovov commented on testing/matrix/linter/rules/rules.go
> +		cutPos := strings.LastIndex(c.Image, "@imageHash")
It is ununderstabdable. Do we need it at all?

2023-02-13 14:58 UTC, apolovov commented on testing/matrix/linter/rules/rules.go
> +		cutPos := strings.LastIndex(c.Image, "@imageHash")
/(.+)(@|:)imageHash$/\1/

2023-02-13 14:58 UTC, apolovov commented on testing/matrix/linter/rules/rules.go
> +				"Cannot parse repository from path - "+c.Image,
```suggestion
				"Cannot parse repository from image: "+c.Image,
```

2023-02-13 14:58 UTC, apolovov commented on candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
>      PACKAGE="$(awk -F ":" '{print $1}' <<< "${PACKAGE_WITH_TAG}")"
TAG -> DIGEST

2023-02-20 07:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-20 07:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-20 07:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-20 07:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-20 07:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-20 07:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-20 17:42 UTC, duckhawk commented
/e2e/abort openstack;Standard;containerd;1.21 4220969384 4220969384-1-con-1-21 /sys/deckhouse-oss/install:pr3318 debian@31.41.155.22

2023-02-20 17:42 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.21 4220969116 4220969116-1-con-1-21 /sys/deckhouse-oss/install:pr3318 ubuntu@10.220.203.26

2023-02-20 17:42 UTC, duckhawk commented
/e2e/abort static;Static;containerd;1.21 4220969008 4220969008-1-con-1-21 /sys/deckhouse-oss/install:pr3318 astra@192.168.199.105

2023-02-20 17:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 17:42 UTC, duckhawk commented
/e2e/abort azure;Standard;containerd;1.21 4220968803 4220968803-1-con-1-21 /sys/deckhouse-oss/install:pr3318 azureuser@40.113.167.135

2023-02-20 17:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 17:42 UTC, duckhawk commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.21 4220968724 4220968724-1-con-1-21 /sys/deckhouse-oss/install:pr3318 cloud-user@158.160.54.34

2023-02-20 17:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 17:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 17:43 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.21 4220968573 4220968573-1-con-1-21 /sys/deckhouse-oss/install:pr3318 user@34.141.94.165

2023-02-20 17:43 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.21 4220968573 4220968573-1-con-1-21 /sys/deckhouse-oss/install:pr3318 user@34.141.94.165

2023-02-20 17:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 17:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 17:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-20 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-20 19:07 UTC, duckhawk commented
/e2e/abort openstack;Standard;containerd;1.21 4226032681 4226032681-1-con-1-21 /sys/deckhouse-oss/install:pr3318 debian@185.91.53.131

2023-02-20 19:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 19:10 UTC, duckhawk commented
/e2e/abort static;Static;containerd;1.21 4226032395 4226032395-1-con-1-21 /sys/deckhouse-oss/install:pr3318 astra@192.168.199.29

2023-02-20 19:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-20 19:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-20 19:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-21 02:21 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.21 4226434958 4226434958-1-con-1-21 /sys/deckhouse-oss/install:pr3318 centos@3.76.56.184

2023-02-21 02:21 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.21 4226434958 4226434958-1-con-1-21 /sys/deckhouse-oss/install:pr3318 centos@3.76.56.184

2023-02-21 02:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-21 02:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-21 07:53 UTC, duckhawk commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.21 4226435226 4226435226-1-con-1-21 /sys/deckhouse-oss/install:pr3318 cloud-user@51.250.64.102

2023-02-21 07:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-21 07:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-21 08:53 UTC, duckhawk commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.21 4230419381 4230419381-1-con-1-21 /sys/deckhouse-oss/install:pr3318 cloud-user@51.250.85.30

2023-02-21 08:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-21 12:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-21 13:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-21 13:21 UTC, duckhawk commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.21 4232499324 4232499324-1-con-1-21 /sys/deckhouse-oss/install:pr3318 cloud-user@158.160.61.165

2023-02-21 13:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-23 11:01 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.21 4220968570 4220968570-1-con-1-21 /sys/deckhouse-oss/install:pr3318 centos@35.156.198.25

2023-02-23 11:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-28 08:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-28 08:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-28 08:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-28 08:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-28 08:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-28 08:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-28 08:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-28 08:57 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.23 4290847212 4290847212-1-con-1-23 /sys/deckhouse-oss/install:pr3318 ubuntu@10.220.203.26

2023-02-28 08:57 UTC, duckhawk commented
/e2e/abort openstack;Standard;containerd;1.23 4290847806 4290847806-1-con-1-23 /sys/deckhouse-oss/install:pr3318 debian@46.161.53.198

2023-02-28 08:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-28 08:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-28 08:58 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.23 4290847397 4290847397-1-con-1-23 /sys/deckhouse-oss/install:pr3318 user@35.198.127.126

2023-02-28 08:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-28 09:36 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4290847892 4290847892-1-con-1-23 /sys/deckhouse-oss/install:pr3318 centos@18.193.186.235

2023-02-28 09:36 UTC, duckhawk commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4290847893 4290847893-1-con-1-23 /sys/deckhouse-oss/install:pr3318 cloud-user@158.160.37.197

2023-02-28 09:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-28 09:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-28 10:02 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.21 4234804411 4234804411-1-con-1-21 /sys/deckhouse-oss/install:pr3318 cloud-user@158.160.36.109

2023-02-28 10:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-28 13:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-28 13:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-28 13:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-28 13:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-28 13:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-28 13:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-28 13:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-28 15:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-28 15:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-28 15:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-28 15:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-28 15:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-01 07:00 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.25 4294816725 4294816725-1-con-1-25 /sys/deckhouse-oss/install:pr3318 ubuntu@10.220.203.26

2023-03-01 07:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-01 07:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-01 07:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-01 07:50 UTC, z9r5 submitted a review, later dismissed

2023-03-01 10:17 UTC, RomanenkoDenys commented on global-hooks/discovery/modules_images_tags.go
> +	tagsFile := "/deckhouse/modules/images_digests.json"
You need to rename hook and variables

2023-03-01 10:17 UTC, RomanenkoDenys commented on global-hooks/discovery/modules_images_tags.go
> +		tagsFile = os.Getenv("D8_DIGESTS_TMP_FILE")
digestsFile ?

2023-03-01 10:17 UTC, RomanenkoDenys commented on global-hooks/discovery/modules_images_tags.go
> +		moduleTagsObj, err := parseImagesTagsFile(filepath.Join(evalPath, "images_digests.json"))
moduleDigestsObj ?

2023-03-01 10:18 UTC, RomanenkoDenys commented on helm_lib/charts/deckhouse_lib_helm/templates/_module_image.tpl
> +  {{- $imageDigest := index $context.Values.global.modulesImages.tags $moduleName $containerName }}
helm_lib now is external package, so you need second PR to helm lib repo

2023-03-01 10:21 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/lock_bashible_apiserver.go
> +	valuesDigest := input.Values.Get("global.modulesImages.tags.nodeManager.bashibleApiserver").String()
we should change path to `global.modulesImages.digests`

2023-03-01 10:22 UTC, RomanenkoDenys commented on modules/040-node-manager/images/bashible-apiserver/pkg/template/context.go
>  	c.contextBuilder.SetImagesData(imagesTags)
imagesDigests ?

2023-03-01 10:25 UTC, RomanenkoDenys requested changes
Questions

2023-03-02 03:35 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.23 4290847627 4290847627-1-con-1-23 /sys/deckhouse-oss/install:pr3318 astra@192.168.199.204

2023-03-02 03:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-03 15:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-03 15:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-03 15:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-03 15:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-03 15:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-03 15:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-03 15:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-03 16:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-03 16:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-03 16:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-03 16:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-03 16:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-03 16:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-03 17:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-03 17:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-03 17:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-03 17:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-03 17:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-03 17:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-03 17:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-03 17:57 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.24 4325830228 4325830228-1-con-1-24 /sys/deckhouse-oss/install:pr3318 user@34.107.50.5

2023-03-03 17:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-03 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-04 11:22 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.24 4325830277 4325830277-1-con-1-24 /sys/deckhouse-oss/install:pr3318 ubuntu@10.220.203.30

2023-03-04 11:22 UTC, duckhawk commented
/e2e/abort openstack;Standard;containerd;1.24 4325830602 4325830602-1-con-1-24 /sys/deckhouse-oss/install:pr3318

2023-03-04 11:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-04 11:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-04 11:22 UTC, duckhawk commented
/e2e/abort azure;Standard;containerd;1.24 4325830175 4325830175-1-con-1-24 /sys/deckhouse-oss/install:pr3318 azureuser@74.234.202.185

2023-03-04 11:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-04 12:10 UTC, duckhawk commented on modules/002-deckhouse/hooks/update_deckhouse_image.go
>  	"github.com/flant/addon-operator/pkg/module_manager/go_hook/metrics"
This is just small refactor, in phase 2 I'll rewrite this totally

2023-03-04 14:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-04 14:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-04 14:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-04 14:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-04 14:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-04 14:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-04 14:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-04 14:44 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.23 4331357572 4331357572-1-con-1-23 /sys/deckhouse-oss/install:pr3318 ubuntu@10.220.203.29

2023-03-04 14:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-04 14:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-04 15:23 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.23 4331533882 4331533882-1-con-1-23 /sys/deckhouse-oss/install:pr3318 ubuntu@10.220.203.29

2023-03-04 15:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-04 15:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-04 16:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-04 16:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-04 16:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-04 16:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-04 16:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-04 16:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-04 16:31 UTC, duckhawk commented
/e2e/abort azure;Standard;containerd;1.24 4331760919 4331760919-1-con-1-24 /sys/deckhouse-oss/install:pr3318 azureuser@74.234.194.3

2023-03-04 16:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-04 18:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-04 18:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-04 18:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-04 18:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-04 18:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-04 18:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-04 18:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-04 18:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-06 15:19 UTC, z9r5 approved these changes

2023-03-07 08:02 UTC, shvgn submitted a review, later dismissed
✔️ upmeter

2023-03-09 08:25 UTC, kvaps requested changes
Found a few places with `:` instead of `@`:
https://github.com/deckhouse/deckhouse/blob/9a8df4685b458f88528a34245fe117db84bd2e8f/modules/500-operator-trivy/templates/configmap.yaml#L24

https://github.com/deckhouse/deckhouse/blob/9a8df4685b458f88528a34245fe117db84bd2e8f/modules/041-linstor/templates/linstor-csi/linstorcsidriver.yaml#L158-L163

[linstor]()

2023-03-09 08:25 UTC, kvaps commented on modules/041-linstor/templates/linstor-csi/linstorcsidriver.yaml
> +  csiSnapshotterImage: "{{ .registry.base }}:{{ index .digests.common (list "csiExternalSnapshotter" $kubeVersion.Major $kubeVersion.Minor | join "") }}"
```suggestion
  csiAttacherImage: "{{ .registry.base }}@{{ index .digests.common (list "csiExternalAttacher" $kubeVersion.Major $kubeVersion.Minor | join "") }}"
  csiLivenessProbeImage: "{{ .registry.base }}@{{ index .digests.common (list "csiLivenessprobe" $kubeVersion.Major $kubeVersion.Minor | join "") }}"
  csiNodeDriverRegistrarImage: "{{ .registry.base }}@{{ index .digests.common (list "csiNodeDriverRegistrar" $kubeVersion.Major $kubeVersion.Minor | join "") }}"
  csiProvisionerImage: "{{ .registry.base }}@{{ index .digests.common (list "csiExternalProvisioner" $kubeVersion.Major $kubeVersion.Minor | join "") }}"
  csiResizerImage: "{{ .registry.base }}@{{ index .digests.common (list "csiExternalResizer" $kubeVersion.Major $kubeVersion.Minor | join "") }}"
  csiSnapshotterImage: "{{ .registry.base }}@{{ index .digests.common (list "csiExternalSnapshotter" $kubeVersion.Major $kubeVersion.Minor | join "") }}"
```

2023-03-09 08:26 UTC, kvaps commented on modules/041-linstor/templates/linstor-csi/linstorcsidriver.yaml
> +  csiSnapshotterImage: "{{ .registry.base }}:{{ index .digests.common (list "csiExternalSnapshotter" $kubeVersion.Major $kubeVersion.Minor | join "") }}"
better solution:

```suggestion
  csiAttacherImage: {{ include "helm_lib_module_image" (list . (list "csiExternalAttacher" $kubeVersion.Major $kubeVersion.Minor | join "" )) }}
  csiLivenessProbeImage: {{ include "helm_lib_module_image" (list . (list "csiLivenessprobe" $kubeVersion.Major $kubeVersion.Minor | join "" )) }}
  csiNodeDriverRegistrarImage: {{ include "helm_lib_module_image" (list . (list "csiNodeDriverRegistrar" $kubeVersion.Major $kubeVersion.Minor | join "" )) }}
  csiProvisionerImage: {{ include "helm_lib_module_image" (list . (list "csiExternalProvisioner" $kubeVersion.Major $kubeVersion.Minor | join "" )) }}
  csiResizerImage: {{ include "helm_lib_module_image" (list . (list "csiExternalResizer" $kubeVersion.Major $kubeVersion.Minor | join "" )) }}
  csiSnapshotterImage: {{ include "helm_lib_module_image" (list . (list "csiExternalSnapshotter" $kubeVersion.Major $kubeVersion.Minor | join "" )) }}
```

2023-03-09 10:05 UTC, RomanenkoDenys approved these changes
LGTM

2023-03-13 07:43 UTC, zuzzas submitted a review, later dismissed
You've not touched the trivy-db image, so I expect to regressions.

2023-03-15 12:18 UTC, yalosev commented on global-hooks/discovery/modules_images_tags.go
> +	digestsFile := "/deckhouse/modules/images_digests.json"
Shouldn't we support both cases for external modules? I guess external module could be done with image tag only, then this hook will fail

2023-03-15 15:50 UTC, kvaps approved these changes
LGTM

2023-03-16 12:21 UTC, name212 requested changes
need to release new version of lib-helm

2023-03-16 16:50 UTC, apolovov submitted a review, later dismissed

2023-03-28 14:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-28 14:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-28 14:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-28 14:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-28 14:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-28 14:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-28 15:17 UTC, duckhawk commented
/e2e/abort azure;Standard;containerd;1.22 4544474796 4544474796-1-con-1-22 /sys/deckhouse-oss/install:pr3318 azureuser@74.234.193.172

2023-03-28 15:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-28 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-28 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-28 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-28 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-28 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-28 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-28 16:03 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4544939438 4544939438-1-con-1-23 /sys/deckhouse-oss/install:pr3318

2023-03-28 16:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-28 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-28 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-28 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-28 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-28 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-28 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-28 18:19 UTC, duckhawk commented
/e2e/abort static;Static;containerd;1.25 4546209313 4546209313-1-con-1-25 /sys/deckhouse-oss/install:pr3318 astra@192.168.199.46

2023-03-28 18:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-29 04:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-29 04:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-29 04:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-29 04:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-29 04:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-29 04:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-29 04:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-29 06:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-29 06:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-29 06:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-29 06:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-03-29 06:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-29 06:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-29 08:24 UTC, name212 submitted a review, later dismissed

2023-03-29 08:26 UTC, yalosev commented on helm_lib/charts/deckhouse_lib_helm/Chart.yaml
> +version: 1.1.0
Change to the `1.1.1` version, please

2023-03-29 08:28 UTC, duckhawk commented on helm_lib/charts/deckhouse_lib_helm/Chart.yaml
> +version: 1.1.0
fixed

2023-03-29 08:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-03-29 08:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-03-29 08:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-29 08:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-03-30 11:59 UTC, merged