Create bashible failure events in the default namespace
deckhouse/deckhouse pull request #3351
Opened 2022-12-19 18:20 UTC by Diaderius

## Description
Create bashible failure events in the default namespace.

## Why do we need it, and what problem does it solve?
It is feature regarding for creation events in the **default** namespace if cluster isn't bootstrapped. By this way, you doesn't need to connect to node directly - the event with reference to bashible failure step should be created.
It refers to: #2827

## What is the expected result?
If bashible step is failed, it calls the creating event with bashible step failure in the **default** namespace.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: create bashible events with errors in the default namespace
```

2022-12-26 17:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2022-12-26 18:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-12-26 18:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2022-12-26 19:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-12-28 19:29 UTC, RomanenkoDenys requested changes
need some changes as discussed

2023-01-12 07:15 UTC, yalosev commented on candi/bashible/bashbooster/20_event.sh
> +    eventHash="$(echo -n "$(hostname -s)")-$(journalctl -xeu bashible.service -n 7 | grep -e "Step" | sed -r 's/.*\/(.*)\.sh/\1/' | md5sum | awk '{print $1}' | cut -b -5)"
I think we need a comment here to describe - what are we doing here?

2023-01-18 16:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-19 09:15 UTC, yalosev commented on candi/bashible/bashible.sh.tpl
> +          namespace: d8-cloud-instance-manager
Do we have a namespace for Node object?

2023-01-19 12:56 UTC, Diaderius commented on candi/bashible/bashible.sh.tpl
> +          namespace: d8-cloud-instance-manager
fixed to default ns.

2023-01-20 07:47 UTC, RomanenkoDenys commented on candi/bashible/bashible.sh.tpl
> +    eventLog="/var/lib/bashible/step.log"
step should be an argument of the bb-event-error-create function

2023-01-20 07:48 UTC, RomanenkoDenys reviewed
one simple change

2023-01-20 17:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-20 18:35 UTC, RomanenkoDenys approved these changes
LGTM

2023-01-23 09:01 UTC, yalosev approved these changes

2023-01-23 09:02 UTC, merged