[candi] Temporary disable seccomp for kube-controller-manager
deckhouse/deckhouse pull request #3426
Opened 2022-12-27 19:07 UTC by konstantin-axenov

Signed-off-by: Konstantin Aksenov <konstantin.aksenov@flant.com>

## Description

Explicitly set seccompProfile type to Unconfined

## Why do we need it, and what problem does it solve?

Kubeadm sets seccomp to RuntimeDefault for kube-controller-manager in Kubernetes clusters > 1.21
```
  securityContext:
    seccompProfile:
      type: RuntimeDefault
```
We still have Docker with different runc version. And at least with runc version `1.0.0-rc92` we have problem with ceph rbd in-tree
```
Thread::try_create(): pthread_create failed with error 1./src/common/Thread.cc: In function 'void Thread::create(const char*, size_t)' thread 7f07ccea9340 time 2022-12-27T18:42:01.846784+0000
./src/common/Thread.cc: 165: FAILED ceph_assert(ret == 0)
 ceph version 17.2.0 (43e2e60a7559d3f46c9d53f1ca875fd499a1e35e) quincy (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x128) [0x7f07ce02a369]
 2: /usr/lib/x86_64-linux-gnu/ceph/libceph-common.so.2(+0x257525) [0x7f07ce02a525]
 3: /usr/lib/x86_64-linux-gnu/ceph/libceph-common.so.2(+0x32cb4e) [0x7f07ce0ffb4e]
 4: (global_pre_init(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const*, std::vector<char const*, std::allocator<char const*> >&, unsigned int, code_environment_t, int)+0x3ec) [0x55fd31b6655c]
 5: (global_init(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const*, std::vector<char const*, std::allocator<char const*> >&, unsigned int, code_environment_t, int, bool)+0x84) [0x55fd31b689a4]
 6: (rbd::Shell::execute(int, char const**)+0x157) [0x55fd319f80a7]
 7: main()
 8: /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f07cd7f2d90]
 9: __libc_start_main()
 10: _start()
```
Runc update or disabling seccomp fixes the problem. I'd prefer to disable seccomp until Docker support isn't dropped.

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: Temporary disable seccomp for kube-controller-manager
```

2022-12-27 19:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2022-12-28 07:47 UTC, RomanenkoDenys approved these changes
LGTM

2022-12-28 07:53 UTC, RomanenkoDenys requested changes
one small thing

2022-12-28 07:53 UTC, RomanenkoDenys commented on candi/control-plane-kubeadm/patches/kube-controller-manager.yaml.tpl
> +{{- if semverCompare "> 1.21" .clusterConfiguration.kubernetesVersion }}
We need TODO comment here

2022-12-28 08:14 UTC, konstantin-axenov commented on candi/control-plane-kubeadm/patches/kube-controller-manager.yaml.tpl
> +{{- if semverCompare "> 1.21" .clusterConfiguration.kubernetesVersion }}
Done

2022-12-28 08:17 UTC, RomanenkoDenys approved these changes

2022-12-28 22:39 UTC, merged

2022-12-28 22:39 UTC, deckhouse-BOaTswain commented
Cherry pick PR [3449](https://github.com/deckhouse/deckhouse/pull/3449) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!