[deckhouse] one source of truth for deckhouse registry (stage #2)
deckhouse/deckhouse pull request #3499
Opened 2023-01-10 12:12 UTC by fl64

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-01-18 13:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-01-18 15:14 UTC, name212 requested changes
- remove unused constant
- support image path with port

2023-01-18 15:14 UTC, name212 commented on modules/002-deckhouse/hooks/set_module_image_value.go
> +	parts := strings.SplitN(image, ":", 2)
Deckhouse image can contain port. for example `air-gap-domain.com:7777/deckhouse/fe:v.1.42.0` It is important for air gap environments. We should support it. This code split string for only 2 parts.

2023-01-18 15:14 UTC, name212 commented on modules/002-deckhouse/hooks/set_module_image_value_test.go
> +				Expect(f.ValuesGet("deckhouse.internal.currentReleaseImageName").String()).To(Equal("registry.deckhouse.io/deckhouse/fe:test"))
Add test for 'with port' case

2023-01-18 15:14 UTC, name212 commented on tools/change-registry.sh
> +  DECKHOUSE_TAG="$(kubectl -n d8-system get deploy deckhouse -o json | jq '.spec.template.spec.containers[] | select(.name=="deckhouse") | .image | split(":")[1]' -r)"
Need support image paths with port

2023-01-18 15:14 UTC, name212 commented on tools/change-registry.sh
>    fi
Also please fix [this](https://github.com/deckhouse/deckhouse/pull/3499/files#diff-8bf4756771579a6415a1f1eef7cc430258b62a822e0470732b116b6c4c45d631R105) validator for support images paths with port

2023-01-18 15:16 UTC, name212 commented on tools/change-registry.sh
>    fi
https://github.com/deckhouse/deckhouse/blob/8efbfc6b68208d461c839379c62ffcc7d1f965f9/tools/change-registry.sh#L105

2023-01-18 15:17 UTC, name212 commented on tools/change-registry.sh
>    fi
And one thing. Do you check changing registry operation with CA file?

2023-01-19 10:02 UTC, fl64 commented on dhctl/pkg/kubernetes/actions/manifests/manifests.go
> -
fixed

2023-01-19 10:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @fl64. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-01-19 16:09 UTC, name212 submitted a review, later dismissed

2023-01-23 12:28 UTC, yalosev requested changes

2023-01-23 12:28 UTC, yalosev commented on go_lib/dependency/cr/cr.go
> +	auths := gjson.Get(string(dockerCfg), "auths").Map()
handle this situation
```
{
  "auths": {
    "dev-registry.deckhouse.io": {
      "auth": "d3JpdGV0b2tlbjo0YWM5ZmUyYjcwYzU0ZDA5ZjZkNDM1MzI4ZGZmMDg0NA=="
    },
     "prod-registry.deckhouse.io": {
      "auth": "d3JpdGV0b2tlbjo0YWM5ZmUyYjcwYzU0ZDA5ZjZkNDM1MzI4ZGZmMDg0NA=="
    }
  }
}
```

2023-01-23 12:28 UTC, yalosev commented on go_lib/dependency/cr/cr.go
> +	dockerCfg, err := base64.StdEncoding.DecodeString(dockerCfgBase64)
````
u1, _ := url.Parse(repo)
u1.Host
```

key := u1.Host

  var tmp map[string]interface{}
  json.Unmarshal(a, &tmp)

for _, a := range tmp {
  u2, _ := url.Parse(a)
  if u2 != u1 { 
    continue
  }
...
}

2023-01-23 12:28 UTC, yalosev commented on go_lib/dependency/cr/cr.go
> +func NewClient(repo, dockerCfgBase64 string, options ...Option) (Client, error) {
```
func WithAuth(dockerCfg string) Option {
	return func(options *registryOptions) {
		options.dockerCfg = dockerCfg
	}
}
```

repo may be `registry.deckhouse.io/ee/modules`

2023-01-24 06:40 UTC, yalosev approved these changes

2023-01-24 06:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-01-24 07:36 UTC, name212 commented on modules/002-deckhouse/hooks/set_module_image_value_test.go
> +				Expect(f.ValuesGet("deckhouse.internal.currentReleaseImageName").String()).To(Equal("registry.deckhouse.io/deckhouse/fe:test666"))
it should be equal `registry.deckhouse.io:666/deckhouse/ce:test666` not `registry.deckhouse.io/deckhouse/fe:test666`. Or does not equal? and why?

2023-01-24 07:38 UTC, name212 approved these changes

2023-01-24 07:39 UTC, merged