[candi][registrypackages] Downgrade kubernetes-cni to 0.8.7 for centos due to flannel binary missing in 1.1.1
deckhouse/deckhouse pull request #3503
Opened 2023-01-10 14:50 UTC by gmaiorov

Signed-off-by: Gleb Maiorov <gleb.maiorov@flant.com>

## Description

Downgrade kubernetes-cni to 0.8.7 for centos due to flannel binary missing in `kubernetes-cni:1.1.1` rpm package.

## Why do we need it, and what problem does it solve?

Update to K8s 1.23 broken on CentOS-based systems due to this issue.
## What is the expected result?

Update to K8s 1.23 works on CentOS-based systems.
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Downgrade kubernetes-cni to 0.8.7 for centos
impact_level: default
```

2023-01-11 09:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-11 13:45 UTC, gmaiorov commented
/e2e/abort aws;WithoutNAT;containerd;1.23 3891508847 3891508847-1-con-1-23 /sys/deckhouse-oss/install:pr3503 centos@35.156.149.189

2023-01-11 13:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-11 14:17 UTC, gmaiorov commented
/e2e/abort aws;WithoutNAT;containerd;1.23 3891508847 3891508847-1-con-1-23 /sys/deckhouse-oss/install:pr3503 centos@35.156.149.189

2023-01-11 14:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-11 15:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-11 16:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-11 17:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-01-11 17:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-11 17:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-12 12:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-12 12:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-12 12:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-01-12 12:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-12 17:27 UTC, gmaiorov commented
/e2e/abort aws;WithoutNAT;containerd;1.21 3902365105 3902365105-1-con-1-21 /sys/deckhouse-oss/install:pr3503 centos@3.123.56.131

2023-01-12 17:27 UTC, gmaiorov commented
/e2e/abort aws;WithoutNAT;containerd;1.23 3902365105 3902365105-1-con-1-23 /sys/deckhouse-oss/install:pr3503 centos@3.126.122.136

2023-01-12 17:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-12 17:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-12 17:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-12 18:06 UTC, gmaiorov commented
/e2e/abort aws;WithoutNAT;containerd;1.21 3904640148 3904640148-1-con-1-21 /sys/deckhouse-oss/install:pr3503 centos@18.184.237.9

2023-01-12 18:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-12 18:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-13 06:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-13 07:39 UTC, RomanenkoDenys requested changes
LGTM

2023-01-13 07:39 UTC, RomanenkoDenys commented on modules/007-registrypackages/images/kubernetes-cni-centos/scripts/install
> +[[ -e flannel ]] && cp flannel /opt/cni/bin/flannel
```suggestion
[[ -e flannel ]] && cp -f flannel /opt/cni/bin/flannel
```

2023-01-13 08:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @gmaiorov. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-13 08:53 UTC, RomanenkoDenys approved these changes

2023-01-13 08:54 UTC, merged

2023-01-13 09:14 UTC, deckhouse-BOaTswain commented
Cherry pick PR [3534](https://github.com/deckhouse/deckhouse/pull/3534) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!