[candi] added force libseccomp2 installation while containerd install/update
deckhouse/deckhouse pull request #3504
Opened 2023-01-10 14:51 UTC by duckhawk

## Description
Added force libseccomp2 installation while containerd install/update (due issue https://github.com/containerd/containerd/discussions/6577)

## Why do we need it, and what problem does it solve?
Workaround about issue https://github.com/containerd/containerd/discussions/6577

## What is the expected result?

Correct containerd installation/update

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: Added force libseccomp2 installation while containerd install/update (due issue https://github.com/containerd/containerd/discussions/6577)
impact_level: low
```

2023-01-10 15:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-10 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-01-10 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-10 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-10 15:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-01-11 08:21 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.23 3884660946 3884660946-1-con-1-23 /sys/deckhouse-oss/install:pr3504 ubuntu@10.220.203.26

2023-01-11 08:21 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.23 3884662773 3884662773-1-con-1-23 /sys/deckhouse-oss/install:pr3504 user@34.159.68.184

2023-01-11 08:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-11 08:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-11 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-11 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-11 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-11 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-01-11 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-01-12 06:06 UTC, RomanenkoDenys requested changes

2023-01-12 06:06 UTC, RomanenkoDenys commented on candi/bashible/bundles/debian/node-group/031_install_containerd.sh.tpl
> +  fi
```suggestion
  bb-apt-install libseccomp2 --force
```

2023-01-12 06:06 UTC, RomanenkoDenys commented on candi/bashible/bundles/ubuntu-lts/node-group/031_install_containerd.sh.tpl
> +  fi
same

2023-01-16 16:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-16 16:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-01-16 16:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-16 16:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-01-16 21:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-01-16 21:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-16 21:59 UTC, apolovov commented
/e2e/abort openstack;Standard;containerd;1.23 3934089161 3934089161-1-con-1-23 /sys/deckhouse-oss/install:pr3504 debian@5.159.103.163
/e2e/abort vsphere;Standard;containerd;1.23 3934089567 3934089567-1-con-1-23 /sys/deckhouse-oss/install:pr3504 ubuntu@10.220.203.26

2023-01-16 21:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-16 22:01 UTC, apolovov commented
/e2e/abort vsphere;Standard;containerd;1.23 3934089567 3934089567-1-con-1-23 /sys/deckhouse-oss/install:pr3504 ubuntu@10.220.203.26

2023-01-16 22:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @apolovov. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-16 22:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @apolovov. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-16 22:55 UTC, apolovov approved these changes

2023-01-17 08:47 UTC, merged

2023-01-17 08:48 UTC, deckhouse-BOaTswain commented
Cherry pick PR [3562](https://github.com/deckhouse/deckhouse/pull/3562) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!