[candi] noProxy clarification
deckhouse/deckhouse pull request #3526
Opened 2023-01-11 23:31 UTC by apolovov

Signed-off-by: Andrey Polovov <andrey.polovov@flant.com>

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-01-12 05:41 UTC, RomanenkoDenys requested changes

2023-01-12 05:41 UTC, RomanenkoDenys commented on candi/openapi/cluster_configuration.yaml
> +          > Caution! To avoid interference with internal requests ut is important to fill `noProxy` parameter with host subnets.
```suggestion
          > Caution! To avoid interference with internal requests it is important to fill `noProxy` parameter with host subnets.
```

2023-01-12 05:41 UTC, RomanenkoDenys commented on candi/openapi/doc-ru-cluster_configuration.yaml
> +          > Внимание! Для того, чтобы избежать вмешательства в запросы между компонентами кластера, важно заполнить параметр `noProxy` списком подсетей, которые используются на нодах.
```suggestion
          > Внимание! Для того, чтобы избежать использования прокси в запросах между компонентами кластера, важно заполнить параметр `noProxy` списком подсетей, которые используются на нодах.
```

2023-01-12 11:05 UTC, RomanenkoDenys approved these changes

2023-01-12 11:06 UTC, merged

2023-01-13 09:16 UTC, deckhouse-BOaTswain commented
Cherry pick PR [3535](https://github.com/deckhouse/deckhouse/pull/3535) to the branch [release-1.42](https://github.com/deckhouse/deckhouse/tree/release-1.42) successful!