[dhctl][deckhouse] Control plane node readiness check before converge node
deckhouse/deckhouse pull request #353
Opened 2021-12-09 14:18 UTC by name212

## Description
Add probes for check connection to control plane nodes and control-plane manager pod for node.
Add hook for terraform runner with 3 methods: before operation action, check ready and before action.
For control plane nodes we set special label on node and evict deckhouse pod (if need) wait deckhouse is ready, check connect to each node and check ready control-plane manager pod on each node is ready.

Another things:
- small refact converge 
- heal ssh-host param for control plane nodes
- add additional commands for check
- ssh-agent now started in one instance
- add node affinity for deckhouse for evicting

## Why we need it and what problem does it solve?
Close [issue](https://github.com/deckhouse/deckhouse/issues/113)

We need to make sure that the control plane components are ready and healthy in order to safely update the node.

## Changelog entries

```changes
module: dhctl
type: feature
description: "Control plane readiness check before control plane node converging"
note: |
  Add next changes:
  - small refact converge 
  - heal ssh-host param for control plane nodes
  - add additional commands for check
  - ssh-agent now started in one instance
---
module: deckhouse
type: feature
description: "Add node affinity in deckhouse deployment for evicting pod from converging node"
note: "Node with label 'dhctl.deckhouse.io/node-for-converge' exclude from scheduling deckhouse pod"
```

2022-01-28 07:35 UTC, diafour requested changes

2022-01-28 07:35 UTC, diafour commented on dhctl/pkg/kubernetes/actions/converge/converge.go
> +	if nodeGroup.Name == "master" {
```suggestion
	if nodeGroup.Name == MasterNodeGroupName {
```

2022-01-28 07:35 UTC, diafour commented on dhctl/pkg/kubernetes/actions/converge/converge.go
> +		log.DebugLn("Have not nodes to delete")
```suggestion
		log.DebugLn("No nodes to delete")
```

2022-01-28 07:35 UTC, diafour commented on dhctl/pkg/kubernetes/actions/converge/converge.go
> +		log.DebugLn("Skip delete nodes because destructive operations is disabled")
```suggestion
		log.DebugLn("Skip delete nodes because destructive operations are disabled")
```

2022-01-28 07:35 UTC, diafour commented on dhctl/pkg/kubernetes/actions/converge/converge.go
> +			return fmt.Errorf(`Cannot delete ALL master nodes. If you want remove cluster use 'dhctl destroy' command`)
```suggestion
			return fmt.Errorf(`Cannot delete ALL master nodes. If you want to remove cluster use 'dhctl destroy' command`)
```

2022-01-28 07:35 UTC, diafour commented on dhctl/pkg/kubernetes/actions/converge/converge.go
> +		log.DebugF("Skip delete %s node group because destructive operations is disabled\n", c.name)
```suggestion
		log.DebugF("Skip delete %s node group because destructive operations are disabled\n", c.name)
```

2022-01-31 10:52 UTC, name212 commented on dhctl/pkg/util/maputils/maputils.go
> +func NotExistsKeys(m map[string]string, keys ...string) []string {
This function is unused :-) I'll delete it

2022-01-31 10:52 UTC, name212 commented on dhctl/pkg/state/cache/init.go
> +	"github.com/deckhouse/deckhouse/dhctl/pkg/util/stringsutils"
done

2022-01-31 10:53 UTC, name212 commented on dhctl/pkg/kubernetes/actions/deckhouse/pod.go
> +func RestartPod(kubeCl *client.KubernetesClient) error {
Hm. Ok

2022-01-31 10:56 UTC, name212 commented on dhctl/pkg/kubernetes/actions/converge/converge.go
> +		}
Yes.

2022-01-31 11:16 UTC, name212 commented on dhctl/pkg/system/ssh/client.go
> +		inst := frontend.NewAgent(&session.AgentSettings{
done

2022-02-02 13:18 UTC, name212 commented
@diafour I added a comment explaining reconnect to proxy when we delete control-plane node

2022-02-04 08:04 UTC, deckhouse-BOaTswain commented
Run workflow "e2e/run/openstack"...

2022-02-10 07:41 UTC, diafour submitted a review, later dismissed

2022-02-11 19:01 UTC, deckhouse-BOaTswain commented
Running workflow "e2e/run/openstack"...

2022-02-14 06:45 UTC, nabokihms approved these changes

2022-02-14 06:45 UTC, merged