[linstor] add scheduler-injector-webhook
deckhouse/deckhouse pull request #3559
Opened 2023-01-16 20:51 UTC by kvaps

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-01-18 12:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @kvaps. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-01-18 17:08 UTC, z9r5 commented on modules/041-linstor/docs/USAGE_RU.md
> +Any Pod using linstor volumes will be automatically configured to use the `linstor` scheduler.
```suggestion
Любой Pod, использующий тома linstor, будет автоматически настроен на использование планировщика `linstor`.
```

2023-01-18 17:09 UTC, z9r5 commented on modules/041-linstor/docs/USAGE_RU.md
> +Any Pod using linstor volumes will be automatically configured to use the `linstor` scheduler.
```suggestion
Любой Pod, использующий тома linstor, будет автоматически настроен на использование планировщика `linstor`.
```

2023-01-18 17:13 UTC, z9r5 submitted a review, later dismissed

2023-01-20 09:32 UTC, apolovov requested changes
There are points.

2023-01-20 10:02 UTC, kvaps commented on modules/041-linstor/templates/linstor-scheduler-admission/webhook.yaml
> +    - key: kubernetes.io/metadata.name
internaly discussed to keep system namespaces excluded

2023-01-20 10:04 UTC, kvaps commented on tools/linstor_scheduler_webhook/main.go
> +var excludeNamespaces = []string{
internaly discussed to keep system namespaces excluded

2023-01-20 12:04 UTC, kvaps commented on modules/041-linstor/templates/linstor-scheduler-admission/service.yaml
> +      port: 8080
done

2023-01-20 12:06 UTC, kvaps commented on tools/linstor_scheduler_webhook.go
> +Copyright 2022 Flant JSC
fixed

2023-01-20 12:07 UTC, kvaps commented on modules/041-linstor/pod.yaml
> +---
fixed

2023-01-20 12:51 UTC, kvaps commented on modules/041-linstor/hooks/generate_webhook_certs.go
> +/*
didn't know that, thanks,  fixed

2023-01-23 02:54 UTC, z9r5 approved these changes

2023-01-23 07:48 UTC, apolovov approved these changes

2023-01-23 07:49 UTC, z9r5 approved these changes

2023-01-23 08:55 UTC, yalosev approved these changes

2023-01-23 09:07 UTC, merged