[cni-cilium] add labels config value
deckhouse/deckhouse pull request #3573
Opened 2023-01-18 09:25 UTC by RomanenkoDenys

Signed-off-by: Denis Romanenko <denis.romanenko@flant.com>

## Description

Add labels config value.
## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: feature
summary: Added Deckouse config value for cilium entity labels
impact: Cilium pods should be restarted.
impact_level: default
```

2023-01-18 10:59 UTC, zuzzas requested changes

2023-01-18 10:59 UTC, zuzzas commented on modules/021-cni-cilium/templates/configmap.yaml
> +  labels: {{.Values.cniCilium.labelsRegex | join " " | quote }}
```suggestion
  labels: {{ .Values.cniCilium.labelsRegex | join " " | quote }}
```

2023-01-18 11:52 UTC, zuzzas submitted a review, later dismissed

2023-01-20 08:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-20 10:36 UTC, RomanenkoDenys commented
/e2e/abort vsphere;Standard;containerd;1.21 3965985472 3965985472-1-con-1-21 /sys/deckhouse-oss/install:pr3573 ubuntu@10.220.203.30
/e2e/abort vsphere;Standard;containerd;1.23 3965985472 3965985472-1-con-1-23 /sys/deckhouse-oss/install:pr3573 ubuntu@10.220.203.29

2023-01-20 10:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-20 10:43 UTC, RomanenkoDenys commented
/e2e/abort vsphere;Standard;containerd;1.23 3965985472 3965985472-1-con-1-23 /sys/deckhouse-oss/install:pr3573 ubuntu@10.220.203.29

2023-01-20 10:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-01-20 10:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-23 18:26 UTC, konstantin-axenov commented on modules/021-cni-cilium/openapi/config-values.yaml
> +      Labels regexes to reduce identity cardinality.
```suggestion
      Labels regexes to reduce [identity cardinality](https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#limiting-identity-relevant-labels).
```

2023-01-23 18:26 UTC, konstantin-axenov commented on modules/021-cni-cilium/openapi/doc-ru-config-values.yaml
> +      Regex-ы лейблов для уменьшения количества создаваемых identity.
```suggestion
      Regex-ы лейблов для уменьшения [количества создаваемых identity](https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#limiting-identity-relevant-labels).
```

2023-01-24 09:59 UTC, konstantin-axenov approved these changes

2023-01-24 10:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @konstantin-axenov. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-01-24 11:32 UTC, merged