pmacct json-log support for openvpn
deckhouse/deckhouse pull request #3592
Opened 2023-01-20 19:12 UTC by trublast

## Description
pmacct json-log support for openvpn

## Why do we need it, and what problem does it solve?
Sometimes it's required to check user actions over vpn.

## What is the expected result?
Add sidecar with pmacctd.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-01-27 00:04 UTC, apolovov requested changes
It is important to explain the feature in docs/README.md.
I think, there must be additional header like "User's traffic audit" with the explanation.

2023-01-27 00:04 UTC, apolovov commented on modules/500-openvpn/openapi/doc-ru-config-values.yaml
> +      Включить логирование IP соединений в виде json-логов для клиентских openvpn подключений.
Mind the foreign-word-based-words, there must be dash.
```suggestion
      Включить логирование IP-соединений в виде json-логов для клиентских openvpn-подключений.
```

2023-01-27 00:10 UTC, apolovov commented
Also:
* fix the DCO (add a string `Signed-off-by: John Doe <john.doe@example.com>` and repush the commit).
* fix the description — no one knows what pmacct is. Describe the feature a bit wider.
* I prepared the Changelog entries — pls, add the description here.

2023-01-28 08:48 UTC, z9r5 commented on modules/500-openvpn/docs/README.md
> +using the [log-shipper](../460-log-shipper/) module.
```suggestion
The module has the ability to enable logging of all user connections made via VPN in JSON format. Traffic is grouped
by `src_ip, dst_ip, src_port, dst_port, ip_proto` fields. Container logs can be collected and sent for storage or analysis
using the [log-shipper](../460-log-shipper/) module.
```

2023-01-28 08:49 UTC, z9r5 commented on modules/500-openvpn/docs/README_RU.md
> +с помощью модуля [log-shipper](../460-log-shipper/).
```suggestion
Модуль позволяет включить логирование всех пользовательских VPN-соединений в JSON-формате. Группировка трафика происходит по полям `src_ip, dst_ip, src_port, dst_port, ip_proto`. Логи контейнера могут быть собраны и отправлены на хранение или анализ с помощью модуля [log-shipper](../460-log-shipper/).
```

2023-01-28 08:51 UTC, z9r5 commented on modules/500-openvpn/openapi/doc-ru-config-values.yaml
> +      в виде `{"event_type": "purge", "ip_src": "172.25.175.10", "ip_dst": "10.222.0.10", "port_src": 32172, "port_dst": 53, "ip_proto": "udp", "packets": 1, "bytes": 53}`
```suggestion
      Включить логирование VPN-подключений в JSON-формате.
      
      Все соединения внутри `tun` интерфейсов будут собраны через `libpcap` и записаны в лог
      в виде `{"event_type": "purge", "ip_src": "172.25.175.10", "ip_dst": "10.222.0.10", "port_src": 32172, "port_dst": 53, "ip_proto": "udp", "packets": 1, "bytes": 53}`.
```

2023-01-28 08:54 UTC, z9r5 commented on modules/500-openvpn/openapi/config-values.yaml
> +      Enable json-log IP traffic accounting for openvpn client connections.
```suggestion
      Enable logging of VPN connections in JSON format.
```

2023-01-28 08:58 UTC, z9r5 commented
Some tests didn't pass...

2023-01-30 13:04 UTC, apolovov commented
https://github.com/deckhouse/deckhouse/pull/3686

2023-01-30 13:04 UTC, closed without merging