fix false positives in upmeter scheduler monitoring
deckhouse/deckhouse pull request #36
Opened 2021-08-08 11:23 UTC by Nitive

- Increase pod deletion timeout in Upmeter scheduler monitoring
- Upmeter: properly configure timeout for pod lifecycle checker

2021-08-08 11:25 UTC, Nitive commented on modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_pod.go
> +	timeout := controlPlaneChecker.Timeout + c.garbageCollectionTimeout + c.creationTimeout + c.schedulingTimeout + c.deletionTimeout
I'm not sure if control plane checker and garbage collection timeouts were left out on purpose or not

2021-08-10 13:39 UTC, shvgn requested changes
I suggest reverting the timeout calculation in probe for the time being. Nothing else blocks this PR from merging.

2021-08-10 13:39 UTC, shvgn commented on modules/500-upmeter/images/upmeter/pkg/probe/controlplane.go
> +				DeletionTimeout:          20 * time.Second,
Looks reasonable.

2021-08-10 14:04 UTC, Nitive commented on modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_pod.go
> +	timeout := controlPlaneChecker.Timeout + c.garbageCollectionTimeout + c.creationTimeout + c.schedulingTimeout + c.deletionTimeout
Ok, I've reverted the change back

2021-08-10 15:02 UTC, shvgn approved these changes
LGTM

2021-08-10 17:09 UTC, merged