proposal: [documentation] LocalPathProvisioner examples are not clear enough
deckhouse/deckhouse pull request #366
Opened 2021-12-10 10:05 UTC by mac2000

## Description

Did add some more examples, questions and answers we have struggled with while tried to figure out how everything works

## Why we need it and what problem does it solve?

Not sure if I only one who did not realize all that things from the start, but hopefully it will help future users to get up and running faster

## Changelog entries

```changes
module: local-path-provisioner
type: feature
description: documentation examples added
note: documentation on website should differ and have more content after release
```

---

Fixes #360

2021-12-28 07:41 UTC, RomanenkoDenys requested changes

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/FAQ.md
> +At moment delete retention policy is hardcoded, and there is no way to change it [issue](https://github.com/deckhouse/deckhouse/issues/360)
Retention policy `Delete` is hardcoded, and there is no way to change it [issue](https://github.com/deckhouse/deckhouse/issues/360).

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/FAQ.md
> +If you do comething like `kubectl delete -f demo.yml` it does delete `LocalPathProvisioner` which is responsible for folder deletion, so in other words there is no one who will be able to run `rm -rf
I think this typo is not needed due to absent demo.yml in examples.

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/FAQ_RU.md
> +На текущий момент политика удаления зашита в исходные коды и не может быть изменена [issue](https://github.com/deckhouse/deckhouse/issues/360)
Политика удаления установлена в `Delete` и не может быть изменена [issue](https://github.com/deckhouse/deckhouse/issues/360).

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/FAQ_RU.md
> +Если была выполнена команда по типу `kubectl delete -f demo.yml` она удалила все разом, включая `LocalPathProvisioner` который в свою очередь отвечает за фактическое удаление папки, другими словами п
I think this typo is not needed due to absent demo.yml in examples.

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/FAQ_RU.md
> +Для того что бы все сработало как надо, необходимо удалить pod'ы, следом pvc, уже затем модуль `LocalPathProvisioner` увидит эти изменения и очистит папки на сервере.
Папки на диске удаляются `localPathProvisioner` автоматически после удаления pod'ов и pvc.

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/FAQ_RU.md
> +## Почему папка не была удалена с сервера после очистки?
## Удаление папок с диска.

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/FAQ.md
> +## Why folder not deleted from server after cleanup?
## Folder removing from disk.

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/README_RU.md
> +- `Delete` политика зашита в исходные коды [issue](https://github.com/deckhouse/deckhouse/issues/360)
```suggestion
-  Политика по умолчанию - `Delete`, изменить это нельзя [issue](https://github.com/deckhouse/deckhouse/issues/360)
```

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/USAGE.md
> +- This example will create `localpath-system` storage class which **must** be used by pods for everything to work
```suggestion
- This example will create `localpath-system` storage class which be used by prometheus pods to store data.
```

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/USAGE.md
> +- Volumes created by provisioner will have delete retention policy which is hardcoded ([issue](https://github.com/deckhouse/deckhouse/issues/360))
```suggestion
- Volumes created by provisioner will have default delete retention policy which is hardcoded ([issue](https://github.com/deckhouse/deckhouse/issues/360)).
```

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/USAGE.md
> +- If provisioner will be delete before claims folders will not be deleted from node
```suggestion
- If the provisioner will be deleted before claims folders will not be deleted from node.
```

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/USAGE.md
> +- Note that in example `system` node is used which probably will have some taints so pods **must** have corresponding tolerations
this isn't needed due to prometheus has tolerations for system nodes by default.

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/USAGE_RU.md
> +- Этот пример создаст `localpath-system` класс (`storage class`) который **должен** быть использован в pod'ах что бы все заработало
```suggestion
- Этот пример создаст `localpath-system` storage-class который  будет использоваться для хранения данных в pod'ах prometheus.
```

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/USAGE_RU.md
> +- Все создаваемые хранилища будут иметь политику очистки `Delete` ([issue](https://github.com/deckhouse/deckhouse/issues/360))
```suggestion
- Все создаваемые хранилища будут иметь политику очистки по-умолчанию `Delete`, которую нельзя изменить ([issue](https://github.com/deckhouse/deckhouse/issues/360)).
```

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/USAGE_RU.md
> +- Обратите внимание - в примере предпологается создание папок на системных нодах, которые скорее всего имеют ряд ограничителей (taints), а как следствие pod'ы **должны** иметь соотв. tolerations
this isn't needed due to prometheus has tolerations for system nodes by default.

2021-12-28 07:41 UTC, RomanenkoDenys commented on modules/031-local-path-provisioner/docs/USAGE_RU.md
> +- Если этот объект будет удален раньше чем объекты его использующие, папки с сервера удалены не будут
```suggestion
- Если `provisioner` будет удален раньше чем объекты его использующие, папки с сервера удалены не будут.
```

2022-01-29 11:57 UTC, nabokihms commented
Denys and Mac2000 reached the agreement, that the problem with retention is fixed by this PR https://github.com/deckhouse/deckhouse/pull/561

As no more work is planned for this PR, I will close it. Feel free to reopen if needed.

2022-01-29 11:57 UTC, closed without merging