[extended-monitoring] Fixed keychain panic in IAE
deckhouse/deckhouse pull request #3685
Opened 2023-01-30 12:49 UTC by zuzzas

Signed-off-by: Andrey Klimentyev <andrey.klimentyev@flant.com>

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-01-30 14:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-01-31 17:28 UTC, RomanenkoDenys approved these changes

2023-01-31 17:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-01-31 18:53 UTC, apolovov requested changes

2023-01-31 18:53 UTC, apolovov commented on modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
> +RUN wget --no-check-certificate https://github.com/deckhouse/k8s-image-availability-exporter/tarball/v0.3.4 -O - | tar -xz --strip-components=1 && \
Why --no-check-certificate?

2023-02-01 13:45 UTC, zuzzas commented on modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
> +RUN wget --no-check-certificate https://github.com/deckhouse/k8s-image-availability-exporter/tarball/v0.3.4 -O - | tar -xz --strip-components=1 && \
Fixed.

2023-02-02 14:05 UTC, RomanenkoDenys approved these changes

2023-02-03 23:13 UTC, nabokihms approved these changes

2023-02-03 23:13 UTC, merged