Openvpn pmacctd
deckhouse/deckhouse pull request #3686
Opened 2023-01-30 13:03 UTC by trublast

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-02-02 06:58 UTC, z9r5 approved these changes

2023-02-06 07:46 UTC, vitaliy-sn requested changes
Need to fix tests and DCO

2023-02-06 15:47 UTC, z9r5 commented
@trublast Please, rebase to the fresh main branch to pass linters.

2023-03-02 11:11 UTC, vitaliy-sn approved these changes
lgfm

2023-03-02 16:52 UTC, apolovov approved these changes

2023-03-02 16:52 UTC, apolovov commented on modules/500-openvpn/docs/README.md
> +using the [log-shipper](../460-log-shipper/) module.
```suggestion
The module can log user's activity via VPN in JSON format. Traffic is grouped
by `src_ip, dst_ip, src_port, dst_port, ip_proto` fields. Container logs can be collected and sent to storage for further audit
using the [log-shipper](../460-log-shipper/) module.
```

2023-03-02 16:52 UTC, apolovov commented on modules/500-openvpn/docs/README_RU.md
> +Модуль позволяет включить логирование VPN-подключений в JSON-формате. Группировка трафика происходит по полям `src_ip, dst_ip, src_port, dst_port, ip_proto`. Логи контейнера могут быть собраны и отпр
```suggestion
Модуль позволяет включить логирование пользовательской активности через VPN в JSON-формате. Группировка трафика происходит по полям `src_ip, dst_ip, src_port, dst_port, ip_proto`. Логи контейнера могут быть собраны и отправлены на хранение для последующего аудита с помощью модуля [log-shipper](../460-log-shipper/).
```

2023-03-02 16:52 UTC, apolovov commented on modules/500-openvpn/openapi/config-values.yaml
> +      as `{"event_type": "purge", "ip_src": "172.25.175.10", "ip_dst": "10.222.0.10", "port_src": 32172, "port_dst": 53, "ip_proto": "udp", "packets": 1, "bytes": 53}`
```suggestion
      Enable logging of user's activity via VPN in JSON format.

      All connections within `tun` interfaces will be collected via `libpcap` and logged
      as `{"event_type": "purge", "ip_src": "172.25.175.10", "ip_dst": "10.222.0.10", "port_src": 32172, "port_dst": 53, "ip_proto": "udp", "packets": 1, "bytes": 53}`
```

2023-03-02 16:52 UTC, apolovov commented on modules/500-openvpn/openapi/doc-ru-config-values.yaml
> +      в виде `{"event_type": "purge", "ip_src": "172.25.175.10", "ip_dst": "10.222.0.10", "port_src": 32172, "port_dst": 53, "ip_proto": "udp", "packets": 1, "bytes": 53}`.
```suggestion
      Включить логирование пользовательской активности через VPN в JSON-формате.
      
      Все соединения внутри `tun` интерфейсов будут собраны через `libpcap` и записаны в лог
      в виде `{"event_type": "purge", "ip_src": "172.25.175.10", "ip_dst": "10.222.0.10", "port_src": 32172, "port_dst": 53, "ip_proto": "udp", "packets": 1, "bytes": 53}`.
```

2023-03-02 16:53 UTC, apolovov approved these changes

2023-03-02 16:55 UTC, merged