[istio] fix dataplane upgrade
deckhouse/deckhouse pull request #3710
Opened 2023-02-01 06:55 UTC by fl64

## Description
Added check of isiotd operation before controller starts upgrading required resources

## Why do we need it, and what problem does it solve?
Upgraded resources may receive old versions of sidecars because the required istiod is not ready

## What is the expected result?
Resources are not upgraded as long as istiod is out of service

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: istio
type: fix
summary: Added check of isiotd operation before controller starts upgrading required resources
impact_level: default
```

2023-02-06 21:33 UTC, apolovov commented
The dataplane upgrade doc is in wrong place. Move it to examples, please and add add two links to the alert:
* to control-plane upgrade instruction
* to data-plane upgrade instruction

2023-02-06 21:34 UTC, apolovov reviewed
The dataplane upgrade doc is in wrong place. Move it to examples, please and add add two links to the alert:

to control-plane upgrade instruction
to data-plane upgrade instruction

2023-02-06 21:34 UTC, apolovov requested changes
The dataplane upgrade doc is in wrong place. Move it to examples, please and add add two links to the alert:

* to control-plane upgrade instruction
* to data-plane upgrade instruction

2023-02-12 14:20 UTC, z9r5 commented on ee/modules/110-istio/docs/EXAMPLES.md
> +### Auto upgrade istio data-plane
```suggestion
### Auto upgrading istio data-plane
```

2023-02-12 14:21 UTC, z9r5 submitted a review, later dismissed

2023-02-18 01:50 UTC, apolovov commented on ee/modules/110-istio/monitoring/prometheus-rules/dataplane.yaml
> +        Also consider automating the istio data-plane update described in the documentation: https://deckhouse.io/documentation/v1/modules/110-istio/examples.html#upgrading-istio
```suggestion
        Also consider using the automatic istio data-plane update described in the documentation: https://deckhouse.io/documentation/v1/modules/110-istio/examples.html#upgrading-istio
```

2023-02-18 01:51 UTC, apolovov submitted a review, later dismissed

2023-02-18 01:58 UTC, apolovov approved these changes

2023-02-19 05:36 UTC, z9r5 approved these changes

2023-02-19 05:36 UTC, merged