loki module
deckhouse/deckhouse pull request #3735
Opened 2023-02-02 06:52 UTC by trublast

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-02-02 08:25 UTC, kvaps requested changes

2023-02-02 08:25 UTC, kvaps commented on modules/041-linstor/templates/linstor-scheduler-admission/webhook.yaml
> +      - d8-loki
loki can use persistent volumes, please add it to exclusions of linstor-scheduler-admission webhook generator

https://github.com/deckhouse/deckhouse/blob/16d6f2c524e913e88fb356c0253c9dde4a3f9517/tools/linstor_scheduler_webhook/main.go#L32-L37

2023-02-06 11:39 UTC, z9r5 commented on modules/462-loki/docs/README.md
> +[Loki](https://grafana.com/oss/loki/) - module for storing and viewing logs.
```suggestion
[Loki](https://grafana.com/oss/loki/) - module for storing and viewing logs.
```
Does the module allow you to view logs?  Maybe  - "The module for aggregating logs"?

2023-02-06 12:37 UTC, z9r5 commented on modules/462-loki/docs/README_RU.md
> +[Loki](https://grafana.com/oss/loki/) - модуль для хранения и просмотра логов.
```suggestion
Модуль предназначен для организации хранилища логов.

Модуль использует проект [Grafana Loki](https://grafana.com/oss/loki/).

Модуль разворачивает хранилище логов на базе Grafana Loki, при необходимости настраивает модуль log-shipper на использование loki и добавляет в Grafana соответствующий datasource. 
```

2023-02-06 12:42 UTC, z9r5 commented on modules/462-loki/openapi/config-values.yaml
> +      Disk size for log store. PVC size if `effectiveStorageClass` set.
```suggestion
      Disk size for storing logs or the size of the PVC when specifying the [storageClass](#parameters-storageclass) parameters.
```
It seems that the effectiveStorageClass parameter have te be named as storageClass.

2023-02-06 12:42 UTC, z9r5 commented on modules/462-loki/openapi/config-values.yaml
> +      Store logs from d8-* namespaces into loki. [log-shipper](../460-log-shipper) module must be enabled.
```suggestion
      Store logs from `d8-*` namespaces into loki.

      The [log-shipper](../460-log-shipper) module must be enabled.
```

2023-02-06 12:43 UTC, z9r5 commented on modules/462-loki/openapi/config-values.yaml
> +      The same as in the Pods' `spec.tolerations` parameter in Kubernetes;
```suggestion
      The same as in the Pods' `spec.tolerations` parameter in Kubernetes.
```

2023-02-06 12:43 UTC, z9r5 commented on modules/462-loki/openapi/config-values.yaml
> +      If the `vertical-pod-autoscaler` module is disabled, then these values become the default ones.
```suggestion
      Max amounts of CPU and memory resources that the Pod can request when selecting a node.

      If the [vertical-pod-autoscaler](../302-vertical-pod-autoscaler/) module is disabled, then these values become the default ones.
```

2023-02-06 12:44 UTC, z9r5 commented on modules/462-loki/openapi/doc-ru-config-values.yaml
> +      Размер диска для хранения логов. Размер PVC при указании `effectiveStorageClass`
```suggestion
      Размер диска для хранения логов или размер PVC при указании параметра [storageClass](#parameters-storageclass).
```

2023-02-06 12:44 UTC, z9r5 commented on modules/462-loki/openapi/doc-ru-config-values.yaml
> +      Сохранять логи из d8-* неймспейсов в loki. Должен быть включен модуль [log-shipper](../460-log-shipper).
```suggestion
      Сохранять логи из пространства имен `d8-*` в loki.

      Для работы необходим включенный модуль [log-shipper](../460-log-shipper).
```

2023-02-06 12:44 UTC, z9r5 commented on modules/462-loki/openapi/doc-ru-config-values.yaml
> +      Если модуль `vertical-pod-autoscaler` выключен, максимальные значения становятся значениями по умолчанию.
```suggestion
      Если модуль [vertical-pod-autoscaler](../302-vertical-pod-autoscaler/) выключен, то максимальные значения становятся значениями по умолчанию.
```

2023-02-07 07:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2023-02-09 13:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2023-02-09 13:16 UTC, z9r5 commented on modules/462-loki/openapi/config-values.yaml
> +      **CAUTION!** Setting this value to one that differs from the current one (in the existing PVC) will result in Loki volume reprovisioning and data loss.
```suggestion
      The name of the StorageClass to use.

      If omitted, the StorageClass of the existing Loki PVC is used. If there is no PVC yet, either the global [StorageClass](../../deckhouse-configure-global.html#parameters-storageclass) or `global.discovery.defaultStorageClass` is used, and if those are undefined, the emptyDir volume is used to store the data.

      `storageClass: false` — forces the `emptyDir` usage. You will need to delete the old PVC and restart the Pod manually.

      **CAUTION!** Setting this value to one that differs from the current one (in the existing PVC) will result in Loki volume reprovisioning and data loss.
```

2023-02-09 13:16 UTC, z9r5 commented on modules/462-loki/openapi/doc-ru-config-values.yaml
> +
```suggestion
      Если не указано — используется StorageClass существующей PVC Loki, а если PVC пока нет — используется или  [глобальный StorageClass](../../deckhouse-configure-global.html#parameters-storageclass), или `global.discovery.defaultStorageClass`, а если и их нет — данные сохраняются в `emptyDir`.

```

2023-02-09 13:23 UTC, z9r5 submitted a review, later dismissed

2023-02-10 11:30 UTC, z9r5 commented on modules/462-loki/openapi/config-values.yaml
> +      Loki does not have the ability to automatically delete old data when the disk is full.
```suggestion
      Loki cannot automatically delete old data when the disk is full.
```

2023-02-10 11:34 UTC, z9r5 commented on modules/462-loki/openapi/doc-ru-config-values.yaml
> +      Loki не имеет возможности производить удаление старых данных автоматически при заполнении диска.
```suggestion
      Loki не может удалять старые данные автоматически при заполнении диска.
```

2023-02-10 11:35 UTC, z9r5 commented on modules/462-loki/openapi/config-values.yaml
> +      Loki does not have the ability to automatically delete old data when the disk is full.
```suggestion
      Loki cannot automatically delete old data when the disk is full.
```

2023-02-10 12:02 UTC, z9r5 commented on modules/462-loki/openapi/config-values.yaml
> +      `retentionPeriodHours` and `diskSizeGigabytes`.
```suggestion
      **CAUTION!** If the Loki data disk becomes full, the application will stop working. You should choose the necessary balance between the values of `retentionPeriodHours` and `diskSizeGigabytes`.
```

2023-02-10 12:03 UTC, z9r5 commented on modules/462-loki/openapi/doc-ru-config-values.yaml
> +      `retentionPeriodHours` и `diskSizeGigabytes`.
```suggestion
      **ОСТОРОЖНО!**  Если диск с данными Loki переполнится, то приложение перестанет работать. Вам следует выбрать необходимый баланс между значениями параметров `retentionPeriodHours` и `diskSizeGigabytes`.
```

2023-02-10 12:18 UTC, RomanenkoDenys reviewed
LGTM

2023-02-10 12:19 UTC, RomanenkoDenys approved these changes

2023-02-15 14:35 UTC, kirkonru approved these changes

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +      Store logs from `d8-*` namespaces into loki.
```suggestion
      Save logs from the `d8-*` namespaces to loki.
```

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +      The same as in the Pods' `spec.nodeSelector` parameter in Kubernetes.
```suggestion
      The same as the Pods' `spec.nodeSelector` parameter in Kubernetes.
```

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +      The same as in the Pods' `spec.tolerations` parameter in Kubernetes.
```suggestion
      The same as the Pods' `spec.tolerations` parameter in Kubernetes.
```

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +      Max amounts of CPU and memory resources that the Pod can request when selecting a node.
```suggestion
      The max amounts of CPU and memory resources the Pod can request when being scheduled on a node.
```

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +                  Maximum allowed CPU requests.
```suggestion
                  The max amount of CPU requests the VPA can set.
```

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +                  Minimum allowed CPU requests.
```suggestion
                  The min amount of CPU requests the VPA can set.
```

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +                  Maximum allowed memory requests.
```suggestion
                  The max amount of memory requests the VPA can set.
```

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +                  Minimum allowed memory requests.
```suggestion
                  The min amount of memory requests the VPA can set.
```

2023-02-15 14:35 UTC, kirkonru commented on modules/462-loki/openapi/config-values.yaml
> +                  Maximum allowed CPU requests.
I'm not sure if I get this right, but it's still worth a try.

2023-02-15 14:53 UTC, z9r5 approved these changes

2023-02-26 15:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-04-05 07:50 UTC, z9r5 commented on modules/462-loki/docs/README_RU.md
> +Модуль разворачивает хранилище логов на базе Grafana Loki, при необходимости настраивает модуль log-shipper на использование loki и добавляет в Grafana соответствующий datasource.
```suggestion
Модуль разворачивает хранилище логов на базе Grafana Loki, при необходимости настраивает модуль [log-shipper](../460-log-shipper/) на использование loki и добавляет в Grafana соответствующий datasource.
```

2023-04-05 07:50 UTC, z9r5 commented on modules/462-loki/docs/README.md
> +The module deploys log storage based on Grafana Loki, configures the [log-shipper](../460-log-shipper) module to use loki if necessary, and adds the corresponding data source to Grafana.
```suggestion
The module deploys log storage based on Grafana Loki, configures the [log-shipper](../460-log-shipper/) module to use loki if necessary, and adds the corresponding data source to Grafana.
```

2023-04-05 23:27 UTC, nabokihms commented on modules/462-loki/templates/statefulset.yaml
> +      containers:
We can add it in the future.

2023-04-05 23:43 UTC, nabokihms commented on modules/462-loki/templates/statefulset.yaml
> +      containers:
https://github.com/deckhouse/deckhouse/issues/4315
https://github.com/deckhouse/deckhouse/issues/4314

2023-04-05 23:59 UTC, merged