[deckhouse] generate bashible context inside bashible-apiserver
deckhouse/deckhouse pull request #375
Opened 2021-12-12 19:34 UTC by yalosev

## Description
Move context generation into bashible-apiserver

## Why we need it and what problem does it solve?
Bashible context Is too big and can't be handled with kubernetes secret (due to size limitations).
We want to pass only input values to bashible-server and generate a context in memory

## Changelog entries

```changes
module: deckhouse
type: fix
description: Move context generation into bashible-apiserver
note: bashible-apiserver will restart
```

2021-12-14 15:56 UTC, nabokihms requested changes
Overall, it looks nice. 

Managed to find some NITs, though. Would you please check the comments when you have time?

2021-12-14 15:56 UTC, nabokihms commented on modules/040-node-manager/images/bashible-apiserver/pkg/apiserver/apiserver.go
> +func (cs checksumSecretUpdater) OnCheckumUpdate(ngmap map[string][]byte) {
Typo
```suggestion
func (cs checksumSecretUpdater) OnChecksumUpdate(ngmap map[string][]byte) {
```

2021-12-14 15:56 UTC, nabokihms commented on modules/040-node-manager/images/bashible-apiserver/pkg/template/context.go
> +func (c *BashibleContext) parseImageTagsFile() {
nit: file is called `images_tags`.

2021-12-14 18:14 UTC, yalosev commented on modules/020-deckhouse/templates/registry.yaml
> +{{ include "helm_lib_module_labels" (list . (dict "app" "registry")) | indent 2 }}
added

2021-12-14 18:14 UTC, yalosev commented on modules/040-node-manager/images/bashible-apiserver/pkg/template/context.go
> +func (c *BashibleContext) parseImageTagsFile() {
+

2021-12-14 20:43 UTC, yalosev commented on modules/020-deckhouse/templates/rbac-for-us.yaml
> +  name: bashible-apiserver-readregsecret
It doesn't work:
```
    Linter error:
    
        🐒 [#MANIFEST053]
        	Message	- Role with prefix "bashible-apiserver" should be deployed in namespace "d8-cloud-instance-manager"
        	Object	- kind = Role ; name = bashible-apiserver-readregsecret ; namespace = d8-system
        	Value	- d8-system
        
        🐒 [#MANIFEST053]
        	Message	- Role in "templates/bashible-apiserver/rbac-for-us.yaml" should start with "bashible-apiserver" or "node-manager:bashible-apiserver"
        	Object	- kind = Role ; name = d8:bashible-apiserver-readconfig ; namespace = d8-cloud-instance-manager
        	Value	- d8:bashible-apiserver-readconfig
```

2021-12-14 20:57 UTC, nabokihms commented on modules/020-deckhouse/templates/rbac-for-us.yaml
> +  name: bashible-apiserver-readregsecret
You can find the example here https://github.com/deckhouse/deckhouse/blob/41a6fd88f5877f1c66abf8c250bb40b6ff6d541a/modules/040-node-manager/templates/bashible/rbac-for-us.yaml#L43

2021-12-15 10:26 UTC, nabokihms approved these changes
Approved, everything seems ok. @konstantin-axenov, do you want to take a look, or can we merge this?

2021-12-15 10:31 UTC, merged