[openvpn] Setup HA for openvpn module
deckhouse/deckhouse pull request #3820
Opened 2023-02-09 16:21 UTC by Diaderius

Signed-off-by: Konstantin Maltsev <konstantin.maltsev@flant.com>

## Description
There is a configuration of **highAvailability** flag for openvpn module.

## Why do we need it, and what problem does it solve?
There is horizontal scaling of openvpn server for high availability.
It refers to this issue: #1622 

## What is the expected result?
In case of specifying 'false' or non-specified - there would be only 1 replica of server.
In case of specifying 'true' - there would be 2 replicas of server.
Also it controls by global **highAvailability** parameter.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: openvpn
type: feature
summary: configuration HA for openvpn server
```

2023-02-09 16:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-09 20:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-16 06:54 UTC, vitaliy-sn requested changes
For the hostPort inlet, antiaffinity must be added so that more than one openvpn pod cannot be scheduled per node.

2023-02-20 07:32 UTC, vitaliy-sn approved these changes

2023-02-20 07:40 UTC, merged