[candi] Remove early-oom
deckhouse/deckhouse pull request #3821
Opened 2023-02-09 16:41 UTC by Diaderius

Signed-off-by: Konstantin Maltsev <konstantin.maltsev@flant.com>

## Description
Removing early-oom with references.

## Why do we need it, and what problem does it solve?
Due to incorrect work, we must remove it and continue with another evictions.
It refers to this issue: #2874 

## What is the expected result?
Early-oom would be disabled at all.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: early-oom removing
```

2023-02-09 19:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-09 19:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @Diaderius. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-03-07 14:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-07 15:26 UTC, zuzzas commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4355414264 4355414264-1-con-1-23 /sys/deckhouse-oss/install:pr3821 cloud-user@158.160.58.176

2023-03-07 15:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @zuzzas. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-03-09 07:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-09 11:14 UTC, apolovov commented
It is more about [node-manager] imo.

2023-03-09 11:21 UTC, zuzzas commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4372013294 4372013294-1-con-1-23 /sys/deckhouse-oss/install:pr3821 cloud-user@158.160.60.240

2023-03-09 11:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-09 12:14 UTC, RomanenkoDenys commented on candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
> +function dynamic_memory_sizing {
need comment where this function is.

2023-03-09 12:15 UTC, RomanenkoDenys commented on ee/modules/040-node-manager/openapi/config-values.yaml
> -      Set to 'false' to disable early OOM killer in case it behaves incorrectly.
We need module config conversion here

2023-03-09 12:16 UTC, RomanenkoDenys requested changes
nits

2023-03-10 13:39 UTC, zuzzas commented on candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
> +function dynamic_memory_sizing {
Done.

2023-03-10 13:39 UTC, zuzzas commented on ee/modules/040-node-manager/openapi/config-values.yaml
> -      Set to 'false' to disable early OOM killer in case it behaves incorrectly.
Done.

2023-03-10 13:40 UTC, zuzzas commented on candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
> +function dynamic_memory_sizing {
Done.

2023-03-10 18:57 UTC, RomanenkoDenys requested changes

2023-03-10 18:57 UTC, RomanenkoDenys commented on modules/040-node-manager/settings-conversion/conversion.go
> +Copyright 2022 Flant JSC
```suggestion
Copyright 2023 Flant JSC
```

2023-03-10 18:57 UTC, RomanenkoDenys commented on modules/040-node-manager/settings-conversion/conversion_test.go
> +Copyright 2022 Flant JSC
```suggestion
Copyright 2023 Flant JSC
```

2023-03-12 17:48 UTC, yalosev requested changes
Not completed

2023-03-15 12:26 UTC, RomanenkoDenys approved these changes

2023-03-23 11:03 UTC, yalosev approved these changes

2023-03-27 10:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-04-07 08:28 UTC, merged