[candi] Fixes for centos 9 based bundles and force apparmor install in ubuntu
deckhouse/deckhouse pull request #3863
Opened 2023-02-14 16:36 UTC by duckhawk

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-02-15 05:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-15 05:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-15 05:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-15 05:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-15 05:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-15 05:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-15 05:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-15 05:47 UTC, duckhawk commented
/e2e/abort azure;Standard;containerd;1.23 4180935858 4180935858-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-15 05:47 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4180935908 4180935908-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-15 05:47 UTC, duckhawk commented
/e2e/abort vsphere;Standard;containerd;1.23 4180935900 4180935900-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-15 05:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-15 05:48 UTC, duckhawk commented
/e2e/abort openstack;Standard;containerd;1.23 4180935957 4180935957-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-15 05:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-15 05:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-15 05:48 UTC, duckhawk commented
/e2e/abort static;Static;containerd;1.23 4180936054 4180936054-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-15 05:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-15 05:48 UTC, duckhawk commented
/e2e/abort gcp;WithoutNAT;containerd;1.23 4180936921 4180936921-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-15 05:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-15 05:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-15 06:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-15 06:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-15 06:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-15 06:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-15 06:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-15 06:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-15 06:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-15 06:11 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4181091600 4181091600-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-15 06:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-15 08:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-15 08:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-15 08:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-15 08:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-15 08:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-15 08:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-15 08:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-15 09:25 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4182024153 4182024153-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-15 09:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-16 06:04 UTC, RomanenkoDenys commented on candi/bashible/bundles/centos/node-group/031_install_containerd.sh.tpl
> +
Why we remove runc?

2023-02-16 06:06 UTC, RomanenkoDenys commented on modules/007-registrypackages/images/containerd-centos/werf.inc.yaml
> +  - selinux-policy-targeted.x86_64.rpm
this is applicable only for centos 9

2023-02-16 06:07 UTC, RomanenkoDenys requested changes
need some attention

2023-02-22 13:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-22 13:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-22 13:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-22 15:01 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4243403548 4243403548-1-con-1-23 /sys/deckhouse-oss/install:pr3863 centos@18.198.40.237

2023-02-22 15:01 UTC, duckhawk commented
/e2e/abort static;Static;containerd;1.23 4243404079 4243404079-1-con-1-23 /sys/deckhouse-oss/install:pr3863 astra@192.168.199.164

2023-02-22 15:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-22 15:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-22 15:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-22 15:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-22 15:07 UTC, duckhawk commented
/e2e/abort static;Static;containerd;1.23 4244023096 4244023096-1-con-1-23 /sys/deckhouse-oss/install:pr3863

2023-02-22 16:19 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4244022836 4244022836-1-con-1-23 /sys/deckhouse-oss/install:pr3863 centos@18.159.233.187

2023-02-22 16:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-22 16:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-22 16:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-22 16:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-22 16:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-22 16:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-22 16:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-22 16:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-22 19:29 UTC, name212 commented
/e2e/abort static;Static;containerd;1.23 4244795269 4244795269-1-con-1-23 /sys/deckhouse-oss/install:pr3863 astra@192.168.199.56

2023-02-22 19:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-22 19:42 UTC, name212 commented
/e2e/abort static;Static;containerd;1.23 4243404079 4243404079-1-con-1-23 /sys/deckhouse-oss/install:pr3863 astra@192.168.199.164

2023-02-22 19:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-23 11:03 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4244795263 4244795263-1-con-1-23 /sys/deckhouse-oss/install:pr3863 centos@3.64.137.244

2023-02-23 11:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-27 10:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-27 10:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-27 10:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-27 10:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-27 10:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-27 10:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-02-27 10:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-27 11:20 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4281242487 4281242487-1-con-1-23 /sys/deckhouse-oss/install:pr3863 centos@3.76.79.141

2023-02-27 11:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-27 11:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-27 14:25 UTC, duckhawk commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4281886541 4281886541-2-con-1-23 /sys/deckhouse-oss/install:pr3863 centos@3.66.11.87

2023-02-27 14:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-27 14:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-27 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-02-27 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-02-27 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-02-27 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-02-27 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-27 16:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-27 16:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-02-27 16:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @duckhawk. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-02-27 20:24 UTC, name212 commented
/e2e/abort static;Static;containerd;1.23 4281242313 4281242313-1-con-1-23 /sys/deckhouse-oss/install:pr3863 astra@192.168.199.156

2023-02-28 09:34 UTC, RomanenkoDenys approved these changes

2023-02-28 09:46 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 4284078990 4284078990-1-con-1-23 /sys/deckhouse-oss/install:pr3863 cloud-user@158.160.54.47

2023-02-28 09:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-02-28 10:04 UTC, merged