[node-local-dns] New health checking machinery
deckhouse/deckhouse pull request #388
Opened 2021-12-13 07:57 UTC by zuzzas

## Description

Rewrote ready checking. Removed locking. All logic resides in the sidecar container now.

## Why we need it and what problem does it solve?

1. iptables rules gets removed within one second of coredns being shutdown
2. if a coredns process closes a listening socket (typically due to unexpected death of the coredns), `-m socket` will stop matching

## Changelog entries

```changes
module: node-local-dns
type: fix
description: Reworked health checking logic
note: Now Pods shouldn't crash unexpectedly now due to poor implementation of locking/probing.
```

2021-12-28 11:03 UTC, konstantin-axenov requested changes

2022-03-25 06:47 UTC, zuzzas commented on ee/modules/350-node-local-dns/templates/daemonset.yaml
> +        readinessProbe:
First part is done.

I do not believe that it is reasonable to restart the container earlier than one minute in its lifetime. We install no iptables rules and gain nothing by constantly restarting the container.

2022-03-25 06:47 UTC, zuzzas commented on ee/modules/350-node-local-dns/images/iptables-loop/iptables-loop.sh
> +    iptables -w 600 -W 100000 -t raw -D PREROUTING -d ${KUBE_DNS_SVC_IP}/32 -m socket --nowildcard -j NOTRACK
Done.

2022-03-25 06:47 UTC, zuzzas commented on ee/modules/350-node-local-dns/images/iptables-loop/iptables-loop.sh
> +while read -r filename event <&3; do
Done.

2022-03-25 06:47 UTC, zuzzas commented on ee/modules/350-node-local-dns/images/iptables-loop/iptables-loop.sh
> +trap delete_rule INT TERM
Done.

2022-03-25 09:40 UTC, zuzzas commented on ee/modules/350-node-local-dns/images/coredns/readiness.sh
> +trap error ERR
EXIT
```suggestion
trap error ERR EXIT
```

2022-03-25 09:48 UTC, konstantin-axenov approved these changes

2022-03-28 09:14 UTC, zuzzas commented on ee/modules/350-node-local-dns/images/coredns/start.sh
Write `not-ready` here.

2022-03-31 08:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @zuzzas. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2022-04-01 14:16 UTC, nabokihms approved these changes

2022-04-01 14:16 UTC, merged