[azure] docs fixes and improvements
deckhouse/deckhouse pull request #401
Opened 2021-12-13 22:25 UTC by apolovov

## Description
Microsoft Azure documentation fixes and improvements.

## Changelog entries

```changes
module: cloud-provider-aws
type: fix
description: Documentation fixes.
```

2021-12-15 06:45 UTC, z9r5 requested changes
Made minor changes

2021-12-20 07:29 UTC, vitaliy-sn submitted a review, later dismissed

2021-12-20 07:37 UTC, z9r5 approved these changes

2022-01-29 14:00 UTC, nabokihms approved these changes

2022-01-29 14:01 UTC, merged