[log-shipper] Add buffer settings for vector config
deckhouse/deckhouse pull request #4095
Opened 2023-03-14 13:40 UTC by alex123012

## Description

## Why do we need it, and what problem does it solve?

Fix #1352
## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: log-shipper
type: feature
summary: Add buffer settings for vector config
impact_level: default
```

2023-03-15 08:08 UTC, alex123012 commented on modules/460-log-shipper/apis/v1alpha1/cluster_log_destination.go
> +func (t BufferType) ToVectorValue() string {
done

2023-03-15 08:08 UTC, alex123012 commented on modules/460-log-shipper/crds/cluster-log-destination.yaml
> +                        - Splunk
done

2023-03-16 08:37 UTC, nabokihms requested changes

2023-03-16 08:37 UTC, nabokihms commented on modules/460-log-shipper/crds/cluster-log-destination.yaml
> +                        maxSizeBytes:
```suggestion
                        maxSizeBytes:
```
This is not `Bytes` anymore. 
1. Just maxSize?
2. Examples are required and descriptions should be rewritten.

2023-03-16 08:37 UTC, nabokihms commented on modules/460-log-shipper/hooks/testdata/multiple-dest/manifests.yaml
> +      maxSizeBytes: 268435488
Test with a string value is required, e.g. 2Gi, 2Mi.

2023-03-16 23:30 UTC, nabokihms approved these changes

2023-03-16 23:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @nabokihms. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-03-17 06:42 UTC, merged