[monitoring] fixed links deckhouse.io in D8IstioDeprecatedIstioVersio…
deckhouse/deckhouse pull request #4219
Opened 2023-03-24 11:44 UTC by alexey-gavrilov-flant

## Description
fixed links deckhouse.io in D8IstioDeprecatedIstioVersionInstalled

## Why do we need it, and what problem does it solve?
now the link points to the stable branch. which describes the procedure for updating to the current version for earlier release channels

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring
type: fix
summary: fixed links deckhouse.io in D8IstioDeprecatedIstioVersionInstalled
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default
```

2023-04-04 15:43 UTC, apolovov requested changes
```
{{`{{$labels.version}}`}}
```
Results in `{{$labels.version}}` без кавычек, что рендерится в 1.13. Нужны ещё кавычки вокруг всей конструкции.
То же самое здесь:
        severity_level: {{"{{$labels.alert_severity}}"}}
Надо добавить двойные кавычки вокруг.
То есть, вот так:
        severity_level: "{{"{{$labels.alert_severity}}"}}"
и так

2023-04-04 15:43 UTC, apolovov commented on ee/modules/110-istio/monitoring/prometheus-rules/versions.tpl
> +          There is deprecated istio version {{`{{$labels.version}}`}} installed.
```suggestion
          There is deprecated istio version `{{"{{$labels.version}}"}}` installed.
```
Your
```
{{`{{$labels.version}}`}}
```
results in `{{$labels.version}}` without quotations "`" in Prometheus it is being rendered to `1.13`. But we need commas around the version.
Inside "{{}}" i changed "`" to '"' for more transparency.

2023-04-04 17:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-04-04 18:43 UTC, apolovov submitted a review, later dismissed

2023-04-05 07:52 UTC, apolovov approved these changes

2023-04-05 07:53 UTC, merged