[log-shipper] multiline parser `Custom` type with user provided regex
deckhouse/deckhouse pull request #4247
Opened 2023-03-28 15:17 UTC by alex123012

## Description

Add new multiline parser type and give users ability to pass their own regexes for multiline log parsing 
## Why do we need it, and what problem does it solve?

Fix #1342 
## What is the expected result?

New multiline parser `Custom` type with user provided regex parsing
## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: log-shipper
type: feature
summary: multiline parser `Custom` type with user provided regex
impact_level: default
```

2023-03-28 17:05 UTC, nabokihms requested changes

2023-03-28 17:05 UTC, nabokihms commented on modules/460-log-shipper/hooks/internal/vector/transform/multiline.go
> +	}
```suggestion
	switch {
	case parserRegex.NotRegex != nil:
		multilineRegex = *parserRegex.NotRegex
	case parserRegex.Regex != nil:
		multilineRegex = *parserRegex.Regex 
    default: 
        return fmt.Errorf("regex or notRegex should be provided")
	}
```

2023-03-28 17:06 UTC, nabokihms commented on modules/460-log-shipper/crds/doc-ru-cluster-logging-config.yaml
> +                              description: регулярное выражение, которое считает мэтчем строки, попавшие в него
And all other dots. Also the sentence should start with a capital letter.

2023-03-29 07:24 UTC, alex123012 commented on modules/460-log-shipper/hooks/internal/vector/transform/multiline.go
> +	}
I think, that we should check, that only one of regex or notRegex is provided for parser:
https://github.com/deckhouse/deckhouse/pull/4247/files#diff-f96ecfc87fb685b19794447432b09a05bb4909d50d52192e24eb75d915701910R61

2023-03-29 07:33 UTC, nabokihms submitted a review, later dismissed

2023-03-29 08:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @alex123012. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-29 08:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @alex123012. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-03-29 10:07 UTC, merged