[virtualization] Minor fixes
deckhouse/deckhouse pull request #4368
Opened 2023-04-11 14:04 UTC by kvaps

Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-04-12 16:38 UTC, apolovov requested changes
Add a test case pls.

2023-05-19 12:04 UTC, z9r5 commented
@kvaps rebase please

2023-05-19 16:22 UTC, apolovov approved these changes

2023-05-19 16:22 UTC, merged

2023-05-19 16:22 UTC, deckhouse-BOaTswain commented
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/5026264633) for details.