[cloud-provider-aws] Change default etcd disk size and type
deckhouse/deckhouse pull request #4560
Opened 2023-05-04 06:43 UTC by vitaliy-sn

## Description

Change default etcd disk type from gp2 to gp3 and  disk size from 150GB to 20GB.

## Why do we need it, and what problem does it solve?

This is necessary to reduce costs.

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-aws
type: chore
summary: Change default etcd disk type from gp2 to gp3 and  disk size from 150GB to 20GB.
```

2023-05-04 07:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-05-05 09:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-05-08 04:10 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4892096448 4892096448-1-con-1-23 /sys/deckhouse-oss/install:pr4560 centos@3.76.159.125

2023-05-08 04:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-05-08 04:10 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.23 4880082803 4880082803-1-con-1-23 /sys/deckhouse-oss/install:pr4560 centos@18.194.70.132

2023-05-08 04:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-05-11 12:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-05-11 13:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @yalosev. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-05-11 13:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-05-11 13:33 UTC, yalosev requested changes
@vitaliy-sn I think you have to rebase. Because e2e test fails with:
```
	Cloud provider message - InvalidParameterValue: User data is limited to 16384 bytes
│ 	status code: 400, request id: f628df0b-6695-470a-aec3-111e5dcbd22b
```

2023-05-12 12:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-05-15 07:38 UTC, yalosev approved these changes

2023-05-18 09:44 UTC, nabokihms approved these changes

2023-05-18 09:45 UTC, merged