[control-plane-manager] default audit policy
deckhouse/deckhouse pull request #467
Opened 2021-12-21 11:02 UTC by 31337Ghost

## Description
Add default audit policy. Collect logs about actions of service accounts from system namespaces (kube-system, d8-*) and about all actions taken on the resources from these namespaces.

## Why we need it and what problem does it solve?
Closes https://github.com/deckhouse/deckhouse/issues/337

## Changelog entries

```changes
module: control-plane-manager
type: feature
description: |
  Add default audit-policy.
note: |
  Due to new default audit-policy api-server component will be restarted.
```

2022-01-11 10:13 UTC, RomanenkoDenys requested changes

2022-01-11 10:13 UTC, RomanenkoDenys commented on modules/040-control-plane-manager/docs/FAQ.md
> +crictl stopp $(crictl pods --name=kube-apiserver -q)
```suggestion
crictl stop $(crictl pods --name=kube-apiserver -q)
```

2022-01-12 17:15 UTC, apolovov requested changes
There is a pile of minor fixes and doc modification proposals.

2022-01-12 17:15 UTC, apolovov commented on modules/040-control-plane-manager/docs/FAQ_RU.md
>  На данный момент используются фиксированные параметры ротации логов:
Это в конец параграфа.

2022-01-12 17:15 UTC, apolovov commented on modules/040-control-plane-manager/openapi/config-values.yaml
> +      defaultAuditPolicyEnabled:
default -> basic or system.

2022-01-12 17:15 UTC, apolovov commented on modules/040-control-plane-manager/docs/README_RU.md
> +В кластере с Deckhouse всегда присутствует политика для логирования событий, связанных с операциями создания, удаления и изменения:
Тут должно быть то же самое, что и в FAQ.
* что такое аудит
* результат аудита -- лог-файлик
* в декхаусе по умолчанию включен...
* кастомные правила включить — см faq

2022-01-12 23:01 UTC, apolovov commented on modules/040-control-plane-manager/hooks/audit_policy_generated.go
> +// Code generated by "audit_policy.go" DO NOT EDIT.
I would also rename the file to something like audit_policy_basic_metadata_generated.go

2022-01-13 13:36 UTC, apolovov commented on modules/040-control-plane-manager/docs/FAQ_RU.md
> +Если вам требуется вести учёт операций в своих Namespace или отдебажить неожиданное поведение — для всего этого в Kubernetes предусмотрен [Auditing](https://kubernetes.io/docs/tasks/debug-application
В FAQ оставить только "как настроить кастомную политику аудита"

2022-01-13 13:40 UTC, apolovov commented on modules/040-control-plane-manager/hooks/audit_policy.go
> +
```suggestion
```

2022-01-17 09:26 UTC, 31337Ghost commented on tools/audit_policy/main.go
> +	for i := 0; i < 3; i++ { // ../../
That code do not remove `../../` from the end of path, but returns directory path two levels upper.

2022-01-17 09:31 UTC, 31337Ghost commented on tools/audit_policy/main.go
> +			r := regexp.MustCompile(`apiVersion: v1
Yes, it's true. The strict way to retrieve all Service Account names is to compile all templates from all modules and parse them as Kubernetes resources. Regex is used here to make retrieval fast. Later, when we abandon Helm — we will have another great, easy way to refactor that.

2022-01-17 09:33 UTC, 31337Ghost commented on modules/040-control-plane-manager/openapi/config-values.yaml
> +      defaultAuditPolicyEnabled:
✅ `defaultAuditPolicyEnabled` became `basicAuditPolicyEnabled`

2022-01-17 09:51 UTC, 31337Ghost commented on modules/040-control-plane-manager/hooks/audit_policy_generated.go
> +// Code generated by "audit_policy.go" DO NOT EDIT.
I've put the full path to generator script in that comment:
```go
// Code generated by "tools/audit_policy.go" DO NOT EDIT.
```

Good point to make generated file name more suitable to it purpose. But `metadata` keyword is too broad here, so I used **targets** keyword here `audit_policy_basic_targets_generated.go`.

It should be easy to find a way to regenerate that file, by opening `tools/audit_policy.go` where you will immediately see the button: 
<img width="447" alt="Screenshot 2022-01-17 at 12 49 19" src="https://user-images.githubusercontent.com/6999035/149746984-38b9e1d5-e0fb-4e87-ae6a-19b7cdcc7c8a.png">

2022-01-17 09:52 UTC, 31337Ghost commented on modules/040-control-plane-manager/hooks/audit_policy.go
> +	if input.Values.Get("controlPlaneManager.apiserver.defaultAuditPolicyEnabled").Bool() {
Thank you ☺️

2022-01-17 09:52 UTC, 31337Ghost commented on modules/040-control-plane-manager/hooks/audit_policy.go
> +	var policy audit.Policy
Thank you 👍

2022-01-17 11:12 UTC, 31337Ghost commented on modules/040-control-plane-manager/docs/README.md
> +- committed with resources in the "system" Namespace `kube-system, d8- *`.
✅

2022-01-17 11:12 UTC, 31337Ghost commented on modules/040-control-plane-manager/docs/README_RU.md
> +- совершаемых от имён сервисных аккаунтов из системных Namespace `kube-system, d8-*`;
✅

2022-01-17 11:12 UTC, 31337Ghost commented on modules/040-control-plane-manager/docs/README_RU.md
> +- совершаемых с ресурсами в системных Namespace `kube-system, d8-*`.
✅

2022-01-17 11:13 UTC, 31337Ghost commented on modules/040-control-plane-manager/docs/README.md
> +- committed from the names of ServiceAccounts from the "system" Namespace `kube-system, d8- *`;
✅

2022-01-17 11:58 UTC, 31337Ghost commented on modules/040-control-plane-manager/docs/FAQ_RU.md
>  На данный момент используются фиксированные параметры ротации логов:
✅

2022-01-17 12:05 UTC, 31337Ghost commented on modules/040-control-plane-manager/docs/FAQ.md
> +## How do I add audit policies?
✅
```markdown
## How do I configure additional audit policies?
```

2022-01-17 14:28 UTC, 31337Ghost commented on modules/040-control-plane-manager/docs/README_RU.md
> +В кластере с Deckhouse всегда присутствует политика для логирования событий, связанных с операциями создания, удаления и изменения:
✅

2022-01-17 14:28 UTC, 31337Ghost commented on modules/040-control-plane-manager/docs/FAQ_RU.md
> +Если вам требуется вести учёт операций в своих Namespace или отдебажить неожиданное поведение — для всего этого в Kubernetes предусмотрен [Auditing](https://kubernetes.io/docs/tasks/debug-application
✅

2022-01-17 19:41 UTC, apolovov approved these changes
👍

2022-01-18 09:29 UTC, apolovov approved these changes

2022-01-18 10:47 UTC, merged