[node-manager] Add deckhouse release requirements about docker presence (#4807)
deckhouse/deckhouse pull request #4816
Opened 2023-05-31 14:09 UTC by aleksey-su

## Description
Add deckhouse release requirements about docker presence

## Why do we need it, and what problem does it solve?
Issues #4807 

## Why do we need it in the patch release (if we do)?
In release-1.47 we want to remove use of docker CRI. So, in release 1.46 we need release requirement function, which prevents update from 1.46 to 1.47 in case of docker nodes presence.

## What is the expected result?
Checking for the presence of containerd on all nodes

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: Add deckhouse release requirements about docker presence.
impact: It will be impossible to update Deckhouse until docker is replaced with containerd.
impact_level: default
```

2023-06-05 11:58 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/99723890-5e58-4eee-a228-97839038f32e)

2023-06-05 15:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-06-05 16:27 UTC, name212 approved these changes

2023-06-05 18:11 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes.go
> +// Copyright 2022 Flant JSC
```suggestion
// Copyright 2023 Flant JSC
```

2023-06-05 18:12 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes.go
> +	hasNodesOtherThanContainerD = "nodeManager:hasNodesOtherThanContainerD"
```suggestion
	hasNodesOtherThanContainerd = "nodeManager:hasNodesOtherThanContainerd"
```

2023-06-05 18:14 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes.go
> +
Please add // TODO about removing this hook after 1.47 release

2023-06-05 18:14 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes.go
> +			FilterFunc: applyNodesContainerVersionFilter,
```suggestion
			FilterFunc: applyNodesCRIVersionFilter,
```

2023-06-05 18:16 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes.go
> +	snap := input.Snapshots["check_containerd_nodes"]
check_containerd_nodes used in two places, consider use const for it.

2023-06-05 18:17 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +// Copyright 2022 Flant JSC
```suggestion
// Copyright 2023 Flant JSC
```

2023-06-05 18:17 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +	nodeContainerD = `
```suggestion
	nodeContainerd = `
```

2023-06-05 18:19 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +		It("Should have a container engine type check true", func() {
```suggestion
		It("All nodes use only containerd CRI", func() {
```

2023-06-05 18:22 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +		It("Should have no a container engine type check", func() {
```suggestion
		It("All nodes use containerd CRI", func() {
```

2023-06-05 18:22 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +	Context("One node with containerD", func() {
```suggestion
	Context("One node with containerd CRI", func() {
```

2023-06-05 18:28 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +		It("Should have a container engine type check true", func() {
same

2023-06-05 18:28 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +		It("Should have a container engine type check false", func() {
same

2023-06-05 18:28 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +		It("Should have a container engine type check true", func() {
same

2023-06-05 18:28 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +		It("Should have a container engine type check true", func() {
same

2023-06-05 18:28 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +		It("Should have a container engine type check true", func() {
same

2023-06-05 18:29 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_containerd_nodes_test.go
> +		It("Should have a container engine type check true", func() {
same

2023-06-05 18:29 UTC, RomanenkoDenys commented on modules/040-node-manager/requirements/check.go
> +	hasNodesOtherThanContainerDKey = "nodeManager:hasNodesOtherThanContainerD"
```suggestion
	hasNodesOtherThanContainerDKey = "nodeManager:hasNodesOtherThanContainerd"
```

2023-06-05 18:29 UTC, RomanenkoDenys commented on modules/040-node-manager/requirements/check.go
> +	checkContainerDRequirementFunc := func(requirementValue string, getter requirements.ValueGetter) (bool, error) {
```suggestion
	checkContainerdRequirementFunc := func(requirementValue string, getter requirements.ValueGetter) (bool, error) {
```

2023-06-05 18:30 UTC, RomanenkoDenys commented on modules/040-node-manager/requirements/check.go
> +		hasNodesOtherThanContainerD, exists := getter.Get(hasNodesOtherThanContainerDKey)
```suggestion
		hasNodesOtherThanContainerD, exists := getter.Get(hasNodesOtherThanContainerdKey)
```

2023-06-05 18:34 UTC, RomanenkoDenys commented on modules/040-node-manager/requirements/check_test.go
> +	t.Run("containerD requirement successfully", func(t *testing.T) {
```suggestion
	t.Run("containerd requirement runs successfully", func(t *testing.T) {
```

2023-06-05 18:35 UTC, RomanenkoDenys commented on modules/040-node-manager/requirements/check_test.go
> +	t.Run("containerD requirement fail", func(t *testing.T) {
```suggestion
	t.Run("containerd requirement fails", func(t *testing.T) {
```

2023-06-05 18:35 UTC, RomanenkoDenys commented on modules/040-node-manager/requirements/check_test.go
> +		requirements.SaveValue(hasNodesOtherThanContainerDKey, true)
```suggestion
		requirements.SaveValue(hasNodesOtherThanContainerdKey, true)
```

2023-06-05 18:35 UTC, RomanenkoDenys commented on modules/040-node-manager/requirements/check_test.go
> +		ok, err := requirements.CheckRequirement(containerDRequirementsKey, "true")
```suggestion
		ok, err := requirements.CheckRequirement(containerdRequirementsKey, "true")
```

2023-06-05 18:36 UTC, RomanenkoDenys requested changes
I think we should rename hook to something line check_nodes_cri

2023-06-06 07:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-06-06 08:44 UTC, name212 submitted a review, later dismissed

2023-06-06 08:51 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/check_nodes_cri_test.go
> +	Context("Node with containerD and docker and unknownVersion and node without status.nodeInfo.containerRuntimeVersion set", func() {
```suggestion
	Context("Node with containerd and docker and unknownVersion and node without status.nodeInfo.containerRuntimeVersion set", func() {
```

2023-06-06 08:52 UTC, RomanenkoDenys requested changes
lgtm

2023-06-06 09:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-06-06 10:35 UTC, RomanenkoDenys approved these changes

2023-06-06 10:36 UTC, name212 approved these changes

2023-06-06 10:41 UTC, merged

2023-06-06 10:42 UTC, deckhouse-BOaTswain commented
Cherry pick PR [4864](https://github.com/deckhouse/deckhouse/pull/4864) to the branch [release-1.46](https://github.com/deckhouse/deckhouse/tree/release-1.46) successful!