[cert-manager] Added max concurrent challenges parameter
deckhouse/deckhouse pull request #4821
Opened 2023-05-31 18:37 UTC by EvgeniiAl

## Description

Add max concurrent challenges parameter for cert-manager-controller

## Why do we need it, and what problem does it solve?
The simultaneous update of a large number of certificates with HTTP challenges can generate a high load on ingress controllers

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cert-manager
type: feature
summary: Added max concurrent challenges parameter for cert-manager-controller
impact: restart of cert-manager deployment
impact_level: default
```

2023-06-26 08:32 UTC, nabokihms approved these changes

2023-06-26 08:33 UTC, yalosev approved these changes

2023-06-26 08:33 UTC, nabokihms requested changes
Sorry for the long delay, a couple of suggestions.

2023-06-26 08:33 UTC, nabokihms commented on modules/101-cert-manager/openapi/config-values.yaml
> +    type: int
```suggestion
    type: number
```

2023-07-13 17:14 UTC, EvgeniiAl commented on modules/101-cert-manager/openapi/config-values.yaml
> +    x-examples: [25]
I've change the type to `integer` with the format `int32` and add the minimum parameter, because a pattern is supported for string type only afaik

2023-07-21 14:55 UTC, nabokihms approved these changes

2023-07-21 14:55 UTC, merged