[deckhouse-controller] add vpa debug logs
deckhouse/deckhouse pull request #4848
Opened 2023-06-04 20:36 UTC by AleksZimin

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-06-08 15:41 UTC, nabokihms requested changes
@AleksZimin it is good that you added VPA logs. Yet, in addition, we needed logs of a cluster autoscaler from the d8-cloud-instance-manager namespace.

2023-06-08 23:58 UTC, AleksZimin commented
> @AleksZimin it is good that you added VPA logs. Yet, in addition, we needed logs of a cluster autoscaler from the d8-cloud-instance-manager namespace.

Oh, sorry about that. I have added cluster autoscaler logs. Should I delete the VPA logs?

2023-06-15 16:56 UTC, yalosev approved these changes

2023-06-15 17:12 UTC, z9r5 approved these changes

2023-06-15 17:13 UTC, z9r5 commented
`impact_level` changed to `default`.

2023-06-16 06:16 UTC, nabokihms approved these changes

2023-06-16 06:16 UTC, merged