[linstor] Update drbd to 9.2.4
deckhouse/deckhouse pull request #4882
Opened 2023-06-07 13:45 UTC by duckhawk

## Description

Update drbd to 9.2.4. Added disruptive step for updating.

Co-developed-by: Andrei Kvapil (@kvaps)

## Why do we need it, and what problem does it solve?

This is patch release, that fixes multiple errors in drbd. Also, it adds check of drbd version on nodes, and step with node reboot, if it necessary.

## What is the expected result?

Fix multiple issues in drbd. Actual drbd version in clusters.
- https://github.com/LINBIT/linstor-server/issues/329
- https://github.com/LINBIT/linstor-server/issues/321
- Resolves possible deadlocks due to network failure

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: linstor
type: chore
summary: Update drbd to 9.2.4
impact: | 
  This update requires disruption, so all nodes with linstor will be restarted.
  * If NodeGroup spec.disruptions.approvalMode is set to Manual, you will recieve alert NodeRequiresDisruptionApprovalForUpdate.
  * If NodeGroup spec.disruptions.approvalMode is set to Automatic, nodes will be drained and restartred one by one.
impact_level: high
```

2023-06-07 18:00 UTC, kvaps requested changes

2023-06-07 18:00 UTC, kvaps commented on modules/041-linstor/images/drbd-driver-loader/Dockerfile
This change will remove SELinux support from our setups. The upstream introduced new environment variable to control this behavior. Please take a look https://github.com/LINBIT/drbd/commit/8ecbec8e4bc533e0733e5b595b8f9b671c11bd04

2023-06-08 05:14 UTC, duckhawk commented on modules/041-linstor/images/drbd-driver-loader/Dockerfile
Thanks, noticed this too late

2023-06-08 08:27 UTC, kvaps submitted a review, later dismissed
lgtm

2023-06-14 17:49 UTC, kvaps reviewed
Since it include changes from #4788 could you add

```
Co-authored-by: Andrei Kvapil <kvapss@gmail.com>
```

to the commit message please

2023-06-14 18:03 UTC, apolovov requested changes

2023-06-14 18:03 UTC, apolovov commented on modules/041-linstor/hack/update.sh
> +if [ -n "$drbd_alert_version" ]; then
What alert? The pr don't provide any alerts.

2023-06-14 18:06 UTC, kvaps commented on modules/041-linstor/images/spaas/Dockerfile
> +ARG DRBD_VERSION=9.2.4
```suggestion
```

2023-06-14 18:07 UTC, kvaps commented on modules/041-linstor/images/spaas/Dockerfile
> +RUN echo ${DRBD_VERSION} > /drbd_version
```suggestion
```

2023-06-15 16:03 UTC, apolovov submitted a review, later dismissed

2023-06-16 09:40 UTC, nabokihms approved these changes

2023-06-16 10:48 UTC, kvaps commented on modules/041-linstor/images/drbd-reactor/Dockerfile
drbd-utils v9.24.0 just been released, let's update to stable version
https://lists.linbit.com/pipermail/drbd-announce/2023-June/000663.html?utm_content=253159763&utm_medium=social&utm_source=twitter&hss_channel=tw-56531410

2023-06-16 10:48 UTC, kvaps commented on modules/041-linstor/images/linstor-server/Dockerfile
drbd-utils v9.24.0 just been released, let's update to stable version
https://lists.linbit.com/pipermail/drbd-announce/2023-June/000663.html?utm_content=253159763&utm_medium=social&utm_source=twitter&hss_channel=tw-56531410

2023-06-21 11:48 UTC, konstantin-axenov approved these changes

2023-06-21 11:50 UTC, merged