[cloud-provider-azure] fixed the behavior of the acceleratedNetworking variable
deckhouse/deckhouse pull request #5000
Opened 2023-06-22 16:05 UTC by xeonic-ant

## Description

Fixed helm to render correctly booleans.

## Why do we need it, and what problem does it solve?

Closes https://github.com/deckhouse/deckhouse/issues/4988

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-azure
type: fix
summary:  fixed the behavior of the acceleratedNetworking variable 
impact_level: default
```

2023-06-26 17:05 UTC, alexey-gavrilov-flant commented
https://github.com/deckhouse/deckhouse/issues/4988

2023-06-26 17:10 UTC, alexey-gavrilov-flant commented
https://github.com/deckhouse/deckhouse/pull/5042

2023-06-27 07:34 UTC, alexey-gavrilov-flant commented on modules/040-node-manager/template_tests/module_test.go
> +				//checksum := mcdt.Field("spec.properties.networkProfile.acceleratedNetworking").String()
You have to delete the line with the comment

2023-06-27 16:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-06-28 08:43 UTC, RomanenkoDenys commented on modules/040-node-manager/template_tests/module_test.go
> +			It("spec.properties.networkProfile.acceleratedNetworking default true", func() {
```suggestion
			It("spec.properties.networkProfile.acceleratedNetworking is not ser (default true)", func() {
```

2023-06-28 08:44 UTC, RomanenkoDenys commented on modules/040-node-manager/template_tests/module_test.go
> +			It("spec.properties.networkProfile.acceleratedNetworking true", func() {
```suggestion
			It("spec.properties.networkProfile.acceleratedNetworking is set to true", func() {
```

2023-06-28 08:44 UTC, RomanenkoDenys commented on modules/040-node-manager/template_tests/module_test.go
> +			It("spec.properties.networkProfile.acceleratedNetworking false", func() {
```suggestion
			It("spec.properties.networkProfile.acceleratedNetworking is set to false", func() {
```

2023-06-28 09:04 UTC, RomanenkoDenys requested changes
some nits

2023-06-30 06:58 UTC, miklezzzz commented
@xeonic-ant Hi, review suggestions please. For now, the PR isn't getting into 1.47.x.

2023-07-03 07:43 UTC, z9r5 commented
Please fill the changes section accroding to changes.

2023-07-03 20:34 UTC, merged