[prometheus] add hook for setting lookbackDelta option
deckhouse/deckhouse pull request #5006
Opened 2023-06-23 11:50 UTC by miklezzzz

## Description
WIP

## Why do we need it, and what problem does it solve?
Close #4951 

## Why do we need it in the patch release (if we do)?

## What is the expected result?
WIP

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: feature
summary: Set lookbackDelta Prometheus parameter value to be twice bigger than the scrapeInterval value
impact: Prometheus main restart
impact_level: low
```

2023-06-23 12:16 UTC, nabokihms requested changes

2023-06-23 12:25 UTC, miklezzzz commented on modules/300-prometheus/hooks/set_lookback_delta.go
> +		lookBackDelta = scrapeInterval * 2
and what if scrapeInterval is set to `5m30s`?

2023-06-23 12:59 UTC, miklezzzz commented on modules/300-prometheus/hooks/set_lookback_delta.go
> +		lookBackDelta = scrapeInterval * 2
and what do you think of idea to have some reasonable minimum lookbackDelta value imposed? while it's possible to set scrapeInterval to something like 10ms, I assumed that having 20ms set for lookbackDelta wouldn't be OK.

2023-06-23 13:51 UTC, nabokihms commented on modules/300-prometheus/hooks/set_lookback_delta.go
> +		lookBackDelta = scrapeInterval * 2
Didn't get the problem with 5m30s. Is this not valid? X2 interval will be 11 minutes.

About defaulting, I asked a question below. Is there a problem with low values? AFAIK it is totally ok, and this is the approach VictoriaMetrics uses.

2023-06-26 06:58 UTC, miklezzzz commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 5356917480 5356917480-1-con-1-23 /sys/deckhouse-oss/install:pr5006 cloud-user@84.201.159.16

2023-06-26 08:38 UTC, miklezzzz commented on modules/300-prometheus/hooks/set_lookback_delta.go
> +		lookBackDelta = scrapeInterval * 2
@nabokihms I've updated the PR and its description, ready for review.

2023-06-26 09:46 UTC, nabokihms approved these changes

2023-06-26 11:44 UTC, yalosev approved these changes

2023-06-26 15:07 UTC, merged

2023-06-27 08:50 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 5356917480 5356917480-1-con-1-23 /sys/deckhouse-oss/install:pr5006 cloud-user@84.201.159.16

2023-06-27 08:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->