[bashible] Move kubernetes api proxy configuration step
deckhouse/deckhouse pull request #5047
Opened 2023-06-27 11:02 UTC by artbin

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-06-28 11:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-06-28 11:42 UTC, artbin commented
Manual testing
==============

Master node command:
```bash
kubectl create -f - <<EOF
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: manual-approval-worker
spec:
  nodeType: CloudEphemeral
  cloudInstances:
    minPerZone: 1
    maxPerZone: 1
    classReference:
      kind: OpenStackInstanceClass
      name: worker
  disruptions:
    approvalMode: Manual
EOF
```
Output:
```
nodegroup.deckhouse.io/manual-approval-worker created
```

Worker node command:
```bash
ls -1 /var/lib/bashible/bundle_steps/ > steps1.txt
```

Master node command:
```bash
kubectl -n d8-system set image deployment/deckhouse deckhouse=dev-registry.deckhouse.io/sys/deckhouse-oss:pr5047
```
Output:
```
deployment.apps/deckhouse image updated
```

Worker node command:
```bash
journalctl -fu bashible
```
Output:
```
Jun 28 09:42:44 dev-manual-approval-worker-b5a33d15-79b5c-d5488 systemd[1]: Started Bashible service.
Jun 28 09:42:50 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:42:50 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/000_discover_node_ip.sh
Jun 28 09:42:50 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/001_configure_kubernetes_api_proxy.sh
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/001_setting_approval_annotations.sh
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9156]: Setting update.node.deckhouse.io/waiting-for-approval= annotation on our Node...
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9193]: node/dev-manual-approval-worker-b5a33d15-79b5c-d5488 annotated
Jun 28 09:42:51 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9156]: Waiting for update.node.deckhouse.io/approved= annotation on our Node...
Jun 28 09:42:52 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9154]: Steps are waiting for approval to start.
Jun 28 09:42:52 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9154]: Note: Deckhouse is performing a rolling update. If you want to force an update, use the following command.
Jun 28 09:42:52 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9154]: kubectl annotate node dev-manual-approval-worker-b5a33d15-79b5c-d5488 update.node.deckhouse.io/approved=
Jun 28 09:42:52 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9154]: Retry in 10sec...
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/002_add_system_proxy.sh
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/002_install_ca_certificates.sh
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9311]: bb-apt [INFO] Updating apt cache
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9347]: Hit:1 http://nova.clouds.archive.ubuntu.com/ubuntu jammy InRelease
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9347]: Hit:2 http://nova.clouds.archive.ubuntu.com/ubuntu jammy-updates InRelease
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9347]: Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu jammy-backports InRelease
Jun 28 09:43:02 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9347]: Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Jun 28 09:43:04 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9347]: Reading package lists...
Jun 28 09:43:04 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9311]: bb-apt [INFO] Installing packages 'ca-certificates'
Jun 28 09:43:04 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9311]: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Jun 28 09:43:04 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9607]: Reading package lists...
Jun 28 09:43:04 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9607]: Building dependency tree...
Jun 28 09:43:04 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9607]: Reading state information...
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9607]: ca-certificates is already the newest version (20230311ubuntu0.22.04.1).
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9607]: 0 upgraded, 0 newly installed, 0 to remove and 181 not upgraded.
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[9664]: ca-certificates was already set on hold.
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/002_migrate_containerd_to_cgroupfs.sh
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/003_add_deckhouse_path.sh
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/003_disable_rp_filter.sh
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/003_disable_swap.sh
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/003_install_mandatory_packages.sh
Jun 28 09:43:05 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:06 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:06 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/003_install_mandatory_packages_for_cloud_nodes.sh
Jun 28 09:43:06 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:06 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:06 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === Step: /var/lib/bashible/bundle_steps/003_set_short_hostname.sh
Jun 28 09:43:06 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:06 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: ===
Jun 28 09:43:06 dev-manual-approval-worker-b5a33d15-79b5c-d5488 bashible.sh[8974]: === St [...]

2023-07-05 08:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-07-05 10:09 UTC, RomanenkoDenys commented on candi/bashible/common-steps/node-group/001_setting_approval_annotations.sh.tpl
i think name should be waiting_approval_annotations.sh.tpl

2023-07-05 10:09 UTC, RomanenkoDenys requested changes
some nits

2023-07-05 14:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-07-06 09:17 UTC, RomanenkoDenys approved these changes
LGTM

2023-07-06 10:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-07-06 10:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-07-06 10:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-07-06 10:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-07-06 10:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-07-06 10:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-07-06 11:59 UTC, artbin commented
/e2e/abort azure;Standard;containerd;1.23 5474493159 5474493159-1-con-1-23 /sys/deckhouse-oss/install:pr5047 azureuser@20.86.148.178

2023-07-06 12:03 UTC, artbin commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 5474493339 5474493339-1-con-1-23 /sys/deckhouse-oss/install:pr5047 cloud-user@158.160.107.198

2023-07-06 12:16 UTC, artbin commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.23 5474493339 5474493339-1-con-1-23 /sys/deckhouse-oss/install:pr5047 cloud-user@158.160.107.198

2023-07-06 12:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-07-06 12:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-07-06 13:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-07-06 13:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-07-06 13:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-07-06 13:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-07-06 17:32 UTC, RomanenkoDenys commented
/e2e/abort azure;Standard;containerd;1.23 5475969716 5475969716-1-con-1-23 /sys/deckhouse-oss/install:pr5047 azureuser@68.219.177.222

2023-07-06 18:08 UTC, RomanenkoDenys commented
/e2e/abort azure;Standard;containerd;1.23 5475969716 5475969716-1-con-1-23 /sys/deckhouse-oss/install:pr5047 azureuser@68.219.177.222

2023-07-06 18:59 UTC, name212 commented
/e2e/abort azure;Standard;containerd;1.23 5475969716 5475969716-1-con-1-23 /sys/deckhouse-oss/install:pr5047 azureuser@68.219.177.222

2023-07-06 18:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-07-07 16:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-07-10 08:30 UTC, RomanenkoDenys approved these changes
LGTM

2023-07-10 08:33 UTC, merged