[extended-monitoring] Add cert-exporter alerts
deckhouse/deckhouse pull request #512
Opened 2021-12-27 21:11 UTC by kvaps

## Description

This PR adds cert-exporter alerts to the extended-monitoring module

## Why do we need it, and what problem does it solve?

follows-up #479
fixes #365

## Changelog entries

```changes
module: extended-monitoring
type: feature
description: Add cert-exporter alerts
note: |
  Added alerts to track certificates expiration and cert-exporter health
```

2021-12-29 10:25 UTC, kvaps commented
PR rebased

2021-12-29 16:00 UTC, nabokihms requested changes

2021-12-29 16:00 UTC, nabokihms commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +- name: kubernetes.certmanager.certificate
I would like to recommend adding the `group by` rules for the following alerts (plk_grouped_by__main annotation). You can take a look for samples in the `d8.extended-monitoring.cert-exporter.availability` alerts group from your PR.

2021-12-29 16:11 UTC, kvaps commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +        cert_exporter_secret_not_after{job="cert-exporter", secretkey!="ca.crt"} - time() < 0
Those ca.crt are injected into every cert by ca-injecter (part of cert-manager).
The same CA certificates are usually persist as normal tls.crt/tls.key in separate secrets.

2021-12-29 16:13 UTC, kvaps commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +        cert_exporter_secret_not_after{job="cert-exporter", secretkey!="ca.crt"} - time() < 1209600
No objections. Do you have reliable example? This one is taken from cert-manager module:

https://github.com/deckhouse/deckhouse/blob/9a778f491c4c340b0c774bd8fb5274ff8d34549b/modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml#L1-L13

Guess we can update it too

2021-12-29 16:24 UTC, kvaps commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +      severity: warning
Let's create an issue to update it everywhere in other modules as well.

2021-12-29 17:25 UTC, kvaps commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +        cert_exporter_secret_not_after{job="cert-exporter", secretkey!="ca.crt"} - time() < 1209600
done https://github.com/deckhouse/deckhouse/issues/534

2021-12-29 17:28 UTC, kvaps commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +      severity: warning
done https://github.com/deckhouse/deckhouse/issues/534

2021-12-29 17:51 UTC, nabokihms commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +        cert_exporter_secret_not_after{job="cert-exporter", secretkey!="ca.crt"} - time() < 0
Okay, that makes sense.

2021-12-29 17:51 UTC, nabokihms commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +        cert_exporter_secret_not_after{job="cert-exporter", secretkey!="ca.crt"} - time() < 1209600
For extended monitoring, we have special threshold annotations:
https://deckhouse.io/en/documentation/v1/modules/340-extended-monitoring/configuration.html#standard-annotations-and-supported-kubernetes-objects

I thought about adding one more annotation and using it like this.

```
max by (name, namespace) (
  cert_exporter_secret_not_after{job="cert-exporter", secretkey!="ca.crt"} - time()
)
> on (name, namespace) (
  max by (name, namespace) (extended_monitoring_secret_threshold{threshold="certificate-expiration"})
)
```
However, it turned out that we do not collect annotations from secrets, and it is not worth adding such support. It seems like complications without benefits. Let's leave a constant threshold value there; 1209600 is good enough.

2021-12-30 09:24 UTC, nabokihms requested changes
The last minor change left, and we will be done.

2021-12-30 09:24 UTC, nabokihms commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +      plk_grouped_by__main: "CertificateSecretExpiration,tier=cluster,prometheus=deckhouse"
```suggestion
      plk_grouped_by__main: "CertificateSecretExpiration,tier=~tier,prometheus=deckhouse"
```

2021-12-30 09:24 UTC, nabokihms commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +      plk_grouped_by__main: "CertificateSecretExpiration,tier=cluster,prometheus=deckhouse"
```suggestion
      plk_grouped_by__main: "CertificateSecretExpiration,tier=~tier,prometheus=deckhouse"
```

2021-12-30 09:24 UTC, nabokihms commented on ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
> +      plk_grouped_by__main: "CertificateSecretExpiration,tier=cluster,prometheus=deckhouse"
This is needed to groups alerts by tiers to route them. Alerts about certificates from system namespaces will have the `tier-cluster` label, and from other namespaces will have the `tier=application`.

2021-12-30 10:50 UTC, nabokihms approved these changes

2021-12-30 10:51 UTC, merged