[preflight-check] Checking the possibility of opening ports 6443 2379 2380 on the server (#5070)
deckhouse/deckhouse pull request #5195
Opened 2023-07-13 14:47 UTC by aleksey-su

## Description
Checking the possibility of opening ports 6443 2379 2380 on the server and connection to them

## Why do we need it, and what problem does it solve?
issue #5070 

## Why do we need it in the patch release (if we do)?

## What is the expected result?
Preventing failures before bootstrap execution

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: preflight-check
type: feature
summary: Checking the possibility of opening ports 6443 2379 2380 on the server and connection to them before bootstrap 
impact_level: default
```

2023-07-14 09:55 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/4b72a526-bcef-4d2d-83c2-dd59f2ffcdfb)
![image](https://github.com/deckhouse/deckhouse/assets/485892/39d18424-c87b-4de9-a1eb-b2b3862372bb)

2023-07-14 10:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-07-14 10:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-07-14 15:32 UTC, name212 commented on candi/bashible/preflight/check_ports.sh
> +        exit 1
please accumulate errors

2023-07-14 15:33 UTC, name212 commented on dhctl/pkg/preflight/ports.go
> +		log.InfoLn("Skip availability ports preflight check")
availability ports preflight check
```suggestion
		log.InfoLn("Availability ports preflight check was skipped")
```

2023-07-14 15:40 UTC, name212 requested changes
some comments

2023-07-17 09:54 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/43c67707-1aca-4eb5-aa4a-e6cad1c8c59d)
![image](https://github.com/deckhouse/deckhouse/assets/485892/f382b668-735a-4c5f-afa0-03e4157075fc)

2023-07-17 09:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-07-17 14:40 UTC, aleksey-su commented
/e2e/abort static;Static;containerd;1.23 5574230140 5574230140-2-con-1-23 /sys/deckhouse-oss/install:pr5195 astra@192.168.199.231

2023-07-17 14:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-07-18 09:19 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/b8fcd8a5-464c-449c-b6f9-50fadf310409)
![image](https://github.com/deckhouse/deckhouse/assets/485892/27cd53c5-3fe6-4a61-a448-d4b9ee40b73b)

2023-07-19 06:15 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.23 5574230140 5574230140-1-con-1-23 /sys/deckhouse-oss/install:pr5195 astra@192.168.199.114

2023-07-19 06:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-07-20 04:38 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.23 5574230140 5574230140-1-con-1-23 /sys/deckhouse-oss/install:pr5195 astra@192.168.199.114

2023-07-20 04:39 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-07-21 09:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-07-21 12:49 UTC, RomanenkoDenys approved these changes
LGTM

2023-07-24 11:35 UTC, name212 approved these changes

2023-07-24 11:36 UTC, merged