Change wrong description of vector tap in russian documentation
deckhouse/deckhouse pull request #5228
Opened 2023-07-17 11:16 UTC by Beastlex

## Description
There were some in description. And clients can read as 'will not transform' instead 'were not transformed' 

## Why do we need it, and what problem does it solve?
Exclude inaccuracies in the client's reading

## Why do we need it in the patch release (if we do)?
Exclude inaccuracies in the client's reading

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-07-18 04:01 UTC, z9r5 commented on modules/460-log-shipper/docs/ADVANCED_USAGE_RU.md
> +Измененные логи, которые поступают на вход следующих в цепочки компонентов каналов:
```suggestion
Измененные логи, которые поступают на вход следующих в цепочке компонентов каналов:
```

2023-07-18 04:03 UTC, z9r5 commented on modules/460-log-shipper/docs/ADVANCED_USAGE_RU.md
> +Например, `d8_cluster_source_*`).
```suggestion
Вы можете использовать команду `vector tap`, чтобы получить входные данные для любых компонентов каналов.
Единственный аргумент, который нужно задать — ID стадии обработки. Также поддерживаются выборки в формате glob (например, `d8_cluster_source_*`).
```

2023-07-18 04:04 UTC, z9r5 commented on modules/460-log-shipper/docs/ADVANCED_USAGE_RU.md
> +первой стадией обработки согласно вывода команды `vector graph` ):
```suggestion
С помощью такой команды вы сможете увидеть log'и до применения правил трансформации (`d8_cluster_source_*` является первой стадией обработки согласно вывода команды `vector graph`):
```

2023-07-18 07:13 UTC, z9r5 approved these changes

2023-07-18 07:13 UTC, z9r5 commented
@Beastlex Please fix the DCO

2023-07-21 11:43 UTC, nabokihms requested changes

2023-07-21 11:43 UTC, nabokihms commented on modules/460-log-shipper/docs/ADVANCED_USAGE.md
>  vector tap d8_cluster_source_*
```suggestion
vector tap 'cluster_logging_config/*'
```

2023-07-21 11:43 UTC, nabokihms commented on modules/460-log-shipper/docs/ADVANCED_USAGE.md
>  vector tap d8_tf_*
```suggestion
vector tap 'transform/*'
```

2023-07-21 11:43 UTC, nabokihms commented on modules/460-log-shipper/docs/ADVANCED_USAGE_RU.md
> +Например, `d8_cluster_source_*`).
```suggestion
Например, `cluster_logging_config/*`).
```

2023-07-21 11:43 UTC, nabokihms commented on modules/460-log-shipper/docs/ADVANCED_USAGE_RU.md
> +С помощью следующей команды вы сможете увидеть логи до применения правил трансформации (`d8_cluster_source_*` является первой стадией обработки согласно вывода команды `vector graph`):
```suggestion
С помощью следующей команды вы сможете увидеть логи до применения правил трансформации (`cluster_logging_config/*` является первой стадией обработки согласно вывода команды `vector graph`):
```

2023-07-21 11:43 UTC, nabokihms commented on modules/460-log-shipper/docs/ADVANCED_USAGE_RU.md
>  vector tap d8_tf_*
```suggestion
vector tap 'transform/*'
```

2023-07-21 11:43 UTC, nabokihms commented on modules/460-log-shipper/docs/ADVANCED_USAGE_RU.md
>  vector tap d8_cluster_source_*
```suggestion
vector tap 'cluster_logging_config/*'
```

2023-07-25 15:37 UTC, merged

2023-07-25 15:37 UTC, deckhouse-BOaTswain commented
Backport failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/5658846459) for details.