[control-plane-manager] added a state check before changing the master node
deckhouse/deckhouse pull request #5487
Opened 2023-08-09 12:59 UTC by alexey-gavrilov-flant

## Description
added a state check before changing the master node

## Why do we need it, and what problem does it solve?
better documentation

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: control-plane-manager
type: fix 
summary: added a state check before changing the master node
impact_level: low
```

2023-08-10 06:42 UTC, z9r5 submitted a review, later dismissed

2023-08-22 13:16 UTC, RomanenkoDenys commented on modules/040-control-plane-manager/docs/FAQ.md
> +
We do this check after master replicas change, cluster needs to be converged at this point.

2023-08-22 13:17 UTC, RomanenkoDenys requested changes
Improper place

2023-08-22 14:09 UTC, RomanenkoDenys commented on modules/040-control-plane-manager/docs/FAQ.md
> +     --ssh-host <MASTER-NODE-0-HOST> --ssh-host <MASTER-NODE-1-HOST> --ssh-host <MASTER-NODE-2-HOST>
```suggestion
   dhctl terraform check --ssh-agent-private-keys=/tmp/.ssh/<SSH_KEY_FILENAME> --ssh-user=<USERNAME> --ssh-host <MASTER-NODE-0-HOST>
```

2023-08-22 14:09 UTC, RomanenkoDenys commented on modules/040-control-plane-manager/docs/FAQ.md
> +     --ssh-host <MASTER-NODE-0-HOST> --ssh-host <MASTER-NODE-1-HOST> --ssh-host <MASTER-NODE-2-HOST>
```suggestion
   dhctl terraform check --ssh-agent-private-keys=/tmp/.ssh/<SSH_KEY_FILENAME> --ssh-user=<USERNAME> --ssh-host <MASTER-NODE-0-HOST>
```

2023-08-22 14:10 UTC, RomanenkoDenys commented on modules/040-control-plane-manager/docs/FAQ_RU.md
> +     --ssh-host <MASTER-NODE-0-HOST> --ssh-host <MASTER-NODE-1-HOST> --ssh-host <MASTER-NODE-2-HOST>
```suggestion
   dhctl terraform check --ssh-agent-private-keys=/tmp/.ssh/<SSH_KEY_FILENAME> --ssh-user=<USERNAME> --ssh-host <MASTER-NODE-0-HOST>
```

2023-08-22 14:11 UTC, RomanenkoDenys commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First check what will change `dhctl terraform check`.
```suggestion
        First, check what will change by running the `dhctl terraform check` command.
```

2023-08-22 14:11 UTC, RomanenkoDenys commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First check what will change `dhctl terraform check`.
```suggestion
        First, check what will change by running the `dhctl terraform check` command.
```

2023-08-22 14:12 UTC, RomanenkoDenys commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First check what will change `dhctl terraform check`.
```suggestion
        First, check what will change by running the `dhctl terraform check` command.
```

2023-08-22 14:12 UTC, RomanenkoDenys commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First check what will change `dhctl terraform check`.
```suggestion
        First, check what will change by running the `dhctl terraform check` command.
```

2023-08-22 14:13 UTC, RomanenkoDenys approved these changes
LGTM

2023-08-22 14:27 UTC, z9r5 commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First, check what will change by running the `dhctl terraform check` command.
```suggestion
        First, run the `dhctl terraform check` command to check what will change.
```

2023-08-22 14:27 UTC, z9r5 commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First, check what will change by running the `dhctl terraform check` command.
```suggestion
        First, run the `dhctl terraform check` command to check what will change.
```

2023-08-22 14:27 UTC, z9r5 commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First, check what will change by running the `dhctl terraform check` command.
```suggestion
        First, run the `dhctl terraform check` command to check what will change.
```

2023-08-22 14:28 UTC, z9r5 commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First check what will change `dhctl terraform check`.
```suggestion
        First, run the `dhctl terraform check` command to check what will change.
```

2023-08-22 14:28 UTC, z9r5 commented on modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
> +        First, check what will change by running the `dhctl terraform check` command.
```suggestion
        First, run the `dhctl terraform check` command to check what will change.
```

2023-08-22 14:29 UTC, z9r5 submitted a review, later dismissed

2023-08-22 17:06 UTC, RomanenkoDenys approved these changes
LGTM

2023-08-23 00:09 UTC, merged