[candi] Convert InitConfiguration configOverrides to a set of ModuleConfig's during bootstrap
deckhouse/deckhouse pull request #5534
Opened 2023-08-14 10:58 UTC by mvasl

## Description

Deckhouse config overrides are now converted to a set of `ModuleConfig`'s during `dhctl bootstrap` execution. Modules hooks are set on hold during this process by a new global hook that continuously checks for `deckhouse-bootstrap-lock` ConfigMap existence in `d8-system` namespace. That ConfigMap acts as a marker of ongoing configuration conversion.

## Why do we need it, and what problem does it solve?

See #3776 

## What is the expected result?

Cluster must contain `ModuleConfig`s according to what was set in `InitConfiguration`'s `deckhouse.configOverrides` after bootstrap is completed.

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: feature
summary: ModuleConfig's are created during cluster bootstrap according to InitConfiguration
impact_level: default
```

2023-08-14 11:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-14 14:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-08-14 14:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-08-14 15:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-14 16:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-08-14 16:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-14 17:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-08-14 21:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-08-15 07:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-15 11:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-15 12:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-08-16 16:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-16 17:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-08-16 18:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-08-17 06:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-17 08:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-17 13:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-17 13:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-08-17 13:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-17 14:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @m-vasilenko. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-08-28 05:49 UTC, name212 commented on dhctl/pkg/operations/bootstrap/module_configs.go
> +		moduleName, overrideIsEnableProperty := stringsutil.CutSuffix(key, "Enabled")
please use strings.TrimSuffix instead of your own function

2023-08-28 05:55 UTC, name212 commented on dhctl/pkg/operations/bootstrap/module_configs.go
> +	_ = unstructured.SetNestedField(mc.Object, int64(1), "spec", "version")
interesting.

We can have version > 1 for module and for config with version 2 and may not have setting.
We need think about it.

2023-08-28 06:53 UTC, name212 requested changes
We have two unresolved problems
1. version in moduleconfig
2. originally it was conceived for initialConfig validation using the config module, but 1. validation is enabled in the 002-deckhouse module and when creating the config module at the primary stage, validation is not performed 2. validation settings are deployed only when the cluster is bootstrapped 3. during the initial synch in, the global hook , we simply skip non-valid module configs.

It's worth discussing these issues in a design review.

2023-10-31 08:07 UTC, raabdullaev-fl commented
https://github.com/deckhouse/deckhouse/pull/6061

2023-10-31 08:07 UTC, closed without merging