[linstor] Added section about data nodes nodeSelector in docs
deckhouse/deckhouse pull request #5618
Opened 2023-08-22 16:07 UTC by duckhawk

## Description

Added section about data nodes nodeSelector in docs

## Why do we need it, and what problem does it solve?

We have no mentions about data nodes nodeSelector in documentation

## What is the expected result?

Actual documentation

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: linstor
type: chore
summary: Added section about data nodes nodeSelector in docs.
impact_level: low
```

2023-08-23 15:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2023-08-23 16:21 UTC, z9r5 approved these changes

2023-08-23 17:45 UTC, apolovov requested changes

2023-08-23 17:45 UTC, apolovov commented on modules/041-linstor/docs/USAGE_RU.md
> +description: Примеры конфигурации модуля linstor Deckhouse. Конфигурация хранилища LINSTOR. Настройка data-locality - размещение приложения возле данных. Storage-based fencing. Перенос приложения при
```suggestion
description: Примеры конфигурации модуля linstor. Настройка data-locality — размещение приложения возле данных. Storage-based fencing. Перенос приложения при проблемах с узлом.
```

2023-08-23 17:45 UTC, apolovov commented on modules/041-linstor/docs/USAGE_RU.md
> +Работоспособность модуля гарантируется только для стоковых ядер, поставляемых вместе с дистрибутивами перечисленными в [списке поддерживаемых ОС](../../supported_versions.html#linux).
```suggestion
Работоспособность модуля гарантируется только для стоковых ядер, поставляемых вместе с дистрибутивами, перечисленными в [списке поддерживаемых ОС](../../supported_versions.html#linux).
```

2023-08-23 17:45 UTC, apolovov commented on modules/041-linstor/docs/USAGE_RU.md
> +После включения модуля кластер автоматически настраивается на использование LINSTOR и остается только сконфигурировать хранилище.
```suggestion
После включения модуля, кластер автоматически настраивается на использование LINSTOR и остается только сконфигурировать хранилище.
```

2023-08-23 17:45 UTC, apolovov commented on modules/041-linstor/docs/USAGE_RU.md
> +Отдельные функции модуля могут потребовать указания мастер-пароля.
Уточнить пример, где нужен мастер-пароль.

2023-08-23 17:45 UTC, apolovov commented on modules/041-linstor/docs/USAGE_RU.md
> +Для того чтобы задать мастер-пароль, создайте Secret в пространстве имен `d8-system`:
```suggestion
Для того чтобы задать мастер-пароль, создайте Secret в пространстве имён `d8-system`:
```

2023-08-23 17:45 UTC, apolovov commented on modules/041-linstor/docs/USAGE_RU.md
> +Подойдите ответственно к выбору мастер-пароля для LINSTOR. При его потере зашифрованные данные окажутся недоступными.
```suggestion
Подойдите ответственно к выбору мастер-пароля для LINSTOR. При его потере, зашифрованные данные окажутся недоступными.
```
По-моему, запятая нужна.

2023-08-23 17:48 UTC, z9r5 commented on modules/041-linstor/docs/USAGE_RU.md
> +После включения модуля кластер автоматически настраивается на использование LINSTOR и остается только сконфигурировать хранилище.
IMHO запятая не нужна.

2023-08-23 17:49 UTC, z9r5 commented on modules/041-linstor/docs/USAGE_RU.md
> +После включения модуля кластер автоматически настраивается на использование LINSTOR и остается только сконфигурировать хранилище.
@kirkonru your turn :)

2023-08-24 07:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2023-08-24 08:36 UTC, z9r5 commented on modules/041-linstor/docs/CONFIGURATION_RU.md
> +description: Параметры настройки модуля linstor Deckhouse
```suggestion
description: Параметры настройки модуля linstor Deckhouse.
```

2023-08-31 11:03 UTC, apolovov approved these changes

2023-09-01 06:22 UTC, AleksZimin approved these changes

2023-09-01 07:11 UTC, nabokihms approved these changes

2023-09-01 07:12 UTC, merged