[candi] Use /opt/deckhouse/tmp instead of /tmp during bootstrap
deckhouse/deckhouse pull request #5739
Opened 2023-09-06 12:25 UTC by mvasl

## Description

Temporary files created by bashible steps during bootstrap will now be put into `/opt/deckhouse/tmp` instead of `/tmp`. `dhctl` will create this directory during master node bootstrap.

## Why do we need it, and what problem does it solve?

This solves points 1,3,4 and 5 of [#5597](https://github.com/deckhouse/deckhouse/issues/5597#issuecomment-1695348015)

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: chore
summary: Point $TMPDIR to `/opt/deckhouse/tmp` during bashible bootstrap.
impact_level: default
```

```changes
section: dhctl
type: chore
summary: Render bootstrap bundle into `/opt/deckhouse/tmp`.
impact_level: default
```

```changes
section: candi
type: fix
summary: Delete registrypackage files if it failed to install before retrying installation.
impact_level: default
```

2023-09-07 13:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-09-11 17:29 UTC, RomanenkoDenys requested changes
some minor changes

2023-09-11 17:29 UTC, RomanenkoDenys commented on dhctl/pkg/operations/bootstrap.go
> +			if err := sshClient.Command("mkdir", "-p", "/opt/deckhouse/bin").Sudo().Run(); err != nil {
Move "/opt/deckhouse/bin" to constant and use it in code

2023-09-11 17:29 UTC, RomanenkoDenys commented on dhctl/pkg/operations/bootstrap.go
> +				return fmt.Errorf("ssh: mkdir -p -m 1777 /opt/deckhouse/tmp: %w", err)
Move "/opt/deckhouse/tmp" to constant and use it in code

2023-09-14 08:25 UTC, RomanenkoDenys commented on dhctl/pkg/operations/bootstrap.go
> +			return fmt.Errorf("cannot create /opt/deckhouse/ directories: %w", err)
```suggestion
			return fmt.Errorf("cannot create %s directories: %w",NodeDeckhouseDirectoryPath, err)
```

2023-09-14 08:26 UTC, RomanenkoDenys commented on dhctl/pkg/system/ssh/frontend/upload-script.go
> +		remotePath = "/opt/deckhouse/tmp/" + scriptName
const?

2023-09-14 08:26 UTC, RomanenkoDenys commented on dhctl/pkg/system/ssh/frontend/upload-script.go
> +	err = NewFile(u.Session).Upload(bundleLocalFilepath, "/opt/deckhouse/tmp")
const?

2023-09-14 08:26 UTC, RomanenkoDenys commented on dhctl/pkg/system/ssh/frontend/upload-script.go
> +	tarCmdline := fmt.Sprintf("tar xpof /opt/deckhouse/tmp/%s -C /var/lib && /var/lib/%s/%s %s", bundleName, bundleDir, u.ScriptPath, strings.Join(u.Args, " "))
const?

2023-09-14 08:26 UTC, RomanenkoDenys reviewed
consts

2023-09-15 08:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-15 13:51 UTC, RomanenkoDenys approved these changes
LGTM

2023-09-19 07:23 UTC, name212 approved these changes

2023-09-19 07:24 UTC, merged