Fix api version for cronjobs to display with dashboard module
deckhouse/deckhouse pull request #5799
Opened 2023-09-11 08:58 UTC by Beastlex

## Description

Fix api version for cronjobs to display with dashboard module

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: modules
type: fix
summary: Fix api version for cronjobs to display with dashboard module
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default
```

2023-09-14 08:45 UTC, aleksey-su requested changes
Please create a file README.md in the patches folder and describe what your patch does

2023-09-14 08:45 UTC, aleksey-su commented on modules/500-dashboard/images/dashboard/Dockerfile
> +FROM golang:1.19.12-alpine3.18 as patchbuilder
```suggestion
ARG BASE_GOLANG_19_ALPINE

# to fix dashboard can display cronjobs v1
FROM $BASE_GOLANG_19_ALPINE as patchbuilder
```

2023-09-14 08:45 UTC, aleksey-su commented on modules/500-dashboard/images/dashboard/Dockerfile
> +# COPY --from=artifact /dashboard /dashboard
```suggestion
```

2023-09-14 08:48 UTC, RomanenkoDenys commented on modules/500-dashboard/images/dashboard/Dockerfile
> +    wget -c https://github.com/kubernetes/dashboard/archive/refs/tags/v2.7.0.zip && \
use git clone here

2023-09-14 08:48 UTC, RomanenkoDenys commented on modules/500-dashboard/images/dashboard/Dockerfile
> +RUN patch -u dashboard-2.7.0/src/app/backend/resource/cronjob/jobs.go -i 001-fix-cronjob-ver.patch --ignore-whitespace --fuzz 3 && \
use git apply here

2023-09-14 10:54 UTC, aleksey-su commented
@Beastlex I suggest using cherry-pick from commit 'f79f3a5e25df152df6164ddfaf2ffc1f09e5058f' instead of using patch

2023-09-15 14:06 UTC, RomanenkoDenys approved these changes
LGTM

2023-09-18 10:11 UTC, Beastlex commented
Create test CronJob with content:

2023-09-18 10:12 UTC, Beastlex commented
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

2023-09-18 10:13 UTC, Beastlex commented
![image](https://github.com/deckhouse/deckhouse/assets/36466535/974cb6b8-6d7d-4b90-8d49-82503d942cea)

2023-09-18 10:14 UTC, Beastlex commented
![image](https://github.com/deckhouse/deckhouse/assets/36466535/757899fa-107b-45a9-b950-b1240f6ba18a)

2023-09-18 10:18 UTC, aleksey-su approved these changes

2023-09-18 10:25 UTC, RomanenkoDenys commented on modules/500-dashboard/images/dashboard/Dockerfile
> +RUN apk add --no-cache git patch make zip wget && \
```suggestion
RUN apk add --no-cache git patch make zip && \
```

2023-09-18 10:26 UTC, RomanenkoDenys commented on modules/500-dashboard/images/dashboard/Dockerfile
> +    git clone https://github.com/kubernetes/dashboard && \
```suggestion
    git clone ${SOURCE_REPO}/kubernetes/dashboard && \
```

2023-09-18 10:27 UTC, RomanenkoDenys commented on modules/500-dashboard/images/dashboard/Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X github.com/kubernetes/dashboard/src/app/backend/client.Version=v2.7.0" -o dashboard .
```suggestion
RUN go build -a -installsuffix cgo -ldflags "-X github.com/kubernetes/dashboard/src/app/backend/client.Version=v2.7.0" -o dashboard .
```

2023-09-18 10:27 UTC, RomanenkoDenys commented on modules/500-dashboard/images/dashboard/Dockerfile
> +FROM $BASE_GOLANG_19_ALPINE as patchbuilder
```suggestion
FROM $BASE_GOLANG_19_ALPINE as patchbuilder

ARG GOPROXY
ARG SOURCE_REPO

ENV GOPROXY=${GOPROXY} \
    SOURCE_REPO=${SOURCE_REPO} \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
```

2023-09-18 10:27 UTC, RomanenkoDenys requested changes
Some nits

2023-09-21 19:00 UTC, nabokihms approved these changes

2023-09-21 19:13 UTC, RomanenkoDenys commented on modules/500-dashboard/images/dashboard/Dockerfile
> +    git clone https://${SOURCE_REPO}/kubernetes/dashboard && \
```suggestion
    git clone ${SOURCE_REPO}/kubernetes/dashboard && \
```

2023-09-21 19:38 UTC, RomanenkoDenys commented on modules/500-dashboard/images/dashboard/Dockerfile
> +    git cherry-pick f79f3a5e25df152df6164ddfaf2ffc1f09e5058f && \
```suggestion
    # Use batch/v1 for fetching cronjob jobs https://github.com/kubernetes/dashboard/pull/7465
    git cherry-pick f79f3a5e25df152df6164ddfaf2ffc1f09e5058f && \
```

2023-09-23 20:41 UTC, aleksey-su requested changes

2023-09-23 20:41 UTC, aleksey-su commented on modules/500-dashboard/images/dashboard/Dockerfile
>  FROM kubernetesui/dashboard:v2.7.0@sha256:2e500d29e9d5f4a086b908eb8dfe7ecac57d2ab09d65b24f588b1d449841ef93 as artifact
```suggestion
```

2023-09-27 12:34 UTC, RomanenkoDenys approved these changes
LGTM

2023-11-01 07:28 UTC, merged