[dhctl] Check dhctl version against current release channel version before bootstrap
deckhouse/deckhouse pull request #5832
Opened 2023-09-14 15:58 UTC by mvasl

## Description

Added a preflight check that ensures installer image is "compatible" with current Deckhouse version in selected release channel. If this preflight check fails, installation is aborted with an error message that describes the problem and provides means to fix it.

There is an override to this behavoiur that allows to force installation even if `dhctl` is not "compatible" via `DHCTL_CLI_PREFLIGHT_SKIP_INCOMPATIBLE_VERSION_CHECK` enviroment variable.

Term "compatible" here means that deckhouse container image digests match between dhctl build and deckhouse release channel image it is configured to install.

## Why do we need it, and what problem does it solve?

Closes #5073 and #3251 

## Manual testing
https://github.com/deckhouse/deckhouse/pull/5832#issuecomment-1728973475

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: dhctl will check if it is compatible with deckhouse version it is bootstrapping
impact_level: default
```

2023-09-15 07:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-21 07:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-21 08:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-21 14:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-23 21:11 UTC, aleksey-su requested changes

2023-09-23 21:11 UTC, aleksey-su commented on dhctl/pkg/preflight/preflight.go
> +		buildDigestProvider:     &dhctlBuildDigestProvider{DigestFilePath: app.DeckhouseImageDigestFile},
Maybe it's worth creating constructor functions that will return the corresponding interfaces as a type?

2023-09-25 09:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-09-25 09:23 UTC, name212 approved these changes

2023-09-25 09:51 UTC, name212 approved these changes

2023-09-25 10:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-09-25 10:50 UTC, name212 submitted a review, later dismissed

2023-09-25 11:13 UTC, aleksey-su approved these changes

2023-09-25 11:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-09-25 12:26 UTC, name212 approved these changes

2023-09-25 12:26 UTC, merged