[WIP] Change deckhouse-controller user to deckhouse
deckhouse/deckhouse pull request #5841
Opened 2023-09-15 11:57 UTC by asviel

## Description

Add `deckhouse` user for deckhouse-controller and use it instead of `nobody`.

Fixes https://github.com/deckhouse/deckhouse/issues/2797

## Why do we need it, and what problem does it solve?

We'd like to run every process inside deckhouse-borne containers through a single UID/GID to ease mapping.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: feature
summary: Change deckhouse-controller user to deckhouse
impact_level: default
```

2023-10-09 12:13 UTC, yalosev commented on werf.yaml
> +  # TODO: Remove after the next release
Specify the release please. It will take some time to figure out what means `next`.
Better to set `Remove after the deckhouse release 1.55`

2023-10-09 12:14 UTC, yalosev approved these changes

2023-10-09 12:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-13 01:10 UTC, name212 commented on helm_lib/charts/deckhouse_lib_helm/templates/_module_security_context.tpl
> -{{- /* Usage: {{ include "helm_lib_module_container_security_context_not_allow_privilege_escalation_with_selinux" . }} */ -}}
1. Why did we delete this.
2. Do not edit helm_lib [directly](https://github.com/deckhouse/deckhouse/tree/main/helm_lib#helm_lib)

2023-10-13 01:13 UTC, name212 commented on modules/global-values.yaml
why do we need to rename this file?

2023-10-13 01:14 UTC, name212 requested changes
helm lib and questions

2023-10-18 09:42 UTC, name212 approved these changes

2023-10-18 09:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-18 09:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-10-20 10:23 UTC, yalosev approved these changes

2023-10-20 10:23 UTC, merged