Add CRD validations for wrong names of properties
deckhouse/deckhouse pull request #5853
Opened 2023-09-18 11:05 UTC by Beastlex

## Description
CRDs couldn't have fields like x-examples, examples only example despite of openapi specs

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: testing
type: feature
summary: add validation test for wrong prop names
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: low
```

2023-10-04 20:10 UTC, yalosev requested changes
Could you add a test, please

2023-10-13 18:54 UTC, yalosev requested changes
So, we have some failed CRDs in validation CI.
They should be fixed

2023-10-17 18:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @yalosev. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-17 19:44 UTC, yalosev submitted a review, later dismissed

2023-10-26 10:24 UTC, yalosev commented on candi/cloud-providers/gcp/openapi/instance_class.yaml
> +                  x-doc-x-doc-examples: |
```suggestion
                  x-doc-examples: |
```

2023-10-26 10:25 UTC, yalosev commented on candi/cloud-providers/yandex/openapi/instance_class.yaml
> +                  x-doc-x-doc-examples: |
```suggestion
                  x-doc-examples: |
```

2023-10-26 10:25 UTC, yalosev commented on candi/cloud-providers/yandex/openapi/instance_class.yaml
> +                  x-doc-x-doc-examples: |
```suggestion
                  x-doc-examples: |
```

2023-10-26 10:26 UTC, yalosev submitted a review, later dismissed

2023-10-26 10:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2023-10-26 13:55 UTC, merged