[deckhouse][docs] Fix images copier docs
deckhouse/deckhouse pull request #591
Opened 2022-01-14 12:43 UTC by name212

## Description
Fix images copier docs

## Why do we need it, and what problem does it solve?
`How it works` section is confuse

## Changelog entries

2022-01-17 20:37 UTC, apolovov requested changes
I realized we need some tool to generate the new registry secret with new creds.
It is quite painful to generate it manually.

2022-01-21 08:35 UTC, apolovov approved these changes

2022-01-21 13:38 UTC, nabokihms approved these changes

2022-01-21 13:38 UTC, merged

2022-01-24 10:02 UTC, z9r5 commented
Cherry-picked into release-1.30