[dhctl] Check if registry can be reached through proxy
deckhouse/deckhouse pull request #5926
Opened 2023-09-22 13:24 UTC by mvasl

## Description

Added a preflight check that tries to reach registry api using a proxy if one is given and registry address is not blacklisted for proxying.

## Why do we need it, and what problem does it solve?

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: Dhctl will check if container registry can be reached with provided HTTP\HTTPS proxy
impact_level: default
```

2023-09-22 13:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-25 13:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-09-25 13:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-09-25 16:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-09-26 05:50 UTC, name212 requested changes
good job, but unfortunately we have to run the check not from the machine with the installer (directly from dhctl), but from the master.

You need to try to come up with some magic on ssh tunnels so that the request comes from the master or upload a script to the master that will check availability directly from the master.

2023-09-26 06:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-09-27 11:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-10-16 09:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-10-16 09:58 UTC, mvasl commented
/e2e/abort static;Static;containerd;1.25 6531939517 6531939517-1-con-1-25 /sys/deckhouse-oss/install:pr5926 astra@192.168.199.219

2023-10-16 09:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-16 10:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-10-18 08:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-10-18 09:55 UTC, name212 approved these changes

2023-10-18 09:57 UTC, merged