[user-authn] Add openapi spec
deckhouse/deckhouse pull request #593
Opened 2022-01-14 14:58 UTC by nabokihms

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

## Description
Add the `openapi` folder with specs that describes Deckhouse configmap and Helm templates inputs. 

## Why do we need it, and what problem does it solve?
This is a part of Global refactoring. We need these specs to validate values coming from users.

## Changelog entries
```changes
module: user-authn
type: feature
description: Add an OpenAPI spec to validate Deckhouse configuration parameters for the user-authn module.
```

2022-01-14 15:18 UTC, deckhouse-BOaTswain commented
Run workflow "deploy/web/test"...

2022-01-20 17:05 UTC, z9r5 submitted a review, later dismissed

2022-01-20 17:15 UTC, deckhouse-BOaTswain commented
Run workflow "deploy/web/stage"...

2022-01-20 17:51 UTC, deckhouse-BOaTswain commented
Run workflow "deploy/web/stage"...

2022-01-23 19:00 UTC, yalosev requested changes

2022-01-23 19:00 UTC, yalosev commented on modules/150-user-authn/openapi/config-values.yaml
> +    pattern: '^[0-9]+[mh]{1}$'
'^[0-9]+[mh]{1}$'
```suggestion
    pattern: '^[0-9]+[smh]{1}$'
```

2022-01-24 10:46 UTC, z9r5 approved these changes

2022-01-24 14:27 UTC, merged