[cloud-provider-aws] Reduce cloud-init data size
deckhouse/deckhouse pull request #5939
Opened 2023-09-25 12:16 UTC by vitaliy-sn

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-09-25 12:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-09-25 17:49 UTC, vitaliy-sn commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6299366839 6299366839-1-con-1-25 /sys/deckhouse-oss/install:pr5939 centos@3.79.217.11

2023-09-25 17:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-09-25 18:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-09-25 19:18 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-09-26 06:26 UTC, RomanenkoDenys requested changes
A Fistful of Symbols

2023-09-26 06:26 UTC, RomanenkoDenys commented on modules/040-node-manager/templates/node-group/_bootstrap_script.tpl
> +export TMPDIR=/opt/deckhouse/tmp
```suggestion
export TMPDIR=/opt/deckhouse/tmp
mkdir -p "$TMPDIR"
```

2023-09-26 09:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-09-26 12:12 UTC, yalosev approved these changes

2023-09-26 12:18 UTC, merged