[dhctl] Bootstrap deckhouse with a version tag instead of release channel tag and refactor preflight checks messages
deckhouse/deckhouse pull request #5955
Opened 2023-09-26 11:34 UTC by mvasl

## Description

Adjusted image tag selection logic to allow usage of deckhouse version tag from `/deckhouse/version` for installation. Deckhouse is now bootstrapped using this tag.

Also preflight checks code was refactored.

And refactored preflight check error messages.

## Why do we need it, and what problem does it solve?

Fixes #3251 

![image](https://github.com/deckhouse/deckhouse/assets/30695496/19b86d6d-52c8-48dc-9b68-3add2e6a9e51)

![image](https://github.com/deckhouse/deckhouse/assets/30695496/bc5d8c0a-2c3e-47af-be98-6925ffdb9591)

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: Allow installing Deckhouse from tag. Refactor preflight checks code.
impact_level: default
```

2023-09-26 11:47 UTC, RomanenkoDenys requested changes
allmost all ok

2023-09-26 11:47 UTC, RomanenkoDenys commented on dhctl/pkg/kubernetes/actions/deckhouse/install.go
> +	}
please use https://pkg.go.dev/golang.org/x/mod/semver#IsValid here

2023-09-26 11:47 UTC, RomanenkoDenys requested changes
allmost all ok

2023-09-26 12:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-26 13:18 UTC, RomanenkoDenys approved these changes
LGTM

2023-09-26 16:38 UTC, name212 commented on dhctl/pkg/preflight/dhctl_obsolescence.go
> -	imageReference, err := name.ParseReference(pc.installConfig.GetImage())
why are not we using for preflight check force using tag?

2023-09-27 07:36 UTC, name212 commented on dhctl/pkg/preflight/dhctl_obsolescence.go
> -	imageReference, err := name.ParseReference(pc.installConfig.GetImage())
Why compare with the image of the release channel? When we insert an end tag into the deployment. If the final goal is that no updates occur during installation, then we need to compare both the image tag for the tag and for the release channel, if there is one. In general, the release channel planned to transfer the config from the init configuration to the config module and remove it from the init configuration.

2023-09-27 07:37 UTC, name212 commented on dhctl/pkg/preflight/dhctl_obsolescence.go
> -	imageReference, err := name.ParseReference(pc.installConfig.GetImage())
>to transfer the config from the init configuration to the config module and remove it from the init configuration.
and then it becomes optional altogether

2023-09-27 14:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-29 06:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-09-29 11:05 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.25 6347886355 6347886355-1-con-1-25 /sys/deckhouse-oss/install:pr5955 astra@192.168.199.154

2023-10-18 15:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-10-18 15:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-18 17:03 UTC, name212 approved these changes

2023-10-18 17:03 UTC, RomanenkoDenys commented on dhctl/pkg/preflight/dhctl_obsolescence.go
> +		return nil, fmt.Errorf("parse image refernce: %w", err)
```suggestion
		return nil, fmt.Errorf("parse image reference: %w", err)
```

2023-10-18 17:05 UTC, RomanenkoDenys requested changes
one mistake

2023-10-18 17:11 UTC, name212 submitted a review, later dismissed

2023-10-18 17:33 UTC, name212 approved these changes

2023-10-19 07:34 UTC, merged