[operator-trivy] update report-updater dictionary on a schedule
deckhouse/deckhouse pull request #5973
Opened 2023-09-27 13:59 UTC by miklezzzz

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-10-02 11:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-04 20:01 UTC, yalosev commented on ee/modules/500-operator-trivy/images/report-updater/web/hook/hook.go
> +	ticker := time.NewTicker(6 * time.Hour)
Could we pass this as argument with default value (6 hours) please

2023-10-04 20:04 UTC, yalosev commented on ee/modules/500-operator-trivy/images/report-updater/cache/cache.go
> +	err = json.Unmarshal(b, &dockerConfig)
```suggestion
	err = json.NewDecoder(dockerConfigFile).Decode(&dockerConfig)
```

2023-10-04 20:07 UTC, yalosev commented on ee/modules/500-operator-trivy/images/report-updater/cache/cache.go
> +			defer readCloser.Close()
`defer` in `for loop` is not safe, would be better to wrap it with a function. At least anonymous one

2023-10-04 20:08 UTC, yalosev commented on ee/modules/500-operator-trivy/images/report-updater/cache/cache.go
> +			err = json.Unmarshal(b, &tempDict)
```suggestion
			err = json.NewDecoder(tarReader).Decode(&tempDict)
```

2023-10-04 20:09 UTC, yalosev requested changes
A few details

2023-10-05 12:53 UTC, miklezzzz commented
nice! I've got the point, I guess..

2023-10-13 01:22 UTC, name212 approved these changes

2023-10-13 01:23 UTC, merged