[distroless] move cloud-controller-manager binaries to distroless
deckhouse/deckhouse pull request #5985
Opened 2023-09-28 13:46 UTC by universal-itengineer

## Description

## Why do we need it, and what problem does it solve?

This PR is a part of moving Deckhouse to distroless.

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-09-29 06:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-09-29 11:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-09-29 14:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-09-29 15:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-09-29 16:55 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6351209586 6351209586-1-con-1-25 /sys/deckhouse-oss/install:pr5985 centos@3.74.49.178

2023-09-29 16:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-09-29 16:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-02 07:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-02 07:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-02 07:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-02 07:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-02 08:49 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6376972203 6376972203-1-con-1-25 /sys/deckhouse-oss/install:pr5985 centos@35.156.149.44

2023-10-02 09:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-02 11:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-02 11:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-02 11:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-02 11:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-03 10:01 UTC, RomanenkoDenys requested changes
Please add https://github.com/deckhouse/deckhouse/tree/main/ee/modules providers

2023-10-03 13:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-03 13:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-04 04:31 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6376972203 6376972203-1-con-1-25 /sys/deckhouse-oss/install:pr5985 centos@35.156.149.44

2023-10-04 04:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-04 07:36 UTC, universal-itengineer commented
/e2e/abort vsphere;Standard;containerd;1.25 6394012131 6394012131-1-con-1-25 /sys/deckhouse-oss/install:pr5985 ubuntu@10.220.203.29

2023-10-04 07:39 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-04 09:35 UTC, z9r5 commented
/e2e/abort vsphere;Standard;containerd;1.25 6402998204 6402998204-1-con-1-25 /sys/deckhouse-oss/install:pr5985 ubuntu@10.220.203.27

2023-10-04 09:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-04 09:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-04 18:56 UTC, RomanenkoDenys commented on ee/modules/030-cloud-provider-openstack/images/cloud-controller-manager/werf.inc.yaml
> +  {{- end }}
strange construction, simply move openstack-cloud-controller-manager-amd64 to openstack-cloud-controller-manager

2023-10-04 18:57 UTC, RomanenkoDenys requested changes
one simple question

2023-10-05 07:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-05 08:46 UTC, RomanenkoDenys approved these changes
LGTM

2023-10-05 08:46 UTC, merged