proxy-failover
deckhouse/deckhouse pull request #6028
Opened 2023-10-03 14:11 UTC by aleksey-su

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-10-04 13:37 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/8247627d-aad6-4195-bf40-28d43f7fe89c)
![image](https://github.com/deckhouse/deckhouse/assets/485892/9002ba86-686e-43a9-9be3-8029e98cecb7)
![image](https://github.com/deckhouse/deckhouse/assets/485892/6fde752d-67a7-4935-a364-7389d4dc9c39)

2023-10-05 06:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-09 07:16 UTC, RomanenkoDenys commented on modules/402-ingress-nginx/images/proxy-failover/werf.inc.yaml
> +from: {{ .Images.BASE_NGINX_ALPINE }}
it looks like we can build static nginx and use distroless

2023-10-09 07:17 UTC, RomanenkoDenys requested changes
use static build please

2023-10-11 12:48 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/73994045-89a7-42f6-b942-290157c44962)

2023-10-11 13:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-11 20:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-12 04:35 UTC, z9r5 commented
/e2e/abort openstack;Standard;containerd;1.25 6487781621 6487781621-1-con-1-25 /sys/deckhouse-oss/install:pr6028 debian@45.12.229.247

2023-10-12 04:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 07:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-12 15:01 UTC, aleksey-su commented
befor migrations
![image](https://github.com/deckhouse/deckhouse/assets/485892/3017702f-58da-48a8-9699-c920af3b5140)
![image](https://github.com/deckhouse/deckhouse/assets/485892/83fb1ea7-9eac-4718-a897-aa47880b33d5)

2023-10-12 15:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-12 19:09 UTC, RomanenkoDenys approved these changes
LGTM

2023-10-13 01:38 UTC, name212 approved these changes

2023-10-13 07:47 UTC, yalosev approved these changes

2023-10-16 07:44 UTC, nabokihms approved these changes

2023-10-16 07:45 UTC, merged