[distroless] move cloud-provider csi-plugin to distroless
deckhouse/deckhouse pull request #6073
Opened 2023-10-05 19:37 UTC by universal-itengineer

## Description

- [ ] cloud-provider-aws
- [ ] cloud-provider-azure
- [ ] cloud-provider-gcp
- [ ] cloud-provider-yandex
- [ ] ee/cloud-provider-openstack
- [ ] ee/cloud-provider-vsphere

## Why do we need it, and what problem does it solve?

This PR is a part of moving Deckhouse to distroless.

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-aws
type: chore
summary: "`cloud-controller-manager` use distroless based image."
impact_level: default
---
section: cloud-provider-azure
type: chore
summary: "`` use distroless based image."
impact_level: default
---
section: cloud-provider-gcp
type: chore
summary: "`` use distroless based image."
impact_level: default
---
section: cloud-provider-yandex
type: chore
summary: "`` use distroless based image."
impact_level: default
---
section: ee/cloud-provider-openstack
type: chore
summary: "`` use distroless based image."
impact_level: default
---
section: ee/cloud-provider-vsphere
type: chore
summary: "`` use distroless based image."
impact_level: default
```

2023-10-05 21:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-06 06:34 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6424458356 6424458356-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@3.76.130.183

2023-10-06 06:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-06 14:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-06 14:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-09 04:35 UTC, z9r5 commented
/e2e/abort azure;Standard;containerd;1.25 6433032082 6433032082-1-con-1-25 /sys/deckhouse-oss/install:pr6073 azureuser@74.234.176.125

2023-10-09 04:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-09 04:36 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6433032576 6433032576-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@18.198.70.226

2023-10-09 04:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-09 10:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-09 11:15 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6455279377 6455279377-1-con-1-25 /sys/deckhouse-oss/install:pr6073 user@34.159.182.170

2023-10-09 11:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-09 16:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-09 16:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-09 16:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-09 21:00 UTC, universal-itengineer commented
/e2e/abort azure;Standard;containerd;1.25 6459410047 6459410047-1-con-1-25 /sys/deckhouse-oss/install:pr6073 azureuser@20.56.5.35

2023-10-09 21:00 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6459411120 6459411120-1-con-1-25 /sys/deckhouse-oss/install:pr6073 user@34.159.182.170

2023-10-09 21:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-10 10:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-10 14:49 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6467804729 6467804729-1-con-1-25 /sys/deckhouse-oss/install:pr6073 user@34.159.182.170

2023-10-10 14:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-10 15:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-11 06:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-11 10:25 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6479010279 6479010279-2-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@3.65.250.16

2023-10-11 10:25 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6479011912 6479011912-1-con-1-25 /sys/deckhouse-oss/install:pr6073 ubuntu@158.160.123.177

2023-10-11 10:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-11 10:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-11 11:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-11 11:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-11 11:46 UTC, universal-itengineer commented
/e2e/abort openstack;Standard;containerd;1.25 6481606814 6481606814-1-con-1-25 /sys/deckhouse-oss/install:pr6073 debian@45.12.231.87

2023-10-11 11:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-11 13:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-11 13:58 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6483107015 6483107015-1-con-1-25 /sys/deckhouse-oss/install:pr6073 user@34.107.15.239

2023-10-11 13:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-11 14:37 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6482956145 6482956145-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.126.86

2023-10-11 14:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-11 14:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-11 15:34 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6484250139 6484250139-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@3.75.107.152

2023-10-11 15:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 04:57 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6484591239 6484591239-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.99.189

2023-10-12 04:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 05:01 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6479010279 6479010279-2-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@3.65.250.16

2023-10-12 05:02 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6479010279 6479010279-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@3.126.238.147

2023-10-12 05:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 05:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 06:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-12 07:32 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6492263728 6492263728-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.110.34

2023-10-12 07:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 07:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-12 07:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-12 09:02 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6492733021 6492733021-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.113.79

2023-10-12 09:02 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6492733412 6492733412-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@18.192.167.128

2023-10-12 09:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 09:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 09:19 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6492733021 6492733021-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.113.79

2023-10-12 09:19 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6492733412 6492733412-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@18.192.167.128

2023-10-12 09:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 09:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 10:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-12 13:00 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6494179760 6494179760-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.32.141

2023-10-12 13:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-12 13:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-12 16:43 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6496604256 6496604256-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@51.250.76.161

2023-10-12 16:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-13 14:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-13 15:38 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6509237993 6509237993-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.127.182

2023-10-13 15:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-13 17:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-13 20:11 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6511224288 6511224288-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.125.170

2023-10-13 20:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-16 20:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-16 21:36 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6538744984 6538744984-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@62.84.116.77

2023-10-16 21:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-17 06:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-17 13:29 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6543636853 6543636853-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.99.63

2023-10-17 13:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-18 21:04 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6562292305 6562292305-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@51.250.69.25

2023-10-18 21:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-19 06:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-19 08:08 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6570534450 6570534450-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.98.67

2023-10-19 08:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-19 08:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-19 11:06 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6571892756 6571892756-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.116.18

2023-10-19 11:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-19 11:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-19 19:55 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6574116079 6574116079-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@84.252.128.50

2023-10-19 19:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-20 06:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-20 08:38 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6584227351 6584227351-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@62.84.114.156

2023-10-20 08:39 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-20 08:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-20 14:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-20 14:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-20 16:48 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6589364213 6589364213-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@3.67.112.17

2023-10-20 16:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-23 13:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-23 14:51 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6613698274 6613698274-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@18.197.180.197

2023-10-23 14:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-23 16:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-23 20:21 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6455279377 6455279377-1-con-1-25 /sys/deckhouse-oss/install:pr6073 user@34.159.182.170

2023-10-23 20:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-24 06:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-24 08:40 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6623164184 6623164184-1-con-1-25 /sys/deckhouse-oss/install:pr6073 user@35.246.148.182

2023-10-24 10:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-24 10:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-24 10:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-24 13:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-24 13:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-24 19:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-24 20:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-24 20:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-24 20:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-25 03:46 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6615257489 6615257489-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@18.157.154.105

2023-10-25 03:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-25 14:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-25 14:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-26 07:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-26 10:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-26 10:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-26 10:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-26 10:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-26 10:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-26 10:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-26 19:42 UTC, RomanenkoDenys commented
impact in description should be csi-plugin and ... should be restarted

2023-10-27 15:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-27 15:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-27 15:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-27 15:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-27 17:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-10-27 18:18 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6669401035 6669401035-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.32.83

2023-10-27 18:18 UTC, universal-itengineer commented
/e2e/abort azure;Standard;containerd;1.25 6669401122 6669401122-1-con-1-25 /sys/deckhouse-oss/install:pr6073 azureuser@98.71.132.13

2023-10-27 18:18 UTC, universal-itengineer commented
/e2e/abort openstack;Standard;containerd;1.25 6669401218 6669401218-1-con-1-25 /sys/deckhouse-oss/install:pr6073 debian@5.159.102.190

2023-10-27 18:18 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6669401757 6669401757-1-con-1-25 /sys/deckhouse-oss/install:pr6073 centos@3.78.119.44

2023-10-27 18:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-27 18:19 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6669403568 6669403568-1-con-1-25 /sys/deckhouse-oss/install:pr6073 user@35.198.107.174

2023-10-27 18:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-27 18:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-27 18:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-27 18:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-27 19:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-27 20:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-27 21:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-27 21:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-27 21:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-10-27 22:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-28 06:25 UTC, universal-itengineer commented
/e2e/abort vsphere;Standard;containerd;1.25 6672619550 6672619550-1-con-1-25 /sys/deckhouse-oss/install:pr6073 ubuntu@10.220.203.41

2023-10-28 06:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-30 10:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-30 12:09 UTC, universal-itengineer commented
/e2e/abort vsphere;Standard;containerd;1.25 6691661792 6691661792-1-con-1-25 /sys/deckhouse-oss/install:pr6073 ubuntu@10.220.203.41

2023-10-30 12:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-10-30 12:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-30 12:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-10-30 12:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-30 12:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-30 12:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-10-30 12:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-02 13:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-02 15:56 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6733464299 6733464299-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@84.201.131.210

2023-11-02 15:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-02 16:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-02 18:23 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 6735483052 6735483052-1-con-1-25 /sys/deckhouse-oss/install:pr6073 cloud-user@158.160.122.12

2023-11-02 18:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-02 18:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-03 19:40 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-07 07:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-07 07:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-07 07:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-07 07:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-07 07:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-07 07:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-07 10:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-07 10:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-07 11:05 UTC, RomanenkoDenys commented on ee/modules/030-cloud-provider-openstack/images/cinder-csi-plugin/werf.inc.yaml
> +      xfsprogs
Why we need xfsprogs,e2fsprogs,util-linux,mount here ?

2023-11-07 11:06 UTC, RomanenkoDenys commented on ee/modules/030-cloud-provider-openstack/images/cinder-csi-plugin/werf.inc.yaml
> +  - git clone https://github.com/kubernetes/cloud-provider-openstack.git {{ $csiBuildPath }}
We use git clone --depth=1 and SOURCE_REPO

2023-11-07 11:07 UTC, RomanenkoDenys commented on ee/modules/030-cloud-provider-vsphere/images/vsphere-csi-plugin-legacy/werf.inc.yaml
> +  - git clone --depth 1 --branch v0.2.1 https://github.com/flant/cloud-provider-vsphere.git /src
SOURCE_REPO

2023-11-07 11:14 UTC, RomanenkoDenys commented on ee/modules/030-cloud-provider-vsphere/images/vsphere-csi-plugin-legacy/werf.inc.yaml
> +  - wget https://github.com/flant/vsphere-csi-driver/archive/6189afc2522d83a96d3857110c61478710110347.tar.gz -O - | tar -xz --strip-components=1 -C .
use git clone here

2023-11-07 11:20 UTC, RomanenkoDenys commented on modules/000-common/images/alt/werf.inc.yaml
> +{{ $csiBINARYES := "/bin/chmod /bin/mount /bin/mkdir /bin/rmdir /bin/umount /bin/findmnt /bin/lsblk /sbin/badblocks /sbin/blockdev /sbin/blk* /sbin/btrfs* /sbin/dumpe2fs /sbin/e2* /sbin/findfs /sbin/
csiBinaries

2023-11-08 06:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-08 06:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-08 06:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-08 06:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-08 06:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-08 06:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-08 07:06 UTC, universal-itengineer commented
/e2e/abort vsphere;Standard;containerd;1.25 6794481282 6794481282-1-con-1-25 /sys/deckhouse-oss/install:pr6073 ubuntu@10.220.203.155

2023-11-08 07:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-08 07:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-08 10:35 UTC, universal-itengineer commented
/e2e/abort vsphere;Standard;containerd;1.25 6795150005 6795150005-4-con-1-25 /sys/deckhouse-oss/install:pr6073 ubuntu@10.220.203.172

2023-11-08 10:37 UTC, universal-itengineer commented
/e2e/abort vsphere;Standard;containerd;1.25 6795150005 6795150005-3-con-1-25 /sys/deckhouse-oss/install:pr6073 ubuntu@10.220.203.163

2023-11-08 10:38 UTC, universal-itengineer commented
/e2e/abort vsphere;Standard;containerd;1.25 6795150005 6795150005-2-con-1-25 /sys/deckhouse-oss/install:pr6073 ubuntu@10.220.203.162

2023-11-08 10:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-08 10:38 UTC, universal-itengineer commented
/e2e/abort vsphere;Standard;containerd;1.25 6795150005 6795150005-1-con-1-25 /sys/deckhouse-oss/install:pr6073 ubuntu@10.220.203.155

2023-11-08 10:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-08 10:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-08 10:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-08 11:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-08 12:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-08 13:14 UTC, RomanenkoDenys commented on modules/000-common/images/alt/binary_replace.sh
> +function get_binnary_path () {
```suggestion
function get_binary_path () {
```

2023-11-08 13:14 UTC, RomanenkoDenys commented on modules/000-common/images/alt/binary_replace.sh
> +  get_binnary_path ${BIN_TEMPLATE}
```suggestion
  get_binary_path ${BIN_TEMPLATE}
```

2023-11-08 13:14 UTC, RomanenkoDenys commented on modules/000-common/images/alt/binary_replace.sh
> +  get_binnary_path ${TEMPLATE_BINS}
```suggestion
  get_binary_path ${TEMPLATE_BINS}
```

2023-11-08 13:16 UTC, RomanenkoDenys requested changes
LGTM

2023-11-08 13:31 UTC, RomanenkoDenys approved these changes
LGTM

2023-11-08 14:21 UTC, name212 approved these changes

2023-11-08 15:14 UTC, merged