[metallb] Distroless
deckhouse/deckhouse pull request #6125
Opened 2023-10-10 10:09 UTC by vitaliy-sn

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-10-11 14:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-12 18:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-15 19:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-16 14:45 UTC, RomanenkoDenys commented on ee/modules/380-metallb/images/controller/werf.inc.yaml
> +    - git clone --depth 1 -b v0.13.11 https://github.com/metallb/metallb.git .
SOURCE_REPO and GOPROXY

2023-10-16 14:45 UTC, RomanenkoDenys commented on ee/modules/380-metallb/images/speaker/werf.inc.yaml
> +    - git clone --depth 1 -b v0.13.11 https://github.com/metallb/metallb.git .
same

2023-10-16 14:46 UTC, RomanenkoDenys requested changes
aslo i think we should use one artifact to build all binaries

2023-10-17 14:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-17 15:17 UTC, vitaliy-sn commented on ee/modules/380-metallb/images/speaker/werf.inc.yaml
> +    - git clone --depth 1 -b v0.13.11 https://github.com/metallb/metallb.git .
done

2023-10-17 15:17 UTC, vitaliy-sn commented on ee/modules/380-metallb/images/controller/werf.inc.yaml
> +    - git clone --depth 1 -b v0.13.11 https://github.com/metallb/metallb.git .
done

2023-10-18 07:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-18 11:00 UTC, name212 approved these changes

2023-10-19 06:56 UTC, RomanenkoDenys approved these changes
LGTM

2023-10-19 09:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-19 09:59 UTC, apolovov approved these changes

2023-10-19 09:59 UTC, merged