[podreloader] distroless
deckhouse/deckhouse pull request #6126
Opened 2023-10-10 10:41 UTC by vitaliy-sn

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-10-11 13:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-12 07:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-13 06:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-16 14:40 UTC, RomanenkoDenys commented on modules/465-pod-reloader/images/pod-reloader/werf.inc.yaml
> +    - git clone --depth 1 -b v1.0.42 https://github.com/stakater/Reloader.git .
SOURCE_REPO please

2023-10-16 14:40 UTC, RomanenkoDenys commented on modules/465-pod-reloader/images/pod-reloader/werf.inc.yaml
> +    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o /reloader main.go
GOPROXY needed

2023-10-16 14:41 UTC, RomanenkoDenys requested changes
some nits

2023-10-17 14:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-17 15:17 UTC, vitaliy-sn commented on modules/465-pod-reloader/images/pod-reloader/werf.inc.yaml
> +    - git clone --depth 1 -b v1.0.42 https://github.com/stakater/Reloader.git .
done

2023-10-18 10:59 UTC, name212 approved these changes

2023-10-19 06:48 UTC, RomanenkoDenys approved these changes
LGTM

2023-10-19 06:49 UTC, merged