[ci] Build pipeline optimizing
deckhouse/deckhouse pull request #616
Opened 2022-01-18 20:08 UTC by apolovov

## Description
Build optimization for ci pipeline.

## Why do we need it, and what problem does it solve?
No one loves wasting his life watching the black screen with jumping symbols. We are no exception.

## Changelog entries

```changes
module: <kebab-case>
type: fix | feature
description: <what effectively changes>
note: <what to expect>
```

2022-02-10 23:08 UTC, apolovov commented
Optimization needed:
https://github.com/deckhouse/deckhouse/pull/616/files#diff-7e9daa94d6bf20cc7735c2e8d0e0f23503bbf180fa4d06b078ce821840acebd6R56

2022-02-11 17:37 UTC, diafour requested changes
Looks good. I have only minor concerns.

2022-02-11 17:37 UTC, diafour commented on werf.yaml
> +  {{- range $ImageYamlMainfest := (include "module_image_template" $ctx | splitList "---\n") }}
"---\n" is not a safe separator for the split. Imagine someone decides to embed an SSL certificate in the image. "^---\n" is safer, but we can't use it here. So just a note.

2022-02-11 17:37 UTC, diafour commented on werf.yaml
> +          {($moduleName): {($imageName): $tag}}
```suggestion
          $i | ltrimstr("MODULES_IMAGES_TAGS_") | sub("=";"_") |
          split("_") as [$moduleName, $imageName, $tag] |
          {($moduleName): {($imageName): $tag}}
```

WDYT?

2022-02-11 17:40 UTC, diafour commented
One more thought: we should change Gitlab configuration. At least everything related to .gitlab-ci-simple.yml

2022-02-17 06:54 UTC, diafour requested changes

2022-02-17 06:54 UTC, diafour commented on .github/ci_templates/build.yml
> +          docker image rmi ${DESTINATION_RELEASE_CHANNEL_VERSION_IMAGE} || truea
```suggestion
          docker image rmi ${DESTINATION_RELEASE_CHANNEL_VERSION_IMAGE} || true
```

2022-02-18 07:37 UTC, nabokihms approved these changes

2022-02-18 07:38 UTC, merged