[dhctl] Deckhouse registry mirroring
deckhouse/deckhouse pull request #6257
Opened 2023-10-19 16:14 UTC by mvasl

## Description
Added `mirror` subcommand for dhctl, that allows to copy a particular set of Deckhouse releases to a local filesystem and then push that copy to some third-party registry. 

This subcommand does not support copying of Community Edition images.

Example of copying current Deckhouse-release channels images to local filesystem mounted into `/d8-images`:

```bash
dhctl mirror -l "license-token" -i /d8-images
```

Or, to copy Deckhouse images starting from release 1.49 to local filesystem mounted into `/d8-images`.
```bash
dhctl mirror --license="license-token" --min-version="1.49" --images=/d8-images
```

To copy downloaded images into third-party registry:

```bash
dhctl mirror --images="/d8-images" --registry="registry.infra.int:5000" --registry-login="user" --registry-password="pass" 
```

Or in short flags

```bash
dhctl mirror -i "/d8-images" -r "registry.infra.int:5000" -u "user" -p "pass"
```

See `dhctl help mirror` for more information on flags:
```
usage: dhctl mirror --images="PATH" [<flags>]

Copy Deckhouse images from Deckhouse registry to local filesystem and to third-party registry

Flags:
  -h, --help                     Show context-sensitive help (also try --help-long and --help-man).
      --logger-type=pretty       Format logs output of a dhctl in different ways. ($DHCTL_CLI_LOGGER_TYPE)
      --tmp-dir="/var/folders/c0/rprsq8c55kb0c__gchv8fmz80000gn/T/dhctl"  
                                 Set temporary directory for debug purposes. ($DHCTL_CLI_TMP_DIR)
      --version                  Show application version.
  -l, --license=LICENSE          Pull Deckhouse images to local machine using license key. Conflicts with --registry. ($DHCTL_CLI_MIRROR_LICENSE)
  -r, --registry=REGISTRY        Push Deckhouse images to your private registry, specified as registry-host[:port]. Conflicts with --license. ($DHCTL_CLI_MIRROR_PRIVATE_REGISTRY)
  -u, --registry-login=REGISTRY-LOGIN  
                                 Username to log into your registry. ($DHCTL_CLI_MIRROR_USER)
  -p, --registry-password=REGISTRY-PASSWORD  
                                 Password to log into your registry. ($DHCTL_CLI_MIRROR_PASS)
      --fe                       Copy Flant Edition images instead of Enterprise Edition. ($DHCTL_CLI_MIRROR_FE)
  -v, --min-version=MIN-VERSION  Minimal Deckhouse release to copy. Cannot be above current Rock Solid release. ($DHCTL_CLI_MIRROR_MIN_VERSION)
  -i, --images                   Directory for pulled images. ($DHCTL_CLI_MIRROR_IMAGES_PATH)
      --insecure                 Skip TLS checks.

```

## Why do we need it, and what problem does it solve?

This is supposed to replace `d8-pull.sh`/`d8-push.sh` method of installation in air-gapped enviroments

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: feature
summary: Implemented copying of Deckhouse images to third-party registries for air-gapped installation.
impact_level: default
```

2023-10-24 16:21 UTC, name212 commented on dhctl/cmd/dhctl/commands/mirror.go
we need to build deckhouse miror only ee and ce version 
like here https://github.com/deckhouse/deckhouse/pull/5131/files#diff-0fc921a8a3ad48eda2e4f217e64da1aceb58a432cd125dd933cb257c02b8bbcbR1

2023-10-24 16:24 UTC, name212 commented on dhctl/cmd/dhctl/commands/mirror.go
> +	cmd := parent.Command("mirror", "Copy Deckhouse registry for air-gaped installation.")
```suggestion
	cmd := parent.Command("mirror", "Copy Deckhouse images from Deckhouse registry to local file system")
```

2023-10-24 16:24 UTC, name212 commented on dhctl/cmd/dhctl/commands/mirror.go
> +			return log.Process("mirror", "Push mirrored Deckhouse Registry images to private registry", func() error {
```suggestion
			return log.Process("mirror", "Push mirrored Deckhouse images from local file system to private registry", func() error {
```

2023-10-24 16:29 UTC, name212 commented on dhctl/pkg/operations/mirror.go
> +	// "github.com/google/go-containerregistry/pkg/v1"
dead code
```suggestion
```

2023-10-24 16:42 UTC, name212 commented on dhctl/pkg/operations/mirror/validate.go
> +const (
duplicated with it. Need to keep only one source of true 
https://github.com/deckhouse/deckhouse/pull/6257/files#diff-0596f6ae70c0bb6f7ee4ecb270c0d20ab22e959a76cf213b4dd0b2f25409d889R34

2023-10-24 16:47 UTC, name212 commented on dhctl/pkg/operations/mirror/index.go
> +	"github.com/deckhouse/deckhouse/dhctl/pkg/util/maputil"
sort imports

2023-10-25 08:17 UTC, RomanenkoDenys commented on dhctl/cmd/dhctl/commands/mirror.go
> +	cmd := parent.Command("mirror", "Copy Deckhouse images from Deckhouse registry to local filesystem")
```suggestion
	cmd := parent.Command("mirror", "Copy Deckhouse images from Deckhouse registry to local filesystem and back to third-party registry")
```

2023-10-25 08:19 UTC, RomanenkoDenys commented on dhctl/cmd/dhctl/commands/mirror.go
> +		return log.Process("mirror", "Pull Deckhouse to local filesystem", func() error {
```suggestion
		return log.Process("mirror", "Pull Deckhouse images from registry to local filesystem", func() error {
```

2023-10-25 08:24 UTC, RomanenkoDenys commented on dhctl/pkg/app/mirror.go
> +				"Leave only --registry if you already pulled Deckhouse and want to push it to your private registry.")
```suggestion
				"Leave only --license if you want to pull Deckhouse images from public registry.\n" +
				"Leave only --registry if you already pulled Deckhouse images and want to push it to your private registry.")
```

2023-10-25 08:37 UTC, RomanenkoDenys commented on dhctl/pkg/operations/mirror/index.go
> +		&layouts.ReleaseChannel: filepath.Join(rootFolder, registryRepo+"/release-channel"),
```suggestion
		&layouts.Install:        filepath.Join(rootFolder, registryRepo, "/install"),
		&layouts.ReleaseChannel: filepath.Join(rootFolder, registryRepo, "/release-channel"),
```

2023-10-25 08:38 UTC, RomanenkoDenys commented on dhctl/pkg/operations/mirror/index.go
> +		path := filepath.Join(rootFolder, registryRepo+"/modules/"+module.Name)
```suggestion
		path := filepath.Join(rootFolder, registryRepo, "modules", module.Name)
```

2023-10-25 08:39 UTC, RomanenkoDenys commented on dhctl/pkg/operations/mirror/index.go
> +		path = filepath.Join(rootFolder, registryRepo+"/modules/"+module.Name+"/release")
```suggestion
		path = filepath.Join(rootFolder, registryRepo, "modules", module.Name, "release")
```

2023-10-25 08:42 UTC, RomanenkoDenys commented on dhctl/pkg/operations/mirror/index.go
> +	layouts.DeckhouseImages = map[string]struct{}{
May be cycle be more convenient

2023-10-25 08:48 UTC, RomanenkoDenys commented on dhctl/pkg/operations/mirror/modules.go
> +		m.Releases, err = crane.ListTags(m.RegistryPath + "/release")
why crane ?

2023-10-25 08:52 UTC, RomanenkoDenys commented on dhctl/pkg/operations/mirror/versions.go
> +	tags, err := crane.ListTags(mirrorCtx.RegistryRepo+"/release-channel", craneOpts...)
why crane ?

2023-10-25 08:54 UTC, RomanenkoDenys requested changes
Some nits

2023-10-25 14:23 UTC, mvasl commented
Docker registry
<img width="1710" alt="Снимок экрана 2023-10-25 в 17 21 39" src="https://github.com/deckhouse/deckhouse/assets/5184586/5323ce68-4564-4527-b35a-bdedc6b0b78d">

2023-10-25 14:59 UTC, mvasl commented
Red Hat Quay 3.9.3
<img width="1242" alt="Снимок экрана 2023-10-25 в 17 57 51" src="https://github.com/deckhouse/deckhouse/assets/5184586/172f1c62-69a8-4aed-b126-074af5f6bde7">
<img width="1376" alt="Снимок экрана 2023-10-25 в 17 57 37" src="https://github.com/deckhouse/deckhouse/assets/5184586/c961aafd-0f56-4eb1-bad5-c3b144aaf5c6">
<img width="1220" alt="Снимок экрана 2023-10-25 в 17 59 02" src="https://github.com/deckhouse/deckhouse/assets/5184586/77129462-7219-4c83-b404-04e84b30979b">

2023-10-25 15:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-26 09:40 UTC, name212 approved these changes

2023-10-26 09:43 UTC, RomanenkoDenys approved these changes
LGTM

2023-10-26 09:43 UTC, merged