[cve] fix: temporary comment Send report job
deckhouse/deckhouse pull request #6352
Opened 2023-10-27 14:26 UTC by universal-itengineer

## Description

Temporary remove "Send report" job
## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: workflows | cve-weekly
type: fix
summary: Temporary remove "Send report" job
impact_level: low

section: workflows_templates | cve-weekly
type: fix
summary: Temporary remove "Send report" job
impact_level: low
```

2023-10-27 17:01 UTC, RomanenkoDenys approved these changes

2023-10-27 17:52 UTC, name212 commented on .github/workflows/cve-weekly.yml
> +  # send-email-report:
I guess that you comment it manually. It is wrong way.
https://github.com/deckhouse/deckhouse/actions/runs/6668585535/job/18126516667?pr=6352

2023-10-27 17:52 UTC, name212 requested changes
render workflow check is not finished
https://github.com/deckhouse/deckhouse/actions/runs/6668585535/job/18126516667?pr=6352

2023-10-30 07:30 UTC, name212 approved these changes

2023-10-30 07:30 UTC, merged