[distroless] aws node-termination-handler to distroless
deckhouse/deckhouse pull request #6376
Opened 2023-10-30 14:18 UTC by universal-itengineer

## Description

- [ ] cloud-provider-aws/node-termination-handler
## Why do we need it, and what problem does it solve?

This PR is a part of moving Deckhouse to distroless.
## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cloud-provider-aws
type: chore
summary: "`node-termination-handler` use distroless based image."
impact: 
impact_level:

section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-10-30 14:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-10-30 15:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-01 11:17 UTC, RomanenkoDenys commented on modules/030-cloud-provider-aws/images/node-termination-handler/werf.inc.yaml
> +  - git clone --depth 1 --branch v1.5.0 https://github.com/aws/aws-node-termination-handler.git /src
We use SOURCE_REPO here

2023-11-01 11:18 UTC, RomanenkoDenys commented on candi/image_versions.yml
> +BASE_ALT: "alt:p10@sha256:f105773c682498700680d7cd61a702a4315c4235aee3622757591fd510fb8b4a"
Why BASE_ALT is needed here ?

2023-11-01 11:18 UTC, RomanenkoDenys requested changes
some comments

2023-11-08 14:35 UTC, universal-itengineer commented
Before sent termination-time
<img width="681" alt="image" src="https://github.com/deckhouse/deckhouse/assets/141920865/e75b29b3-2863-46bc-8cc5-d2f93b2e505e">

Sent termination-time
<img width="835" alt="image" src="https://github.com/deckhouse/deckhouse/assets/141920865/167f7ba2-874f-4ba4-afb6-fad9812801f8">

Node scheduled for disable
<img width="807" alt="image" src="https://github.com/deckhouse/deckhouse/assets/141920865/d95749f3-8b21-4a00-ab40-2662e56b2bb7">

2023-11-08 15:07 UTC, universal-itengineer commented
How to test:

1. Download  helm chart **amazon-ec2-metadata-mosk**  
`curl -L https://github.com/aws/amazon-ec2-metadata-mock/releases/download/v1.11.2/amazon-ec2-metadata-mock-1.11.2.tgz -o amazon-ec2-metadata-mock-1.11.2.tgz`
2. Install helm chart **amazon-ec2-metadata-mosk**  
`helm install amazon-ec2-metadata-mock amazon-ec2-metadata-mock-1.11.2.tgz --namespace d8-cloud-provider-aws`
3. Check that service exist
```
kubectl -n d8-cloud-provider-aws get svc -o wide
```
```
#Output
NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE    SELECTOR
amazon-ec2-metadata-mock-service   ClusterIP   10.222.105.219   <none>        1338/TCP   106s   app.kubernetes.io/instance=amazon-ec2-metadata-mock
```
4. Configure daemonset `node-termination-handler` to get events from ~~aws~~ amazon-ec2-metadata-mock
```
kubectl -n d8-cloud-provider-aws edit daemonset node-termination-handler
```
```yaml
...
spec:
  containers:
    - name: aws-node-termination-handler
...
    env:
      - name: NODE_NAME
        ...
      - name: INSTANCE_METADATA_URL
        value: "http://10.222.105.219:1338" #example of meta instance url
...
```
5. Check service  
```
curl http://10.222.105.219:1338/latest/meta-data
```

```
#Output
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
elastic-inference/
events/
hostname
iam/
instance-action
instance-id
instance-life-cycle
instance-type
kernel-id
local-hostname
local-ipv4
mac
network/
placement/
product-codes
public-hostname
public-ipv4
public-keys/
ramdisk-id
reservation-id
security-groups
services/
spot/
tags/
```
6. For example, send termination-time  
```
curl http://10.222.105.219:1338/latest/meta-data/spot/termination-time
```
```
#Output
2023-11-08T14:10:29Z
```
7. Check that node drain node  
```
kubectl get node
```
```
#Output
NAME                                            STATUS                     ROLES                  AGE   VERSION
distroless-pr6376-master-0                      Ready                      control-plane,master   84m   v1.25.15
distroless-pr6376-worker-dc42b8d2-676c4-8pc5c   Ready,SchedulingDisabled   worker                 76m   v1.25.15
```

2023-11-08 15:31 UTC, name212 approved these changes

2023-11-08 18:18 UTC, merged