Mc dhctl fixes
deckhouse/deckhouse pull request #6382
Opened 2023-10-30 19:39 UTC by name212

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-10-30 19:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-10-30 19:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2023-10-30 19:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-10-31 13:43 UTC, raabdullaev-fl requested changes

2023-10-31 13:43 UTC, raabdullaev-fl commented on dhctl/pkg/config/load.go
> +			return fmt.Errorf("Schema for module config %s wasn't found. Check module name or use resources file for external modules", mc.GetName())
```suggestion
			return fmt.Errorf("Schema for module config %s wasn't found. Check module name or use resources file for modules from sources", mc.GetName())
```

2023-10-31 13:43 UTC, raabdullaev-fl commented on dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
> +		err := template.OnlyExternalModuleConfigsInResources(app.ResourcesPath)
```suggestion
		err := template.OnlyModulesFromSourcesConfigsInResources(app.ResourcesPath)
```

2023-10-31 13:43 UTC, raabdullaev-fl commented on dhctl/pkg/template/resources.go
> +func OnlyExternalModuleConfigsInResources(path string) error {
```suggestion
func OnlyModulesFromSourcesConfigsInResources(path string) error {
```

2023-10-31 13:43 UTC, raabdullaev-fl commented on docs/documentation/pages/installing/README_RU.md
> +  Внимание! Параметр `configOverrides` устарел и будет удален в версии Deckhouse 1.55. Используйте набор [ModuleConfig](../DECKHOUSE_CONFIGURE_RU.md) для установки параметров встроенных модулей Deckh
```suggestion
  Внимание! Параметр `configOverrides` устарел и будет удален. Используйте набор [ModuleConfig](../DECKHOUSE_CONFIGURE_RU.md) для установки параметров встроенных модулей Deckhouse.
```

2023-10-31 13:43 UTC, raabdullaev-fl commented on docs/documentation/pages/installing/README.md
> +  Warning! The `configOverrides` option is deprecated and will be removed in Deckhouse version 1.55. Use the [ModuleConfig](../DECKHOUSE_CONFIGURE.md) to set parameters for built-in Deckhouse modules
```suggestion
  Warning! The `configOverrides` option is deprecated and will be removed. Use the [ModuleConfig](../DECKHOUSE_CONFIGURE.md) to set parameters for built-in Deckhouse modules.
```

2023-10-31 17:50 UTC, z9r5 approved these changes

2023-10-31 19:38 UTC, raabdullaev-fl approved these changes

2023-11-01 07:15 UTC, merged