[candi] wait node before annotate node
deckhouse/deckhouse pull request #6443
Opened 2023-11-07 05:36 UTC by artbin

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-11-07 05:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-07 08:36 UTC, artbin commented
Bootstrap log:
```
===
=== Step: /var/lib/bashible/bundle_steps/099_reboot.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/100_disable-ntp-on-node.sh
===
Removed /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service.
Error from server (NotFound): nodes "akulyabin-main-ubuntu-18-c87545be-dd7f9-x7mrk" not found
Failed to check existence of node akulyabin-main-ubuntu-18-c87545be-dd7f9-x7mrk ... retry in 10 seconds.
```

2023-11-13 18:39 UTC, RomanenkoDenys approved these changes
LGTM

2023-12-04 03:36 UTC, artbin commented
/e2e/abort openstack;Standard;containerd;1.25 7081652941 7081652941-1-con-1-25 /sys/deckhouse-oss/install:pr6443 debian@5.159.103.10

2023-12-04 03:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-12-04 03:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-12-04 03:52 UTC, artbin commented
/e2e/abort openstack;Standard;containerd;1.25 7081709233 7081709233-1-con-1-25 /sys/deckhouse-oss/install:pr6443 debian@185.91.54.3

2023-12-06 09:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @RomanenkoDenys. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-12-06 09:06 UTC, RomanenkoDenys commented on candi/bashible/bashible.sh.tpl
> +  error=$(kubectl_exec get node $(hostname -s) 2>&1 >/dev/null)
kubectl_exec executes only one time.

2023-12-06 09:10 UTC, RomanenkoDenys requested changes
some comments

2023-12-06 11:54 UTC, artbin commented on candi/bashible/bashible.sh.tpl
> +  error=$(kubectl_exec get node $(hostname -s) 2>&1 >/dev/null)
fixed

2023-12-06 12:10 UTC, RomanenkoDenys approved these changes

2023-12-26 10:17 UTC, RomanenkoDenys approved these changes
LGTM

2024-01-10 16:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-01-10 16:54 UTC, name212 commented
/e2e/abort aws;WithoutNAT;containerd;1.25 7478011868 7478011868-1-con-1-25 /sys/deckhouse-oss/install:pr6443 centos@18.194.132.209

2024-01-10 16:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-01-11 05:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-01-11 09:21 UTC, name212 approved these changes

2024-01-11 09:22 UTC, merged