[distroless] Distroless cni simple bridge
deckhouse/deckhouse pull request #6469
Opened 2023-11-08 12:50 UTC by universal-itengineer

## Description

- [x] cni-simple-bridge/simple-bridge

## Why do we need it, and what problem does it solve?

This PR is a part of moving Deckhouse to distroless.
## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-simple-bridge
type: chore
summary:  "`simple-bridge`" use distroless based image.
impact: "`simple-bridge` pods will restart; affected clouds AWS,Azure,GCP,Yandex-Cloud."
impact_level: default
```

2023-11-09 08:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-09 08:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-09 09:49 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6809225980 6809225980-1-con-1-25 /sys/deckhouse-oss/install:pr6469 user@34.159.211.87

2023-11-09 09:50 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 6809226144 6809226144-1-con-1-25 /sys/deckhouse-oss/install:pr6469 centos@3.124.239.249

2023-11-09 09:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-09 09:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-09 09:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-09 09:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-09 09:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-09 09:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-09 11:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-09 11:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-09 12:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-09 12:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-09 12:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-09 12:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-09 16:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-09 16:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-09 16:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-09 16:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-09 16:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-10 11:56 UTC, RomanenkoDenys commented on modules/035-cni-simple-bridge/images/simple-bridge/werf.inc.yaml
> +{{ $csiBinaries := "/bin/awk /bin/chmod /bin/cat /bin/rm /bin/ln /usr/sbin/update-alternatives /bin/true /bin/echo /usr/bin/tee /bin/sleep /bin/hostname /usr/bin/python3 /usr/bin/curl /usr/bin/jq /bi
why we need curl and chmod and tee and update-alternatives and so on ?

2023-11-10 11:57 UTC, RomanenkoDenys commented on modules/035-cni-simple-bridge/images/simple-bridge/werf.inc.yaml
> +  ENTRYPOINT: ["/iptables-wrapper-installer.sh"]
Please use common/iptables-wrapper

2023-11-10 11:57 UTC, RomanenkoDenys requested changes
some questions

2023-11-10 15:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-13 07:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-13 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-13 13:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-13 14:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-13 15:20 UTC, universal-itengineer commented
![image](https://github.com/deckhouse/deckhouse/assets/141920865/78439f45-b6e9-4808-b91d-d763b6547a1a)

2023-11-14 09:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-14 09:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-14 09:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-14 09:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-14 10:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-14 11:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-14 16:31 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6864106182 6864106182-1-con-1-25 /sys/deckhouse-oss/install:pr6469 user@34.159.60.141

2023-11-14 16:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->
  :fast_forward: `e2e destroy failed: GCP, Containerd, Kubernetes 1.25` for `refs/heads/main` [started](https://github.com/deckhouse/deckhouse/actions/runs/6866615106).

2023-11-14 16:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->
  :fast_forward: `e2e: Yandex.Cloud, Containerd, Kubernetes 1.25` for `deckhouse:distroless-cni-simple-bridge` [started](https://github.com/deckhouse/deckhouse/actions/runs/6866619993).


Yandex.Cloud-WithoutNAT-Containerd-1.25 - Connection string: `ssh  cloud-user@51.250.9.230`

2023-11-14 19:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-14 19:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-14 22:28 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 6868580179 6868580179-1-con-1-25 /sys/deckhouse-oss/install:pr6469 user@34.89.204.162

2023-11-14 22:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-15 06:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-15 07:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-15 07:32 UTC, universal-itengineer commented
<img width="702" alt="image" src="https://github.com/deckhouse/deckhouse/assets/141920865/e7ea7af6-64ca-4484-bd6e-fb6c4810ce7b">

2023-11-15 07:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-15 07:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-20 11:48 UTC, RomanenkoDenys approved these changes

2023-11-28 08:24 UTC, aleksey-su approved these changes

2023-11-28 08:36 UTC, merged