[terraform-manager] Distroless build
deckhouse/deckhouse pull request #6639
Opened 2023-11-23 13:05 UTC by mvasl

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-11-23 14:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-23 14:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-23 14:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-23 14:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-23 14:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-23 14:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-23 14:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-23 14:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-23 14:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-24 13:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-11-24 13:50 UTC, RomanenkoDenys approved these changes
LGTM

2023-11-27 16:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-27 16:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-27 16:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-27 16:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-27 16:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-27 20:18 UTC, deckhouse-BOaTswain commented
:green_circle: `e2e destroy failed: Yandex.Cloud` for `refs/heads/main` [succeeded](https://github.com/deckhouse/deckhouse/actions/runs/7010090469) in 47s.
<details><summary>Workflow details</summary>


:green_circle: `e2e destroy failed: Yandex.Cloud, Containerd, Kubernetes 1.25` succeeded in 22s.<!-- result-for: e2e destroy failed: Yandex.Cloud, Containerd, Kubernetes 1.25 -->

</details>

2023-11-28 08:09 UTC, mvasl commented
/e2e/abort azure;Standard;containerd;1.25 7007879024 7007879024-1-con-1-25 /sys/deckhouse-oss/install:pr6639

2023-11-28 08:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-28 10:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-28 11:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-28 11:24 UTC, mvasl commented
/e2e/abort azure;Standard;containerd;1.25 7018019898 7018019898-1-con-1-25 /sys/deckhouse-oss/install:pr6639

2023-11-28 11:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-28 11:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-28 12:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-28 12:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-28 12:07 UTC, mvasl commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7018444937 7018444937-1-con-1-25 /sys/deckhouse-oss/install:pr6639

2023-11-28 14:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-28 17:30 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2023-11-28 17:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-28 17:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-29 18:59 UTC, RomanenkoDenys commented on modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
> +    PATH: "/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root:/"
```suggestion
    PATH: "/root:/"
```

2023-11-29 18:59 UTC, RomanenkoDenys requested changes
some nits

2023-11-30 12:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2023-11-30 12:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-30 12:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-11-30 12:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-30 12:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-11-30 13:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-11-30 13:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2023-11-30 14:19 UTC, mvasl commented
<img width="1340" alt="Снимок экрана 2023-11-30 в 17 17 31" src="https://github.com/deckhouse/deckhouse/assets/5184586/771d6b5f-b928-4d89-a21d-505e839c7392">

2023-11-30 14:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2023-12-02 18:39 UTC, merged