[prometheus] distroless prometheus
deckhouse/deckhouse pull request #6644
Opened 2023-11-23 15:08 UTC by aleksey-su

## Description

Prometheus are now based on minimal image.

## Why do we need it, and what problem does it solve?

We'd like to base our images on a distroless image.

## What is the expected result?

We use scratch along with a minimal number of files from Alpine packages. We pass files in packages though an rsync whitelist.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: prometheus
type: feature
summary: Images are based on a distroless image.
impact_level: default
```

2023-11-24 13:15 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/f713f229-4fbf-4f20-a732-7e5ecad309c8)
![image](https://github.com/deckhouse/deckhouse/assets/485892/e5db21fb-9eae-49ef-81be-87b597c49e10)

2023-11-24 13:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2023-11-24 14:14 UTC, RomanenkoDenys commented on modules/300-prometheus/images/prometheus/werf.inc.yaml
> +    && NODE_MAJOR=20 \
```suggestion
    - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/nodesource.gpg
    - export NODE_MAJOR=20
```

2023-11-24 14:14 UTC, RomanenkoDenys requested changes
Please do not use &&

2023-11-24 19:05 UTC, RomanenkoDenys approved these changes
LGTM

2023-11-27 08:09 UTC, name212 approved these changes

2023-11-30 07:17 UTC, merged