[cni-cilium] add RBAC for ciliumnetworkpolicies
deckhouse/deckhouse pull request #6813
Opened 2023-12-07 16:22 UTC by AndreyPavlovFlant

## Description

Grant users access to view and edit `ciliumnetworkpolicies` based on `user-authz` roles

## Why do we need it, and what problem does it solve?

Currently, users created and configured with `user-authz` and `user-authn` do not have access to view and edit `ciliumnetworkpolicies`.

## What is the expected result?

Users created and configured with `user-authz` and `user-authn` will have access to view and edit `ciliumnetworkpolicies`.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: chore
summary: Add user-authz RBACs for `ciliumnetworkpolicies`.
```

2023-12-13 10:14 UTC, apolovov commented on modules/021-cni-cilium/templates/user-authz-cluster-roles.yaml
> +  - update
```suggestion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    user-authz.deckhouse.io/access-level: User
  name: d8:user-authz:cni-cilium:privileged-user
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
rules:
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    user-authz.deckhouse.io/access-level: Editor
  name: d8:user-authz:cni-cilium:editor
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
rules:
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    user-authz.deckhouse.io/access-level: ClusterAdmin
  name: d8:user-authz:cni-cilium:cluster-editor
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
rules:
- apiGroups:
  - cilium.io
  resources:
  - ciliumclusterwidenetworkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
```

2023-12-13 10:15 UTC, apolovov approved these changes

2023-12-25 07:37 UTC, RomanenkoDenys requested changes
Please fix all tests

2023-12-26 09:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-12-26 11:46 UTC, AndreyPavlovFlant commented
/e2e/abort static;Static;containerd;1.25 7328544581 7328544581-2-con-1-25 /sys/deckhouse-oss/install:pr6813 astra@192.168.199.234

2023-12-26 11:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-12-26 11:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-12-26 12:41 UTC, AndreyPavlovFlant commented
/e2e/abort static;Static;containerd;1.25 7329254697 7329254697-1-con-1-25 /sys/deckhouse-oss/install:pr6813 astra@192.168.199.61

2023-12-26 12:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-12-26 12:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2023-12-26 13:51 UTC, AndreyPavlovFlant commented
/e2e/abort static;Static;containerd;1.25 7329637727 7329637727-2-con-1-25 /sys/deckhouse-oss/install:pr6813 astra@192.168.199.10

2023-12-26 13:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-12-26 13:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2023-12-27 07:53 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.25 7329637727 7329637727-1-con-1-25 /sys/deckhouse-oss/install:pr6813 astra@192.168.199.10

2023-12-27 07:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2023-12-27 17:54 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.25 7329637727 7329637727-1-con-1-25 /sys/deckhouse-oss/install:pr6813 astra@192.168.199.10

2023-12-27 17:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-01-17 10:24 UTC, RomanenkoDenys approved these changes
LGTM

2024-01-18 13:43 UTC, nabokihms approved these changes

2024-01-18 13:43 UTC, merged