add metrics and alert for deprecated scrape config method
deckhouse/deckhouse pull request #6912
Opened 2023-12-18 06:56 UTC by sh1kel

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-12-20 13:08 UTC, z9r5 commented on modules/300-prometheus/docs/FAQ_RU.md
> +## Как добавить дополнительные эндпойнты в scrape config
```suggestion
## Как добавить дополнительные эндпойнты в scrape config?
```

2023-12-20 13:09 UTC, z9r5 commented on modules/300-prometheus/docs/FAQ.md
> +## How to add additional endpoints to scrape config. New way with CRD
```suggestion
## How do I add additional endpoints to scrape config?
```

2023-12-20 13:09 UTC, z9r5 approved these changes

2023-12-25 14:03 UTC, yalosev commented on modules/300-prometheus/docs/FAQ_RU.md
> +## Как добавить дополнительные эндпойнты в scrape config?
```suggestion
## Как добавить дополнительные эндпоинты в scrape config?
```

2023-12-25 14:04 UTC, yalosev commented on modules/300-prometheus/monitoring/prometheus-rules/deprecation.yaml
> +          Old way for describing additional scrape config via secrets will be deprecated in prometheus-operator > v0.65.1. Please use CRD instead.
```suggestion
          Old way for describing additional scrape config via secrets will be deprecated in prometheus-operator > v0.65.1. Please use CRD ScrapeConfig instead.
```

2023-12-25 14:05 UTC, yalosev approved these changes

2023-12-25 15:06 UTC, yalosev requested changes
Some problems here. It's not rendering

2023-12-27 12:09 UTC, yalosev commented on modules/300-prometheus/templates/prometheus/prometheus.yaml
> +  scrapeConfigSelector: {}
ns `d8-monitoring` and label `additional-configs-for-prometheus=main`
same as secrets

2023-12-28 07:05 UTC, yalosev commented on modules/300-prometheus/docs/FAQ.md
> +  namespace: example-ns
```suggestion
  namespace: d8-monitoring
```

2023-12-28 07:05 UTC, yalosev commented on modules/300-prometheus/docs/FAQ_RU.md
> +  namespace: example-ns
```suggestion
  namespace: d8-monitoring
```

2023-12-28 07:05 UTC, yalosev commented on modules/300-prometheus/monitoring/prometheus-rules/deprecation.yaml
> +        severity_level: "4"
```suggestion
        severity_level: "8"
```

2023-12-28 07:05 UTC, yalosev commented on modules/300-prometheus/templates/prometheus/prometheus.yaml
> +  scrapeConfigNamespaceSelector: null
```suggestion
  scrapeConfigNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: d8-monitoring
```

2023-12-28 07:29 UTC, yalosev approved these changes

2023-12-28 13:24 UTC, nabokihms approved these changes

2023-12-28 20:07 UTC, merged