[network-gateway] migrate network-gateway module to distroless
deckhouse/deckhouse pull request #6968
Opened 2023-12-21 02:13 UTC by artbin

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-12-26 03:09 UTC, artbin commented
Manual testing
==============

Enable `network-gateway` module:
```bash
kubectl create -f - <<EOF
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: network-gateway
spec:
  settings:
    nodeSelector:
      network-gateway: "true"
    subnet: 10.100.0.6/24
    publicAddress: 9.9.9.9
  enabled: true
  version: 1
EOF
```

Get dhcp pod logs:
```bash
kubectl -n d8-network-gateway logs dhcp-0
```

Output:
```
dnsmasq: started, version 2.89 cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN2 DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-nftset auth cryptohash DNSSEC loop-detect inotify dumpfile
dnsmasq: reading /etc/resolv.conf
dnsmasq: using nameserver 10.222.0.10#53
dnsmasq: read /etc/hosts - 8 names
```

Get snat pod iptables rules:
```bash
kubectl exec -i -t -n d8-network-gateway snat-64w2f -- iptables -w -t nat -n --list D8-NETWORK-GATEWAY-SNAT
```

Output:
```
Chain D8-NETWORK-GATEWAY-SNAT (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            10.222.0.0/16        /* d8_netgw_cfgHash_9402a66bcae6868bd2debe8082af27b1855f31880b0a537be65b55a65bb375a9 */
RETURN     all  --  0.0.0.0/0            10.111.0.0/16        /* d8_netgw_cfgHash_9402a66bcae6868bd2debe8082af27b1855f31880b0a537be65b55a65bb375a9 */
RETURN     all  --  0.0.0.0/0            10.100.0.0/24        /* d8_netgw_cfgHash_9402a66bcae6868bd2debe8082af27b1855f31880b0a537be65b55a65bb375a9 */
RETURN     all  --  0.0.0.0/0            224.0.0.0/4          /* d8_netgw_cfgHash_9402a66bcae6868bd2debe8082af27b1855f31880b0a537be65b55a65bb375a9 */
SNAT       all  --  0.0.0.0/0            0.0.0.0/0            /* d8_netgw_cfgHash_9402a66bcae6868bd2debe8082af27b1855f31880b0a537be65b55a65bb375a9 */ to:9.9.9.9
```

2023-12-26 10:06 UTC, RomanenkoDenys commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
> +shell:
move it to artifact

2023-12-26 10:07 UTC, RomanenkoDenys requested changes
some nits

2024-01-17 10:22 UTC, RomanenkoDenys commented on ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
> +    before: install
Please add this dirs to relocated.

2024-01-17 10:23 UTC, RomanenkoDenys commented on ee/modules/450-network-gateway/images/snat/werf.inc.yaml
> +    before: setup
same

2024-01-17 10:23 UTC, RomanenkoDenys requested changes
some nits

2024-01-17 10:38 UTC, RomanenkoDenys approved these changes

2024-01-17 10:38 UTC, merged