[network-audit-engine] add trusted service accounts
deckhouse/deckhouse pull request #7001
Opened 2023-12-25 04:20 UTC by artbin

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2023-12-26 11:09 UTC, artbin commented
Manual testing
==============

Create service account `account1` in `kube-system` namespace:
```bash
kubectl -n kube-system create sa account1
```

Output:
```
serviceaccount/account1 created
```

Find audit log entry with `account1` service account creation:
```bash
kubectl -n d8-runtime-audit-engine logs runtime-audit-engine-g2ssq | grep account1
```

Output:
```
{"hostname":"akulyabin-main-master-0","output":"10:53:21.803773000: Warning Service account created in kube namespace (user=kubernetes-admin serviceaccount=account1 resource=serviceaccounts ns=kube-system)","priority":"Warning","rule":"ServiceAccount created in a system namespace","source":"k8s_audit","tags":["fstec","rbac_drift"],"time":"2023-12-26T10:53:21.803773000Z", "output_fields": {"evt.time":1703588001803773000,"ka.target.name":"account1","ka.target.namespace":"kube-system","ka.target.resource":"serviceaccounts","ka.user.name":"kubernetes-admin"}}
```

2024-01-16 14:18 UTC, RomanenkoDenys approved these changes

2024-01-16 14:20 UTC, RomanenkoDenys approved these changes

2024-01-18 07:00 UTC, nabokihms requested changes
Could you please elaborate more on how the feature will work with the modules deployed from sources?

2025-03-21 08:42 UTC, closed without merging