[cni-cilium] change dashboard title
deckhouse/deckhouse pull request #7032
Opened 2023-12-26 11:26 UTC by kirill-kashin

## Description

Change dashboard title Cilium v1.12 Agent Metrics to Cilium Agent Metrics

## Why do we need it, and what problem does it solve?

In newer versions of deckhouse using cni-cilium may be confused by the name of the metrics

## Why do we need it in the patch release (if we do)?

## What is the expected result?
The dashboard description will not be misleading about the cilium version

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: cni-cilium
type: fix 
summary: change title
impact_level: low
```

2023-12-28 13:37 UTC, RomanenkoDenys commented on modules/021-cni-cilium/monitoring/grafana-dashboards/kubernetes-cluster/cilium-agent.json
> +  "title": "Cilium Agent Metrics",
The main problem is not naming, we cannot update dashboard when update to cilium 1.14.

2023-12-28 13:37 UTC, RomanenkoDenys requested changes
update dashboard

2024-01-18 13:52 UTC, apolovov approved these changes

2024-01-18 13:57 UTC, RomanenkoDenys approved these changes

2024-01-18 13:58 UTC, merged