[linstor] add validating webhook to disable module
deckhouse/deckhouse pull request #7086
Opened 2024-01-10 11:09 UTC by duckhawk

## Description

Add a validating webhook to prevent the linstor module from being enabled

## Why do we need it, and what problem does it solve?

The linstor module should not be allowed to be enabled because we are moving to sds-drbd module.

## What is the expected result?

It will not be possible to enable the module if it has not been enabled before, alas to change module config.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: linstor
type: chore
summary: Added a validating webhook to prevent the linstor module from being enabled.
impact: The `linstor` module cannot be enabled, but it will continue to work if it was already enabled before the update (users must switch to sds-drbd module ASAP).
impact_level: default
```

2024-01-10 21:19 UTC, apolovov commented on modules/002-deckhouse/webhooks/validating/disable_virtualization_module
> +    fi
```suggestion
    if context::jq -e '.review.request.object.spec.enabled' >/dev/null; then
      cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":false, "message":"moduleconfigs.deckhouse.io \"linstor\" is deprecated, please use sds-drbd module instead (https://deckhouse.io/modules/)." }
EOF
    return 0
    fi
```

2024-01-10 21:20 UTC, apolovov commented on modules/002-deckhouse/webhooks/validating/disable_virtualization_module
> +    if [[ "$linstorModuleEnabled" == "true" ]]; then
```suggestion
    if context::jq -e '.review.request.object.spec.enabled' >/dev/null; then
```

2024-01-10 21:21 UTC, apolovov requested changes
A small optimization.

2024-01-15 09:16 UTC, yalosev approved these changes

2024-01-16 07:16 UTC, apolovov approved these changes

2024-01-16 17:24 UTC, AleksZimin approved these changes

2024-01-17 03:50 UTC, merged