[linstor] Remove module
deckhouse/deckhouse pull request #7091
Opened 2024-01-10 12:24 UTC by duckhawk

## Description

Remove linstor module.

## Why do we need it, and what problem does it solve?

Linstor module removed, so users must switch to sds-drbd module.

## What is the expected result?

Linstor module will be removed.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse-controller
type: chore
summary: Remove linstor module
impact:  Deckhouse update is not possible until users migrate from the Linstor module to sds-drbd.
impact_level: high
```

2024-02-12 16:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-02-13 09:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-02-13 09:55 UTC, z9r5 approved these changes

2024-02-28 09:35 UTC, aleksey-su requested changes
Rebase please

2024-03-04 21:14 UTC, nabokihms approved these changes

2024-03-04 21:15 UTC, merged