[log-shipper] add node labels to logs metadata
deckhouse/deckhouse pull request #7098
Opened 2024-01-10 16:19 UTC by sh1kel

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-01-19 10:23 UTC, nabokihms requested changes

2024-01-19 10:23 UTC, nabokihms commented on modules/460-log-shipper/hooks/internal/vector/source/kubernetes.go
> +			NodeLabels: "node_labels",
Not all node labels should be exposed to logs, only the label with the node group.  The case with the missing label should also be covered.

2024-01-19 10:23 UTC, nabokihms commented on modules/460-log-shipper/hooks/internal/vector/source/kubernetes.go
> +	NodeLabels string `json:"node_labels,omitempty"`
New metadata field should also be added to the doc 
https://deckhouse.io/documentation/v1/modules/460-log-shipper/#kubernetes

2024-01-22 08:17 UTC, nabokihms commented on modules/460-log-shipper/hooks/internal/vrl/cleanup.go
> +	del(.node_labels)
```suggestion
}
del(.node_labels)
```

2024-01-22 08:17 UTC, nabokihms commented on modules/460-log-shipper/hooks/internal/vrl/cleanup.go
> +	del(.node_labels)
The `node_labels` object should always be deleted despite having the `node.deckhouse.io/group` annotation.

2024-01-22 08:18 UTC, nabokihms commented on modules/460-log-shipper/docs/README.md
> +
```suggestion
| Label        | Node spec path                            |
|--------------|-------------------------------------------|
| `node_group` | metadata.labels[].node.deckhouse.io/group |

```

Russian doc should be fixed as well

2024-01-22 12:27 UTC, z9r5 approved these changes

2024-01-27 17:56 UTC, nabokihms approved these changes

2024-01-27 17:58 UTC, nabokihms requested changes
Sorry, realised that tests do not work. Rebase is required.

2024-02-05 09:52 UTC, nabokihms approved these changes

2024-02-05 09:52 UTC, merged