[dhctl] Trim prefix scheme http and https for imagesRepo
deckhouse/deckhouse pull request #7122
Opened 2024-01-11 15:58 UTC by unreturned

## Description
Trim prefix scheme from imagesRepo.
For example, `https://registry.deckhouse.io/deckhouse/ce` -> `registry.deckhouse.io/deckhouse/ce`

## Why do we need it, and what problem does it solve?
Fix https://github.com/deckhouse/deckhouse/issues/7046

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Trim prefix scheme for imagesRepo
impact_level: low
```

2024-01-16 13:55 UTC, RomanenkoDenys requested changes
We do not need to trim prefix, we need the openapi validation

2024-01-16 20:40 UTC, unreturned commented
@RomanenkoDenys Thanks for your reply! Please, look when possible for https://github.com/deckhouse/deckhouse/pull/7169

2024-01-23 10:47 UTC, nabokihms commented
Isn't this PR superseded by the https://github.com/deckhouse/deckhouse/pull/7169?

2024-01-23 11:45 UTC, unreturned commented
@nabokihms Thanks for your reply!
Yep, superseded

2024-01-23 11:45 UTC, closed without merging