[cilium] migrate cilium-hubble images to distroless
deckhouse/deckhouse pull request #7174
Opened 2024-01-17 10:14 UTC by AndreyPavlovFlant

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-01-18 12:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-01-18 14:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-01-18 21:56 UTC, apolovov requested changes
A single fix

2024-01-18 21:56 UTC, apolovov commented on modules/500-cilium-hubble/images/ui-frontend/werf.inc.yaml
> +  before: install
get rid of this file pls

2024-01-19 08:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-01-19 08:58 UTC, AndreyPavlovFlant commented
/e2e/abort static;Static;containerd;1.25 7581139851 7581139851-1-con-1-25 /sys/deckhouse-oss/install:pr7174 astra@192.168.199.109

2024-01-19 08:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-01-19 09:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-01-19 10:40 UTC, AndreyPavlovFlant commented
/e2e/abort static;Static;containerd;1.25 7581607776 7581607776-1-con-1-25 /sys/deckhouse-oss/install:pr7174 astra@192.168.199.162

2024-01-19 10:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-01-19 12:05 UTC, AndreyPavlovFlant commented
/e2e/abort static;Static;containerd;1.25 7583203576 7583203576-1-con-1-25 /sys/deckhouse-oss/install:pr7174 astra@192.168.199.97

2024-01-19 12:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-01-19 13:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-01-19 14:03 UTC, AndreyPavlovFlant commented
/e2e/abort openstack;Standard;containerd;1.25 7584533314 7584533314-1-con-1-25 /sys/deckhouse-oss/install:pr7174 debian@45.12.231.84

2024-01-19 14:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-01-19 14:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-01-22 09:29 UTC, apolovov approved these changes

2024-01-22 09:31 UTC, merged