[prometheus] Bump version of prometheus from v2.44.0 to v2.45.0
deckhouse/deckhouse pull request #7195
Opened 2024-01-18 14:00 UTC by unreturned

## Description
Bump version of prometheus from v2.44.0 to v2.45.0

## Why do we need it, and what problem does it solve?
Fixes https://github.com/deckhouse/deckhouse/issues/7193

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Bump version of `prometheus` from `v2.44.0` to `v2.45.0`.
impact_level: low
```

2024-01-18 17:26 UTC, unreturned commented
<img width="1582" alt="Screenshot 2024-01-18 at 20 20 30" src="https://github.com/deckhouse/deckhouse/assets/742504/fb16a220-b797-4f04-b525-e89c7c1c50e6">

2024-01-19 08:21 UTC, nabokihms requested changes
There is one more piece of code to update Prometheus
https://github.com/deckhouse/deckhouse/blob/e25172c14c1dee4fe00d9e92401450f049aa1979/modules/002-deckhouse/images/webhook-handler/werf.inc.yaml#L11-L20

2024-01-19 08:30 UTC, unreturned commented
@nabokihms Thanks for your review! I changed this peace of code, please, check

2024-01-19 13:23 UTC, nabokihms approved these changes

2024-01-19 13:23 UTC, merged