[node-manager](caps) fix StaticInstance deletion
deckhouse/deckhouse pull request #7244
Opened 2024-01-22 04:29 UTC by artbin

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-01-29 08:08 UTC, name212 approved these changes

2024-01-29 09:26 UTC, RomanenkoDenys commented on modules/040-node-manager/docs/FAQ.md
> +To delete a `StaticInstance` in any state other than `Pending` (`Runnig`, `Cleaning`, `Bootstraping`), you need to:
```suggestion
To delete a `StaticInstance` in any state other than `Pending` (`Running`, `Cleaning`, `Bootstraping`), you need to:
```

2024-01-29 09:27 UTC, RomanenkoDenys commented on modules/040-node-manager/docs/FAQ_RU.md
> +Чтобы удалить `StaticInstance` находящийся в любом состоянии отличном от `Pending` (`Runnig`, `Cleaning`, `Bootstraping`):
```suggestion
Чтобы удалить `StaticInstance` находящийся в любом состоянии отличном от `Pending` (`Running`, `Cleaning`, `Bootstraping`):
```

2024-01-29 09:29 UTC, RomanenkoDenys reviewed
some errors

2024-01-29 13:58 UTC, z9r5 approved these changes

2024-01-29 13:58 UTC, z9r5 commented on modules/040-node-manager/docs/FAQ.md
> +To delete a `StaticInstance` in any state other than `Pending` (`Running`, `Cleaning`, `Bootstraping`), you need to:
```suggestion
To delete a `StaticInstance` in any state other than `Pending` (`Running`, `Cleaning`, `Bootstrapping`), you need to:
```

2024-01-29 13:58 UTC, z9r5 commented on modules/040-node-manager/docs/FAQ_RU.md
> +Чтобы удалить `StaticInstance` находящийся в любом состоянии отличном от `Pending` (`Running`, `Cleaning`, `Bootstraping`):
```suggestion
Чтобы удалить `StaticInstance` находящийся в любом состоянии отличном от `Pending` (`Running`, `Cleaning`, `Bootstrapping`):
```

2024-02-14 06:27 UTC, artbin commented
Manual testing
=============

Add `allow-bootstrap: "false"` label:

<img width="719" alt="Screenshot 2024-02-14 at 14 24 44" src="https://github.com/deckhouse/deckhouse/assets/191757/b554b82a-399f-4aa0-a4fc-0eb4c3db4d17">


Remove `allow-bootstrap: "false"` label:

<img width="719" alt="Screenshot 2024-02-14 at 14 25 06" src="https://github.com/deckhouse/deckhouse/assets/191757/6d9af252-bab5-4aea-b4f5-eb01675741c9">

2024-02-21 17:52 UTC, RomanenkoDenys commented
@artbin, one note from the nabokihms that the label should be in the deckhouse.io group.

2024-02-28 04:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-03-04 14:58 UTC, nabokihms approved these changes

2024-03-04 15:02 UTC, nabokihms requested changes
There is only one suggestion left. Overall, LGTM.

2024-03-04 15:02 UTC, nabokihms commented on modules/040-node-manager/images/caps-controller-manager/src/internal/scope/machine_scope.go
> +	allowBootstrapRequirement, err = labels.NewRequirement("deckhouse.io/allow-bootstrap", selection.NotIn, []string{"false"})
```suggestion
	allowBootstrapRequirement, err = labels.NewRequirement("node.deckhouse.io/allow-bootstrap", selection.NotIn, []string{"false"})
```

2024-03-04 15:02 UTC, nabokihms commented on modules/040-node-manager/images/caps-controller-manager/src/internal/scope/machine_scope.go
>  }
Do we need a unit test for this? Probably no, but it is better to ask 🙂

2024-03-11 12:09 UTC, artbin commented on modules/040-node-manager/docs/FAQ.md
> +1. Add the label `"deckhouse.io/allow-bootstrap": "false"` to the `StaticInstance`.
done

2024-03-11 12:10 UTC, artbin commented on modules/040-node-manager/docs/FAQ_RU.md
> +1. Добавьте лейбл `"deckhouse.io/allow-bootstrap": "false"` в `StaticInstance`.
done

2024-03-11 12:10 UTC, artbin commented on modules/040-node-manager/images/caps-controller-manager/src/internal/scope/machine_scope.go
> +	allowBootstrapRequirement, err = labels.NewRequirement("deckhouse.io/allow-bootstrap", selection.NotIn, []string{"false"})
done

2024-03-11 19:25 UTC, nabokihms approved these changes

2024-03-11 19:26 UTC, merged