[cilium-hubble] build cilium-hubble from src
deckhouse/deckhouse pull request #7305
Opened 2024-01-26 12:10 UTC by AndreyPavlovFlant

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-01-28 14:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-01-28 14:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-01-29 11:49 UTC, AndreyPavlovFlant commented
/e2e/abort openstack;Standard;containerd;1.25 7686413660 7686413660-1-con-1-25 /sys/deckhouse-oss/install:pr7305 debian@5.159.101.99

2024-01-29 11:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-01-30 08:09 UTC, apolovov requested changes

2024-01-30 08:09 UTC, apolovov commented on modules/500-cilium-hubble/images/ui-backend/werf.inc.yaml
> +  add: /tmp/install/backend
/go/src/github.com/cilium/hubble-ui/backend/backend pls

2024-01-30 08:09 UTC, apolovov commented on modules/500-cilium-hubble/images/ui-frontend/werf.inc.yaml
> +from: node:18-alpine3.18@sha256:a315556d82ef54561e54fca7d8ee333382de183d4e56841dcefcd05b55310f46
Push the image to our registry with https://github.com/deckhouse/deckhouse/blob/main/tools/regcopy/main.go.

2024-01-30 15:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @AndreyPavlovFlant. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-01-31 08:52 UTC, apolovov approved these changes

2024-01-31 10:47 UTC, name212 approved these changes

2024-01-31 11:00 UTC, merged