[node-manager] Preventing node removal by autoscaler
deckhouse/deckhouse pull request #7339
Opened 2024-01-31 07:41 UTC by vitaliy-sn

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-02-01 08:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-02-02 11:39 UTC, name212 approved these changes

2024-02-02 11:39 UTC, name212 commented on modules/040-node-manager/hooks/handle_node_templates.go
> +			if nodeObj.Labels["node.deckhouse.io/type"] == "CloudPermanent" || nodeObj.Labels["node.deckhouse.io/type"] == "Static" {
CloudStatic also

2024-02-02 11:39 UTC, name212 requested changes
one thing

2024-02-08 10:31 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/handle_node_templates.go
> +			if nodeObj.Labels["node.deckhouse.io/type"] == "CloudPermanent" || nodeObj.Labels["node.deckhouse.io/type"] == "Static" {
```suggestion
			if set.New("CloudPermanent", "CloudStatic", "Static").Has(nodeObj.Labels["node.deckhouse.io/type"]) {
```

Little deckhouse magic

2024-02-08 10:32 UTC, RomanenkoDenys requested changes
one thing

2024-02-13 08:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-02-13 08:27 UTC, vitaliy-sn commented on modules/040-node-manager/hooks/handle_node_templates.go
> +			if nodeObj.Labels["node.deckhouse.io/type"] == "CloudPermanent" || nodeObj.Labels["node.deckhouse.io/type"] == "Static" {
done

2024-02-13 08:27 UTC, vitaliy-sn commented on modules/040-node-manager/hooks/handle_node_templates.go
> +			if nodeObj.Labels["node.deckhouse.io/type"] == "CloudPermanent" || nodeObj.Labels["node.deckhouse.io/type"] == "Static" {
done

2024-02-15 13:05 UTC, name212 approved these changes

2024-02-19 07:47 UTC, RomanenkoDenys approved these changes

2024-02-19 07:48 UTC, merged