[docks] Warning Istio sidecar-injector work with admission-policy-engine
deckhouse/deckhouse pull request #7398
Opened 2024-02-06 09:32 UTC by kirill-kashin

## Description

In deckhouse version >= 1.55. Istio sidecar-injector container starts only in `Privileged` mode
Described warning messages about this in two places istio and admision-policy-engine modules
## Why do we need it, and what problem does it solve?

When working with istio sidecar-injector, there will be a warning about setting the `Privileged` policy in the admision-policy-engine module or putting a `Privileged` label on the nymspace to reduce the level of policies
Only for deckhopuse version >= 1.55.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: fix 
impact_level:  low
```

2024-02-06 10:05 UTC, z9r5 approved these changes

2024-02-06 10:05 UTC, z9r5 commented on modules/015-admission-policy-engine/docs/README_RU.md
> +В версии Deckhouse >= 1.55. Контейнер `sidecar-injector` Istio запускается только в режиме `Privileged`.
```suggestion
При использовании Deckhouse версии >= 1.55, контейнер `sidecar-injector` Istio запускается только в режиме `Privileged`.
```

2024-02-06 10:05 UTC, z9r5 commented on modules/015-admission-policy-engine/docs/README.md
> +In deckhouse version >= 1.55. Istio sidecar-injector container starts only in `Privileged` mode
```suggestion
When using Deckhouse version >= 1.55, the Istio `sidecar-injector` container runs only in `Privileged` mode.
```

2024-02-06 10:20 UTC, z9r5 commented on modules/110-istio/docs/README_RU.md
> +[admission-policy-engine](https://deckhouse.ru/documentation/v1/modules/015-admission-policy-engine/)
```suggestion
При использовании Deckhouse версии >= 1.55 и включенном модуле [admission-policy-engine](../015-admission-policy-engine/), контейнер `sidecar-injector` Istio запускается только в режиме `Privileged`.
```

2024-02-06 10:21 UTC, z9r5 commented on modules/110-istio/docs/README.md
> +[admission-policy-engine](https://deckhouse.io/documentation/v1/modules/015-admission-policy-engine/)
```suggestion
When using Deckhouse version >= 1.55 and the [admission-policy-engine] module is enabled(../015-admission-policy-engine/), the `sidecar-injector` Istio container runs only in `Privileged` mode.
```

2024-02-06 10:28 UTC, z9r5 commented on modules/110-istio/docs/README.md
> +When using Deckhouse version >= 1.55 and the [admission-policy-engine] module is enabled(../015-admission-policy-engine/), the `sidecar-injector` Istio container runs only in `Privileged` mode.
```suggestion
When using Deckhouse version >= 1.55 and the [admission-policy-engine](../015-admission-policy-engine/) module is enabled, the `sidecar-injector` Istio container runs only in `Privileged` mode.
```

2024-02-12 16:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-02-12 16:22 UTC, z9r5 commented on modules/015-admission-policy-engine/docs/README_RU.md
> +При использовании Deckhouse версии >= 1.55, контейнер `sidecar-injector` Istio запускается только в режиме `Privileged`.
```suggestion

При использовании Deckhouse версии >= 1.55, контейнер `sidecar-injector` Istio запускается только в режиме `Privileged`.
```

2024-02-12 16:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-02-13 12:24 UTC, apolovov requested changes

2024-02-13 12:24 UTC, apolovov commented on modules/015-admission-policy-engine/docs/README.md
> +When using Deckhouse version >= 1.55, the Istio `sidecar-injector` container runs only in `Privileged` mode.
```suggestion
When using Deckhouse version >= 1.55, the module works in `Baseline` mode by default. In this regard, Istio's init-containers can't configure rules for application's traffic interception, so the Pod's can't start. The solution is either configure the module to work in `Restricted` mode or add a label `security.deckhouse.io/pod-policy=privileged` to application's Namespace.
```

2024-02-13 12:24 UTC, apolovov commented on modules/110-istio/docs/README.md
> +When using Deckhouse version >= 1.55 and the [admission-policy-engine](../015-admission-policy-engine/) module is enabled, the `sidecar-injector` Istio container runs only in `Privileged` mode.
```suggestion
When using Deckhouse version >= 1.55 and the [admission-policy-engine](../015-admission-policy-engine/) module is enabled, it works in `Baseline` mode by default. In this regard, Istio's init-containers can't configure rules for application's traffic interception, so the Pod's can't start. The solution is either configure the admission-policy-engine module to work in `Restricted` mode or add a label `security.deckhouse.io/pod-policy=privileged` to application's Namespace.
```

2024-02-13 12:24 UTC, apolovov commented on modules/110-istio/docs/README_RU.md
> +При использовании Deckhouse версии >= 1.55 и включенном модуле [admission-policy-engine](../015-admission-policy-engine/), контейнер `sidecar-injector` Istio запускается только в режиме `Privileged`.
```suggestion
В Deckhouse версии >= 1.55 модуль [admission-policy-engine](../015-admission-policy-engine/) по умолчанию работает в режиме `Baseline`. Если его включить, init-контейнеры Istio не могут добавить необходимые правила для перехвата прикладного трафика и Поды не могут запуститься. Решение — либо поменять политику по умолчанию на `Restricted`, либо выставить эту политику для отдельного приложения с помощью лейбла `security.deckhouse.io/pod-policy=privileged` на прикладной Namespace.
```

2024-02-13 12:25 UTC, apolovov approved these changes

2024-02-15 07:42 UTC, merged