chore: change terraform version to 0.14.8
deckhouse/deckhouse pull request #7513
Opened 2024-02-15 09:12 UTC by universal-itengineer

## Description

## Why do we need it, and what problem does it solve?

For use terraform-provider-kuberneteswith spesific scenario
## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-02-15 11:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-02-15 11:32 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 7914941575 7914941575-1-con-1-25 /sys/deckhouse-oss/install:pr7513

2024-02-15 11:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-02-15 13:08 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-02-15 14:55 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7916416662 7916416662-2-con-1-25 /sys/deckhouse-oss/install:pr7513

2024-02-15 14:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-02-15 14:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-02-15 15:39 UTC, universal-itengineer commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 7917857708 7917857708-1-con-1-25 /sys/deckhouse-oss/install:pr7513

2024-02-15 15:39 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-02-16 07:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-02-16 08:24 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-02-16 11:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-02-16 15:10 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7929885872 7929885872-1-con-1-25 /sys/deckhouse-oss/install:pr7513

2024-02-16 15:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-02-16 15:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-02-16 19:07 UTC, universal-itengineer commented
/e2e/abort aws;WithoutNAT;containerd;1.25 7932500721 7932500721-1-con-1-25 /sys/deckhouse-oss/install:pr7513

2024-02-16 19:07 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-02-16 20:10 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7935527029 7935527029-1-con-1-25 /sys/deckhouse-oss/install:pr7513

2024-02-16 20:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-02-16 20:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-02-16 20:51 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7935782068 7935782068-1-con-1-25 /sys/deckhouse-oss/install:pr7513

2024-02-16 20:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-02-19 09:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-02-19 13:26 UTC, universal-itengineer commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 7957596960 7957596960-1-con-1-25 /sys/deckhouse-oss/install:pr7513

2024-02-19 13:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @universal-itengineer. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-02-26 08:40 UTC, diafour commented on testing/cloud_layouts/script_eks.sh
> +  echo "Rights and owner changed"
```suggestion

  if [ -n $USER_RUNNER_ID ]; then
    echo "Fix temp directories owner before cleanup ..."
    chown -R $USER_RUNNER_ID "$(pwd)/testing" || true
    chown -R $USER_RUNNER_ID "/deckhouse/testing" || true
    chown -R $USER_RUNNER_ID /tmp || true
  else
    echo "Fix temp directories permissions before cleanup ..."
    chmod -f -R 777 "$(pwd)/testing" || true
    chmod -f -R 777 "/deckhouse/testing" || true
    chmod -f -R 777 /tmp || true
  fi
```

2024-02-28 09:13 UTC, aleksey-su requested changes
have passed all cloud tests without exception Plus we need to make sure that in existing clusters a change in terraform will not cause a conversion to be necessary. Without that, you can't accept it.

2024-02-28 16:22 UTC, universal-itengineer commented
e2e test from test repo
![SCR-20240228-navd](https://github.com/deckhouse/deckhouse/assets/141920865/49536ec6-bc56-4875-b40b-997f0dd2213d)
![SCR-20240228-nbef](https://github.com/deckhouse/deckhouse/assets/141920865/e2e72668-2b29-4932-bef5-7795a7d4df23)
![SCR-20240228-pvoe](https://github.com/deckhouse/deckhouse/assets/141920865/c3ada01d-6b99-447d-9fca-a996e12350dc)

2024-02-29 08:26 UTC, universal-itengineer commented
GCP
![SCR-20240229-kird](https://github.com/deckhouse/deckhouse/assets/141920865/adda468a-14d5-4272-b7e6-d2f52fc02b5f)
![SCR-20240229-kjok](https://github.com/deckhouse/deckhouse/assets/141920865/f9cca040-d098-4d0e-9830-2679920f5773)

2024-02-29 11:59 UTC, universal-itengineer commented
Azure
![image](https://github.com/deckhouse/deckhouse/assets/141920865/df547305-4dfd-463e-97b2-2b1b2fc7ed0b)

2024-02-29 15:34 UTC, universal-itengineer commented
vSphere
![image](https://github.com/deckhouse/deckhouse/assets/141920865/6c061d53-2aee-43b4-ab86-262768f9ef94)

2024-03-01 13:46 UTC, universal-itengineer commented
Yandex.Cloud
![image](https://github.com/deckhouse/deckhouse/assets/141920865/97349a65-8acf-44e3-9b77-c9f1d99702a7)
![image](https://github.com/deckhouse/deckhouse/assets/141920865/196fbd68-d18d-401a-8fae-8fc72fa6a625)

2024-03-07 13:21 UTC, RomanenkoDenys reviewed
some question

2024-03-07 13:21 UTC, RomanenkoDenys commented on modules/040-terraform-manager/templates/terraform-auto-converger/deployment.yaml
> +        #  runAsUser: 65534
why you comment it ?

2024-03-07 13:42 UTC, universal-itengineer commented on modules/040-terraform-manager/templates/terraform-auto-converger/deployment.yaml
> +        #  runAsUser: 65534
I forgot to delete it, I corrected it

2024-03-11 18:10 UTC, RomanenkoDenys approved these changes

2024-03-12 12:39 UTC, aleksey-su approved these changes

2024-03-12 12:47 UTC, diafour approved these changes
I've seen it before, in the testing phase, so approve from me.

2024-03-12 12:51 UTC, merged