[admission-policy-engine] Add ability to disable service account auto…
deckhouse/deckhouse pull request #7571
Opened 2024-02-20 11:13 UTC by Dmitrykob

… mount

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-02-22 07:22 UTC, z9r5 approved these changes

2024-02-26 12:07 UTC, yalosev commented on modules/015-admission-policy-engine/crds/doc-ru-security-policy.yaml
> +                      description: "Определяет возможность для подов включать автоматическое монтирование токена сервисного аккаунта"
```suggestion
                      description: "Определяет возможность запуска подов с автоматически примонтированным токеном сервисного аккаунта"
```

2024-02-26 12:07 UTC, yalosev commented on modules/015-admission-policy-engine/crds/security-policy.yaml
> +                      description: "Defines if it's possible to run containers with enabled automountServiceAccountToken."
```suggestion
                      description: "Defines if it's possible to run pods with enabled automountServiceAccountToken."
```

2024-02-26 12:07 UTC, yalosev approved these changes

2024-02-26 13:11 UTC, MariaMakeeva commented on modules/015-admission-policy-engine/crds/doc-ru-security-policy.yaml
>                        description: "Определяет список доступных к использованию seccomp-профилей."
```suggestion
                      description: Определяет список доступных seccomp-профилей.
```

2024-02-27 08:37 UTC, yalosev requested changes
Have to add a migration for existing SecurityPolicy here

2024-03-04 08:59 UTC, MariaMakeeva approved these changes

2024-03-04 09:03 UTC, z9r5 approved these changes

2024-03-06 12:02 UTC, yalosev commented on modules/015-admission-policy-engine/hooks/handle_security_policies.go
> +		sp.Spec.Policies.AutomountServiceAccountToken = newTrue()
```suggestion
		sp.Spec.Policies.AutomountServiceAccountToken = pointer.Bool(true)
```

2024-03-06 13:57 UTC, merged