[node-manager](caps) Check StaticInstance address by tcp connection
deckhouse/deckhouse pull request #7640
Opened 2024-02-27 06:42 UTC by artbin

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-02-28 03:57 UTC, artbin commented
Manual testing
===========

<img width="1273" alt="Screenshot 2024-02-28 at 11 57 05" src="https://github.com/deckhouse/deckhouse/assets/191757/ad829bd4-a381-48c7-8a46-c3617daf08bb">

2024-02-28 03:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-02-28 08:56 UTC, aleksey-su requested changes
Why don't we interrupt bootstrap immediately and wait 20 minutes?

2024-02-28 15:33 UTC, aleksey-su approved these changes

2024-02-28 15:42 UTC, artbin commented on modules/040-node-manager/images/caps-controller-manager/src/internal/client/bootstrap.go
> +	}
done

2024-02-28 15:42 UTC, artbin commented on modules/040-node-manager/images/caps-controller-manager/src/internal/client/bootstrap.go
> +func (c *Client) setStaticInstancePhaseToBootstrapping(ctx context.Context, instanceScope *scope.InstanceScope) (bool, ctrl.Result, error) {
done

2024-03-07 13:05 UTC, RomanenkoDenys approved these changes
LGTM

2024-03-25 08:42 UTC, name212 approved these changes

2024-03-25 08:43 UTC, merged