[cert-manager] Add CertmanagerCertificateIssuerChanged alerts
deckhouse/deckhouse pull request #7698
Opened 2024-03-01 20:09 UTC by ishtarov

## Description

The alert about certificates with expiring dates does not considering the issuer of the certificate, so if the issuer has changed - then Prometheus will merge the data on these different certificates with same names into one. It will trigger falsely and may confuse you while debugging.

To explain this case, new CertmanagerCertificateIssuerChanged alert added - mentioning about cert-manager restart need to update exporter state.

```changes
section: cert-manager
type: chore
summary: Tune cert-expire alerting
impact_level: low
```

2024-03-04 15:14 UTC, nabokihms requested changes

2024-03-04 15:14 UTC, nabokihms commented on modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml
> +      summary: Certificate {{$labels.exported_namespace}}/{{$labels.name}} issuer has changed, probably cert-manager restart needed to update exporter state.
```suggestion
      summary: Certificate {{$labels.exported_namespace}}/{{$labels.name}} issuer has changed. Cert-manager restart is required to update the exported metrics state.
```

2024-03-26 09:14 UTC, yalosev approved these changes

2024-07-23 13:50 UTC, miklezzzz approved these changes
nit

2024-07-23 13:50 UTC, miklezzzz commented on modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml
> +      summary: Certificate {{$labels.exported_namespace}}/{{$labels.name}} issuer has changed. Cert-manager restart is required to update the exported metrics state.
```suggestion
  - alert: CertmanagerCertificateIssuerChanged
    expr: |
      count by (name, exported_namespace) (certmanager_certificate_expiration_timestamp_seconds{job="cert-manager"}) > 1
    for: 15m
    labels:
      severity_level: "9"
    annotations:
      plk_protocol_version: "1"
      plk_create_group_if_not_exists__certificates_issuer_changed: CertmanagerCertificateIssuerChanged,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes
      plk_grouped_by__certificates_issuer_changed: CertmanagerCertificateIssuerChanged,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes
      description: Certificate {{$labels.exported_namespace}}/{{$labels.name}} issuer has changed
      summary: Certificate {{$labels.exported_namespace}}/{{$labels.name}} issuer has changed. Cert-manager restart is required to update the exported metrics state.
```

2024-10-07 09:41 UTC, closed without merging