[gs][bm] Add GS for zVirt
deckhouse/deckhouse pull request #7713
Opened 2024-03-04 13:20 UTC by z9r5

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-04-12 08:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-21 14:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-22 08:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-22 10:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-22 13:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-23 06:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-23 15:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-24 09:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-24 12:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-26 18:32 UTC, name212 commented on docs/site/_includes/getting_started/global/partials/NOTICES_ENVIRONMENT.liquid
> +Перед началом установки убедитесь в наличии {% if page.platform_code == "zvirt" %}ресурсов гипервизора{%- else %}квот облачного провайдера{% endif %}, необходимых для развертывания вашего кластера.{%
I think there is no need to separate zvirt and the other cloud providers because zvirt can be installed on multiple hypervisors

2024-05-26 18:32 UTC, name212 commented on docs/site/_includes/getting_started/global/partials/NOTICES_ENVIRONMENT.liquid
> +Before starting the installation, ensure you have {% if page.platform_code == "zvirt" %}resources{%- else %}the cloud provider quotas{% endif %} required to deploy your cluster.{%- if page.platform_c
https://github.com/deckhouse/deckhouse/pull/7713/files#r1615306645

2024-05-26 18:34 UTC, name212 commented on docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA_RU.liquid
> +  <p><strong>Ресурсы гипервизора.</strong></p>
```suggestion
  <p><strong>Минимальные ресурсы для работы zVirt.</strong></p>
```

2024-05-26 18:35 UTC, name212 commented on docs/site/_includes/getting_started/zvirt/partials/config.ru.yml.standard.ee.inc
> +можно получить путем запроса к zVirt API# [<en>] General cluster parameters.
```suggestion
# [<en>] General cluster parameters.
```

2024-05-26 18:42 UTC, name212 commented on ee/candi/cloud-providers/zvirt/docs/ENVIRONMENT_RU.md
> +  Установите параметры “Оперативная память (разделяемая)”, “Максимум памяти” и “Оперативная память (гарантированная)” в соответствии с системными требованиями Deckhouse: не менее 8192 MB. Параметр “В
Can't we create a template with fewer resources? And why?

2024-05-26 18:43 UTC, name212 requested changes
some nits

2024-05-27 14:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'deploy/web/test'...
<!-- workflow_start -->

2024-05-28 05:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2024-05-28 07:30 UTC, z9r5 commented
LGTM

2024-05-28 11:02 UTC, name212 approved these changes

2024-05-30 11:39 UTC, merged

2024-05-30 11:39 UTC, deckhouse-BOaTswain commented
Cherry pick PR [8553](https://github.com/deckhouse/deckhouse/pull/8553) to the branch [release-1.60](https://github.com/deckhouse/deckhouse/tree/release-1.60) successful!

2024-05-30 11:40 UTC, z9r5 commented
/backport 1.59

2024-05-30 11:40 UTC, deckhouse-BOaTswain commented
Cherry pick PR [8554](https://github.com/deckhouse/deckhouse/pull/8554) to the branch [release-1.59](https://github.com/deckhouse/deckhouse/tree/release-1.59) successful!