[candi] add step for updating legacy tfadm
deckhouse/deckhouse pull request #7714
Opened 2024-03-04 14:01 UTC by sprait

## Description

Add step for updating legacy tfadm key.

## Why do we need it, and what problem does it solve?

Update tfadm key.

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: candi
type: fix
summary: update tfadm pub key.
impact_level: default
```

2024-03-05 14:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-03-05 15:49 UTC, z9r5 commented
/e2e/abort openstack;Standard;containerd;1.25 8157566938 8157566938-1-con-1-25 /sys/deckhouse-oss/install:pr7714 debian@31.129.32.28

2024-03-05 15:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-03-06 12:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-03-07 12:31 UTC, RomanenkoDenys requested changes
some comments

2024-03-07 14:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-03-07 14:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-03-07 15:22 UTC, sprait commented on ee/fe/candi/bashible/common-steps/all/099_upd_tfadm.sh.tpl
> +auth_keys=$(grep -lirs "${TFADM_OLD_PUB}" {/root,/home/*,/home/*/*}/.ssh/authorized_keys || true )
We can use /var/lib/extrausers/passwd, so i tried to cover this case. 
But I found other decision with `getent passwd` which get summary passwd files, pls, recheck it.

2024-03-26 13:50 UTC, name212 approved these changes

2024-03-26 13:51 UTC, RomanenkoDenys approved these changes

2024-03-26 13:51 UTC, merged