[flow-schema] apiVersion for FlowSchema and PriorityLevelConfiguration changed to the minimum available
deckhouse/deckhouse pull request #7750
Opened 2024-03-07 05:59 UTC by vitaliy-sn

## Description

apiVersion for FlowSchema and PriorityLevelConfiguration changed to the minimum available

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: flow-schema
type: fix
summary: apiVersion for FlowSchema and PriorityLevelConfiguration changed to the minimum available
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-03-07 08:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-03-07 12:27 UTC, RomanenkoDenys commented on modules/011-flow-schema/templates/flowschema.yaml
> +  {{- else if semverCompare "> 1.23" .Values.global.discovery.kubernetesVersion }}
minimal version now is 1.25, why we use > 1.23 here?

2024-03-07 12:27 UTC, RomanenkoDenys requested changes
some comments

2024-03-07 12:27 UTC, RomanenkoDenys commented on modules/011-flow-schema/templates/prioritylevelconfiguration.yaml
> +{{- else if semverCompare "> 1.23" .Values.global.discovery.kubernetesVersion }}
minimal version now is 1.25, why we use > 1.23 here?

2024-03-11 11:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @vitaliy-sn. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-03-11 13:22 UTC, name212 approved these changes

2024-03-11 13:30 UTC, merged

2024-03-11 13:31 UTC, deckhouse-BOaTswain commented
Cherry pick PR [7774](https://github.com/deckhouse/deckhouse/pull/7774) to the branch [release-1.58](https://github.com/deckhouse/deckhouse/tree/release-1.58) successful!