[metallb][ingress-nginx] add L2 Load Balancer (artifact with patches)
deckhouse/deckhouse pull request #7752
Opened 2024-03-07 07:27 UTC by Beastlex

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-03-12 13:00 UTC, apolovov commented on ee/modules/380-metallb/images/artifact/werf.inc.yaml
> +    - test -d /patches/ && for patchfile in /patches/*.patch ; do git apply ${patchfile} ; done
```
find /patches -name '*.patch' | xargs git apply --verbose
```

2024-03-12 13:01 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                    * `L2LoadBalancer` - Ingress controller is deployed and the services of `LoadBalancer` (MetalLB) type is provisioned in resilient mode.
?

2024-03-12 13:02 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        Name of MetalLB pool.
```suggestion
                        Name of MetalLB address pool.
```

2024-03-12 13:02 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			ExecuteHookOnSynchronization: pointer.Bool(false),
why not?

2024-03-12 13:03 UTC, apolovov commented on ee/modules/030-cloud-provider-vcd/candi
> -/deckhouse/candi/cloud-providers/vcd
?

2024-03-12 13:20 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                l2LoadBalancer:
move closer to `loadBalancer`

2024-03-12 14:05 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			ExecuteHookOnSynchronization: pointer.Bool(false),
```suggestion
```

2024-03-12 14:08 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			if nodeSelector, exists := controller.Spec["nodeSelector"]; exists {
```suggestion
			if nodeSelector, ok := controller.Spec["nodeSelector"]; ok {
```

2024-03-12 14:12 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			}
```suggestion
			}
			nodeSelectorLabels = labels.Set(nodeSelectorMapStr).AsSelector()
```
Maybe it is the solution for empty nodeSelector?

2024-03-12 14:13 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			nodes := make([]map[string]string, 0, len(controllersFilterResult))
```suggestion
			nodes := make([]map[string]string, 0, len(nodesFilterResult))
```

2024-03-12 14:27 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			nodes := make([]map[string]string, 0, len(controllersFilterResult))
```suggestion
             // nodes["name"] = "kube-front-0"
			nodes := make([]map[string]string, 0, len(controllersFilterResult))
```

2024-03-12 14:29 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			nestedL2Balancer := make(map[string]interface{})
nested?

2024-03-12 14:30 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                    * `L2LoadBalancer` - Ingress controller is deployed and the services of `LoadBalancer` (MetalLB) type is provisioned in resilient mode.
Also, we have to enrich the [examples](https://deckhouse.io/documentation/v1/modules/402-ingress-nginx/examples.html) page.

2024-03-12 14:41 UTC, apolovov commented on ee/modules/380-metallb/images/artifact/patches/001-l2-speker-preffered-node.patch
> +diff --git a/speaker/layer2_controller.go b/speaker/layer2_controller.go
NB for reviewers! For now, the new inlet rely only on nodeSelector to detect frontend-nodes, not tolerations. Not sure we need them.

2024-03-12 14:46 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			var nodeSelectorLabels = labels.Everything()
```suggestion
			var nodeSelectorLabels = labels.Everything() // by default, the selector is "every node"
```

2024-03-12 14:49 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +			nestedL2Balancer := make(map[string]interface{})
```suggestion
			inletL2LoadBalancer := make(map[string]interface{})
```

2024-03-12 14:52 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers_test.go
>    },
Add test cases pls.

2024-03-12 14:56 UTC, apolovov commented on modules/402-ingress-nginx/templates/controller/service-l2-load-balancer.yaml
> +{{- range $index, $node := $crd.spec.l2LoadBalancer.nodes }}
```suggestion
    {{- range $index, $node := $crd.spec.l2LoadBalancer.nodes }}
```

2024-03-12 14:57 UTC, apolovov commented on modules/402-ingress-nginx/templates/controller/service-l2-load-balancer.yaml
> +{{- end }}
```suggestion
    {{- end }}
  {{- end }}
```

2024-03-12 14:58 UTC, apolovov commented on modules/402-ingress-nginx/templates/controller/service-l2-load-balancer.yaml
> +{{- $context := . }}
add a template_test pls.

2024-03-13 12:29 UTC, apolovov requested changes

2024-03-13 12:29 UTC, apolovov commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                      **Внимание!** Необходимо предварительно настроить [MetalLB](/documentation/v1/modules/380-metallb/) в режиме L2 для использования данного inlet-типа.
Inlet is available only in EE.

2024-03-13 12:29 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES.md
> +## An example for Bare metal (MetalLB Load Balancer in L2 Mode)
Add a BGP note in example above.

2024-03-13 12:29 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES_RU.md
> +По тем же соображениям что и в пердыдущем примере speaker-поды MetalLB должны быть запущены на тех же узлах, что и поды Ingress–контроллера.
```suggestion
По тем же соображениям что, и в предыдущем примере, speaker-поды MetalLB должны быть запущены на тех же узлах, что и поды Ingress–контроллера.
```

2024-03-13 12:29 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES_RU.md
> +Контроллер должен получать реальные IP-адреса клиентов — поэтому его Service создается с параметром `externalTrafficPolicy: Local` (запрещая межузловой SNAT), и для удовлетворения данного параметра M
```suggestion
Контроллер должен знать реальные IP-адреса клиентов — поэтому его Service создается с параметром `externalTrafficPolicy: Local` (запрещая межузловой SNAT), и для удовлетворения данного параметра MetalLB speaker анонсирует этот Service только с тех узлов, где запущены целевые поды.
```

2024-03-13 12:29 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES_RU.md
> +metallb:
```suggestion
kind: ModuleConfig

spec:
  settings:
  ...
```

2024-03-19 09:24 UTC, apolovov requested changes

2024-03-19 09:24 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/crds/l2-load-balncer.yaml
> +                  nodeSelector:
```suggestion
                  addressPool: <mandatory>
                  nodeSelector:
```

2024-03-19 09:24 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/templates/controller/ipaddresspools.yaml
> +  autoAssign: {{ index $ipaddressPool "auto-assign" }}
and remove autoassign option from MC.

2024-03-19 09:24 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/templates/monitoring.yaml
> +{{- include "helm_lib_grafana_dashboard_definitions" . }}
TODO (not now, to think):
* make a module metallb-common, which is enabled if one of modules is enabled (mlb or l2lb).
* this modele deploys grafana dashboars and alerts and whatever.

2024-03-19 09:24 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/templates/services/service.yaml
> +{{- if .Values.ltwoLoadBalancer.internal }}
services/service.yaml -> user-services/service.yaml

2024-03-19 09:24 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/templates/speaker/daemonset.yaml
> +            - --port=7472
```suggestion
            - --port=7472
            - --lb-class=...
```

2024-03-21 08:56 UTC, apolovov requested changes

2024-03-21 08:56 UTC, apolovov commented on ee/modules/110-istio/hooks/ee/lib/crd/istiofederation.go
> +	metav1.TypeMeta `json:",inline,omitempty"`
?

2024-03-21 08:56 UTC, apolovov commented on ee/modules/110-istio/hooks/ee/lib/crd/istiofederation.go
> +	metav1.TypeMeta `json:",inline,omitempty"`
```suggestion
	metav1.TypeMeta `json:",inline"`
```

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/crds/l2-load-balncer.yaml
> +                    If parameter is omitted, L2 LoadBalancer will be placed on all nodes.
```suggestion
                    If parameter is omitted, L2 LoadBalancer's speakers will be placed on all nodes.
```

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/crds/l2-load-balncer.yaml
> +                        The cloud provider may not support this option or ignore it.                       .
```suggestion
```

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/crds/l2-load-balncer.yaml
> +                    addressPool:
addressPool to the .spec.

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/hooks/common.go
> +	metav1.ObjectMeta `json:"metadata,omitempty"`
Figure out, how to use the json field.

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/hooks/common.go
> +	Nodes         []map[string]string   `json:"nodes"`
move Nodes to L2LoadBalancerSpec.

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/hooks/common.go
> +	IsLabeled bool
```suggestion
	IsLabeled bool // is there `l2-load-balancer.network.deckhouse.io/member` label
```

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/hooks/common.go
> +type NodeLabelsInfo struct {
```suggestion
type NodeInfo struct {
```

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/hooks/handle_node_labels.go
> +func appendL2LabelsFromNode(obj *unstructured.Unstructured) (*unstructured.Unstructured, error) {
```suggestion
func appendL2LabelsToNode(obj *unstructured.Unstructured) (*unstructured.Unstructured, error) {
```

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/template_tests/module_test.go
> +var _ = Describe("Module :: ltwo-load-balancer :: helm template ::", func() {
```suggestion
var _ = Describe("Module :: l2-load-balancer :: helm template ::", func() {
```

2024-03-21 08:56 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/hooks/handle_node_labels.go
> +/*
The decision — merge both hooks to handle_load_balancers.go.

2024-03-21 09:26 UTC, Beastlex commented on ee/modules/110-istio/hooks/ee/lib/crd/istiofederation.go
> +	metav1.TypeMeta `json:",inline,omitempty"`
omitempty is unnecessary

2024-03-22 12:07 UTC, apolovov requested changes

2024-03-27 08:06 UTC, apolovov commented on deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
> +	_ "github.com/deckhouse/deckhouse/ee/modules/381-ltwo-load-balancer/hooks"
l2 is fixed.

2024-03-27 08:12 UTC, apolovov commented on ee/modules/381-ltwo-load-balancer/monitoring/grafana-dashboards/kubernetes-cluster/l2lb-pool.json
> +{
pleas check jic.

2024-03-27 08:15 UTC, apolovov commented on ee/modules/402-ingress-nginx/templates/controller-l2/service-l2-load-balancer.yaml
> +{{- $context := . }}
service-l2-load-balancer.yaml -> l2-load-balancer.yaml

2024-03-27 08:15 UTC, apolovov commented on modules/402-ingress-nginx/hooks/get_ingress_controllers.go
> +
Don't need the type here.

2024-03-27 08:17 UTC, apolovov commented on testing/openapi_validation/library.go
> +	modulesWithSameCRDs = map[string]struct{}{
```suggestion
	modulesWithCRDEditions = map[string]struct{}{
```

2024-03-27 08:20 UTC, apolovov commented on testing/openapi_validation/validators/edition_crd_subsets.go
> +Copyright 2021 Flant JSC
```suggestion
Copyright 2024 Flant JSC
```

2024-03-28 23:08 UTC, apolovov commented on ee/modules/381-l2-load-balancer/crds/l2-load-balncer.yaml
> +                  labelSelector:
```suggestion
                  selector:
```
!!!

2024-03-29 00:44 UTC, apolovov approved these changes

2024-03-29 09:08 UTC, konstantin-axenov approved these changes

2024-03-29 09:10 UTC, nabokihms approved these changes

2024-03-29 09:10 UTC, merged