[doc] add example of binding IP to ingress controller
deckhouse/deckhouse pull request #7758
Opened 2024-03-07 14:00 UTC by ishtarov

## Description
Add example of binding specific IP address from MetalLB pool to ingress-controller

```changes
section: doc
type: chore
summary: add example of binding IP to ingress controller
impact_level: low
```

2024-03-11 06:06 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Мы создадим Ingress-контроллер с inlet `LoadBalancer`, а также дадим доступ к отдельно запущенному веб серверу Nginx, используя сервис с типом `LoadBalancer`.
```suggestion
В примере представлено создание Ingress-контроллера с inlet `LoadBalancer`, а также предоставление доступа к отдельно запущенному веб-серверу Nginx, с использованием сервиса с типом `LoadBalancer`.
```

2024-03-11 06:08 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Во-первых, необходимо определить, какие NodeGroup'ы будут использоваться для запуска приложений, к которым будет предоставлен доступ.
```suggestion
Необходимо определить, какие группы NodeGroup будут использоваться для запуска разрешенных допусков к приложениям.
```

2024-03-11 06:09 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-кон
```suggestion
К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из набора адресов MetalLB. Для этого Ingress-контроллеру нужно добавить аннотацию `metallb.universe.tf/loadBalancerIPs`, как описано в [документации к модулю ingress-nginx](../../modules/402-ingress-nginx/cr.html#ingressnginxcontroller-v1-spec-loadbalancer-annotations). Доработанный манифест из указанного выше примера, будет выглядеть следующим образом:
```

2024-03-11 06:10 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES.md
>  We will create an Ingress Controller with `LoadBalancer` inlet. And we will also expose standalone Nginx web server using a Service with the `LoadBalancer` type.
```suggestion
The example shows the creation of an Ingress controller with an inlet `LoadBalancer`, as well as providing access to a separately running Nginx web server using a service with the type `LoadBalancer'.
```

2024-03-11 06:12 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES.md
>  First, you have to decide, which NodeGroups will be used to deploy applications that have to be exposed by the LoadBalancer service.
```suggestion
You have to decide, which NodeGroups will be used to deploy applications that have to be exposed by the `LoadBalancer` service.
```

2024-03-11 16:29 UTC, z9r5 commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-кон
пул адресов - устоявшийся термин. Предлагаю оставить. 
@MariaMakeeva

2024-03-11 16:30 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-кон
Окей. Не имею возражений.

2024-03-11 16:32 UTC, z9r5 commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Во-первых, необходимо определить, какие NodeGroup'ы будут использоваться для запуска приложений, к которым будет предоставлен доступ.
В примере "**предоставление доступа** к отдельно запущенному веб-серверу Nginx".  
Откуда взялся допуск?

2024-03-11 16:36 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Во-первых, необходимо определить, какие NodeGroup'ы будут использоваться для запуска приложений, к которым будет предоставлен доступ.
Переписала. Изначальное предложение немного громоздкое, а мой вариант неочевиден, значит  - среднее арифметическое))

2024-03-11 16:43 UTC, z9r5 commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Во-первых, необходимо определить, какие NodeGroup'ы будут использоваться для запуска приложений, к которым будет предоставлен доступ.
Остались группы узлов...

2024-03-11 19:28 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Во-первых, необходимо определить, какие NodeGroup'ы будут использоваться для запуска приложений, к которым будет предоставлен доступ.
Это для склонения во множественном числе, потому что за "NodeGroup'ы" "запинаются" глаза)) Поэтому оставлено склоняемое "группы". Либо оставить "NodeGroup" без склонения.

2024-03-13 04:39 UTC, z9r5 commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Во-первых, необходимо определить, какие NodeGroup'ы будут использоваться для запуска приложений, к которым будет предоставлен доступ.
Да нет, все нормально. Группы узлов настраиваются через ресурс NodeGroup. В документации у нас термин "группы узлов" употребляется. Чтобы исключить непонимание, мы даем ссылку на ресурс.
В английской версии достаточно nodeGroup ИМХО.

Вот так может?
... какие группы узлов (ресурс NodeGroup) будут ...
@MariaMakeeva

2024-03-13 06:07 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Во-первых, необходимо определить, какие NodeGroup'ы будут использоваться для запуска приложений, к которым будет предоставлен доступ.
Да, ссылка - хорошо. Дополнительная информация точно не лишняя.

2024-03-13 06:32 UTC, MariaMakeeva approved these changes

2024-03-13 07:41 UTC, z9r5 commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-кон
```suggestion
К Ingress-контроллеру, согласно [документации MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips), можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-контроллеру нужно добавить аннотацию `metallb.universe.tf/loadBalancerIPs`, как описано в [документации модуля ingress-nginx](../../modules/402-ingress-nginx/cr.html#ingressnginxcontroller-v1-spec-loadbalancer-annotations). Доработанный манифест из указанного выше примера, будет выглядеть следующим образом:
```

2024-03-13 07:42 UTC, z9r5 commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-кон
@MariaMakeeva не против? Мы обычно пишем же "документация Kukebrenetes"  а не к Kubernetes.  Ну и я там больше на запятую дернулся.

2024-03-13 08:14 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-кон
Не поняла. Запятых много уже правила. Читается, как издёвка)))), но понимаю, сколько всяческих описок и ошибко ещё вычистим, и сколько уже вычищено. Такое ощущение, что этот ПР я уже правила. Эти же самые "NodeGroup`ы" опять, хмхм. И не исправленные.

2024-03-13 08:24 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-кон
Если ты про "документации к MetalLB" - то это допустимо. Документации к чему-либо. "К" - предлог, а “MetalLB” - название предмета, к которому относится документация. То есть речь идёт о документации, связанной с MetalLB.

2024-03-13 08:45 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +К Ingress-контроллеру, согласно [документации к MetalLB](https://metallb.universe.tf/usage/#requesting-specific-ips) можно привязать конкретный IP-адрес из пула адресов MetalLB. Для этого Ingress-кон
И да, почему "Kukebrenetes" (искажение названия), если речь об удалении предлога? :)

2024-03-13 08:55 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Metallb можно использовать в статических (bare-metal) кластерах, когда вы не можете заказать балансировщик (load balancer) у облачного провайдера. Metallb может работать в L2- или BGP-режиме.
```suggestion
Metallb можно использовать в статических (bare-metal) кластерах, когда не получается заказать балансировщик (load balancer) у облачного провайдера. Metallb может работать в L2- или BGP-режиме.
```

2024-03-13 11:29 UTC, z9r5 commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  Metallb можно использовать в статических (bare-metal) кластерах, когда вы не можете заказать балансировщик (load balancer) у облачного провайдера. Metallb может работать в L2- или BGP-режиме.
тут скорее - отсутствует возможность/невозможно и т.п.  Т.е. у провайдера нет возможности предоставить балансер (не возможно)

2024-03-13 11:51 UTC, apolovov commented on ee/modules/380-metallb/docs/EXAMPLES.md
> +Metallb can be used in Static (Bare Metal) clusters when you can't order a load balancer from a cloud provider. Metallb can work in L2 or BGP modes.
```suggestion
Metallb can be used in Static (Bare Metal) clusters when you can't order a load balancer from a cloud provider. Metallb can work in L2 or BGP modes.
```

2024-03-13 11:53 UTC, apolovov requested changes

2024-03-13 11:53 UTC, apolovov commented on ee/modules/380-metallb/docs/EXAMPLES.md
> +## Example of binding a MetalLB IP address to an Ingress controller
It is an example for BGP mode, [we are working](https://github.com/deckhouse/deckhouse/pull/7752) on a new inlet, L2LoadBalancer. Not sure if we need IngressNginxController example here.

2024-03-13 15:22 UTC, z9r5 approved these changes

2024-03-15 09:39 UTC, elenashliaga commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +Необходимо определить, какие группы узлов (ресурс [NodeGroup](../040-node-manager/cr.html#nodegroup)) будут использоваться для запуска приложений, к которым предоставляется доступ.
```suggestion
Необходимо определить, какие группы узлов ([_NodeGroup_](../040-node-manager/cr.html#nodegroup)) будут использоваться для запуска приложений, к которым предоставляется доступ.
```

2024-03-15 09:41 UTC, elenashliaga commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
>  В этом примере Ingress-контроллеры запускаются на frontend-узлах, а веб сервер Nginx — на worker-узле. У всех узлов есть общий лейбл `node-role/metallb=""`.
```suggestion
Запустим Ingress-контроллеры на frontend-узлах, а веб сервер Nginx — на worker-узле. У всех узлов есть общий лейбл `node-role/metallb=""`.
```

2024-03-15 09:53 UTC, elenashliaga commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +## Пример использования MetalLB в L2-режиме.
```suggestion
## Пример использования MetalLB в L2-режиме
```

2024-03-15 11:18 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +1. Зададим группы узлов ([_NodeGroup_](../040-node-manager/cr.html#nodegroup)) для запуска приложений, к которым предоставляется доступ.
```suggestion
1. Задайте группы узлов ([_NodeGroup_](../040-node-manager/cr.html#nodegroup)) для запуска приложений, к которым предоставляется доступ.
```

2024-03-15 11:18 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +Создадим Ingress-контроллер с `inlet: LoadBalancer` и предоставим доступ к отдельно запущенному веб-серверу Nginx с использованием сервиса типа `LoadBalancer`.
```suggestion
Создайте Ingress-контроллер с `inlet: LoadBalancer` и предоставьте доступ к отдельно запущенному веб-серверу Nginx с использованием сервиса типа `LoadBalancer`.
```

2024-03-15 11:20 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +   Пусть Ingress-контроллеры запускаются на frontend-узлах, а веб сервер Nginx — на worker-узле. У всех узлов есть общий лейбл `node-role/metallb=""`.
```suggestion
   Например, Ingress-контроллеры запускаются на frontend-узлах, а веб сервер Nginx — на worker-узле. У всех узлов есть общий лейбл `node-role/metallb=""`.
```

2024-03-15 11:21 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +1. Проверим, что на узлах проставлен корректный лейбл, командой `kubectl`:
```suggestion
1. Проверяется, что на узлах проставлен корректный лейбл, командой `kubectl`:
```

2024-03-15 11:22 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +1. Включим модуль `metallb`, потому что он отключен по умолчанию, и зададим корректные параметры `nodeSelector` и `tolerations` для спикеров Metallb.
```suggestion
1. Включается модуль `metallb`, потому что он отключен по умолчанию, и задаются корректные параметры `nodeSelector` и `tolerations` для спикеров Metallb.
```

2024-03-15 11:22 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +1. Создадим _IngressNginxController_.
```suggestion
1. Создается _IngressNginxController_.
```

2024-03-15 11:23 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +1. Проверим, что сервис с типом `LoadBalancer` создан в _Namespace_ `d8-ingress-nginx` с помощью команды `kubectl`:
```suggestion
1. Проверяется, что сервис с типом `LoadBalancer` создан в _Namespace_ `d8-ingress-nginx` с помощью команды `kubectl`:
```

2024-03-15 11:23 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +  Готово, ваш Ingress-контроллер доступен по внешнему IP-адресу.
```suggestion
  Готово, Ingress-контроллер доступен по внешнему IP-адресу.
```

2024-03-15 11:25 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +1. Теперь предоставим доступ к веб-серверу Nginx на порту `8080`.
```suggestion
1. Предоставляется доступ к веб-серверу Nginx на порту `8080`.
```

2024-03-15 11:25 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +1. Проверим сервис.
```suggestion
1. Проверяется сервис.
```

2024-03-15 11:25 UTC, MariaMakeeva commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +Готово, теперь вы можете получить доступ к приложению, используя curl.
```suggestion
Готово, можно получить доступ к приложению, используя curl.
```

2024-03-15 11:29 UTC, elenashliaga commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +Создадим Ingress-контроллер с `inlet: LoadBalancer` и предоставим доступ к отдельно запущенному веб-серверу Nginx с использованием сервиса типа `LoadBalancer`.
@MariaMakeeva это пример, поэтому предлагаю оставить мой вариант

Типа мы это будем делать в этом примере

2024-03-15 11:42 UTC, elenashliaga commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +   Пусть Ingress-контроллеры запускаются на frontend-узлах, а веб сервер Nginx — на worker-узле. У всех узлов есть общий лейбл `node-role/metallb=""`.
ок, подойдет, резолвну

2024-03-15 11:43 UTC, elenashliaga commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +  Готово, ваш Ingress-контроллер доступен по внешнему IP-адресу.
ок, резолвну

2024-03-15 11:51 UTC, elenashliaga commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +Готово, теперь вы можете получить доступ к приложению, используя curl.
ок, резолв

2024-03-15 12:37 UTC, elenashliaga commented on ee/modules/380-metallb/docs/EXAMPLES_RU.md
> +Создадим Ingress-контроллер с `inlet: LoadBalancer` и предоставим доступ к отдельно запущенному веб-серверу Nginx с использованием сервиса типа `LoadBalancer`.
```suggestion
Пример создания Ingress-контроллера с `inlet: LoadBalancer` и предоставления доступа к отдельно запущенному веб-серверу Nginx с использованием сервиса типа `LoadBalancer`.
```

2024-03-18 15:05 UTC, MariaMakeeva approved these changes

2024-03-18 18:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2024-03-18 18:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2024-03-20 09:19 UTC, MariaMakeeva approved these changes

2024-03-28 07:03 UTC, kirkonru approved these changes

2024-03-28 07:03 UTC, kirkonru commented on ee/modules/380-metallb/docs/EXAMPLES.md
> +1. Проверьте, что сервис создан:
```suggestion
1. Verify that the service has been created:
```

2024-03-28 07:03 UTC, kirkonru commented on ee/modules/380-metallb/docs/EXAMPLES.md
> +   Пример вывода:
```suggestion
   Your output should look something like this:
```

2024-03-28 07:03 UTC, kirkonru commented on ee/modules/380-metallb/docs/EXAMPLES.md
> +   Пример:
```suggestion
1. Check if the application is accessible.

   Example:
```

2024-03-28 07:27 UTC, merged