[dhctl] Add parameterization for bootstrapped kube-resources
deckhouse/deckhouse pull request #776
Opened 2022-02-03 18:28 UTC by name212

## Description
Add parameterization for bootstrapped resources.
Now, we can template resources for bootstrap with cloud discovery data.

## Why do we need it, and what problem does it solve?
For example, for yandex layout with interconnect we can add yandex instance classes via resources.yaml
Because for nodes with interconnect we need to set `mainNetwork` with interconnect network id and add kube network id to additional networks. We know interconnect network before bootstrap cluster, but kube network will create with terraform in bootstrap process.  

## Changelog entries

```changes
module: dhctl
type: feature
description: Add parameterization for bootstrapped kube-resources
```

2022-02-03 18:29 UTC, name212 commented
I think, we can get this PR to previous version.

2022-02-03 18:48 UTC, deckhouse-BOaTswain commented
Run workflow "e2e/run/openstack"...

2022-02-04 10:49 UTC, nabokihms requested changes

2022-02-04 10:57 UTC, name212 commented on dhctl/pkg/app/bootstrap.go
> +  cloudDiscovery - cloud discovery data got from terrfarorm output. It depends on provider. See available values in /candi/cloud-providers/PROVIDER_NAME/openapi/cloud_discovery_data.yaml
Ok. Good point. I got it

2022-02-04 10:59 UTC, name212 commented on dhctl/pkg/config/resources.go
> +		t := template.New("resource_render")
For rendering bashible templates we use standard `text/template` package.

Ok. I will add it

2022-02-04 14:33 UTC, name212 commented on dhctl/pkg/config/resources.go
> +		t := template.New("resource_render")
done

2022-02-04 14:33 UTC, deckhouse-BOaTswain commented
Run workflow "e2e/run/openstack"...

2022-02-07 07:40 UTC, nabokihms approved these changes

2022-02-07 07:40 UTC, merged

2022-02-09 15:10 UTC, z9r5 commented
Cherry-picked into release-1.30