[monitoring-kubernetes] ebpf-exporter distroless
deckhouse/deckhouse pull request #7769
Opened 2024-03-11 10:29 UTC by aleksey-su

## Description
ebpf_exporter are now based on minimal image and bump version to v2.3.0.

If an error occurs when starting ebpf_exporter, e.g. there are not enough modules in the kernel to start, the EbpfExporterKernelNotSupported alert will be lit. 
Possible actions to resolve the problem:
 * Built kernel with BTF type information [info](https://github.com/libbpf/libbpf?tab=readme-ov-file#bpf-co-re-compile-once--run-everywhere).
 * [Disable](https://deckhouse.io/documentation/v1/modules/340-monitoring-kubernetes/configuration.html#parameters-ebpfexporterenaled) ebpf_exporter

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?
We use scratch along with a minimal number of files from Alpine packages. We pass files in packages through a rsync whitelist.

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-kubernetes
type: feature
summary: ebpf_exporter image is based on a distroless image. Bump version to v2.3.0.
impact_level: default
```

2024-03-12 11:28 UTC, aleksey-su commented
BTF not supported
![image](https://github.com/deckhouse/deckhouse/assets/485892/f7d7c7e1-241b-4233-8074-02ffe1fd83aa)
![image](https://github.com/deckhouse/deckhouse/assets/485892/03513e77-5f9e-47b5-a966-7e981ee94667)

2024-03-12 14:49 UTC, aleksey-su commented
Normal
![image](https://github.com/deckhouse/deckhouse/assets/485892/6c39a6b8-0e5d-41e2-9401-e32e2052ad0a)
![image](https://github.com/deckhouse/deckhouse/assets/485892/95f5618e-9380-4d92-8e87-a665d8a76157)

2024-03-14 06:41 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/efcd2485-07e2-47ed-98b8-f11439797b25)
![image](https://github.com/deckhouse/deckhouse/assets/485892/9f65a712-2b61-4bdc-a0b8-7e66aeb6c01b)

2024-03-14 06:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-03-14 07:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-03-14 10:56 UTC, RomanenkoDenys commented on modules/340-monitoring-kubernetes/images/ebpf-exporter/werf.inc.yaml
> +from: {{ .Images.BASE_GOLANG_21_BULLSEYE }}
Please use DEV image and remove apt

2024-03-14 10:59 UTC, RomanenkoDenys requested changes

2024-03-14 10:59 UTC, RomanenkoDenys commented on tools/dev_images/additional_tools/alt/binary_replace.sh
> +  cp -a --remove-destination ${file} ${new_place}
We need to rebuild dev_alt image here ad this is a big problem - all containers which builded on the DEV_ALT base should be restarted in the cluster

2024-03-14 10:59 UTC, RomanenkoDenys commented on tools/dev_images/additional_tools/alt/binary_replace.sh
> +    cp -a --remove-destination ${orig_file} ${new_place}
The same as above

2024-03-14 12:25 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/39f47f44-e842-4662-a36d-f70a25ecb0fb)

2024-03-14 12:32 UTC, RomanenkoDenys approved these changes

2024-03-14 13:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-03-26 13:54 UTC, name212 approved these changes

2024-03-27 19:48 UTC, nabokihms approved these changes

2024-03-27 19:49 UTC, merged