[l2-load-balancer] add externalTrafficPolicy option
deckhouse/deckhouse pull request #7968
Opened 2024-04-02 08:32 UTC by Beastlex

## Description
Add externalTrafficPolicy option to L2LoadBalancer custom resource

## Why do we need it, and what problem does it solve?
Цe need to be able to define how to route external traffic to node-local or cluster-wide endpoints. 

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: l2lLoadBalancer
type: chore
summary: externalTrafficPolicy option
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: low
```

2024-04-02 10:49 UTC, apolovov requested changes

2024-04-02 10:49 UTC, apolovov commented on ee/modules/381-l2-load-balancer/crds/doc-ru-l2-load-balncer.yaml
> +                      * Cluster - трафик может быть направлени на любой под в кластере.
```suggestion
                      * Local (по умолчанию) — трафик направляется к подам, расположенным на той же ноде, что и L2 LoadBalancer speaker
                      * Cluster — трафик может быть направлени на любой под в кластере.
```

2024-04-02 10:49 UTC, apolovov commented on ee/modules/381-l2-load-balancer/docs/EXAMPLES.md
> +  kubectl describe l2loadbalancers.deckhouse.io test
```suggestion
  kubectl describe l2loadbalancers.deckhouse.io nginx
```

2024-04-02 10:49 UTC, apolovov commented on ee/modules/381-l2-load-balancer/docs/EXAMPLES_RU.md
> +  kubectl describe l2loadbalancers.deckhouse.io test
```suggestion
  kubectl describe l2loadbalancers.deckhouse.io nginx
```

2024-04-02 10:49 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/handle_load_balancers.go
> +	externalTrafficPolicy := "Local"
default value is in openapi.

2024-04-02 10:49 UTC, apolovov commented on ee/modules/381-l2-load-balancer/crds/doc-ru-l2-load-balncer.yaml
>                    sourceRanges:
pls, configure the externalTrafficPolicy of L2LoadBalancer in ingress-nginx inlet explicitly.

2024-04-09 08:09 UTC, apolovov requested changes

2024-04-09 08:09 UTC, apolovov commented on ee/modules/381-l2-load-balancer/crds/doc-ru-l2-load-balancer.yaml
> +                      * Local (по умолчанию) — трафик направляется к подам, расположенным на той же ноде, что и L2 LoadBalancer speaker
```suggestion
                      * Local (по умолчанию) — трафик направляется к подам, расположенным на той же ноде, что и L2 LoadBalancer speaker.
```

2024-04-09 08:09 UTC, apolovov commented on ee/modules/381-l2-load-balancer/docs/EXAMPLES.md
> +  The assigned IP addresses can also be seen in the Status section of the custom resource L2LoadBalancer:
```suggestion
  The assigned IP addresses can also be seen in the `status` section of the custom resource L2LoadBalancer:
```

2024-04-09 08:10 UTC, apolovov approved these changes

2024-04-09 09:41 UTC, z9r5 approved these changes

2024-04-09 09:41 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/crds/doc-ru-l2-load-balancer.yaml
> +                      * Cluster — трафик может быть направлени на любой под в кластере.
```suggestion
                      Описывает каким образом LoadBalancer отправляет трафик к конечным подам:
                      * `Local` (по умолчанию) — трафик направляется к подам, расположенным на том же узле, что и L2 LoadBalancer speaker.
                      * `Cluster` — трафик может быть направлен на любой под в кластере.
```

2024-04-09 09:41 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/crds/l2-load-balancer.yaml
> +                      Denotes if this L2 LoadBalancer desires to route external traffic to node-local or cluster-wide endpoints. There are two available options: Local (default) and Cluster.
```suggestion
                      Denotes if this L2 LoadBalancer desires to route external traffic to node-local or cluster-wide endpoints. There are two available options: Local (default) and Cluster.
                      * `Local` (by default) — traffic is routed to pods located on the same node as L2 LoadBalancer speaker.
                      * `Cluster` — traffic can be routed to any pod in the cluster.
```

2024-04-09 09:41 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/docs/EXAMPLES_RU.md
> +  Назначенные IP адреса можно также увидеть в разделе Status объекта L2LoadBalacner:
```suggestion
  Назначенные IP-адреса можно также увидеть в поле `status` ресурса `L2LoadBalancer`:
```

2024-04-09 09:41 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/docs/EXAMPLES.md
> +  The assigned IP addresses can also be seen in the `status` section of the custom resource L2LoadBalancer:
```suggestion
  The assigned IP addresses can also be seen in the `status` section of the custom resource `L2LoadBalancer`:
```

2024-04-09 09:43 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/crds/doc-ru-l2-load-balancer.yaml
> +                      Описывает каким образом LoadBalancer отправляет трафик к конечным подам:
```suggestion
                      Описывает каким образом балансировщик отправляет трафик к конечным подам:
```

2024-04-09 09:49 UTC, merged