[node-manager] Errors when adding a NodeUser do not block bashable
deckhouse/deckhouse pull request #8054
Opened 2024-04-10 09:02 UTC by aleksey-su

## Description
Errors when adding a NodeUser do not block bashable

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-04-16 12:55 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/7101e2fe-a0c1-460b-a874-595bd7b90b93)

2024-04-16 13:04 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/09d3cd2e-c59a-4063-a6bd-2805e317d446)

2024-04-17 08:16 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/11299904-2ee3-4d71-9289-24ecf23c1f35)

2024-04-17 14:51 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/3714a6e2-540e-4449-8f40-c38181cc5b68)

2024-04-18 09:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-04-24 09:43 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
Needs comment about why this step is 000_*

2024-04-24 09:45 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +function kubectl_exec() {
bb-kubectl can be used here

2024-04-24 09:48 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +      >&2 echo "failed to NodeUser with kubectl --kubeconfig=/etc/kubernetes/kubelet.conf"
```suggestion
      bb-error "failed to NodeUser with kubectl --kubeconfig=/etc/kubernetes/kubelet.conf"
```

2024-04-24 09:49 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +          echo "The network is not ready for connecting to apiserver yet, waiting..."
```suggestion
          bb-log-info "The network is not ready for connecting to apiserver yet, waiting..."
```

2024-04-24 09:51 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +function nodeuser_patch() {
think about move it in bashbooster. Looks like we can reuse this function in multiple locations

2024-04-24 09:53 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +            >&2 echo "Failed to patch NodeUser. Number of attempts exceeded. NodeUser patch will be skipped."
```suggestion
            bb-log-error "Failed to patch NodeUser. Number of attempts exceeded. NodeUser patch will be skipped."
```

2024-04-24 09:53 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +function error_check() {
use bb-error

2024-04-24 09:54 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +          >&2 echo "Failed to patch NodeUser. ${failure_count} of ${failure_limit} attempts..."
```suggestion
          bb-log-error "Failed to patch NodeUser. ${failure_count} of ${failure_limit} attempts..."
```

2024-04-24 09:54 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +    >&2 echo "failed to patch NodeUser can't find kubelet.conf or bootstrap-token"
```suggestion
    bb-log-error "failed to patch NodeUser can't find kubelet.conf or bootstrap-token"
```

2024-04-24 09:56 UTC, name212 commented on candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
> +set +e
i think it needed for debugging purposes. Needs remove it

2024-04-24 10:03 UTC, name212 commented on modules/040-node-manager/templates/bashible/rbac-for-us.yaml
> +  - nodeusers/status
Please create separated ClusterRole and ClusterRoleBinding for it

2024-04-24 10:16 UTC, name212 requested changes
some nits

2024-04-24 10:16 UTC, name212 commented on modules/040-node-manager/templates/bashible/rbac-for-us.yaml
> +  - kind: Group
https://github.com/deckhouse/deckhouse/pull/8054/files#r1577632019

2024-04-24 10:16 UTC, name212 commented on modules/040-node-manager/templates/bashible/rbac-for-us.yaml
> +  - get
https://github.com/deckhouse/deckhouse/pull/8054/files#r1577632019

2024-04-24 10:16 UTC, name212 commented on modules/040-node-manager/hooks/clear_nodeuser_errors.go
> +	Kubernetes: []go_hook.KubernetesConfig{
Looks like this hook should be schedule periodically as this hook https://github.com/deckhouse/deckhouse/blob/29d02b2f3fc8565e25142ff55241b25ed4e4cab0/modules/005-external-module-manager/hooks/cleanup_releases.go#L55

2024-04-24 10:16 UTC, name212 commented on modules/040-node-manager/hooks/clear_nodeuser_errors.go
> +	nodes := make(map[string]struct{})
can use go_lib.Set here

2024-04-24 10:16 UTC, name212 commented on modules/040-node-manager/hooks/clear_nodeuser_errors.go
> +	return result, has
we can return only result slice and check len of slice in the hook

2024-04-24 10:16 UTC, name212 commented on modules/040-node-manager/hooks/clear_nodeuser_errors.go
> +	result := []string{}
```suggestion
	result := make([]string, 0, 0)
```

2024-04-24 10:16 UTC, name212 commented on modules/040-node-manager/hooks/clear_nodeuser_errors.go
Need test for this hook

2024-05-02 13:24 UTC, z9r5 approved these changes

2024-05-06 07:16 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/5297b6f0-c802-4c30-a9c3-140813e855c0)

2024-05-06 12:19 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/5b2e4b64-1647-4ca0-ba8c-3a27ed313af0)

2024-05-06 13:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-05-13 13:13 UTC, name212 commented on candi/bashible/bashbooster/65_nodeuser.sh
> +# Copyright 2024 Flant JSC
move please to 000_add_node_users.sh.tpl

2024-05-13 13:19 UTC, name212 commented on modules/040-node-manager/webhooks/validating/node_user
> +    apiVersion: deckhouse.io/v1alpha1
why deckhouse.io/v1alpha1 ?

2024-05-13 13:19 UTC, name212 commented on modules/040-node-manager/webhooks/validating/node_user
> +    apiVersion: deckhouse.io/v1alpha1
```suggestion
    apiVersion: deckhouse.io/v1
```

2024-05-13 13:23 UTC, name212 approved these changes
two small things

2024-05-15 10:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-05-16 16:03 UTC, RomanenkoDenys approved these changes

2024-05-17 08:34 UTC, merged