[node-manager] Add NodeGroup metrics
deckhouse/deckhouse pull request #8355
Opened 2024-05-13 03:03 UTC by artbin

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-05-13 04:31 UTC, artbin commented
Manual testing
==============

Create the `workers` NodeGroup with `minPerZone: 1` and `maxPerZone: 1`:
```yaml
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: workers
spec:
  nodeType: CloudEphemeral
  cloudInstances:
    minPerZone: 1
    maxPerZone: 1
    classReference:
      kind: OpenStackInstanceClass
      name: workers
```

Change the `workers` NodeGroup with `minPerZone: 5` and `maxPerZone: 10`:
```yaml
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: workers
spec:
  nodeType: CloudEphemeral
  cloudInstances:
    minPerZone: 5
    maxPerZone: 10
    classReference:
      kind: OpenStackInstanceClass
      name: workers
```

An error occurred after updating the NodeGroup specification:
```bash
kubectl get nodegroup workers -o json | jq '.status.conditions[] | select( .type | contains("Error"))'
```
```json
{
"lastTransitionTime": "2024-05-13T04:10:58Z",
"message": "Cloud provider message - error creating the server: Request forbidden: error message: {\"forbidden\": {\"code\": 403, \"message\": \"Quota exceeded for ram: Requested 2048, but already used 24576 of 24576 ram\"}}",
"status": "True",
"type": "Error"
}
```

Change the `workers` NodeGroup with `minPerZone: 2` and `maxPerZone: 4`:
```yaml
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: workers
spec:
  nodeType: CloudEphemeral
  cloudInstances:
    minPerZone: 2
    maxPerZone: 4
    classReference:
      kind: OpenStackInstanceClass
      name: workers
```

<details>
  <summary>Grafana screenshots</summary>
  
<img width="1274" alt="Screenshot 2024-05-13 at 12 23 30" src="https://github.com/deckhouse/deckhouse/assets/191757/b2d81b01-8f07-484e-840a-cd38432f163d">
<img width="1274" alt="Screenshot 2024-05-13 at 12 23 37" src="https://github.com/deckhouse/deckhouse/assets/191757/ba2b54eb-2a74-451e-8f4e-2a214a12a356">
<img width="1274" alt="Screenshot 2024-05-13 at 12 23 42" src="https://github.com/deckhouse/deckhouse/assets/191757/a2f3fc83-6615-4151-8cc4-b40cd0abac35">
<img width="1274" alt="Screenshot 2024-05-13 at 12 23 52" src="https://github.com/deckhouse/deckhouse/assets/191757/88fcb32f-8b50-4613-b09c-5036b5c6c9f3">
<img width="1274" alt="Screenshot 2024-05-13 at 12 24 00" src="https://github.com/deckhouse/deckhouse/assets/191757/5d1896d3-0e83-4470-94c1-0eadd37298e1">
<img width="1274" alt="Screenshot 2024-05-13 at 12 24 05" src="https://github.com/deckhouse/deckhouse/assets/191757/1a141352-577a-4700-ad59-0fbef3bf7c59">
<img width="1274" alt="Screenshot 2024-05-13 at 12 24 10" src="https://github.com/deckhouse/deckhouse/assets/191757/6ee224c0-48f9-414d-bb66-506108ec8919">
<img width="1274" alt="Screenshot 2024-05-13 at 12 24 15" src="https://github.com/deckhouse/deckhouse/assets/191757/1eace845-db44-41a1-b233-ef566f4a7469">
<img width="1274" alt="Screenshot 2024-05-13 at 12 24 22" src="https://github.com/deckhouse/deckhouse/assets/191757/88c5a1d9-bc1d-477f-8eef-02a10712f119">

</details>

2024-05-13 06:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-05-13 13:56 UTC, RomanenkoDenys commented on modules/040-node-manager/hooks/node_group_metrics.go
> +	HaseErrors float64
May be HasErrors ?

2024-05-13 13:56 UTC, RomanenkoDenys requested changes
Please add tests

2024-05-23 06:06 UTC, artbin commented on modules/040-node-manager/hooks/node_group_metrics.go
> +	HaseErrors float64
fixed

2024-05-24 07:31 UTC, z9r5 approved these changes

2024-05-26 19:10 UTC, name212 commented on modules/040-node-manager/docs/README_RU.md
> +Группы узлов (ресурс `NodeGroup`) экспортируют метрики доступности, которые обрабатываются Prometheus.
```suggestion
Для групп узлов (ресурс `NodeGroup`) DKP экспортируют метрики доступности группы
```

2024-05-26 19:12 UTC, name212 approved these changes

2024-05-26 19:35 UTC, RomanenkoDenys approved these changes
please see @name212 suggestion

2024-05-27 06:36 UTC, sprait approved these changes

2024-05-27 16:18 UTC, kirkonru approved these changes

2024-05-27 16:18 UTC, kirkonru commented on modules/040-node-manager/docs/README.md
> +### What information does Prometheus collect, and in what form?
```suggestion
### What information does Prometheus collect and in what form?
```

2024-05-27 16:18 UTC, kirkonru commented on modules/040-node-manager/docs/README.md
> +Metrics have the prefix `d8_node_group_`.
```suggestion
Metrics have the `d8_node_group_` prefix.
```

2024-05-27 16:18 UTC, kirkonru commented on modules/040-node-manager/docs/README.md
> +Metrics collected for each node group:
```suggestion
The following metrics are collected for each node group:
```

2024-05-27 16:18 UTC, kirkonru commented on modules/040-node-manager/docs/README.md
> +- `d8_node_group_min` — the minimal amount of instances in the group.
```suggestion
- `d8_node_group_min` — the minimum number of instances in the group.
```

2024-05-27 16:18 UTC, kirkonru commented on modules/040-node-manager/docs/README.md
> +- `d8_node_group_max` — the maximum amount of instances in the group.
```suggestion
- `d8_node_group_max` — the maximum number of instances in the group.
```

2024-05-27 16:18 UTC, kirkonru commented on modules/040-node-manager/docs/README.md
> +- `d8_node_group_standby` — the number of over provisioned instances (see [standby](cr.html#nodegroup-v1-spec-cloudinstances-standby) parameter) in the group.
```suggestion
- `d8_node_group_standby` — the number of over provisioned instances (see the [standby](cr.html#nodegroup-v1-spec-cloudinstances-standby) parameter) in the group.
```

2024-05-27 16:18 UTC, kirkonru commented on modules/040-node-manager/docs/README.md
> +- `d8_node_group_ready` — the number of ready Kubernetes nodes in the group.
```suggestion
- `d8_node_group_ready` — the number of Kubernetes nodes in the group that are `Ready`.
```

2024-05-27 16:18 UTC, kirkonru commented on modules/040-node-manager/docs/README.md
> +- `d8_node_group_has_errors` — the boolean value equal to 1 if there are errors in the group.
```suggestion
- `d8_node_group_has_errors` — equals to 1 if there are errors in the group.
```

2024-05-29 08:14 UTC, aleksey-su approved these changes

2024-05-31 07:26 UTC, merged