[cloud-provider-vcd][discovery] Support multiple VCD API versions
deckhouse/deckhouse pull request #8451
Opened 2024-05-22 11:23 UTC by asviel

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-05-23 10:37 UTC, aleksey-su approved these changes

2024-05-24 12:47 UTC, RomanenkoDenys commented on ee/candi/cloud-providers/vcd/openapi/cloud_discovery_data.yaml
> +      version:
```suggestion
      vcdApi:
```

2024-05-24 12:48 UTC, RomanenkoDenys requested changes
Please discuss openapi naming with Maksim

2024-05-25 08:43 UTC, z9r5 commented
Please note: I've changed milestone to 1.61

2024-05-26 19:55 UTC, name212 approved these changes

2024-05-27 03:08 UTC, z9r5 approved these changes

2024-05-27 08:31 UTC, asviel commented on ee/candi/cloud-providers/vcd/openapi/cloud_discovery_data.yaml
> +      version:
It's not necessary for internal values.

2024-05-29 08:34 UTC, z9r5 commented
> Please discuss openapi naming with Maksim

Discussed at a meeting.

2024-05-29 08:34 UTC, merged

2024-05-29 08:35 UTC, deckhouse-BOaTswain commented
Cherry pick PR [8527](https://github.com/deckhouse/deckhouse/pull/8527) to the branch [release-1.60](https://github.com/deckhouse/deckhouse/tree/release-1.60) successful!