[l2-load-balancer] New implementation of the module
deckhouse/deckhouse pull request #8465
Opened 2024-05-23 10:27 UTC by Beastlex

## Description
The new module l2-load-balancer.

## Why do we need it, and what problem does it solve?
In the current implementation, LoadBalancers based on MetalLB L2 are not fault-tolerant. We are introducing the ability to deploy LoadBalancer services across all load-balancer nodes simultaneously (multiple public IPs per LoadBalancer). This approach prevents the loss of all traffic when one of the speakers becomes unavailable.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: l2-load-balancer
type: feature
summary: The new module for redundant L2 load-balancing
impact_level: default
```

2024-05-28 10:05 UTC, apolovov requested changes

2024-05-28 10:05 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/discovery_l2_load_balancers.go
> +		l2lb, ok := findLoadBalancerInSnapshot(service.L2LoadBalancerName, input.Snapshots["l2loadbalancers"])
mb map?

2024-05-28 10:05 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/discovery_l2_load_balancers.go
> +			fmt.Println("There no any node with selector for deploy")
All the messages are bad.

2024-05-28 10:15 UTC, apolovov commented on ee/modules/381-l2-load-balancer/crds/l2lbservices.yaml
> +---
move to crds/internal dir.

2024-05-28 10:29 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/discovery_l2_load_balancers.go
> +	return l2loadbalancer, nil
Need an info object with name, pool and nodeSelector.

2024-05-28 10:34 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/discovery_l2_load_balancers.go
> +		for i := 1; i <= service.ExternalIPCount; i++ {
```suggestion
		for i := 1; i <= service.ExternalIPsCount; i++ {
```

2024-05-28 10:34 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/discovery_l2_load_balancers.go
> +	input.Values.Set("l2LoadBalancer.internal.l2lbservices", l2lbservices)
sort the l2lbservices before Set.

2024-05-28 10:37 UTC, apolovov commented on ee/modules/381-l2-load-balancer/images/artifact/patches/004-l2lbservice-custom-resource.patch
> +From: Alexander Zverev <beastlex@gmail.com>
```suggestion
From: xxx
```

2024-06-27 07:43 UTC, apolovov commented on ee/modules/381-l2-load-balancer/templates/speaker/_helper.tpl
> +kind: BGPAdvertisement
Don't need one.

2024-06-27 07:45 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/update_node_labels.go
> +/*
node_membership_handler

2024-07-01 08:12 UTC, apolovov commented
Need dashboards.

2024-07-01 08:54 UTC, apolovov commented
What if we deleted L2LoadBalancer resource with alive Service?

2024-07-01 09:04 UTC, apolovov requested changes

2024-07-01 09:04 UTC, apolovov commented on ee/modules/381-l2-load-balancer/templates/controller/rbac-for-us.yaml
> +      - l2lbservices/status
```suggestion
      - sdninternall2lbservices
      - sdninternall2lbservices/status
```

2024-07-03 08:01 UTC, apolovov commented on ee/modules/381-l2-load-balancer/crds/doc-ru-l2loadbalancers.yaml
> +                        Или прямого указания, например, `10.10.10.1-10.10.10.100`.
```suggestion
                        Массив диапазонов публичных IP-адресов. Каждый диапазон может быть указан с помощью CIDR или прямого указания.
```

2024-07-03 08:04 UTC, apolovov commented on ee/modules/381-l2-load-balancer/crds/l2loadbalancers.yaml
> +                APIVersion defines the versioned schema of this representation of an object.
Get rid of autogenerated docs.

2024-07-03 08:05 UTC, apolovov commented on ee/modules/381-l2-load-balancer/crds/l2loadbalancers.yaml
> +                  type: array
```suggestion
                  type: array
                  x-examples:
                  - ["10.42.0.0/24", "10.33.5.100-10.33.5.106"]
```

2024-07-03 08:08 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/discovery_l2_load_balancers.go
> +			input.MetricsCollector.Set("d8_l2_load_balancer_irrelevant_service", 1, map[string]string{"namespace": service.Namespace, "name": service.Name}, metrics.WithGroup("d8_l2_load_balancer"))
```suggestion
			input.MetricsCollector.Set("d8_l2_load_balancer_orphan_service", 1, map[string]string{"namespace": service.Namespace, "name": service.Name}, metrics.WithGroup("d8_l2_load_balancer"))
```

2024-07-03 08:09 UTC, apolovov commented on ee/modules/381-l2-load-balancer/monitoring/prometheus-rules/services.yaml
> +    - alert: L2LoadBalancerIrrelevantServiceFound
```suggestion
    - alert: L2LoadBalancerOrphanServiceFound
```

2024-07-03 08:11 UTC, apolovov commented on ee/modules/381-l2-load-balancer/monitoring/prometheus-rules/services.yaml
> +        plk_grouped_by__istio_irrelevant_external_services: L2LoadBalancerIrrelevantServices,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes
```suggestion
        plk_create_group_if_not_exists__istio_irrelevant_external_services: ClusterHasL2LoadBalancerOrphanServices,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes
        plk_grouped_by__istio_irrelevant_external_services: ClusterHasL2LoadBalancerOrphanServices,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes
```

2024-07-03 08:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2024-07-03 09:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2024-07-03 12:35 UTC, apolovov commented on ee/modules/381-l2-load-balancer/hooks/update_service_status.go
> +						Message: fmt.Sprintf("%d public IPs from %d were assigned", assignedIPs, totalIPs),
```suggestion
						Message: fmt.Sprintf("%d of %d public IPs were assigned", assignedIPs, totalIPs),
```

2024-07-03 12:37 UTC, apolovov approved these changes

2024-07-03 13:03 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/docs/README_RU.md
> +* Прикложение получит не один, а несколько "публичных" IP. Данные IP потребуется прописать в качестве A-записей для публичного домена приложения. Для последующего горизонтального масштабирования потр
```suggestion
* Приложение получит не один, а несколько "публичных" IP. Данные IP потребуется прописать в качестве A-записей для публичного домена приложения. Для последующего горизонтального масштабирования потребуется добавить дополнительные узлы-балансировщики, соответствующие _Service_ будут созданы автоматически, потребуется лишь добавить их в список A-записей прикладного домена.
```

2024-07-03 13:03 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/docs/README_RU.md
> +* Указать необходимое количетсво IP адресов для L2-анонсирования.
```suggestion
* Указать необходимое количество IP-адресов для L2-анонсирования.
```

2024-07-03 13:03 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/docs/README_RU.md
> +* Какой _L2LoadBalancer_ использовать. Задав этим набор нод и адресов.
```suggestion
* Позволяет с помощью `nodeSelector` связать группу узлов и пул IP-адресов.

После чего мы можем создать стандартный ресурс _Service_ с типом `LoadBalancer` и в нем с помощью аннотаций указать:

* Какой _L2LoadBalancer_ использовать. Задав этим набор узлов и адресов.
```

2024-07-03 13:04 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/crds/doc-ru-l2loadbalancers.yaml
> +                        Задается в виде набора лейблов для фильтрации нод.
```suggestion

                        Задается в виде набора лейблов для фильтрации узлов.
```

2024-07-03 13:05 UTC, z9r5 commented on ee/modules/381-l2-load-balancer/crds/doc-ru-l2loadbalancers.yaml
> +                        интерфейсов на ноде.
```suggestion
                        Список сетевых интерфесов, с которых будет производиться анонс присвоенных IP адресов.
                        
                        Если поле не заполнено или задан пустой массив, то будет просиходить анонс со всех
                        интерфейсов узла.
```

2024-07-05 15:11 UTC, z9r5 approved these changes

2024-07-09 10:00 UTC, nabokihms approved these changes
API - approve

2024-07-10 08:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-07-10 08:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-10 09:22 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 9870592431 9870592431-1-con-1-27 /sys/deckhouse-oss/install:pr8465 redos@158.160.34.242

2024-07-10 09:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-10 09:22 UTC, merged