[dhctl] Preflight check master hostname
deckhouse/deckhouse pull request #8515
Opened 2024-05-28 11:59 UTC by aleksey-su

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-05-29 10:36 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/3e45440c-fd08-4f3f-adbb-90859be31d0c)

2024-05-29 12:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-05-29 12:56 UTC, aleksey-su commented
/e2e/abort openstack;Standard;containerd;1.25 9286335234 9286335234-1-con-1-25 /sys/deckhouse-oss/install:pr8515

2024-05-29 12:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-05-29 13:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-05-29 13:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-05-29 13:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-05-29 13:51 UTC, aleksey-su commented
/e2e/abort openstack;Standard;containerd;1.25 9286587856 9286587856-2-con-1-25 /sys/deckhouse-oss/install:pr8515

2024-06-03 06:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-06-03 06:47 UTC, aleksey-su commented
/e2e/abort static;Static;containerd;1.25 9345350760 9345350760-1-con-1-25 /sys/deckhouse-oss/install:pr8515 astra@192.168.199.17

2024-06-03 06:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-06-03 06:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-06-03 09:41 UTC, aleksey-su commented
/e2e/abort static;Static;containerd;1.25 9345598302 9345598302-1-con-1-25 /sys/deckhouse-oss/install:pr8515 astra@192.168.199.170

2024-06-03 09:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-06-17 09:06 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/6b77cd5c-1ef4-46e9-a1f7-d6a13dc5f973)

2024-06-17 09:18 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/f16e33cd-b50e-45c5-9bf0-ff0d34c32c09)
![image](https://github.com/deckhouse/deckhouse/assets/485892/a71bc1f7-77cf-4e2d-bcd8-23daf1c63595)

2024-06-17 09:20 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-06-17 10:17 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/2c1a635f-36e3-432e-9434-3a51b9e45fcd)

2024-06-17 12:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-06-17 13:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-06-17 18:08 UTC, aleksey-su commented
/e2e/abort static;Static;containerd;1.25 9548604724 9548604724-1-con-1-25 /sys/deckhouse-oss/install:pr8515 astra@192.168.199.136

2024-06-17 18:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-06-19 06:39 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/5023ddd9-9da7-4dc7-b153-6e77cf1e3f45)
![image](https://github.com/deckhouse/deckhouse/assets/485892/0e368fa3-82b2-49d0-a5ab-2a8b05b8c45a)

2024-06-19 07:02 UTC, aleksey-su commented
![image](https://github.com/deckhouse/deckhouse/assets/485892/cadc2cb7-abbd-4270-baeb-2f7f759229fc)
![image](https://github.com/deckhouse/deckhouse/assets/485892/9ac68001-58cf-4046-8b13-aff6e981a74f)

2024-06-19 07:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-06-21 09:10 UTC, aleksey-su commented
/e2e/abort static;Static;containerd;1.27 9577624365 9577624365-1-con-1-27 /sys/deckhouse-oss/install:pr8515 astra@192.168.199.203

2024-06-21 09:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-06-21 09:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-06-21 09:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-06-21 10:52 UTC, mvasl requested changes

2024-06-21 10:52 UTC, mvasl commented on dhctl/pkg/app/preflight.go
> +// Copyright 2024 Flant JSC
No need for this, file was first created in 2023

2024-06-21 10:52 UTC, mvasl commented on dhctl/pkg/preflight/preflight.go
> +// Copyright 2024 Flant JSC
No need for this, file was first created in 2023

2024-06-21 10:52 UTC, mvasl commented on dhctl/pkg/preflight/ssh.go
> +			"for the bootstrap first master, only one --ssh-host parameter should be used for a static cluster",
"During the bootstrap of the first static master node, only one --ssh-host parameter is allowed"

2024-06-21 10:52 UTC, mvasl commented on dhctl/pkg/template/preflight.go
> +// Copyright 2024 Flant JSC
No need for this, file was first created in 2023

2024-06-21 13:40 UTC, aleksey-su commented
/e2e/abort static;Static;containerd;1.27 9611766608 9611766608-1-con-1-27 /sys/deckhouse-oss/install:pr8515 astra@192.168.199.144

2024-06-21 13:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-06-21 18:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-06-24 16:58 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.27 9552600575 9552600575-1-con-1-27 /sys/deckhouse-oss/install:pr8515 astra@192.168.199.188

2024-06-24 16:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-08 06:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-08 09:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-08 11:57 UTC, mvasl commented
Is there really no way to make candi/bashible/common-steps/node-group/069_check_hostname_uniqueness.sh.tpl cleaner? It's really hard to read and will be a nightmare to support

2024-07-09 19:27 UTC, name212 approved these changes

2024-07-11 08:04 UTC, mvasl approved these changes

2024-07-11 09:45 UTC, deckhouse-BOaTswain commented
Aye, aye, @aleksey-su. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-12 06:55 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.27 9889209892 9889209892-2-con-1-27 /sys/deckhouse-oss/install:pr8515 astra@192.168.199.241

2024-07-12 06:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-12 06:56 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.27 9889209892 9889209892-1-con-1-27 /sys/deckhouse-oss/install:pr8515 astra@192.168.199.5

2024-07-12 06:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-24 09:09 UTC, RomanenkoDenys approved these changes

2024-07-24 09:45 UTC, merged