bashible: creating deckhouser user and group
deckhouse/deckhouse pull request #8595
Opened 2024-06-03 12:21 UTC by borg-z

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-06-03 14:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-06-03 15:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-06-04 08:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-06-11 10:59 UTC, RomanenkoDenys commented on candi/bashible/bashbooster/30_user.sh
> +    if id "$username" &>/dev/null; then
what is &> ?

2024-06-11 11:00 UTC, RomanenkoDenys commented on candi/bashible/bashbooster/30_user.sh
> +            bb-log-warning "User $username with UID $userid and GID $groupid already exists. No changes needed."
```suggestion
           
```

2024-06-11 11:12 UTC, RomanenkoDenys commented on candi/bashible/bashbooster/30_user.sh
> +    fi
```suggestion
uid="$(id -u "${username}")"
gid="$(id -g "${groupname}")"

if [ "$(id -u "${username}")" -eq "${userid}" ] && [ "$(id -g "${groupname}")" -eq "${groupid}" ]; then
  return
fi 


if [ -n $uid ] && [ -n $gid ]; then
 bb-log-warning "user or group already exists with different id: uid=${uid}, gid=${gid}"
 return
}

useradd -m -u "$userid" -g "$groupname" "$username"
```

2024-06-11 11:12 UTC, RomanenkoDenys requested changes
some little nits

2024-06-19 15:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-06-19 16:23 UTC, name212 commented
/e2e/abort gcp;WithoutNAT;containerd;1.25 9584634962 9584634962-1-con-1-25 /sys/deckhouse-oss/install:pr8595 user@35.234.91.71

2024-06-19 16:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-06-19 19:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-06-24 11:39 UTC, name212 approved these changes

2024-06-24 11:40 UTC, merged