Chore/dhctl for commander prepare detach cluster
deckhouse/deckhouse pull request #8607
Opened 2024-06-04 08:19 UTC by faroyam

2024-06-10 09:14 UTC, aleksey-su requested changes

2024-06-10 09:35 UTC, faroyam commented on dhctl/pkg/kubernetes/actions/converge/converge.go
> +	"github.com/google/uuid"
thanks, now the imports are sorted

2024-06-10 09:35 UTC, faroyam commented on dhctl/pkg/kubernetes/actions/resources/resources.go
> +				}
added logging and removed code duplication

2024-06-10 09:35 UTC, faroyam commented on dhctl/pkg/kubernetes/actions/resources/resources.go
> +	return namespaced, nil
fixed

2024-06-10 09:43 UTC, aleksey-su approved these changes

2024-06-19 13:55 UTC, name212 commented on dhctl/pkg/kubernetes/actions/resources/resources.go
> +	return isNamespaced(c.kubeCl, gvk, name)
better rename function. In the first time I thought that is recursion method

2024-06-19 14:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-06-19 15:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-06-19 16:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-06-20 02:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-06-20 05:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-06-20 05:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-06-20 05:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-06-20 06:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-06-20 06:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @faroyam. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-06-20 11:28 UTC, name212 approved these changes

2024-06-20 11:29 UTC, merged

2024-06-20 11:29 UTC, deckhouse-BOaTswain commented
Cherry pick PR [8740](https://github.com/deckhouse/deckhouse/pull/8740) to the branch [release-1.61](https://github.com/deckhouse/deckhouse/tree/release-1.61) successful!

2024-06-24 16:47 UTC, z9r5 commented
/e2e/abort aws;WithoutNAT;containerd;1.25 9592270232 9592270232-1-con-1-25 /sys/deckhouse-oss/install:pr8607 centos@35.157.240.156

2024-06-24 16:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-06-29 11:51 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.25 9584554364 9584554364-1-con-1-25 /sys/deckhouse-oss/install:pr8607 redos@158.160.101.239

2024-06-29 11:52 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->