rels cobalt
deckhouse/deckhouse pull request #8666
Opened 2024-06-11 10:50 UTC by borg-z

Signed-off-by: borg-z <me@nikolay-z.top>

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-06-17 09:52 UTC, RomanenkoDenys commented on ee/be/candi/bashible/detect_bundle.sh
> +    case "$VERSION_ID" in 7|7.*)
Why you remove Redos 8?

2024-06-17 09:53 UTC, RomanenkoDenys commented on ee/be/modules/600-flant-integration/images/flant-pricing/hooks/prometheus_metrics.sh
> -                "(?:(redos).*(7))",
@asviel please give attention

2024-06-17 09:54 UTC, RomanenkoDenys commented on ee/be/candi/bashible/bundles/rels/all/002_install_ca_certificates.sh.tpl
> +# Copyright 2022 Flant JSC
```suggestion
# Copyright 2024 Flant JSC
```
Please change in all files for Rosa bundle

2024-06-17 09:54 UTC, RomanenkoDenys requested changes
some nits

2024-06-17 09:56 UTC, asviel commented on ee/be/modules/600-flant-integration/images/flant-pricing/hooks/prometheus_metrics.sh
> -                "(?:(redos).*(7))",
thx

2024-06-17 10:20 UTC, borg-z commented on ee/be/candi/bashible/detect_bundle.sh
> +    case "$VERSION_ID" in 7|7.*)
resl <-> redos

2024-06-17 10:33 UTC, RomanenkoDenys approved these changes

2024-06-17 11:42 UTC, sprait commented on ee/be/candi/bashible/bundles/rels/node-group/004_install_mandatory_packages_for_cloud_nodes.sh.tpl
> +bb-yum-install cloud-utils-growpart
we can try it. I see that growpart it is shell script, which used binaries sfdisk/sgdisk

2024-06-17 11:44 UTC, RomanenkoDenys commented on ee/be/candi/bashible/bundles/rels/node-group/004_install_mandatory_packages_for_cloud_nodes.sh.tpl
> +bb-yum-install cloud-utils-growpart
we should do not install unneeded binaries, so we need solution to do growpart

2024-06-19 20:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-06-25 12:53 UTC, RomanenkoDenys approved these changes

2024-06-27 12:03 UTC, name212 approved these changes

2024-06-28 04:59 UTC, z9r5 approved these changes

2024-06-28 11:23 UTC, merged