[docs] Add information and command to access Deckhouse controller in HA mode
deckhouse/deckhouse pull request #8668
Opened 2024-06-11 13:21 UTC by haosb

## Description

This PR will add information and command to access Deckhouse controller in HA mode.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: docs
type: fix
summary: Add information and command to access Deckhouse controller in HA mode 
impact_level: default

2024-06-11 13:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @haosb. I've started the workflow for label 'deploy/web/stage'...
<!-- workflow_start -->

2024-06-12 16:57 UTC, miklezzzz approved these changes
the command and its documentation in general are fine, but I can't help wondering if we should go this way instead of providing a more elegant way of working with replicated Deckhouse instances in the first place.

2024-06-14 15:01 UTC, kirkonru requested changes

2024-06-27 18:07 UTC, z9r5 commented on docs/documentation/pages/DECKHOUSE-FAQ_RU.md
> +В кластерах с несколькими master-узлами Deckhouse запускается в режиме высокой доступности. Поэтому для привычного доступа к контроллеру Deckhouse нужно использовать команду:
```suggestion
В кластерах с несколькими master-узлами Deckhouse запускается в режиме высокой доступности (в нескольких экземплярах). Для доступа к активному контроллеру Deckhouse можно использовать следующую команду (на примере команды `deckhouse-controller queue list`):
```

2024-06-27 18:07 UTC, z9r5 commented on docs/documentation/pages/DECKHOUSE-FAQ_RU.md
> +
```suggestion

```

2024-06-27 18:07 UTC, z9r5 commented on docs/documentation/pages/DECKHOUSE-FAQ.md
> +In clusters with multiple master nodes, Deckhouse runs in high availability mode. This is why you have to use the following command to access the Deckhouse controller:
```suggestion
In clusters with multiple master nodes Deckhouse runs in high availability mode (in several instances). To access the active Deckhouse controller, you can use the following command (as an example of the command `deckhouse-controller queue list`):
```

2024-06-27 18:07 UTC, z9r5 commented on docs/documentation/pages/DECKHOUSE-FAQ.md
> +
```suggestion

```

2024-06-27 18:10 UTC, merged

2024-06-27 18:11 UTC, deckhouse-BOaTswain commented
Cherry pick PR [8843](https://github.com/deckhouse/deckhouse/pull/8843) to the branch [release-1.61](https://github.com/deckhouse/deckhouse/tree/release-1.61) successful!