Add missing variable to deprecated-apis dashboard
deckhouse/deckhouse pull request #8689
Opened 2024-06-14 11:01 UTC by Regrau

## Description
A variable was missing in the Kubernetes Cluster/Deprecated APIs dasboard. Commit adds the variable so the dashboard works again.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-06-17 10:04 UTC, vladimirGuryanov requested changes

2024-06-17 10:04 UTC, vladimirGuryanov commented on modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/deprecated-resources.json
> +      },
Not valid json, you have an extra comma.

2024-06-17 10:04 UTC, vladimirGuryanov commented on modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/deprecated-resources.json
> +        "queryValue": "",
This variable must be hidden. You can use something like this:
```json
  "templating": {
    "list": [
       {
        "current": {
          "selected": false,
          "text": "default",
          "value": "default"
        },
        "hide": 2,
        "includeAll": false,
        "label": "Prometheus",
        "multi": false,
        "name": "ds_prometheus",
        "options": [],
        "query": "prometheus",
        "queryValue": "",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "type": "datasource"
      },
      {
        "datasource": {
          "type": "prometheus",
          "uid": "$ds_prometheus"
        },
        "definition": "label_values(apiserver_requested_deprecated_apis, removed_release)",
        "hide": 0,
        "includeAll": false,
        "label": "Desired K8s version",
        "multi": false,
        "name": "k8s",
        "options": [],
        "query": {
          "query": "label_values(apiserver_requested_deprecated_apis, removed_release)",
          "refId": "StandardVariableQuery"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
...

2024-06-17 12:22 UTC, vladimirGuryanov approved these changes

2024-06-18 11:58 UTC, nabokihms approved these changes

2024-06-18 11:58 UTC, merged

2024-06-24 10:47 UTC, deckhouse-BOaTswain commented
Cherry pick PR [8766](https://github.com/deckhouse/deckhouse/pull/8766) to the branch [release-1.61](https://github.com/deckhouse/deckhouse/tree/release-1.61) successful!