[docs] Add examples for Blitz OIDC
deckhouse/deckhouse pull request #8697
Opened 2024-06-14 16:46 UTC by kusaleev

## Description

Add examples and description for Blitz OIDC

## Why do we need it, and what problem does it solve?

Extends documentation with real integration examples.

## Why do we need it in the patch release (if we do)?

No needed.

## What is the expected result?

The documentation has been updated on the website.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: doc
type: feature
summary: Added examples for Blitz oidc.
impact_level: low
```

2024-06-19 11:55 UTC, VV-corrector commented on modules/150-user-authn/docs/USAGE_RU.md
> +Для того чтобы корректно отрабатывал выход из приложений (происходил отзыв токена и требовалась повторная авторизация), нужно установить `login` в значении параметра `promptType`.
«Для того чтобы» → «Чтобы»

2024-06-19 11:56 UTC, VV-corrector commented on modules/150-user-authn/docs/USAGE_RU.md
> +* Добавить группы к пользователю (наименования групп должны совпадать как на стороне Blitz, так и на стороне Deckhouse).
```suggestion
* добавить параметр `allowedUserGroups` в `ModuleConfig` нужного приложения;
* добавить группы к пользователю (наименования групп должны совпадать как на стороне Blitz, так и на стороне Deckhouse).
```

2024-06-19 13:45 UTC, kirkonru approved these changes

2024-06-19 14:02 UTC, Zhbert approved these changes

2024-06-21 08:45 UTC, nabokihms approved these changes

2024-06-21 08:47 UTC, nabokihms requested changes
Could you please run `make lint-markdown-fix` to satisfy the linter?

2024-06-21 10:53 UTC, Zhbert commented
> Could you please run `make lint-markdown-fix` to satisfy the linter?

Done.

2024-06-21 13:17 UTC, merged