grafana 10 ingress tls fixes
deckhouse/deckhouse pull request #8749
Opened 2024-06-21 09:46 UTC by ghostinsoba

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-06-21 21:08 UTC, vladimirGuryanov requested changes

2024-06-21 21:08 UTC, vladimirGuryanov commented on modules/300-prometheus/templates/grafana/ingress-v10.yaml
> ----
Looks like it was removed by mistake

2024-06-21 21:08 UTC, vladimirGuryanov commented on modules/300-prometheus/templates/grafana/ingress.yaml
> ----
Looks like it was removed by mistake

2024-06-21 21:08 UTC, vladimirGuryanov commented on modules/300-prometheus/templates/grafana/certificate.yaml
> +apiVersion: cert-manager.io/v1
Need add ---

2024-06-24 07:38 UTC, ghostinsoba commented on modules/300-prometheus/templates/grafana/certificate.yaml
> +apiVersion: cert-manager.io/v1
fixed

2024-06-24 07:38 UTC, ghostinsoba commented on modules/300-prometheus/templates/grafana/ingress.yaml
> ----
fixed

2024-06-24 07:38 UTC, ghostinsoba commented on modules/300-prometheus/templates/grafana/ingress-v10.yaml
> ----
fixed

2024-06-24 08:09 UTC, vladimirGuryanov approved these changes

2024-06-24 13:26 UTC, merged