[node-manager] caps: allow to skip bootstrap phases for nodes
deckhouse/deckhouse pull request #8753
Opened 2024-06-21 11:56 UTC by mvasl

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-06-26 12:00 UTC, deckhouse-BOaTswain commented
Aye, aye, @mvasl. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-06-26 12:16 UTC, mvasl commented
![Uploading Снимок экрана 2024-06-26 в 14.54.58.png…]()

2024-07-01 13:12 UTC, RomanenkoDenys approved these changes

2024-07-01 13:22 UTC, mvasl commented on modules/040-node-manager/images/caps-controller-manager/src/internal/controller/deckhouse.io/staticinstance_controller.go
> +		machine = &tmp
Done

2024-07-01 13:27 UTC, RomanenkoDenys commented on modules/040-node-manager/images/caps-controller-manager/src/internal/controller/deckhouse.io/staticinstance_controller.go
> +		machine = &tmp
You know what to do )

2024-07-02 17:04 UTC, name212 approved these changes

2024-07-02 17:06 UTC, name212 commented
@mvasl Can we add `static.node.deckhouse.io/skip-bootstrap-phase` for master node in the Static test?

2024-07-02 17:07 UTC, name212 requested changes
question

2024-07-03 09:54 UTC, mvasl commented
We may try that once we fix daily e2e static

2024-07-09 12:16 UTC, artbin approved these changes

2024-07-09 19:40 UTC, name212 approved these changes

2024-07-09 19:41 UTC, merged

2024-07-15 13:28 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-08-05 08:46 UTC, mvasl commented
/e2e/abort vclouddirector;Standard;containerd;1.27 9940323137 9940323137-1-con-1-27 /sys/deckhouse-oss/install:pr8753