Switch snapshot-controller to distroless
deckhouse/deckhouse pull request #8769
Opened 2024-06-24 12:00 UTC by duckhawk

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-06-25 12:46 UTC, RomanenkoDenys commented on modules/045-snapshot-controller/images/snapshot-validation-webhook/werf.inc.yaml
> +from: {{ $.Images.BASE_GOLANG_20_ALPINE }}
```suggestion
from: {{ $.Images.BASE_GOLANG_22_ALPINE_DEV }}
```

2024-06-25 12:47 UTC, RomanenkoDenys commented on modules/045-snapshot-controller/images/snapshot-validation-webhook/werf.inc.yaml
> +    - apk add --no-cache ca-certificates make git
```suggestion
```

2024-06-25 12:51 UTC, RomanenkoDenys commented on modules/045-snapshot-controller/images/snapshot-controller/werf.inc.yaml
> +from: {{ $.Images.BASE_GOLANG_20_ALPINE }}
```suggestion
from: {{ $.Images.BASE_GOLANG_22_ALPINE_DEV }}
```

2024-06-25 12:51 UTC, RomanenkoDenys commented on modules/045-snapshot-controller/images/snapshot-controller/werf.inc.yaml
> +    - apk add --no-cache ca-certificates make git
```suggestion
```

2024-06-25 12:51 UTC, RomanenkoDenys requested changes
some nits

2024-07-01 09:18 UTC, RomanenkoDenys approved these changes

2024-07-01 09:30 UTC, AleksZimin approved these changes

2024-07-01 09:48 UTC, merged