[istio] Adding user authentication to Kiali
deckhouse/deckhouse pull request #8830
Opened 2024-06-27 09:22 UTC by tarabrind

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-07-18 14:41 UTC, apolovov commented on modules/110-istio/hooks/generate_kiali_signing_key.go
> +	return nil
Generate the key here, not in helm template.

2024-07-18 14:47 UTC, apolovov commented on modules/110-istio/templates/kiali/configmap.yaml
>  data:
Need to wipe extra privileges from rpac-for-us. I suppose, that we need to wipe all the clusterroles.

2024-07-22 21:47 UTC, apolovov requested changes

2024-07-22 21:47 UTC, apolovov commented on modules/110-istio/hooks/generate_kiali_signing_key.go
> +	for _, secretSnapshot := range input.Snapshots["kiali_signing_key_secret"] {
it is better to check if the snapshot len is 1.
And the preferred algorithm is:
```
var kialiSigningKey string
if len == 1:
  kialiSigningKey = snapshot.SigningKey
else:
  kialiSigningKey = randomString(32)
end

input.Values.Set("istio.internal.kialiSigningKey", kialiSigningKey)
```

2024-07-22 21:47 UTC, apolovov commented on modules/110-istio/hooks/generate_kiali_signing_key_test.go
> +	Context("Empty cluster; empty value; secret don not exist", func() {
```suggestion
	Context("Empty cluster; empty value; secret doesn't exist", func() {
```

2024-07-22 21:47 UTC, apolovov commented on modules/110-istio/hooks/generate_kiali_signing_key_test.go
> +  key: "NVo4ZFFlT2l1RkpRTllQa2duMmh1bEE0M3FuRzZ0SGI="
```suggestion
  key: "NVo4ZFFlT2l1RkpRTllQa2duMmh1bEE0M3FuRzZ0SGI=" # 5Z8dQeOiuFJQNYPkgn2hulA43qnG6tHb
```

2024-07-22 21:47 UTC, apolovov commented on modules/110-istio/openapi/values.yaml
> +        default: "kiali"
```suggestion
```
Don't need the default value.

2024-07-23 13:21 UTC, apolovov commented on modules/110-istio/openapi/values.yaml
> +        x-examples: "FD9Q24PwNZkg4pV9cxTOV1Se5R0RD1sT"
```suggestion
        x-examples:
        - "FD9Q24PwNZkg4pV9cxTOV1Se5R0RD1sT"
```

2024-07-23 13:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-23 13:53 UTC, tarabrind commented
/e2e/abort openstack;Standard;containerd;1.27 10060142204 10060142204-1-con-1-27 /sys/deckhouse-oss/install:pr8830

2024-07-23 13:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-07-23 13:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-23 15:08 UTC, apolovov commented on modules/110-istio/hooks/generate_kiali_signing_key_test.go
> +
```suggestion

	Context("Wrong signing key is in cluster; empty value", func() {
		BeforeEach(func() {
			f.BindingContexts.Set(f.KubeStateSet(`
---
apiVersion: v1
kind: Secret
metadata:
  name: kiali-signing-key
  namespace: d8-istio
type: Opaque
data:
  key: "d3Jvbmcta2V5" # "wrong-key", not 32 bytes len
`))
			f.RunHook()
		})
		It("Signing key must be generated anew", func() {
			Expect(f).To(ExecuteSuccessfully())
			Expect(f.BindingContexts.Array()).ShouldNot(BeEmpty())

			Expect(len(f.ValuesGet("istio.internal.kialiSigningKey").String())).To(Equal(32))
		})
	})
```

2024-07-23 15:21 UTC, apolovov approved these changes

2024-07-25 08:45 UTC, merged