[chrony] Remove unnecessary permissions and capabilities from chrony and chrony-master
deckhouse/deckhouse pull request #8881
Opened 2024-07-02 12:29 UTC by tarabrind

## Description
Now chrony and chrony-master run as root and have many Linux capabilities. Also, chrony listens on port 123 even though it's not needed.

## Why do we need it, and what problem does it solve?
This will reduce security risks.

## What is the expected result?
- Chrony does not listen on port 123
- Chrony and chrony-master only run with the necessary permissions

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: chore
summary: Removed unnecessary permissions and capabilities from chrony and chrony-master
impact_level: default
```

2024-07-08 11:23 UTC, tarabrind commented
```
root@plodder-master-0:~# kubectl -n d8-chrony get pods -o wide
NAME                  READY   STATUS    RESTARTS   AGE    IP             NODE                                  NOMINATED NODE   READINESS GATES
chrony-master-pw9r2   1/1     Running   0          112s   10.111.0.68    plodder-master-0                      <none>           <none>
chrony-mnsgt          1/1     Running   0          71s    10.111.4.236   plodder-worker-e28794c8-6dfbf-r6zdx   <none>           <none>
chrony-pgwxx          1/1     Running   0          41s    10.111.1.213   plodder-worker-e28794c8-6dfbf-6j7t6   <none>           <none>

root@plodder-master-0:~# kubectl -n d8-chrony exec chrony-mnsgt -- /opt/chrony-static/bin/chronyc sources
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^- 10-111-0-68.chrony-maste>     4   6    37    26    +20us[ +213us] +/- 2832us
^* time.jaa.richiefi.net         1   6    37    25  -8675ns[ +185us] +/-  605us
^- time.cloudflare.com           3   6    37    25   +151us[ +151us] +/- 4147us
^- zabbix.sarik.tech             2   6    37    25   -281us[ -281us] +/-   38ms
^+ static.141.138.216.95.cl>     3   6    37    26    +20us[ +213us] +/- 1378us

root@plodder-master-0:~# kubectl -n d8-chrony exec chrony-pgwxx -- /opt/chrony-static/bin/chronyc sources
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^- 10-111-0-68.chrony-maste>     4   6    37     6    +68us[  +68us] +/- 1506us
^- zabbix.sarik.tech             2   6    37     6   -154us[ -154us] +/-   38ms
^- static.141.138.216.95.cl>     3   6    37     6   +118us[ +118us] +/- 1370us
^* time.jaa.richiefi.net         1   6    37     7   -788ns[ -226us] +/-  523us
^- time.cloudflare.com           3   6    37     6   +121us[ +121us] +/- 4166us
```

2024-07-08 11:24 UTC, tarabrind commented
```shell
root@plodder-master-0:~# ip -br ad | grep ens3
ens3             UP             192.168.199.78/24 metric 100 fe80::f816:3eff:fe8a:6d42/64

root@plodder-master-0:~# ntpdate -u 192.168.199.78
 8 Jul 11:18:37 ntpdate[93336]: adjust time server 192.168.199.78 offset -0.000013 sec
```

2024-07-08 11:25 UTC, tarabrind commented
```shell
root@plodder-master-0:~# date
Mon Jul  8 11:21:00 UTC 2024

root@plodder-master-0:~# date -s "$(date -d "+1 minutes" +'%Y-%m-%d %H:%M:%S')"
Mon Jul  8 11:22:05 UTC 2024

root@plodder-master-0:~# kubectl -n d8-chrony logs chrony-master-8f9sz
2024-07-08T11:23:02Z chronyd version 4.4 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER -SIGND +ASYNCDNS -NTS -SECHASH +IPV6 -DEBUG)
2024-07-08T11:23:02Z Initial frequency -6.591 ppm
2024-07-08T11:23:07Z Selected source 185.251.115.30 (pool.ntp.org.)
2024-07-08T11:23:07Z System clock wrong by -59.122394 seconds
2024-07-08T11:22:08Z System clock was stepped by -59.122394 seconds
```

2024-07-09 08:34 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-10 10:27 UTC, apolovov requested changes

2024-07-10 12:00 UTC, tarabrind commented on modules/470-chrony/templates/daemonset.yaml
>              - DAC_OVERRIDE
Comments are added

2024-07-10 12:03 UTC, tarabrind commented on modules/470-chrony/templates/configmap.yaml
> +    pool {{ .ChronyMastersService }} iburst port 42123
Service was changed.

2024-07-10 12:39 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-10 13:37 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-10 14:22 UTC, tarabrind commented
/e2e/abort static;Static;containerd;1.27 9874362113 9874362113-1-con-1-27 /sys/deckhouse-oss/install:pr8881 astra@192.168.199.56

2024-07-10 14:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-11 07:44 UTC, apolovov requested changes

2024-07-11 07:44 UTC, apolovov commented on modules/470-chrony/templates/daemonset.yaml
> +            # Chrony can change system time.
```suggestion
            # Chrony is designed to adjust system time.
```

2024-07-11 07:44 UTC, apolovov commented on modules/470-chrony/templates/service.yaml
> +      port: 4123
```suggestion
      port: 123
```

2024-07-11 10:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-11 12:14 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-11 12:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-15 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-15 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-15 22:33 UTC, apolovov approved these changes

2024-07-16 04:52 UTC, z9r5 approved these changes

2024-07-23 08:43 UTC, apolovov approved these changes

2024-07-23 08:47 UTC, apolovov requested changes
.PodIP -> HostIP

2024-07-23 15:12 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-07-24 07:52 UTC, apolovov approved these changes

2024-07-25 08:38 UTC, RomanenkoDenys approved these changes

2024-07-25 08:47 UTC, merged