[cloud-provider-*] Minimize RBAC permissions by removing the wildcard…
deckhouse/deckhouse pull request #8969
Opened 2024-07-09 12:39 UTC by artbin

… "*" from ClusterRole

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-07-10 07:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-10 07:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-07-10 08:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-07-10 08:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-07-10 12:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-07-10 12:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-10 13:13 UTC, artbin commented
/e2e/abort vclouddirector;Standard;containerd;1.27 9874538858 9874538858-1-con-1-27 /sys/deckhouse-oss/install:pr8969

2024-07-10 13:13 UTC, artbin commented
/e2e/abort static;Static;containerd;1.27 9874539726 9874539726-1-con-1-27 /sys/deckhouse-oss/install:pr8969 astra@192.168.199.122

2024-07-10 13:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-10 13:13 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-10 23:17 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-07-11 09:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-07-16 03:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-16 03:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-07-16 03:59 UTC, artbin commented
/e2e/abort vclouddirector;Standard;containerd;1.27 9888595355 9888595355-2-con-1-27 /sys/deckhouse-oss/install:pr8969 ubuntu@192.168.254.95

2024-07-16 03:59 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-16 06:46 UTC, artbin commented
/e2e/abort openstack;Standard;containerd;1.27 9950499571 9950499571-1-con-1-27 /sys/deckhouse-oss/install:pr8969 redos@45.12.229.213

2024-07-16 06:46 UTC, artbin commented
/e2e/abort aws;WithoutNAT;containerd;1.27 9950499577 9950499577-1-con-1-27 /sys/deckhouse-oss/install:pr8969 ec2-user@3.71.212.2

2024-07-16 06:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-16 06:46 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-16 07:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-07-16 08:03 UTC, artbin commented
/e2e/abort aws;WithoutNAT;containerd;1.27 9952223778 9952223778-1-con-1-27 /sys/deckhouse-oss/install:pr8969 ec2-user@18.194.141.49

2024-07-16 08:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-23 12:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-23 12:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-07-23 14:00 UTC, artbin commented
/e2e/abort openstack;Standard;containerd;1.27 10059390262 10059390262-1-con-1-27 /sys/deckhouse-oss/install:pr8969

2024-07-23 14:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-23 14:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2024-07-23 14:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-07-23 14:01 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-07-23 14:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-07-23 14:31 UTC, z9r5 commented
/e2e/abort openstack;Standard;containerd;1.27 10060416502 10060416502-1-con-1-27 /sys/deckhouse-oss/install:pr8969

2024-07-23 14:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-08-05 09:40 UTC, aleksey-su approved these changes

2024-08-10 17:37 UTC, name212 commented on ee/modules/030-cloud-provider-openstack/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
please add deletecollection too.
 
https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-10 17:38 UTC, name212 commented on ee/modules/030-cloud-provider-vcd/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
please add `deletecollection` too.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-10 17:38 UTC, name212 commented on ee/modules/030-cloud-provider-vsphere/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
please add `deletecollection` too.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-10 17:38 UTC, name212 commented on ee/modules/030-cloud-provider-zvirt/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
please add `deletecollection` too.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-10 17:38 UTC, name212 commented on modules/030-cloud-provider-aws/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
please add `deletecollection` too.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-10 17:38 UTC, name212 commented on modules/030-cloud-provider-azure/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
please add `deletecollection` too.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-10 17:38 UTC, name212 commented on modules/030-cloud-provider-gcp/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
please add `deletecollection` too.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-10 17:39 UTC, name212 commented on modules/030-cloud-provider-yandex/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
please add `deletecollection` too.

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-10 17:39 UTC, name212 requested changes
please add `deletecollection` in the all cloud providers for `node` object

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-non-resource

2024-08-12 09:30 UTC, artbin commented on ee/modules/030-cloud-provider-openstack/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
added

2024-08-12 09:30 UTC, artbin commented on ee/modules/030-cloud-provider-vcd/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
added

2024-08-12 09:30 UTC, artbin commented on ee/modules/030-cloud-provider-vsphere/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
added

2024-08-12 09:30 UTC, artbin commented on ee/modules/030-cloud-provider-zvirt/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
added

2024-08-12 09:30 UTC, artbin commented on modules/030-cloud-provider-aws/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
added

2024-08-12 09:30 UTC, artbin commented on modules/030-cloud-provider-azure/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
added

2024-08-12 09:30 UTC, artbin commented on modules/030-cloud-provider-gcp/templates/cloud-controller-manager/rbac-for-us.yaml
> +  - delete
added

2024-08-12 10:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-08-12 11:10 UTC, artbin commented
/e2e/abort aws;WithoutNAT;containerd;1.27 10349799330 10349799330-1-con-1-27 /sys/deckhouse-oss/install:pr8969 ec2-user@3.72.189.107

2024-08-12 11:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-08-12 11:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-08-12 11:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/azure'...
<!-- workflow_start -->

2024-08-12 12:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-08-12 12:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-08-12 12:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-08-12 13:42 UTC, artbin commented
/e2e/abort vsphere;Standard;containerd;1.27 10351569840 10351569840-1-con-1-27 /sys/deckhouse-oss/install:pr8969 ubuntu@10.220.203.26

2024-08-12 13:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-08-12 13:43 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-08-12 14:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-08-12 16:49 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-08-14 15:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/vsphere'...
<!-- workflow_start -->

2024-08-14 17:19 UTC, name212 approved these changes

2024-08-14 17:20 UTC, merged