[e2e] Add tests for networks' modules
deckhouse/deckhouse pull request #9025
Opened 2024-07-15 08:54 UTC by Beastlex

## Description
e2e-tests for modules:
* istio
* static-routing-manager

## Why do we need it, and what problem does it solve?
Tests will help identify module deployment errors at an early stage.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: e2e
type: chore
summary: tests for networks' modules
impact_level: low
```

2024-07-15 09:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-15 11:41 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-22 20:48 UTC, apolovov requested changes

2024-07-22 20:48 UTC, apolovov commented on testing/cloud_layouts/script.d/wait_cluster_ready/test_script.sh
> +if [ "$(kubectl -n d8-istio get po | grep operator | wc -l)" -gt 0 ]; then
Why operator? We need the running istiod pod.

2024-07-22 20:48 UTC, apolovov commented on testing/cloud_layouts/Static/resources.tpl.yaml
> +    dedicated.worker: ""
Egressgateway with virtual ip too!

2024-07-24 09:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-24 10:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-07-25 06:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-07-25 08:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-07-25 09:53 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-07-25 12:03 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-07-25 13:32 UTC, apolovov approved these changes

2024-07-25 13:32 UTC, merged

2024-07-25 14:44 UTC, z9r5 commented
/e2e/abort static;Static;containerd;1.27 10073762070 10073762070-1-con-1-27 /sys/deckhouse-oss/install:pr9025 astra@192.168.199.41

2024-07-25 14:44 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-25 14:48 UTC, z9r5 commented
/e2e/abort gcp;WithoutNAT;containerd;1.27 10093718612 10093718612-1-con-1-27 /sys/deckhouse-oss/install:pr9025 user@34.141.22.111

2024-07-25 14:48 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-25 15:04 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10090387397 10090387397-1-con-1-27 /sys/deckhouse-oss/install:pr9025 redos@89.169.129.14

2024-07-25 15:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-07-25 15:05 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10089453785 10089453785-1-con-1-27 /sys/deckhouse-oss/install:pr9025 redos@89.169.129.157

2024-07-25 15:05 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->