[monitoring] Remove trickster
deckhouse/deckhouse pull request #9027
Opened 2024-07-15 10:21 UTC by Regrau

## Description
This PR removes trickster from some modules.

## Why do we need it, and what problem does it solve?
Trickster and the aggregation proxy are solving the same problem. Hence removing trickster
and using the aggregation proxy helps remove redundancy.

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: chore
summary: Remove Trickster.
impact: Prometheus will restart.
---
section: prometheus-metrics-adapter
type: chore
summary: Use aggergating proxy instead of Trickster.
impact: prometheus-metrics-adapter will restart.
```

2024-07-15 13:45 UTC, z9r5 approved these changes

2024-07-16 08:44 UTC, vladimirGuryanov requested changes

2024-07-16 08:44 UTC, vladimirGuryanov commented on modules/110-istio/templates/kiali/rbac-for-us.yaml
> -- apiGroups: ["apps"]
If you remove only the RBAC for Trickster, Kiali won't work with the aggregator proxy. You need to update the RBAC settings for Kiali to work with the aggregator proxy.

2024-07-16 08:44 UTC, vladimirGuryanov commented on modules/300-prometheus/templates/grafana/secret-datasources-list.yaml
> -- name: trickster
This is a list of data sources pending deletion. Generally, this list includes data sources that have already been created and are scheduled for removal. You don't need to remove the Trickster data source from here.

2024-07-16 08:44 UTC, vladimirGuryanov commented on modules/300-prometheus/templates/grafana/secret-datasources-list.yaml
> -- name: main-old
Needs to be moved to the 'Deleted' section, not deleted entirely.

2024-07-16 08:44 UTC, vladimirGuryanov commented on modules/300-prometheus/templates/grafana/secret-datasources-list.yaml
> -  {{- if ne (int .Values.prometheus.longtermRetentionDays) 0 }}
We cannot delete this data source. If we do, users will lose the ability to retrieve data from Prometheus LTS. I suggest updating the aggregation proxy and adding a new server group for access to Prometheus LTS, similar to how it was configured in Trickster. Finally, we should update this data source accordingly.

2024-07-22 21:59 UTC, apolovov approved these changes

2024-11-07 16:35 UTC, closed without merging