aws limit available zones fix
deckhouse/deckhouse pull request #9063
Opened 2024-07-16 13:11 UTC by borg-z

Signed-off-by: borg-z <me@nikolay-z.top>

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-07-18 12:39 UTC, borg-z commented
Now subnet are created in all availability and local zones, but the NAT Gateway is created in the first availability zone.

```
aws ec2 describe-subnets --filters "Name=vpc-id,Values=vpc-***" --query "Subnets[*].{SubnetId:SubnetId,AvailabilityZone:AvailabilityZone}" --output table --no-cli
-pager 
---------------------------------------------------
|                 DescribeSubnets                 |
+--------------------+----------------------------+
|  AvailabilityZone  |         SubnetId           |
+--------------------+----------------------------+
|  eu-north-1b       |  subnet-0c66ff0a2d78dfecb  |
|  eu-north-1c       |  subnet-09506f411b6315caa  |
|  eu-north-1b       |  subnet-03ce4a00c1fedb79c  |
|  eu-north-1a       |  subnet-0f68fdc31b0aba786  |
|  eu-north-1c       |  subnet-0f7cd5783ce15145b  |
|  eu-north-1-hel-1a |  subnet-0b92690b03a550fd0  |
|  eu-north-1a       |  subnet-0bdec5ee2e8430ab8  |
|  eu-north-1-hel-1a |  subnet-04f3d29cc88500129  |
+--------------------+----------------------------+
```


```
 aws ec2 describe-nat-gateways --filter "Name=vpc-id,Values=vpc-05364a5ebd9852004" --query "NatGateways[*].{NatGatewayId:NatGatewayId,SubnetId:SubnetId}" --output table --no-cli-pager     
-------------------------------------------------------
|                 DescribeNatGateways                 |
+------------------------+----------------------------+
|      NatGatewayId      |         SubnetId           |
+------------------------+----------------------------+
|  nat-0799e7862c6b4083e |  subnet-0f68fdc31b0aba786  |
+------------------------+----------------------------+
```


```
aws ec2 describe-subnets --subnet-ids subnet-0f68fdc31b0aba786 --query "Subnets[*].{SubnetId:SubnetId,AvailabilityZone:AvailabilityZone}" --output table --no-cli-pager

--------------------------------------------------
|                 DescribeSubnets                |
+-------------------+----------------------------+
| AvailabilityZone  |         SubnetId           |
+-------------------+----------------------------+
|  eu-north-1a      |  subnet-0f68fdc31b0aba786  |
+-------------------+----------------------------+

```

2024-07-18 15:18 UTC, name212 approved these changes

2024-07-18 15:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-07-19 08:16 UTC, borg-z commented
/e2e/abort aws;WithoutNAT;containerd;1.27 9994203212 9994203212-1-con-1-27 /sys/deckhouse-oss/install:pr9063 ec2-user@18.198.91.237

2024-07-22 07:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-07-22 08:56 UTC, miklezzzz approved these changes

2024-07-22 21:54 UTC, apolovov commented
PR summary isn't precise.
I suggest:
```
section: candi
type: fix
summary: AWS NAT Gateways are forced to be created in first non-local zone.
impact: <none>
impact_level: default
```

2024-07-22 21:57 UTC, apolovov requested changes
PR summary isn't precise.
I suggest:
```
section: candi
type: fix
summary: AWS NAT Gateways are forced to be created in first non-local zone.
impact: <none>
impact_level: default
```

2024-07-22 21:57 UTC, apolovov commented on candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf
> +
```suggestion
```

2024-07-25 08:11 UTC, apolovov approved these changes

2024-07-25 14:25 UTC, name212 approved these changes

2024-07-25 14:26 UTC, merged