Use grafana v10 per default
deckhouse/deckhouse pull request #9076
Opened 2024-07-17 13:15 UTC by Regrau

## Description
Move replace grafana v8 with grafana v10 on the default URL.

## Why do we need it, and what problem does it solve?
This provides the users with the newer version of grafana

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-07-22 10:04 UTC, vladimirGuryanov commented
You forgot to change the Grafana domain here: https://github.com/deckhouse/deckhouse/pull/9076/files#diff-3e2e027c44bdea446fe55ebae34e2f53060863a63fa41b796db547322eec8dcaR35

2024-07-22 10:05 UTC, vladimirGuryanov requested changes

2024-07-22 13:49 UTC, vladimirGuryanov approved these changes

2024-07-23 11:12 UTC, vladimirGuryanov requested changes

2024-07-23 11:12 UTC, vladimirGuryanov commented on modules/300-prometheus/templates/grafana/ingress-v10.yaml
> +    - {{ include "helm_lib_module_public_domain" (list . "grafana") }}
Need to add `- {{ include "helm_lib_module_public_domain" (list . "prometheus") }}` and remove it from ingress.yaml.

2024-07-25 10:08 UTC, vladimirGuryanov approved these changes

2024-07-25 11:42 UTC, lazovskiy approved these changes

2024-07-29 09:19 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-07-29 09:50 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10141569559 10141569559-1-con-1-27 /sys/deckhouse-oss/install:pr9076 redos@89.169.137.246

2024-07-29 10:11 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-07-29 11:14 UTC, merged

2024-07-31 07:50 UTC, z9r5 commented
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10142066574 10142066574-1-con-1-27 /sys/deckhouse-oss/install:pr9076 redos@89.169.143.95

2024-07-31 07:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @z9r5. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->