[cilium] set VXLAN port into allowed range
deckhouse/deckhouse pull request #9089
Opened 2024-07-18 14:46 UTC by Beastlex

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-07-22 21:32 UTC, apolovov requested changes

2024-07-22 21:32 UTC, apolovov commented on modules/021-cni-cilium/hooks/set_vxlan_allowed_ports.go
> +			Name:       "agent-daemonset",
Why don't you use the cilium-configmap to discover if cilium was deployed before?

2024-07-22 21:32 UTC, apolovov commented on modules/021-cni-cilium/hooks/set_vxlan_allowed_ports_test.go
> +Copyright 2023 Flant JSC
```suggestion
Copyright 2024 Flant JSC
```

2024-08-05 09:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/eks'...
<!-- workflow_start -->

2024-08-08 13:34 UTC, apolovov requested changes

2024-08-08 13:34 UTC, apolovov commented on modules/021-cni-cilium/monitoring/prometheus-rules/config.yaml
> +        There is non-standard VXLAN port in Cilium config: `{{$labels.port}}` does not fall within the recommended range (4298, 4299).
```suggestion
        There is non-standard VXLAN port in Cilium config: `{{$labels.port}}` does not fit the recommended range (4298 if the virtualization module enabled or 4299 for regular deckhouse setup).
```

2024-08-08 13:34 UTC, apolovov commented on modules/021-cni-cilium/monitoring/prometheus-rules/config.yaml
> +        It is recommended to check `tunnel-port` parameter in ConfigMap `cilium-configmap` in `d8-cni-cilium` namespace.
```suggestion
        Consider configuring the `tunnel-port` parameter in `cilium-configmap` ConfigMap (`d8-cni-cilium` namespace) according the recommended range. If you know why you need the non-standard port, just ignore the alert.
```

2024-08-08 13:34 UTC, apolovov commented on modules/021-cni-cilium/hooks/set_vxlan_allowed_ports.go
> +}
```suggestion
	Existing: { // existing installation (ConfigMap exists)
		On: { // Virtualization is on
		 	// cm has configured 8469 port, will leave it as is
			TransitionRule{source: 8469, target: 8469},
			
		 	// dreamy case — virtualization was enabled with upgrading d8 simultaneously
			TransitionRule{source: 0, target: 8469},
			
			// dreamy case — virtualization was enabled with upgrading d8 simultaneously and
			// someone configured the port for setup without virtualization 8472 manually, will set the right one
			TransitionRule{source: 8472, target: 4298},
			
			// virtualization module was enabled on regular setup with the right port, will set the 4298
			TransitionRule{source: 4299, target: 4298},
			
			// regular setup with enabled virtualization module and right port, will leave it as is
			TransitionRule{source: 4298, target: 4298},
			
			// if the "source" port is non-standard and didn't mention here, will leave it as is and fire the alert
		},
		Off: { // Virtualization is off
			// our previous standard setup, will set the old default port explicitly
			TransitionRule{source: 0, target: 8472},
			
			// our previous standard setup with explicitly configured 8472 port, will leave the 8472
			TransitionRule{source: 8472, target: 8472},
			
			// regular setup with standard 4299 port, will leave it as is
			TransitionRule{source: 4299, target: 4299},
		},
	},
	New: { // new installation (ConfigMap does not exist)
		On: { // Virtualization is on
			TransitionRule{source: 0, target: 4298},
		},
		Off: { // Virtualization is off
			TransitionRule{source: 0, target: 4299},
		},
	},
}
```

2024-08-09 07:51 UTC, apolovov requested changes

2024-08-12 07:17 UTC, apolovov approved these changes

2024-08-12 07:22 UTC, apolovov approved these changes

2024-08-12 07:22 UTC, apolovov commented on modules/021-cni-cilium/hooks/set_vxlan_allowed_ports.go
> +	Queue:        "/modules/cni-cilium/set-vxlan-allowed-ports",
```suggestion
	Queue:        "/modules/cni-cilium/discover_vxlan_port",
```

2024-08-12 07:22 UTC, apolovov commented on modules/021-cni-cilium/hooks/discover_vxlan_port_test.go
> +var _ = Describe("Modules :: cni-cilium :: hooks :: set_vxlan_allowed_ports ::", func() {
```suggestion
var _ = Describe("Modules :: cni-cilium :: hooks :: discover_vxlan_port ::", func() {
```

2024-08-12 07:22 UTC, apolovov commented on modules/021-cni-cilium/hooks/discover_vxlan_port.go
> +	Queue:        "/modules/cni-cilium/set-vxlan-allowed-ports",
```suggestion
	Queue:        "/modules/cni-cilium/discover_vxlan_port",
```

2024-08-12 07:26 UTC, apolovov approved these changes

2024-08-12 07:28 UTC, apolovov commented on docs/documentation/_data/deckhouse-alerts.yml
> +      sourceFile: modules/021-cni-cilium/monitoring/prometheus-rules/config.yaml
```suggestion
      sourceFile: modules/021-cni-cilium/monitoring/prometheus-rules/configmap.yaml
```

2024-08-13 09:49 UTC, nabokihms approved these changes

2024-08-13 18:09 UTC, merged