[docs] Add guide about installing Deckhouse in kind
deckhouse/deckhouse pull request #918
Opened 2022-02-17 02:20 UTC by z9r5

## Description
Add guide about installing Deckhouse in kind

## Changelog entries
```changes
section: docs
type: feature
summary: Guide about installing Deckhouse in kind
impact_level: low
```

2022-02-17 07:10 UTC, deckhouse-BOaTswain commented
Running workflow "deploy/web/stage"...

2022-02-17 09:47 UTC, Zhbert commented on docs/site/LOCAL_DEV.md
> +Free 80 port to bind
```suggestion
Free 80 port to bind.
```

2022-02-17 09:47 UTC, Zhbert commented on docs/site/LOCAL_DEV.md
> +Open console and start documentation container
```suggestion
Open console and start documentation container:
```

2022-02-17 09:48 UTC, Zhbert commented on docs/site/LOCAL_DEV.md
> +Open separate console and start site container
```suggestion
Open separate console and start site container:
```

2022-02-17 09:50 UTC, Zhbert commented on docs/site/LOCAL_DEV.md
> +Open http://localhost
```suggestion
Open http://localhost.
```

2022-02-17 09:53 UTC, Zhbert commented on docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.liquid
> +- В файл `/kubeconfig` контейнера необходимо смонтировать файл конфигурации kubectl с доступом к Kubernetes API. В руководстве предполагается, что он находится в файле `.kube/config` домашней папки п
```suggestion
- В файл `/kubeconfig` контейнера необходимо смонтировать файл конфигурации kubectl с доступом к Kubernetes API. В руководстве предполагается, что он находится в файле `.kube/config` домашнего каталога пользователя.
```

2022-02-17 10:02 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_FINISH.md
> +- Login — `admin`
```suggestion
- Login — `admin`;
```

2022-02-17 10:07 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_FINISH_RU.md
> +Доступ к Grafana ограничен basic-аутентификацией (больше вариантов аутентификации можно получить включив модуль [user-auth](/{{ page.lang }}/documentation/v1/modules/150-user-authn/):
```suggestion
Доступ к Grafana ограничен basic-аутентификацией (больше вариантов аутентификации можно получить, включив модуль [user-auth](/{{ page.lang }}/documentation/v1/modules/150-user-authn/):
```

2022-02-17 10:08 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_FINISH_RU.md
> +- Логин — `admin`
```suggestion
- Логин — `admin`;
```

2022-02-17 10:10 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_FINISH_RU.md
> +`DexProvider`. После создания `DexProvider`, при попытке доступа ко всем компонентам Deckhouse (Grafana, Dashboard и
```suggestion
`DexProvider`. После создания `DexProvider` при попытке доступа ко всем компонентам Deckhouse (Grafana, Dashboard и
```

2022-02-17 10:10 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_FINISH_RU.md
> +т.д.) потребуются аутентификации через GitHub
```suggestion
т.д.) потребуются аутентификации через GitHub.
```

2022-02-17 10:15 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md
> +Обратите внимание, что некоторые функции, такие как [управление узлами](/{{ page.lang }}/documentation/v1/modules/040-node-manager/), [управление control-plane](/{{ page.lang }}/documentation/v1/modu
```suggestion
Обратите внимание, что некоторые функции, такие как [управление узлами](/{{ page.lang }}/documentation/v1/modules/040-node-manager/) и [управление control-plane](/{{ page.lang }}/documentation/v1/modules/040-control-plane-manager/), работать не будут. 
```

2022-02-17 10:15 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md
> +Данное руководство предлагает установку Deckhouse в **минимальной** конфигурации с включенным [мониторингом](/{{ page.lang }}/documentation/v1/modules/300-prometheus//) на базе Grafana. Для упрощения
```suggestion
Данное руководство предлагает установку Deckhouse в **минимальной** конфигурации с включенным [мониторингом](/{{ page.lang }}/documentation/v1/modules/300-prometheus//) на базе Grafana. Для упрощения при работе с DNS используется сервис [nip.io](https://nip.io).
```

2022-02-17 10:16 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md
> +Вам потребуется персональный компьютер с macOS, Windows или Linux достаточной мощности, с доступом в Интернет. На этом компьютере будет развернут кластер Kubernetes, в который будет установлен Deckho
```suggestion
Вам потребуется персональный компьютер достаточной мощности с macOS, Windows или Linux, а также с доступом в Интернет. На этом компьютере будет развернут кластер Kubernetes, в который будет установлен Deckhouse. 
```

2022-02-17 10:18 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA.md
> +You will need a personal computer with macOS, Windows or Linux of sufficient power, with Internet access. A Kubernetes cluster will be deployed on this computer, and Deckhouse will be installed into
```suggestion
You will need a personal computer of sufficient power with macOS, Windows or Linux and with Internet access. A Kubernetes cluster will be deployed on this computer, and Deckhouse will be installed into a cluster. 
```

2022-02-17 10:19 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_PREPARE.md
> +Install [kind](https://kind.sigs.k8s.io/docs/user/quick-start/#installation), if it is not already installed.:
```suggestion
Install [kind](https://kind.sigs.k8s.io/docs/user/quick-start/#installation), if it is not already installed.
```

2022-02-17 10:19 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/STEP_PREPARE_RU.md
> +> Перед созданием кластера, убедитесь, что у вас не заняты порты 80 и 443.
```suggestion
> Перед созданием кластера убедитесь, что у вас не заняты порты 80 и 443.
```

2022-02-17 10:21 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +# [<en>] section for bootstrapping the Deckhouse cluster (InitConfiguration)
```suggestion
# [<en>] Section for bootstrapping the Deckhouse cluster (InitConfiguration).
```

2022-02-17 10:22 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +# [<en>] version of the Deckhouse API
```suggestion
# [<en>] Version of the Deckhouse API.
```

2022-02-17 10:22 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +# [<ru>] секция первичной инициализации кластера Deckhouse (InitConfiguration)
```suggestion
# [<ru>] Секция первичной инициализации кластера Deckhouse (InitConfiguration).
```

2022-02-17 10:22 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +# [<ru>] используемая версия API Deckhouse
```suggestion
# [<ru>] Используемая версия API Deckhouse.
```

2022-02-17 10:23 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +# [<en>] type of the configuration section
```suggestion
# [<en>] Type of the configuration section.
```

2022-02-17 10:23 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +# [<ru>] тип секции конфигурации
```suggestion
# [<ru>] Тип секции конфигурации.
```

2022-02-17 10:24 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +# [<en>] Deckhouse parameters
```suggestion
# [<en>] Deckhouse parameters.
```

2022-02-17 10:24 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +# [<ru>] секция с параметрами Deckhouse
```suggestion
# [<ru>] Секция с параметрами Deckhouse.
```

2022-02-17 10:41 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +  # [<en>] the release channel in use
```suggestion
  # [<en>] The release channel in use.
```

2022-02-17 10:42 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +  # [<ru>] используемый канал обновлений
```suggestion
  # [<ru>] Используемый канал обновлений.
```

2022-02-17 10:42 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +  # [<en>] the Minimal bundle is used when installing Deckhouse in an existing cluster
```suggestion
  # [<en>] The Minimal bundle is used when installing Deckhouse in an existing cluster.
```

2022-02-17 10:43 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +  # [<ru>] при установке Deckhouse в существующий кластер используется вариант поставки — Minimal
```suggestion
  # [<ru>] При установке Deckhouse в существующий кластер используется вариант поставки — Minimal.
```

2022-02-17 10:43 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ce.inc
> +        # [<ru>] Например, Grafana для %s.example.com будет доступна на домене grafana.example.com
```suggestion
        # [<ru>] Например, Grafana для %s.example.com будет доступна на домене grafana.example.com.
```

2022-02-17 10:44 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +# [<en>] section for bootstrapping the Deckhouse cluster (InitConfiguration)
```suggestion
# [<en>] Section for bootstrapping the Deckhouse cluster (InitConfiguration).
```

2022-02-17 10:44 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +# [<en>] version of the Deckhouse API
```suggestion
# [<en>] Version of the Deckhouse API.
```

2022-02-17 10:45 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +# [<ru>] секция первичной инициализации кластера Deckhouse (InitConfiguration)
```suggestion
# [<ru>] Секция первичной инициализации кластера Deckhouse (InitConfiguration).
```

2022-02-17 10:45 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +# [<ru>] используемая версия API Deckhouse
```suggestion
# [<ru>] Используемая версия API Deckhouse.
```

2022-02-17 10:46 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +# [<en>] type of the configuration section
```suggestion
# [<en>] Type of the configuration section.
```

2022-02-17 10:46 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +# [<ru>] тип секции конфигурации
```suggestion
# [<ru>] Тип секции конфигурации.
```

2022-02-17 10:46 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +# [<en>] Deckhouse parameters
```suggestion
# [<en>] Deckhouse parameters.
```

2022-02-17 10:47 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +# [<ru>] секция с параметрами Deckhouse
```suggestion
# [<ru>] Секция с параметрами Deckhouse.
```

2022-02-17 10:47 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +  # [<en>] address of the Docker registry where the Deckhouse images are located
```suggestion
  # [<en>] Address of the Docker registry where the Deckhouse images are located.
```

2022-02-17 10:48 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +  # [<ru>] адрес Docker registry с образами Deckhouse
```suggestion
  # [<ru>] Адрес Docker registry с образами Deckhouse.
```

2022-02-17 10:48 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +  # [<en>] a special string with your token to access Docker registry (generated automatically for your license token)
```suggestion
  # [<en>] A special string with your token to access Docker registry (generated automatically for your license token).
```

2022-02-17 10:49 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +  # [<ru>] строка с ключом для доступа к Docker registry (сгенерировано автоматически для вашего токена доступа)
```suggestion
  # [<ru>] Строка с ключом для доступа к Docker registry (сгенерировано автоматически для вашего токена доступа).
```

2022-02-17 10:52 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +  # [<en>] the release channel in use
```suggestion
  # [<en>] The release channel in use.
```

2022-02-17 10:53 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +  # [<ru>] используемый канал обновлений
```suggestion
  # [<ru>] Используемый канал обновлений.
```

2022-02-17 10:53 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +  # [<en>] the Minimal bundle is used when installing Deckhouse in an existing cluster
```suggestion
  # [<en>] The Minimal bundle is used when installing Deckhouse in an existing cluster.
```

2022-02-17 10:53 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +  # [<ru>] при установке Deckhouse в существующий кластер используется вариант поставки — Minimal
```suggestion
  # [<ru>] При установке Deckhouse в существующий кластер используется вариант поставки — Minimal.
```

2022-02-17 10:54 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/config.yml.default.ee.inc
> +        # [<ru>] Например, Grafana для %s.example.com будет доступна на домене grafana.example.com
```suggestion
        # [<ru>] Например, Grafana для %s.example.com будет доступна на домене grafana.example.com.
```

2022-02-17 10:54 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/ingress-nginx-controller.yml.inc
> +# [<en>] section containing the parameters of nginx ingress controller
```suggestion
# [<en>] Section containing the parameters of nginx ingress controller.
```

2022-02-17 10:55 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/ingress-nginx-controller.yml.inc
> +# [<en>] version of the Deckhouse API
```suggestion
# [<en>] Version of the Deckhouse API.
```

2022-02-17 10:55 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/ingress-nginx-controller.yml.inc
> +# [<ru>] секция, описывающая параметры nginx ingress controller
```suggestion
# [<ru>] Секция, описывающая параметры nginx ingress controller.
```

2022-02-17 10:56 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/ingress-nginx-controller.yml.inc
> +# [<ru>] используемая версия API Deckhouse
```suggestion
# [<ru>] Используемая версия API Deckhouse.
```

2022-02-17 10:56 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/ingress-nginx-controller.yml.inc
> +  # [<en>] the name of the Ingress class to use with the Ingress nginx controller
```suggestion
  # [<en>] The name of the Ingress class to use with the Ingress nginx controller.
```

2022-02-17 10:56 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/ingress-nginx-controller.yml.inc
> +  # [<ru>] имя Ingress-класса для обслуживания Ingress NGINX controller
```suggestion
  # [<ru>] Имя Ingress-класса для обслуживания Ingress NGINX controller.
```

2022-02-17 10:57 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/ingress-nginx-controller.yml.inc
> +  # [<en>] the way traffic goes to cluster from the outer network
```suggestion
  # [<en>] The way traffic goes to cluster from the outer network.
```

2022-02-17 10:57 UTC, Zhbert commented on docs/site/_includes/getting_started/kind/partials/ingress-nginx-controller.yml.inc
> +  # [<ru>] способ поступления трафика из внешнего мира
```suggestion
  # [<ru>] Способ поступления трафика из внешнего мира.
```

2022-02-17 10:58 UTC, Zhbert requested changes
@z9r5 Please check new updates.

2022-02-17 11:57 UTC, deckhouse-BOaTswain commented
Running workflow "deploy/web/stage"...

2022-02-17 11:57 UTC, Zhbert submitted a review, later dismissed

2022-02-17 12:09 UTC, deckhouse-BOaTswain commented
Running workflow "deploy/web/stage"...

2022-02-18 07:41 UTC, konstantin-axenov submitted a review, later dismissed

2022-02-18 09:04 UTC, deckhouse-BOaTswain commented
Running workflow "deploy/web/test"...

2022-02-18 09:06 UTC, merged