[ingress-nginx] Adding an example with L2LoadBalancer
deckhouse/deckhouse pull request #9214
Opened 2024-07-30 13:29 UTC by Beastlex

## Description
Adding an example of usage ingress-nginx with L2LoadBalancer.

## Why do we need it, and what problem does it solve?
Examples will help improve the customer experience with the platform.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [x] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: ingress-nginx
type: chore
summary: Add an example of usage ingress-nginx with _L2LoadBalancer_ inlet.
impact_level: default
```

2024-07-30 22:02 UTC, apolovov requested changes

2024-07-30 22:02 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES.md
> +* The **network.deckhouse.io/l2-load-balancer-external-ips-count** annotation specifies how many addresses will be allocated from the pool described in _L2LoadBalancer_
```suggestion
* The **network.deckhouse.io/l2-load-balancer-external-ips-count** annotation specifies how many addresses will be allocated from the pool described in _L2LoadBalancer_.
```

2024-07-30 22:02 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES_RU.md
> +Модуль [l2-load-balancer](../381-l2-load-balancer/) на текущий момент доступен только в редакции Enterprise Edition Deckhouse.
alert here

2024-07-30 22:02 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES_RU.md
> +* В аннотации **network.deckhouse.io/l2-load-balancer-name** указывается имя _L2LoadBalancer_ (в примере _L2LoadBalancer_ с именем _ingress_ был создан на предыдущем шаге)
```suggestion
* В аннотации **network.deckhouse.io/l2-load-balancer-name** указывается имя _L2LoadBalancer_.
```

2024-07-30 22:02 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES_RU.md
> +* Аннотация **network.deckhouse.io/l2-load-balancer-external-ips-count** указывает сколько адресов будет выделено из пула, описанного в _L2LoadBalancer_
```suggestion
* Аннотация **network.deckhouse.io/l2-load-balancer-external-ips-count** указывает сколько адресов будет выделено из пула, описанного в _L2LoadBalancer_.
```

2024-07-31 07:54 UTC, apolovov requested changes

2024-07-31 07:54 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES.md
> +Enable the module:
```suggestion
Enable the `l2-load-balancer` module:
```

2024-07-31 07:54 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES.md
> +```
Need a note, how to figure out the public ips.

```
kubectl -n d8-ingress-nginx get svc main
...
```

2024-07-31 07:54 UTC, apolovov commented on modules/402-ingress-nginx/docs/EXAMPLES_RU.md
> +Включите модуль:
```suggestion
Включите модуль `l2-load-balancer`:
```

2024-08-01 08:18 UTC, apolovov approved these changes

2024-08-01 08:19 UTC, apolovov approved these changes

2024-08-12 10:25 UTC, z9r5 approved these changes

2024-08-12 11:47 UTC, merged

2024-08-12 11:47 UTC, deckhouse-BOaTswain commented
Cherry pick PR [9338](https://github.com/deckhouse/deckhouse/pull/9338) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!