added preflight check func
deckhouse/deckhouse pull request #9475
Opened 2024-08-23 15:37 UTC by d2285

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-08-29 14:10 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-08-29 14:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-08-29 14:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-08-29 15:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-08-29 15:26 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-08-29 18:53 UTC, name212 commented on dhctl/pkg/operations/bootstrap/state.go
> +const PreflightBootstrapResultCacheKey = "preflight-bootstrap-result"
we need to add separate cache key for global, cloud and static preflight checks

2024-08-29 18:54 UTC, name212 requested changes
one thing

2024-08-30 12:15 UTC, name212 approved these changes

2024-08-30 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-08-30 12:16 UTC, deckhouse-BOaTswain commented
Aye, aye, @d2285. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-08-30 16:30 UTC, merged