[cloud-provider-zvirt] Fix empty private IP addresses
deckhouse/deckhouse pull request #9533
Opened 2024-08-28 18:24 UTC by ilia601

## Description
Added a condition to use external addresses if internal ones are missing

## Why do we need it, and what problem does it solve?
So that modules such as monitoring-ping work correctly. [Monitoring-ping pods will crash if there are no targets to ping](https://github.com/deckhouse/deckhouse/blob/main/modules/340-monitoring-ping/images/monitoring-ping/monitoring-ping.py#L116)

## Why do we need it in the patch release (if we do)?

## What is the expected result?
zvirt nodes have internal addresses. monitoring-ping pods work as expected without crashes

## Checklist
- [ ] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: monitoring-ping
type: fix
summary: Fix monitoring-ping pods crashing
impact_level: default
```

2024-08-28 18:27 UTC, ilia601 commented
```
Traceback (most recent call last):
  File "/src/monitoring-ping.py", line 181, in <module>
    computed = compute_results(out)
               ^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-1>", line 2, in compute_results
  File "/opt/python-static/lib/python3.11/site-packages/prometheus_client/context_managers.py", line 23, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/src/monitoring-ping.py", line 116, in compute_results
    raise ValueError("regex match\"{}\" found nothing in fping output \"{}\"".format(FPING_REGEX, results))
ValueError: regex match"re.compile('^(\\S*)\\s*: (.*)$', re.MULTILINE)" found nothing in fping output ""
```

<img width="697" alt="Screenshot 2024-08-28 at 21 07 00" src="https://github.com/user-attachments/assets/65f754fe-4a7b-4c0d-a718-520913d5c4e5">

2024-08-28 18:36 UTC, deckhouse-BOaTswain commented
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-08-29 08:52 UTC, ilia601 commented
/e2e/abort openstack;Standard;containerd;1.27 10602482297 10602482297-1-con-1-27 /sys/deckhouse-oss/install:pr9533 redos@5.159.103.12 - for abort failed cluster

2024-08-30 15:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-09-03 07:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-09-03 08:53 UTC, ilia601 commented
<img width="1002" alt="Screenshot 2024-09-03 at 11 51 16" src="https://github.com/user-attachments/assets/e48ae83d-5fe1-4503-b4f7-6cd3b34e323e">
<img width="613" alt="Screenshot 2024-09-03 at 11 52 13" src="https://github.com/user-attachments/assets/8d4949a8-82cf-4f64-b63b-e730b4781862">
<img width="1001" alt="Screenshot 2024-09-03 at 11 52 53" src="https://github.com/user-attachments/assets/2e8957b8-8394-4727-9c79-74881c81cfea">

2024-09-03 08:56 UTC, deckhouse-BOaTswain commented
Aye, aye, @ilia601. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-09-03 09:20 UTC, aleksey-su requested changes

2024-09-03 09:20 UTC, aleksey-su commented on ee/modules/030-cloud-provider-zvirt/images/cloud-controller-manager/src/pkg/cloudprovider/zvirt/instances.go
> +	}
```suggestion
    // If there are no local IP addresses, replace them with external ones
	if len(localIP) == 0 {
		localIP = externalIP
	}
```

2024-09-03 09:20 UTC, aleksey-su commented on ee/modules/030-cloud-provider-zvirt/images/cloud-controller-manager/src/pkg/cloudprovider/zvirt/instances.go
> +	}
You should specify an explicit check condition to make it easier to read the code. And leave comments if you add non-standard behavior

2024-09-03 09:29 UTC, aleksey-su approved these changes

2024-09-03 09:36 UTC, merged

2024-09-03 15:33 UTC, alexey-gavrilov-flant commented
/e2e/abort openstack;Standard;containerd;1.27 10602482297 10602482297-1-con-1-27 /sys/deckhouse-oss/install:pr9533 redos@5.159.103.12

2024-09-03 15:33 UTC, deckhouse-BOaTswain commented
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->