os mcs bootstrap test
deckhouse/deckhouse pull request #9570
Opened 2024-09-02 13:07 UTC by borg-z

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-09-03 12:35 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-09-03 12:54 UTC, borg-z commented
```
kubectl -n d8-monitoring get pvc
NAME                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-longterm-db-prometheus-longterm-0   Bound    pvc-86da4853-8a51-4aa2-88bd-9e6c75cc6fcf   40Gi       RWO            ceph-hdd       30s
prometheus-main-db-prometheus-main-0           Bound    pvc-880031df-3e2f-4fef-b3bf-4e519922fc3b   40Gi       RWO            ceph-hdd       29s
```

2024-09-06 16:47 UTC, name212 commented on go_lib/cloud-data/reconciler.go
> +		c.logger.Fatalln("Cannot update cloud data resource. Timed out. See error messages below.")
On the one hand, the decision to crash is a good one, a kube one. But it was done on purpose. Some providers, especially with openstack, like to block the API at a certain threshold of incorrect requests, so we always do not try to discover data from the cloud, do fire the alert and leave the decision to restart to the engineer.

In fact, a good solution would be to crash on requests to the kube-api, and fire the alert on requests to the cloud

2024-09-06 16:47 UTC, name212 requested changes
suggestion

2024-09-17 10:44 UTC, aleksey-su approved these changes

2024-09-17 11:21 UTC, name212 approved these changes

2024-09-17 11:21 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-09-17 11:25 UTC, name212 commented
/e2e/abort openstack;Standard;containerd;1.27 10902016956 10902016956-1-con-1-27 /sys/deckhouse-oss/install:pr9570

2024-09-17 11:25 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-09-17 11:27 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-09-17 15:39 UTC, name212 approved these changes

2024-09-17 15:50 UTC, merged