[hooks] Fix multiport Services broken by Helm
deckhouse/deckhouse pull request #9573
Opened 2024-09-02 19:00 UTC by tarabrind

## Description
Fixing the broken Services with multiple ports. Helm didn't handle Service resource modification well while deploying https://github.com/deckhouse/deckhouse/pull/8955.

## Why do we need it, and what problem does it solve?
In some clusters Services became broken. In some clusters it was kube-dns.

## Why do we need it in the patch release (if we do)?
The release 1.63 is blocked.

## What is the expected result?
All Services are correspond to their templates.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: global-hooks
type: fix
summary: Fixed the Services with multiple ports broken by Helm.
```

2024-09-03 14:53 UTC, Beastlex approved these changes

2024-09-03 15:02 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-09-03 15:40 UTC, apolovov commented on modules/002-deckhouse/templates/service.yaml
> +  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse" "service-helm-fix" "true")) | nindent 2 }}
```suggestion
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse" "migration.deckhouse.io/fix-services-broken-by-helm" "done")) | nindent 2 }}
```

2024-09-03 15:43 UTC, apolovov commented on modules/110-istio/hooks/migration_service_with_many_ports.go
> +			NameSelector: &types.NameSelector{
```suggestion
                         LabelSelector: &v1.LabelSelector{
                                MatchExpressions: []v1.LabelSelectorRequirement{
                                        {
                                                Key:      "migration.deckhouse.io/fix-services-broken-by-helm",
                                                Operator: v1.LabelSelectorOpNotIn,
                                                Values:   []string{"done"},
                                        },
                                },
                        },
			NameSelector: &types.NameSelector{
```

2024-09-03 15:46 UTC, apolovov requested changes
Discussed.

2024-09-03 21:23 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-09-04 07:47 UTC, apolovov approved these changes

2024-09-04 07:58 UTC, merged