[ingress-nginx] Add loadBalancerClass setting to ingress-nginx service
deckhouse/deckhouse pull request #9585
Opened 2024-09-03 22:07 UTC by tarabrind

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-09-05 13:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @tarabrind. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-09-05 14:16 UTC, Beastlex commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        Allows you to modify the `.spec.loadBalancerClass` setting of a standard Service object.
```suggestion
                        Allows you to modify the `.spec.loadBalancerClass` setting of a ingress-managed load balancer.
```

2024-09-06 03:19 UTC, Beastlex approved these changes

2024-09-06 11:07 UTC, z9r5 approved these changes

2024-09-08 17:30 UTC, AndreyPavlovFlant approved these changes

2024-09-09 07:54 UTC, apolovov requested changes

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                        Позволяет изменять настройку `.spec.loadBalancerClass` балансировщика нагрузки, управляемого с помощью Ingress.
```suggestion
                        Класс балансировщика входящих сетевых запросов (пробрасывается в параметр `spec.loadBalancerClass` заказанного сервиса с типом LoadBalancer).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                        Позволяет изменять настройку `.spec.loadBalancerClass` балансировщика нагрузки, управляемого с помощью Ingress.
```suggestion
                        Класс балансировщика входящих сетевых запросов (пробрасывается в параметр `spec.loadBalancerClass` заказанного сервиса с типом LoadBalancer).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                        Позволяет изменять настройку `.spec.loadBalancerClass` балансировщика нагрузки, управляемого с помощью Ingress.
```suggestion
                        Класс балансировщика входящих сетевых запросов (пробрасывается в параметр `spec.loadBalancerClass` заказанного сервиса с типом LoadBalancer).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                        Позволяет изменять настройку `.spec.loadBalancerClass` балансировщика нагрузки, управляемого с помощью Ingress.
```suggestion
                        Класс балансировщика входящих сетевых запросов (пробрасывается в параметр `spec.loadBalancerClass` заказанного сервиса с типом LoadBalancer).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
> +                        Позволяет изменять настройку `.spec.loadBalancerClass` балансировщика нагрузки, управляемого с помощью Ingress.
```suggestion
                        Класс балансировщика входящих сетевых запросов (пробрасывается в параметр `spec.loadBalancerClass` заказанного сервиса с типом LoadBalancer).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        Allows you to modify the `.spec.loadBalancerClass` setting of a ingress-managed load balancer.
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        Allows you to modify the `.spec.loadBalancerClass` setting of a ingress-managed load balancer.
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        Allows you to modify the `.spec.loadBalancerClass` setting of a ingress-managed load balancer.
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        Allows you to modify the `.spec.loadBalancerClass` setting of a ingress-managed load balancer.
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```

2024-09-09 07:54 UTC, apolovov commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        Allows you to modify the `.spec.loadBalancerClass` setting of a ingress-managed load balancer.
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```

2024-09-09 07:55 UTC, apolovov approved these changes

2024-09-09 09:04 UTC, yalosev approved these changes

2024-09-09 12:33 UTC, kirkonru approved these changes

2024-09-09 12:33 UTC, kirkonru commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service of the LoadBalancer type).
```

2024-09-09 12:33 UTC, kirkonru commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service of the LoadBalancer type).
```

2024-09-09 12:33 UTC, kirkonru commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service of the LoadBalancer type).
```

2024-09-09 12:33 UTC, kirkonru commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service of the LoadBalancer type).
```

2024-09-09 12:33 UTC, kirkonru commented on modules/402-ingress-nginx/crds/ingress-nginx.yaml
> +                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service with the LoadBalancer type).
```suggestion
                        The LoadBalancer class (it is passed to the `spec.loadBalancerClass` parameter of the provisioned service of the LoadBalancer type).
```

2024-09-09 13:32 UTC, merged

2024-09-09 13:33 UTC, deckhouse-BOaTswain commented
Cherry pick PR [9665](https://github.com/deckhouse/deckhouse/pull/9665) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!