8750 node managercapi controller manager linter fix
deckhouse/deckhouse pull request #9596
Opened 2024-09-04 13:30 UTC by borg-z

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-09-04 13:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-09-05 07:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-09-05 07:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-09-05 08:55 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/vcd'...
<!-- workflow_start -->

2024-09-06 16:16 UTC, name212 commented on modules/040-node-manager/templates/capi-controller-manager/rbac-for-us.yaml
> +      - vcdmachinetemplates
need to add zvirt resources

2024-09-06 16:17 UTC, name212 requested changes
one thing

2024-09-17 11:24 UTC, name212 approved these changes

2024-10-09 11:40 UTC, RomanenkoDenys reviewed
one question

2024-10-09 11:53 UTC, borg-z commented on modules/040-node-manager/templates/capi-controller-manager/rbac-for-us.yaml
>  {{- end }}
I don't know, some kind of old artifact

2024-10-14 04:47 UTC, z9r5 approved these changes

2024-10-16 12:10 UTC, merged