[testing] Fallback to curl if wget is not available on e2e tests
deckhouse/deckhouse pull request #9674
Opened 2024-09-10 07:59 UTC by Taior

## Description
Added fallback to curl if wget is not available on e2e test machine.

## Why do we need it, and what problem does it solve?
In some cases, e2e testing can fail after running all tests as wget is not present on the current machine. It is possible to bypass that by using curl.

## What is the expected result?
e2e test script uses curl.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries
```changes
section: testing
type: fix
summary: Add fallback to curl if wget is not available on e2e test machine.
impact_level: low
```

2024-09-10 08:09 UTC, deckhouse-BOaTswain commented
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-09-10 09:02 UTC, RomanenkoDenys commented on testing/cloud_layouts/script.sh
> +if [[ ! -z "\$(which wget)" ]]; then
```suggestion
if which wget >/dev/null; then
```

2024-09-10 09:02 UTC, RomanenkoDenys requested changes
some nits

2024-09-10 09:38 UTC, deckhouse-BOaTswain commented
Aye, aye, @Taior. I've started the workflow for label 'e2e/run/aws'...
<!-- workflow_start -->

2024-09-10 10:48 UTC, RomanenkoDenys approved these changes

2024-09-10 10:48 UTC, merged

2024-09-10 10:53 UTC, deckhouse-BOaTswain commented
Cherry pick PR [9678](https://github.com/deckhouse/deckhouse/pull/9678) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!

2024-09-12 07:28 UTC, Taior commented
/backport 1.63

2024-09-12 07:29 UTC, deckhouse-BOaTswain commented
Cherry pick PR [9701](https://github.com/deckhouse/deckhouse/pull/9701) to the branch [release-1.63](https://github.com/deckhouse/deckhouse/tree/release-1.63) successful!