[registry-packages-proxy] Grooming logs for dhctl
deckhouse/deckhouse pull request #9730
Opened 2024-09-16 11:56 UTC by name212

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-09-16 13:15 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-09-20 07:21 UTC, mvasl commented on go_lib/registry-packages-proxy/proxy/proxy.go
> +		logEntry := fmt.Sprintf("Request from client %s received for repo %s digest %s", requestIP, repository, digest)
```suggestion
		logEntry := fmt.Sprintf("Received request for repo %q from client %s with digest %s", repository, requestIP, digest)
```

2024-09-20 07:23 UTC, mvasl commented on go_lib/registry-packages-proxy/proxy/proxy.go
> +		p.logger.Infof("Package for digest %s sent successfully", digest)
```suggestion
		p.logger.Infof("Package for digest %q sent successfully", digest)
```

2024-09-20 07:24 UTC, mvasl requested changes

2024-09-20 07:24 UTC, mvasl commented on go_lib/registry-packages-proxy/proxy/proxy.go
> +		p.logger.Infof("Digest %s not found in local cache, trying to fetch package from registry", digest)
```suggestion
		p.logger.Infof("Digest %q not found in local cache, trying to fetch package from registry", digest)
```

2024-10-09 19:31 UTC, deckhouse-BOaTswain commented
Aye, aye, @name212. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2024-10-09 22:26 UTC, mvasl approved these changes

2024-10-10 07:01 UTC, merged