Cse release 1.64 kube dns
deckhouse/deckhouse pull request #9803
Opened 2024-09-23 12:05 UTC by borg-z

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-09-24 06:43 UTC, RomanenkoDenys commented on modules/042-kube-dns/images/coredns/werf.inc.yaml
> +from: {{ .Images.BASE_GOLANG_23_ALPINE_DEV }}
src-artifact

2024-09-24 07:04 UTC, RomanenkoDenys commented on modules/042-kube-dns/images/coredns/werf.inc.yaml
> +    - find /patches -name '*.patch' -exec git apply {} \;
```suggestion
    - git apply /patches/*.patch --verbose 
```

2024-09-24 07:07 UTC, RomanenkoDenys requested changes
some nits

2024-09-25 07:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/openstack'...
<!-- workflow_start -->

2024-09-26 09:23 UTC, RomanenkoDenys commented on modules/042-kube-dns/images/coredns/werf.inc.yaml
> +  {{- include "alpine packages proxy" . | nindent 2 }}
```suggestion
```

2024-09-26 09:24 UTC, RomanenkoDenys commented on modules/042-kube-dns/images/sts-pods-hosts-appender-init-container/werf.inc.yaml
> +  {{- include "alpine packages proxy" . | nindent 2 }}
```suggestion
```

2024-09-26 09:24 UTC, RomanenkoDenys commented on modules/042-kube-dns/images/sts-pods-hosts-appender-webhook/werf.inc.yaml
> +  {{- include "alpine packages proxy" . | nindent 2 }}
```suggestion
```

2024-09-26 09:25 UTC, RomanenkoDenys requested changes
some nits

2024-09-26 11:53 UTC, RomanenkoDenys commented on modules/042-kube-dns/images/coredns/werf.inc.yaml
> +    - git clone --depth 1 -b v1.11.3 {{ $.SOURCE_REPO }}/{{ $.ImageName }}/{{ $.ImageName }}.git .
```suggestion
    - git clone --depth 1 -b v1.11.3 {{ $.SOURCE_REPO }}/{{ $.ImageName }}/{{ $.ImageName }}.git /src
```

2024-09-26 11:54 UTC, RomanenkoDenys approved these changes
one nit

2024-09-26 14:18 UTC, merged