Cse release 1.64 kube proxy
deckhouse/deckhouse pull request #9819
Opened 2024-09-24 07:46 UTC by borg-z

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-09-25 07:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @borg-z. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-09-26 09:21 UTC, RomanenkoDenys commented on modules/036-kube-proxy/images/init-container/werf.inc.yaml
> +    {{- include "alpine packages proxy" . | nindent 2 }}
```suggestion
```

2024-09-26 09:22 UTC, RomanenkoDenys commented on modules/036-kube-proxy/images/kube-proxy/werf.inc.yaml
>  from: {{ $.Images.BASE_ALT_DEV }}
use BASE_ALT_P11 here

2024-09-26 09:23 UTC, RomanenkoDenys requested changes
some nits

2024-09-26 13:32 UTC, RomanenkoDenys approved these changes

2024-09-26 13:32 UTC, merged