[istio] add new patern for check cpu limits and request using in sidecar-containers Istio and added test cases
deckhouse/deckhouse pull request #9912
Opened 2024-09-30 09:34 UTC by skurbatov

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-09-30 09:58 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-09-30 11:33 UTC, AndreyPavlovFlant requested changes

2024-09-30 11:33 UTC, AndreyPavlovFlant commented on modules/110-istio/openapi/config-values.yaml
> +                        pattern: '^(["].*["]|[0-9]+m)$'
```suggestion
                        pattern: '^(["][0-9]+["]|[0-9]+m)$'
```

2024-09-30 11:34 UTC, AndreyPavlovFlant requested changes

2024-09-30 11:34 UTC, AndreyPavlovFlant commented on modules/110-istio/openapi/doc-ru-config-values.yaml
> +                      Настройка запроса CPU (CPU requests). Пример указания параметра - "1", "1000m".
```suggestion
                      Настройка запроса CPU (CPU requests).
```

2024-09-30 11:54 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-09-30 13:14 UTC, tarabrind approved these changes

2024-10-01 07:04 UTC, deckhouse-BOaTswain commented
Aye, aye, @skurbatov. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-01 09:22 UTC, AndreyPavlovFlant approved these changes

2024-10-01 09:23 UTC, tarabrind approved these changes

2024-10-01 10:28 UTC, z9r5 approved these changes

2024-10-01 17:58 UTC, apolovov approved these changes

2024-10-01 18:01 UTC, merged

2024-10-08 15:14 UTC, deckhouse-BOaTswain commented
Cherry pick PR [10049](https://github.com/deckhouse/deckhouse/pull/10049) to the branch [release-1.64](https://github.com/deckhouse/deckhouse/tree/release-1.64) successful!