[cni-cilium] adding config override for DVP nodes
deckhouse/deckhouse pull request #9996
Opened 2024-10-04 11:32 UTC by Beastlex

## Description

## Why do we need it, and what problem does it solve?

## Why do we need it in the patch release (if we do)?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

2024-10-04 11:51 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-10-04 12:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2024-10-04 12:29 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/static'...
<!-- workflow_start -->

2024-10-05 06:42 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-08 21:33 UTC, tarabrind commented
In the "Changelog entries":
```
summary: Adding the ability to join nodes created in DVP without problems.
```
It should be replaced "Adding" to "Added" because it'll be written in the changelog.

2024-10-08 21:35 UTC, tarabrind requested changes
In the "Changelog entries":
```
summary: Adding the ability to join nodes created in DVP without problems.
```
It should be replaced "Adding" to "Added" because it'll be written in the changelog.

2024-10-09 09:32 UTC, deckhouse-BOaTswain commented
Aye, aye, @Beastlex. I've started the workflow for label 'e2e/run/yandex-cloud'...
<!-- workflow_start -->

2024-10-10 07:12 UTC, tarabrind approved these changes

2025-04-22 12:22 UTC, deckhouse-BOaTswain commented
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2025-04-23 12:41 UTC, sprait approved these changes

2025-04-23 19:41 UTC, name212 approved these changes

2025-04-24 11:00 UTC, AndreyPavlovFlant approved these changes

2025-05-14 15:06 UTC, deckhouse-BOaTswain commented
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2025-05-29 07:47 UTC, deckhouse-BOaTswain commented
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2025-05-29 07:50 UTC, miklezzzz commented
/e2e/abort gcp;WithoutNAT;containerd;1.30 15319024772 15319024772-1-con-1-30 /sys/deckhouse-oss/install:pr9996

2025-05-29 07:50 UTC, deckhouse-BOaTswain commented
Aye, aye, @miklezzzz. I've recognized your '/e2e/abort' command and started the workflow...
<!-- workflow_start -->

2025-05-29 08:57 UTC, deckhouse-BOaTswain commented
Aye, aye, @miklezzzz. I've started the workflow for label 'e2e/run/gcp'...
<!-- workflow_start -->

2025-05-29 10:45 UTC, miklezzzz commented on tools/helm_generate/runners/alert_templates/template_values/021-cni-cilium.yaml
> +    dvpNestingLevel: 0
done

2025-05-29 10:45 UTC, miklezzzz commented on modules/021-cni-cilium/hooks/discover_vxlan_port.go
>  	"github.com/deckhouse/deckhouse/go_lib/set"
done

2025-05-29 10:45 UTC, miklezzzz commented on candi/bashible/bashbooster/50_virtualization.sh
> +    echo "$DVP_NESTING_LEVEL"
done

2025-06-02 15:19 UTC, apolovov commented on docs/documentation/_data/deckhouse-alerts.yml
> +        The Cilium configuration specifies a non-standard VXLAN port `{{ $labels.currentPort }}`. The recommend port number is `{{ $labels.recommendedPort }}`.
labels.snake_case

2025-06-02 15:28 UTC, apolovov commented on modules/021-cni-cilium/hooks/discover_vxlan_port.go
> +					{source: 4298, target: 4299},
```suggestion
					{source: 4298, target: 4298 - nestingLevel},
```

2025-06-02 22:53 UTC, merged